import { VEIL,EXPEDITION } from './config.js';import { DRIVES,MOLECULE_USES,REGIONS,driveAvailable,growthGoal } from './growth.js';import { bindRepeatAction } from './repeat-action.js';
const DRIVE_SECONDS=DRIVES.combustion.packetSeconds;
export function createSupplyUI({resources,canOpen,canMake,onCommit,onStore,onAnchor}){
 const q=id=>document.getElementById(id),dialog=q('supply-dialog');let choice='hydrogen',optionsKey='',anchorsKey='',announcement='';
 const name=r=>r?.commonNameJa??r?.nameJa??r?.name??'',formula=r=>MOLECULE_USES[r?.id]?.formula??r?.formula??'';
 function select(id){if(resources.record(id)){choice=id;q('molecule-select').value=id;}update();}
 function update(){const s=resources.state;
  for(const el of ['H','C','O']){q(`resource-${el.toLowerCase()}`).textContent=s.elements[el];if(el!=='H')q(`stock-${el.toLowerCase()}`).hidden=!resources.canUseElement(el);}
  for(const [id,key]of [['hydrogen','h2'],['methane','ch4'],['oxygen','o2'],['water','water']])q(`resource-${key}`).textContent=s.molecules[id]??0;
  q('craft-resource-hint').textContent=announcement||growthGoal(s).text;q('supply-goal').textContent=growthGoal(s).text;
  const available=[...new Set([...s.hints,...s.recipes])].filter(id=>resources.record(id)),key=available.join('|')+';'+s.recipes.join('|');
  if(key!==optionsKey){optionsKey=key;const list=q('molecule-select');list.replaceChildren();if(!available.length){const option=document.createElement('option');option.value='';option.textContent='採集すると、構造のヒントが届く';list.append(option);}for(const id of available){const r=resources.record(id),o=document.createElement('option');o.value=id;o.textContent=`${formula(r)} · ${name(r)}${s.recipes.includes(id)?' — 量産可':' — 構造ヒント'}`;list.append(o);}if(!available.includes(choice))choice=available[0]??'';list.value=choice;}
  const record=resources.record(choice),complete=s.recipes.includes(choice),cost=resources.costFor(choice);q('recipe-name').textContent=record?`${formula(record)} · ${name(record)}`:'まずHを集めよう';q('recipe-hint').textContent=record?(MOLECULE_USES[choice]?.hint??'模型と下の結合情報を手がかりに、自分で組み立てよう。'):'';
  q('recipe-model').hidden=!record?.bonds;if(record?.bonds){const path=`./assets/models/molecule-${choice}.svg`;if(q('recipe-model').getAttribute('src')!==path)q('recipe-model').src=path;q('recipe-bonds').textContent=record.bonds.map(([a,b,n])=>`${record.atoms[a]}${a+1} ${n===1?'—':n===2?'＝':'≡'} ${record.atoms[b]}${b+1}`).join(' / ');}q('recipe-connections').hidden=!record?.bonds;
  q('molecule-use').textContent=MOLECULE_USES[choice]?.use??(record?'図鑑に記録できる分子。今回の探索用の特殊作用はありません。':'');q('make-h2').hidden=!complete;q('make-h2').disabled=resources.blocked||!resources.canAfford(cost);q('make-h2').textContent=`${formula(record)} 生成 · 長押し`;q('molecule-stock').textContent=complete?`保管 ${s.molecules[choice]??0} 個`:'初めての1個は、自分で組み立てる';q('molecule-cost').textContent=cost?`1個の原子：${Object.entries(cost).map(([el,n])=>`${el} × ${n}`).join(' / ')}${complete&&!resources.canAfford(cost)?' · 素材が不足':''}`:'';
  q('supply-systems').hidden=!s.recipes.includes('hydrogen');if(s.recipes.includes('hydrogen'))q('supply-propulsion-note').textContent=driveAvailable(s,'combustion')?`出発時に H₂ 最大${EXPEDITION.hydrogenCapacity}、CH₄ 最大${EXPEDITION.methaneCapacity}、O₂ 最大${EXPEDITION.oxygenCapacity}を自動搭載。DRIVEは${DRIVE_SECONDS}秒ごとにCH₄ × 1とO₂ × 2を消費します。`:`出発時にH₂を最大${EXPEDITION.hydrogenCapacity}回分、自動搭載。通常航行では消費せず、BURSTした分だけ在庫から減ります。`;
  const ak=s.progress.regions.join('|');if(ak!==anchorsKey){anchorsKey=ak;const list=q('expedition-anchor'),selected=list.value;list.replaceChildren();for(const [id,text]of [['continue','探索の続き'],...s.progress.regions.map(id=>[id,`${REGIONS[id].name}へ補給`])]){const o=document.createElement('option');o.value=id;o.textContent=text;list.append(o);}list.value=selected||'continue';}
 }
 q('open-supply').addEventListener('click',()=>{if(!canOpen())return;announcement='';update();dialog.showModal();});q('molecule-select').addEventListener('change',()=>{choice=q('molecule-select').value;update();});
 q('expedition-anchor').addEventListener('change',()=>onAnchor(q('expedition-anchor').value));
 bindRepeatAction(q('make-h2'),{delay:VEIL.holdDelayMs,interval:VEIL.holdIntervalMs,action:()=>{if(!canMake())return false;const elements={...resources.state.elements},stock=resources.state.molecules[choice]??0;if(!resources.makeMolecule(choice,1))return false;const committed=onCommit()!==false,saved=committed&&resources.save();if(!saved){Object.assign(resources.state.elements,elements);resources.state.molecules[choice]=stock;}update();if(!saved)return false;const node=q('molecule-stock');node.classList.remove('stock-pulse');void node.offsetWidth;node.classList.add('stock-pulse');return resources.canAfford(resources.costFor(choice));}});
 q('store-h2').addEventListener('click',()=>{const id=onStore();if(!id)return;choice=typeof id==='string'?id:'hydrogen';announcement=MOLECULE_USES[choice]?.discovery??'分子を保管しました。以後は長押しで量産できます。';update();});update();return {update,select,discovered(id){choice=id;announcement=MOLECULE_USES[id]?.discovery??'';update();},clearAnnouncement(){announcement='';},get open(){return dialog.open;}};
}
