import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {mkdtemp,readFile,rm,mkdir,writeFile} from 'node:fs/promises';
import {spawn,spawnSync} from 'node:child_process';
import {extname,join,normalize,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {fileURLToPath} from 'node:url';

const root=resolve(fileURLToPath(new URL('..',import.meta.url))),types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.json':'application/json','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.webmanifest':'application/manifest+json'};
const server=createServer(async(req,res)=>{try{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname),relative=pathname==='/'?'index.html':pathname.replace(/^\/+/,''),file=normalize(join(root,relative));if(!file.startsWith(root)){res.writeHead(403).end();return;}let body=await readFile(file);if(relative==='src/veil/ui.js'){body=Buffer.from(body.toString('utf8').replace('function frame(now){',"function frame(now){globalThis.__returnFlowProbe=()=>({run,returnState,active,renderer});"));}res.writeHead(200,{'content-type':types[extname(file)]??'application/octet-stream','cache-control':'no-store'});res.end(body);}catch{res.writeHead(404).end('not found');}});
await new Promise(done=>server.listen(0,'127.0.0.1',done));const {port}=server.address(),origin=`http://127.0.0.1:${port}`;
let chrome='';for(const command of ['google-chrome','chromium','chromium-browser']){const found=spawnSync('which',[command],{encoding:'utf8'});if(found.status===0&&found.stdout.trim()){chrome=found.stdout.trim();break;}}assert.ok(chrome,'Chromium is required for LOADOUT mobile fit validation');
const profile=await mkdtemp(join(tmpdir(),'molecule-craft-loadout-mobile-fit-')),debugPort=9237,pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));let child=null,socket=null;
try{
  child=spawn(chrome,['--headless=new','--no-sandbox','--disable-gpu','--disable-background-networking',`--user-data-dir=${profile}`,`--remote-debugging-port=${debugPort}`,'about:blank'],{stdio:['ignore','ignore','pipe']});let tabs=null;
  for(let attempt=0;attempt<160;attempt++){try{const response=await fetch(`http://127.0.0.1:${debugPort}/json/list`);if(response.ok){tabs=await response.json();if(tabs.length)break;}}catch{}await pause(100);}assert.ok(tabs?.length,'DevTools endpoint did not become ready');
  socket=new WebSocket(tabs.find(tab=>tab.type==='page')?.webSocketDebuggerUrl??tabs[0].webSocketDebuggerUrl);await new Promise((ok,fail)=>{const timer=setTimeout(()=>fail(new Error('DevTools websocket timeout')),5000);socket.addEventListener('open',()=>{clearTimeout(timer);ok();},{once:true});socket.addEventListener('error',fail,{once:true});});
  let sequence=0;const pending=new Map();socket.addEventListener('message',event=>{const message=JSON.parse(event.data);if(message.id&&pending.has(message.id)){const task=pending.get(message.id);pending.delete(message.id);message.error?task.reject(new Error(message.error.message)):task.resolve(message.result);}});const send=(method,params={})=>new Promise((ok,fail)=>{const id=++sequence;pending.set(id,{resolve:ok,reject:fail});socket.send(JSON.stringify({id,method,params}));});const evaluate=async expression=>{const response=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(response.exceptionDetails)throw new Error(response.exceptionDetails.exception?.description??response.exceptionDetails.text);return response.result?.value;};const waitFor=async(expression,message,attempts=140)=>{for(let i=0;i<attempts;i++){try{if(await evaluate(expression))return;}catch{}await pause(100);}throw new Error(message);};
  const viewport=async(width,height,mobile=true)=>{await send('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile});await pause(160);};const point=selector=>evaluate(`(()=>{const r=document.querySelector(${JSON.stringify(selector)})?.getBoundingClientRect();return r&&{x:r.left+r.width/2,y:r.top+r.height/2,w:r.width,h:r.height};})()`);const tap=async selector=>{const p=await point(selector);assert.ok(p);await send('Input.dispatchMouseEvent',{type:'mousePressed',x:p.x,y:p.y,button:'left',buttons:1,clickCount:1});await send('Input.dispatchMouseEvent',{type:'mouseReleased',x:p.x,y:p.y,button:'left',buttons:0,clickCount:1});};const tapShip=async()=>{const p=await evaluate(`(()=>{const {run,renderer}=globalThis.__returnFlowProbe(),canvas=document.querySelector('#veil-canvas'),r=canvas.getBoundingClientRect(),s=renderer.screen(run.player.x,run.player.y);return{x:r.left+s.x,y:r.top+s.y};})()`);await send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...p,radiusX:3,radiusY:3,force:1,id:1}]});await send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});};
  await send('Runtime.enable');await send('Page.enable');await viewport(390,844,true);await send('Page.navigate',{url:origin+'/'});await waitFor("document.querySelector('#collection-progress')?.textContent?.includes('/ 142')",'Application did not initialize');assert.equal(await evaluate("document.querySelectorAll('#open-reaction-lab,#reaction-lab-dialog').length"),2,'the production Reaction Lab entrypoint and 3D sandbox are mounted');assert.ok(await evaluate("document.querySelector('#open-supply')&&document.querySelector('#open-collection')"),'LOADOUT and Encyclopedia shell controls must remain available');

  await tap('#open-supply');await waitFor("document.querySelector('#supply-dialog').open",'supply open');await tap('#open-collector-applications');await waitFor("document.querySelector('#collector-applications-dialog').open",'materials open');
  assert.equal(await evaluate("document.querySelectorAll('[data-collector-application][data-state=locked]:disabled').length"),3);
  const bounds=await evaluate("(()=>{const d=document.querySelector('#collector-applications-dialog'),r=d.getBoundingClientRect();return{x:r.x,y:r.y,right:r.right,bottom:r.bottom,overflow:d.scrollWidth-d.clientWidth};})()");assert.ok(bounds.x>=0&&bounds.right<=390&&bounds.y>=0&&bounds.bottom<=844&&bounds.overflow<=1,JSON.stringify(bounds));
  await tap('#collector-applications-dialog .sheet-header button');
  await evaluate(`(async()=>{const {createResources}=await import('/src/veil/resources.js');const r=createResources({storage:localStorage});Object.assign(r.state.progress,{choCompleted:true,coreFractured:true,worldAwakened:true,rareEcologyEligible:true});Object.assign(r.state.engineering.fabricated,{WEAR_SKIN:true,THERMAL_SHELL:true,CONTROL_INSULATION:true});r.save();})()`);
  await send('Page.reload',{ignoreCache:true});await waitFor("!!document.querySelector('#open-collector-applications')&&!document.querySelector('#open-supply').disabled",'reload');await tap('#open-supply');await tap('#open-collector-applications');
  assert.equal(await evaluate("document.querySelectorAll('[data-collector-application][data-state=available]').length"),3);
  for(const id of ['WEAR_SKIN','THERMAL_SHELL','CONTROL_INSULATION'])await tap(`[data-collector-application=${id}]`);
  assert.equal(await evaluate("document.querySelectorAll('[data-collector-application][data-state=active][aria-pressed=true]').length"),3);
  await mkdir(join(root,'test-results/collector-applications'),{recursive:true});const shot=await send('Page.captureScreenshot',{format:'png'});await writeFile(join(root,'test-results/collector-applications/390-active.png'),Buffer.from(shot.data,'base64'));
  await tap('[data-collector-application=WEAR_SKIN]');assert.equal(await evaluate("document.querySelector('[data-collector-application=WEAR_SKIN]').dataset.state"),'available');await tap('[data-collector-application=WEAR_SKIN]');
  await send('Page.reload',{ignoreCache:true});await waitFor("!!document.querySelector('#open-collector-applications')&&!document.querySelector('#open-supply').disabled",'restore');await tap('#open-supply');await tap('#open-collector-applications');assert.equal(await evaluate("document.querySelectorAll('[data-collector-application][data-state=active]').length"),3);
  await tap('#collector-applications-dialog .sheet-header button');await tap('#collector-launch-handle');await waitFor("document.querySelector('#expedition-destinations').getAttribute('aria-hidden')==='false'",'destinations');await tap('#expedition-destinations [data-region=veil]');await waitFor("document.querySelector('#veil-view').hidden===false&&!!globalThis.__returnFlowProbe?.().run",'FIELD launch');
  assert.deepEqual(await evaluate("globalThis.__returnFlowProbe().run.collectorMaterial.activeApplications"),{WEAR_SKIN:true,THERMAL_SHELL:true,CONTROL_INSULATION:true});
  for(const [position,label] of [[{x:105,y:-6535},'摩耗軽減'],[{x:760,y:-11300},'熱伝達軽減'],[{x:660,y:-5370},'制御低下軽減']]){
    await evaluate(`(()=>{const {run}=globalThis.__returnFlowProbe();Object.assign(run.player,${JSON.stringify(position)},{vx:0,vy:0});})()`);await waitFor(`document.querySelector('#veil-region-subtitle').textContent.includes(${JSON.stringify(label)})`,'FIELD material feedback '+label);
  }
  console.log('Collector Shell 390x844 actual pointers PASS',JSON.stringify(bounds));
}finally{try{socket?.close();}catch{}try{child?.kill('SIGKILL');}catch{}await pause(100);server.close();await rm(profile,{recursive:true,force:true});}
