import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdtemp,rm} from 'node:fs/promises';
import {spawn,spawnSync} from 'node:child_process';
import {extname,join,normalize,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {fileURLToPath} from 'node:url';

const root=resolve(fileURLToPath(new URL('..',import.meta.url))),types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.json':'application/json','.css':'text/css','.svg':'image/svg+xml','.webmanifest':'application/manifest+json'};
const server=createServer(async(req,res)=>{try{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname),relative=pathname==='/'?'index.html':pathname.replace(/^\/+/,''),file=normalize(join(root,relative));if(!file.startsWith(root)){res.writeHead(403).end();return;}const body=await readFile(file);res.writeHead(200,{'content-type':types[extname(file)]??'application/octet-stream','cache-control':'no-store'});res.end(body);}catch{res.writeHead(404).end('not found');}});
await new Promise(done=>server.listen(0,'127.0.0.1',done));const {port}=server.address();
let chrome='';for(const command of ['google-chrome','chromium','chromium-browser']){const found=spawnSync('which',[command],{encoding:'utf8'});if(found.status===0&&found.stdout.trim()){chrome=found.stdout.trim();break;}}assert.ok(chrome,'A Chromium browser is required');
const profile=await mkdtemp(join(tmpdir(),'molecule-craft-combustion-')),debugPort=9231;let child=null,socket=null;
try{
  child=spawn(chrome,['--headless=new','--no-sandbox','--disable-gpu','--disable-background-networking',`--user-data-dir=${profile}`,`--remote-debugging-port=${debugPort}`,'about:blank'],{stdio:['ignore','ignore','pipe']});let stderr='';child.stderr.setEncoding('utf8');child.stderr.on('data',chunk=>stderr+=chunk);
  let tabs=null;for(let attempt=0;attempt<160;attempt++){try{const response=await fetch(`http://127.0.0.1:${debugPort}/json/list`);if(response.ok){tabs=await response.json();if(tabs.length)break;}}catch{}await new Promise(done=>setTimeout(done,100));}assert.ok(tabs?.length,`Chromium DevTools endpoint did not become ready: ${stderr.slice(-800)}`);
  socket=new WebSocket(tabs.find(tab=>tab.type==='page')?.webSocketDebuggerUrl??tabs[0].webSocketDebuggerUrl);await new Promise((done,reject)=>{const timer=setTimeout(()=>reject(new Error('DevTools websocket open timed out')),5000);socket.addEventListener('open',()=>{clearTimeout(timer);done();},{once:true});socket.addEventListener('error',reject,{once:true});});
  let sequence=0;const pending=new Map();socket.addEventListener('message',event=>{const message=JSON.parse(event.data);if(message.id&&pending.has(message.id)){const task=pending.get(message.id);pending.delete(message.id);message.error?task.reject(new Error(message.error.message)):task.resolve(message.result);}});const send=(method,params={})=>new Promise((done,reject)=>{const id=++sequence;pending.set(id,{resolve:done,reject});socket.send(JSON.stringify({id,method,params}));});
  await send('Runtime.enable');await send('Page.enable');await send('Page.navigate',{url:`http://127.0.0.1:${port}/`});await new Promise(done=>setTimeout(done,500));
  const expression=`(async()=>{
    const roles=await import('/src/veil/molecule-roles.js');const engine=await import('/src/veil/engine.js');const growth=await import('/src/veil/growth.js');const resourcesModule=await import('/src/veil/resources.js');const {THERMAL}=await import('/src/veil/config.js');const database=await fetch('/data/molecules.json').then(r=>r.json());
    const memory=()=>{const data=new Map();return {getItem:key=>data.get(key)??null,setItem:(key,value)=>data.set(key,value),removeItem:key=>data.delete(key)}};const map=()=>({seed:1,dust:[],fields:[],labels:[],routes:[]});
    const resource=(id,f,o)=>{const r=resourcesModule.createResources({storage:memory()});r.setCatalog(database);r.discover(id);r.discover('oxygen');r.state.tanks.fuel={molecule:id,amount:f};r.state.tanks.oxidizer={molecule:'oxygen',amount:o};r.save();return r;};
    const residualResource=resource('n-hexane',4,17),residual=engine.createRun(map(),growth.flightConfig(),{fuel:{fuel:{molecule:'n-hexane',amount:4},oxidizer:{molecule:'oxygen',amount:17}},predators:false});residual.combustionHeatFactor=0;engine.setCombustionHeld(residual,true);const firstEvents=engine.stepRun(residual,{x:0,y:0},1/60,{consumeCombustion:charge=>residualResource.consumeCombustion(charge)});
    const exhaust=(id,f,o)=>{const r=resource(id,f,o),run=engine.createRun(map(),growth.flightConfig(),{fuel:{fuel:{molecule:id,amount:f},oxidizer:{molecule:'oxygen',amount:o}},predators:false});run.combustionHeatFactor=0;engine.setCombustionHeld(run,true);let frames=0;while(!run.driveEmpty&&frames++<12000)engine.stepRun(run,{x:0,y:0},.15,{consumeCombustion:charge=>r.consumeCombustion(charge)});return {fuel:run.fuel.fuel.amount,oxygen:run.fuel.oxidizer.amount,persistentFuel:r.state.tanks.fuel.amount,persistentOxygen:r.state.tanks.oxidizer.amount,frames,overheated:run.overheated};};
    const thermal=engine.createRun(map(),growth.flightConfig(),{fuel:{fuel:{molecule:'methane',amount:3},oxidizer:{molecule:'oxygen',amount:6}},predators:false});thermal.heat=THERMAL.overheatThreshold-.01;engine.setCombustionHeld(thermal,true);const thermalEvents=engine.stepRun(thermal,{x:0,y:0},.15,{consumeCombustion:()=>true});
    return {plan:roles.combustionBurnPlanFor('n-hexane',{fuelAmount:6,oxygenAmount:36}),tail:roles.combustionChargeFor('n-hexane',{fuelAmount:4,oxygenAmount:17}),first:{fuel:residual.fuel.fuel.amount,oxygen:residual.fuel.oxidizer.amount,combustion:residual.player.combustion,overheated:residual.overheated,events:firstEvents.map(e=>e.type)},gauge:growth.propulsionGauge('combustion',{fuel:{molecule:'n-hexane',amount:4},oxidizer:{molecule:'oxygen',amount:17}}),hexane:exhaust('n-hexane',6,36),methane:exhaust('methane',18,36),thermal:{overheated:thermal.overheated,events:thermalEvents.map(e=>e.type)}};
  })()`;
  const evaluated=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});assert.equal(evaluated.exceptionDetails,undefined,JSON.stringify(evaluated.exceptionDetails));const result=evaluated.result.value;
  assert.deepEqual(result.plan,{fuel:'n-hexane',oxidizer:'oxygen',fuelUsed:3,oxygenUsed:29,fuelRemaining:3,oxygenRemaining:7,seconds:31.14,charges:2});assert.deepEqual(result.tail,{fuel:'n-hexane',fuelAmount:1,oxidizer:'oxygen',oxygenAmount:10,seconds:10.38});
  assert.deepEqual(result.first,{fuel:3,oxygen:7,combustion:true,overheated:false,events:['driveIgnition']});assert.ok(result.gauge.seconds>0&&result.gauge.ratio>0,'HUD must report residual n-hexane as usable');assert.deepEqual(result.hexane,{fuel:3,oxygen:7,persistentFuel:3,persistentOxygen:7,frames:210,overheated:false});assert.equal(result.methane.fuel,0);assert.equal(result.methane.oxygen,0);assert.equal(result.methane.overheated,false);assert.equal(result.thermal.overheated,true);assert.ok(result.thermal.events.includes('overheat')&&!result.thermal.events.includes('driveEmpty'));
  console.log(JSON.stringify(result,null,2));
}finally{try{socket?.close();}catch{}try{child?.kill('SIGKILL');}catch{}await new Promise(done=>setTimeout(done,100));server.close();await rm(profile,{recursive:true,force:true});}
