import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile} from 'node:fs/promises';
import {spawn,spawnSync} from 'node:child_process';
import {extname,join,normalize,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {fileURLToPath} from 'node:url';

const root=resolve(fileURLToPath(new URL('..',import.meta.url))),types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.json':'application/json','.svg':'image/svg+xml'};
const server=createServer(async(req,res)=>{try{const path=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(path==='/__fixture__'){res.writeHead(200,{'content-type':types['.html']});res.end('<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"></head><body><div id="target"></div></body></html>');return;}const file=normalize(join(root,path.replace(/^\/+/,'')));if(!file.startsWith(root)){res.writeHead(403).end();return;}const body=await readFile(file);res.writeHead(200,{'content-type':types[extname(file)]??'application/octet-stream'});res.end(body);}catch{if(!res.headersSent)res.writeHead(404);res.end('not found');}});
await new Promise(done=>server.listen(0,'127.0.0.1',done));const {port}=server.address();let chrome='';for(const command of ['google-chrome','chromium','chromium-browser']){const found=spawnSync('which',[command],{encoding:'utf8'});if(found.status===0&&found.stdout.trim()){chrome=found.stdout.trim();break;}}assert.ok(chrome,'Chromium is required for the CRAFT target-button browser acceptance');
const profile=await import('node:fs/promises').then(fs=>fs.mkdtemp(join(tmpdir(),'molecule-craft-target-order-'))),debugPort=9230;let child=null,socket=null;
try{
  child=spawn(chrome,['--headless=new','--no-sandbox','--disable-gpu','--disable-background-networking',`--user-data-dir=${profile}`,`--remote-debugging-port=${debugPort}`,'about:blank'],{stdio:['ignore','ignore','pipe']});let tabs=null;for(let i=0;i<120;i++){try{const response=await fetch(`http://127.0.0.1:${debugPort}/json/list`);if(response.ok){tabs=await response.json();if(tabs.length)break;}}catch{}await new Promise(r=>setTimeout(r,100));}assert.ok(tabs?.length,'Chromium DevTools endpoint did not become ready');socket=new WebSocket(tabs.find(tab=>tab.type==='page')?.webSocketDebuggerUrl??tabs[0].webSocketDebuggerUrl);await new Promise((ok,fail)=>{const timer=setTimeout(()=>fail(new Error('DevTools websocket timed out')),5000);socket.addEventListener('open',()=>{clearTimeout(timer);ok();},{once:true});socket.addEventListener('error',fail,{once:true});});
  let sequence=0;const pending=new Map();socket.addEventListener('message',event=>{const m=JSON.parse(event.data);if(m.id&&pending.has(m.id)){const task=pending.get(m.id);pending.delete(m.id);m.error?task.reject(new Error(m.error.message)):task.resolve(m.result);}});const send=(method,params={})=>new Promise((ok,fail)=>{const id=++sequence;pending.set(id,{resolve:ok,reject:fail});socket.send(JSON.stringify({id,method,params}));});const evaluate=async expression=>{const result=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(result.exceptionDetails)throw new Error(result.exceptionDetails.exception?.description??result.exceptionDetails.text);return result.result?.value;};
  await send('Runtime.enable');await send('Page.enable');await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:2,mobile:true});await send('Page.navigate',{url:`http://127.0.0.1:${port}/__fixture__`});await new Promise(r=>setTimeout(r,120));
  const ready=await evaluate(`(async()=>{const [{renderCraftTargetParts},{decomposeTargetIntoAvailableParts},{matchCraftTarget}]=await Promise.all([import('/src/craft-panel.js?v=44'),import('/src/craft-decomposition.js'),import('/src/craft-target-satisfaction.js')]);const target={atoms:['C','O','C','O','C','N'],bonds:[[0,1,1],[2,3,2],[4,5,1]]},templates=[{id:'part-a',atoms:['C','O'],bonds:[[0,1,1]]},{id:'part-b',atoms:['C','O'],bonds:[[0,1,2]]},{id:'part-c',atoms:['C','N'],bonds:[[0,1,1]]}],pieces=decomposeTargetIntoAvailableParts(target,templates).map(piece=>({...piece,template:templates.find(item=>item.id===piece.partId)})),root=document.querySelector('#target');let workspace={atoms:[],bonds:[]},nextId=100;
    function render(){window.__craftWorkspace=workspace;const result=matchCraftTarget(target,pieces,workspace);renderCraftTargetParts(root,result.unsatisfiedPieces,workspace.atoms,{size:31,onPlace:item=>{const ids=item.atomIndices.map(()=>nextId++),atoms=item.atomIndices.map(index=>target.atoms[index]),bonds=[];for(let a=0;a<item.atomIndices.length;a++)for(let b=a+1;b<item.atomIndices.length;b++){const order=target.bonds.find(([x,y])=>(x===item.atomIndices[a]&&y===item.atomIndices[b])||(x===item.atomIndices[b]&&y===item.atomIndices[a]))?.[2];if(order)bonds.push([ids[a],ids[b],order]);}workspace={atoms:[...workspace.atoms,...atoms.map((element,i)=>({id:ids[i],element}))],bonds:[...workspace.bonds,...bonds.map(([a,b,order])=>({a,b,order}))]};render();}});}
    render();const buttons=[...root.querySelectorAll('button.craft-target-part')];return{count:buttons.length,order:buttons.map(button=>button.dataset.partId),buttons:buttons.map(button=>{const r=button.getBoundingClientRect();return{x:r.left+r.width/2,y:r.top+r.height/2,width:r.width,height:r.height};})};})()`);
  assert.deepEqual(ready.order,['part-a','part-b','part-c'],'three whole production target-part buttons must render in hint order');assert.ok(ready.buttons.every(button=>button.width>0&&button.height>0),'target part buttons must be visible tap targets at 390×844');const right=ready.buttons.at(-1);await send('Input.dispatchMouseEvent',{type:'mousePressed',x:right.x,y:right.y,button:'left',clickCount:1});await send('Input.dispatchMouseEvent',{type:'mouseReleased',x:right.x,y:right.y,button:'left',clickCount:1});
  const state=await evaluate(`(()=>{const buttons=[...document.querySelectorAll('#target button.craft-target-part')],atoms=[...document.querySelectorAll('#target button.craft-target-atom')],workspace=window.__craftWorkspace;return{parts:buttons.map(button=>button.dataset.partId),atomic:atoms.map(button=>button.dataset.element),count:buttons.length+atoms.length,workspace};})()`);assert.deepEqual(state.parts,['part-a','part-b'],'the untouched hint parts must remain whole after tapping the rightmost part');assert.deepEqual(state.atomic,[],'a whole-part tap must not turn unrelated parts into atomic fallback');assert.equal(state.count,2);assert.deepEqual(state.workspace.atoms.map(atom=>atom.element),['C','N'],'rightmost part must be spawned as its whole component');assert.equal(state.workspace.bonds.length,1,'spawned part must retain its bond');assert.equal(state.workspace.bonds[0].order,1,'spawned part bond order must match its target template');
  console.log('CRAFT right-first browser acceptance passed at 390×844: production target-part button tap preserved the spawned C–N bond and kept the other two target parts whole.');
}finally{try{socket?.close();}catch{}try{child?.kill('SIGKILL');}catch{}await new Promise(resolve=>setTimeout(resolve,100));await import('node:fs/promises').then(fs=>fs.rm(profile,{recursive:true,force:true,maxRetries:4,retryDelay:100}));server.close();}
