import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createGameShell} from '../src/game-shell.js';

const root=new URL('../',import.meta.url);
const [index,app,gameShell,craftPanel,pubchemReference,supply,craftControls]=await Promise.all([
  readFile(new URL('index.html',root),'utf8'),readFile(new URL('src/app.js',root),'utf8'),readFile(new URL('src/game-shell.js',root),'utf8'),readFile(new URL('src/craft-panel.js',root),'utf8'),readFile(new URL('src/pubchem-reference.js',root),'utf8'),readFile(new URL('src/veil/supply.js',root),'utf8'),readFile(new URL('src/craft-controls.js',root),'utf8'),
]);
function node(id=''){return{id,className:'',textContent:'',style:{},attributes:new Map(),listeners:new Map(),children:[],setAttribute(key,value){this.attributes.set(key,String(value));},removeAttribute(key){this.attributes.delete(key);},getAttribute(key){return this.attributes.get(key)??null;},addEventListener(type,handler){this.listeners.set(type,handler);},querySelector(){return null;},querySelectorAll(){return[];},replaceChildren(...children){this.children=children;},append(...children){this.children.push(...children);},classList:{add(){},remove(){}},matches(){return false;},closest(){return null;}};}
test('CRAFT collector access remains the exploration-machine control',()=>{const access=node('open-supply');access.className='collector-access';access.textContent='';const originalNavigation=()=>{};access.listeners.set('click',originalNavigation);const document={getElementById(id){return id==='open-supply'?access:null;},querySelector(){return null;},querySelectorAll(){return[];}};const previous=globalThis.document;globalThis.document=document;try{createGameShell();}finally{globalThis.document=previous;}assert.equal(access.listeners.get('click'),originalNavigation);assert.equal(access.className,'collector-access');assert.equal(access.textContent,'');assert.match(supply,/accessCanvas\.id='collector-access-preview'/);assert.match(supply,/access\.append\(accessCanvas\)/);assert.match(supply,/access\.setAttribute\('aria-label','探索機を開く'\)/);});
test('CRAFT history undo is icon-only and visually paired with the destructive trash icon',()=>{assert.match(index,/id="undo-cleanup" class="icon-button craft-history-undo"[^>]*aria-label="直前のCRAFT操作を元に戻す"/);const sharedIcons=index.match(/<svg class="cleanup-icon"/g)??[];assert.ok(sharedIcons.length>=2);assert.match(index,/id="undo-cleanup"[\s\S]*?<path d="M9 7L4 12l5 5"\/><path d="M5 12h7a7 7 0 0 1 7 7"\/>/);assert.match(craftControls,/undo\.style\.marginRight='12px'/);assert.match(craftControls,/document\.querySelector\('#undo-cleanup'\)\?\.addEventListener\('click',onUndo\)/);assert.doesNotMatch(craftControls,/undo\.textContent|← 戻す|↶/);});
test('legacy transient cleanup art and selected-atom delete action are removed end-to-end',()=>{assert.doesNotMatch(index,/<circle cx="7" cy="6\.5"|<circle cx="12" cy="5"|<circle cx="17" cy="6\.5"/);assert.match(index,/id="clear-all"[\s\S]*?<path d="M8 8h8l-\.7 11H8\.7L8 8z"/);for(const source of [index,app,gameShell,craftControls])assert.doesNotMatch(source,/delete-selected|onDelete/);assert.doesNotMatch(app,/削除後の構造を安定化しています/);});
test('PubChem stays with molecule identity and remains an explicit external link',()=>{assert.match(craftPanel,/nodes\.formula\.append\(nodes\.pubchem\)/);assert.match(craftPanel,/pubchemLink\.target='_blank'/);assert.match(craftPanel,/pubchemLink\.rel='noopener noreferrer external'/);assert.match(craftPanel,/PubChemでこの分子を調べる（外部サイト）/);assert.match(craftPanel,/marginLeft:'0'/);assert.match(craftPanel,/borderLeft:'0'/);assert.match(craftPanel,/pubchemReferenceFor\(focus\)/);assert.match(pubchemReference,/return'PubChem ↗'/);});
