import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {mkdtemp,readFile,rm} from 'node:fs/promises';
import {spawn,spawnSync} from 'node:child_process';
import {extname,join,normalize,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {fileURLToPath} from 'node:url';

const root=resolve(fileURLToPath(new URL('..',import.meta.url))),types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.json':'application/json','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.webmanifest':'application/manifest+json'};
const server=createServer(async(req,res)=>{try{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname),relative=pathname==='/'?'index.html':pathname.replace(/^\/+/,''),file=normalize(join(root,relative));if(!file.startsWith(root)){res.writeHead(403).end();return;}const body=await readFile(file);res.writeHead(200,{'content-type':types[extname(file)]??'application/octet-stream','cache-control':'no-store'});res.end(body);}catch{res.writeHead(404).end('not found');}});
await new Promise(done=>server.listen(0,'127.0.0.1',done));const {port}=server.address(),origin=`http://127.0.0.1:${port}`;
let chrome='';for(const command of ['google-chrome','chromium','chromium-browser']){const found=spawnSync('which',[command],{encoding:'utf8'});if(found.status===0&&found.stdout.trim()){chrome=found.stdout.trim();break;}}assert.ok(chrome,'Chromium is required for DOCK validation');
const profile=await mkdtemp(join(tmpdir(),'molecule-craft-dock-')),debugPort=9243,pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));let child=null,socket=null;
try{
  child=spawn(chrome,['--headless=new','--no-sandbox','--disable-gpu','--disable-background-networking',`--user-data-dir=${profile}`,`--remote-debugging-port=${debugPort}`,'about:blank'],{stdio:['ignore','ignore','pipe']});let tabs=null;
  for(let attempt=0;attempt<160;attempt++){try{const response=await fetch(`http://127.0.0.1:${debugPort}/json/list`);if(response.ok){tabs=await response.json();if(tabs.length)break;}}catch{}await pause(100);}assert.ok(tabs?.length,'DevTools endpoint did not become ready');
  socket=new WebSocket(tabs.find(tab=>tab.type==='page')?.webSocketDebuggerUrl??tabs[0].webSocketDebuggerUrl);await new Promise((ok,fail)=>{const timer=setTimeout(()=>fail(new Error('DevTools websocket timeout')),5000);socket.addEventListener('open',()=>{clearTimeout(timer);ok();},{once:true});socket.addEventListener('error',fail,{once:true});});
  let sequence=0;const pending=new Map();socket.addEventListener('message',event=>{const message=JSON.parse(event.data);if(message.id&&pending.has(message.id)){const task=pending.get(message.id);pending.delete(message.id);message.error?task.reject(new Error(message.error.message)):task.resolve(message.result);}});const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++sequence;pending.set(id,{resolve,reject});socket.send(JSON.stringify({id,method,params}));});const evaluate=async expression=>{const response=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(response.exceptionDetails)throw new Error(response.exceptionDetails.exception?.description??response.exceptionDetails.text);return response.result?.value;};const waitFor=async(expression,message,attempts=160)=>{for(let i=0;i<attempts;i++){try{if(await evaluate(expression))return;}catch{}await pause(100);}throw new Error(message);};
  await send('Runtime.enable');await send('Page.enable');await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await send('Page.navigate',{url:origin+'/'});await waitFor("!!document.querySelector('#open-dock')&&!!document.querySelector('#oxygen-upgrades')",'DOCK / LOADOUT did not initialize');
  const seeded=await evaluate(`(async()=>{localStorage.clear();const {createResources}=await import('/src/veil/resources.js');const records=await fetch('/data/molecules.json').then(r=>r.json());const r=createResources({storage:localStorage});r.setCatalog(records);r.collect({H:1000,C:1000,O:1000});for(const id of ['oxygen','ethene','propene','phenol','formaldehyde'])r.discover(id);r.setLoadoutTank('oxidizer','oxygen');return r.save();})()`);assert.equal(seeded,true);
  await send('Page.reload',{ignoreCache:true});await waitFor("!!document.querySelector('#open-dock')&&!!document.querySelector('#oxygen-upgrades')",'DOCK did not restore after seed reload');
  await evaluate("document.querySelector('#open-dock').click()");await waitFor("document.querySelector('#dock-dialog')?.open",'DOCK dialog did not open');
  const initial=await evaluate(`(()=>{const d=document.querySelector('#dock-dialog'),cards=[...d.querySelectorAll('[data-process]')].map(n=>({id:n.dataset.process,status:n.dataset.status,text:n.textContent})),legacy=getComputedStyle(document.querySelector('#oxygen-upgrades')).display,rect=d.getBoundingClientRect(),body=d.querySelector('.dock-body');return{level:d.dataset.level,cards,legacy,rect:{top:rect.top,bottom:rect.bottom,left:rect.left,right:rect.right},body:{scrollHeight:body.scrollHeight,clientHeight:body.clientHeight},text:d.textContent};})()`);
  assert.equal(initial.level,'0');assert.equal(initial.cards.find(row=>row.id==='seal')?.status,'READY');assert.equal(initial.cards.find(row=>row.id==='overwrap')?.status,'LOCKED');assert.equal(initial.legacy,'none','LOADOUT upgrade control must not remain player-facing');assert.match(initial.text,/Polymerization/);assert.match(initial.text,/EPR-type elastomer seal/);assert.match(initial.text,/O₂ 36 → 48/);assert.ok(initial.rect.top>=0&&initial.rect.bottom<=844&&initial.rect.left>=0&&initial.rect.right<=390,'DOCK must fit the mobile viewport');
  const before=await evaluate(`JSON.parse(localStorage.getItem('molecule-craft.resources.v1')).upgrades.oxygenTank`);assert.equal(before,0,'recipe discovery alone must keep capacity at 36');
  await evaluate(`(()=>{const b=document.querySelector('[data-dock-execute="seal"]');b.click();b.click();})()`);await waitFor("document.querySelector('#dock-dialog')?.dataset.level==='1'",'Seal Repair did not commit');await pause(100);
  const afterSeal=await evaluate(`(()=>{const s=JSON.parse(localStorage.getItem('molecule-craft.resources.v1')),cards=[...document.querySelectorAll('#dock-dialog [data-process]')].map(n=>({id:n.dataset.process,status:n.dataset.status}));return{level:s.upgrades.oxygenTank,cards};})()`);assert.equal(afterSeal.level,1,'double tap must not skip directly from 36 to 72');assert.equal(afterSeal.cards.find(row=>row.id==='seal')?.status,'COMPLETE');assert.equal(afterSeal.cards.find(row=>row.id==='overwrap')?.status,'READY');
  await evaluate("document.querySelector('[data-dock-execute=\"overwrap\"]').click()");await waitFor("document.querySelector('#dock-dialog')?.dataset.level==='2'",'Composite Overwrap did not commit');
  const finalState=await evaluate(`JSON.parse(localStorage.getItem('molecule-craft.resources.v1')).upgrades.oxygenTank`);assert.equal(finalState,2);
  await evaluate("document.querySelector('[data-dock-close]').click();document.querySelector('#open-supply').click()");await waitFor("document.querySelector('#supply-dialog')?.open",'LOADOUT did not open after DOCK');await evaluate("document.querySelector('#shell-oxidizer').click()");await waitFor("document.querySelector('#tank-load')?.textContent?.includes('/ 72')",'LOADOUT did not reflect O2 72 capacity');
  await send('Page.reload',{ignoreCache:true});await waitFor("!!document.querySelector('#open-dock')&&!!document.querySelector('#oxygen-upgrades')",'App did not reload after DOCK completion');await evaluate("document.querySelector('#open-dock').click()");await waitFor("document.querySelector('#dock-dialog')?.open",'DOCK did not reopen');const persisted=await evaluate(`(()=>({level:document.querySelector('#dock-dialog').dataset.level,statuses:[...document.querySelectorAll('#dock-dialog [data-process]')].map(n=>n.dataset.status)}))()`);assert.equal(persisted.level,'2');assert.deepEqual(persisted.statuses,['COMPLETE','COMPLETE']);
  console.log('DOCK browser regression',JSON.stringify({initial,afterSeal,persisted}));
}finally{try{socket?.close();}catch{}try{child?.kill('SIGKILL');}catch{}await pause(100);server.close();await rm(profile,{recursive:true,force:true});}
console.log('DOCK Chromium regression passed: explicit sequential fabrication, hidden LOADOUT legacy control, persistence, 72 reflection and mobile fit.');
