import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {mkdir,mkdtemp,readFile,rm,writeFile} from 'node:fs/promises';
import {spawn,spawnSync} from 'node:child_process';
import {extname,join,normalize,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {fileURLToPath} from 'node:url';

const root=resolve(fileURLToPath(new URL('..',import.meta.url))),types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.json':'application/json','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.webmanifest':'application/manifest+json'};
const server=createServer(async(req,res)=>{try{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname),relative=pathname==='/'?'index.html':pathname.replace(/^\/+/,''),file=normalize(join(root,relative));if(!file.startsWith(root)){res.writeHead(403).end();return;}let body=await readFile(file);if(relative==='src/veil/ui.js'){let source=body.toString('utf8');source=source.replace('function frame(now){',"function frame(now){globalThis.__forcedReturnProbe=()=>({run,returnState,anchorLock,active});globalThis.__forcedReturnResources=resources;");source=source.replace('function finish(captured=false){',"function finish(captured=false){globalThis.__forcedReturnFinishCalls=(globalThis.__forcedReturnFinishCalls??0)+1;");source=source.replaceAll("root.hidden=true;document.body.dataset.mode='craft';appShell.inert=false;","root.hidden=true;document.body.dataset.mode='craft';appShell.inert=false;globalThis.__forcedReturnBaseTransitions=(globalThis.__forcedReturnBaseTransitions??0)+1;");body=Buffer.from(source);}res.writeHead(200,{'content-type':types[extname(file)]??'application/octet-stream','cache-control':'no-store'});res.end(body);}catch{res.writeHead(404).end('not found');}});
await new Promise(done=>server.listen(0,'127.0.0.1',done));const {port}=server.address(),origin=`http://127.0.0.1:${port}`;
let chrome='';for(const command of ['google-chrome','chromium','chromium-browser']){const found=spawnSync('which',[command],{encoding:'utf8'});if(found.status===0&&found.stdout.trim()){chrome=found.stdout.trim();break;}}assert.ok(chrome,'Chromium is required for Dust Eater forced-return UI integration');
const profile=await mkdtemp(join(tmpdir(),'molecule-craft-forced-return-ui-')),debugPort=9269,pause=ms=>new Promise(resolvePause=>setTimeout(resolvePause,ms));let child=null,socket=null;
try{
  child=spawn(chrome,['--headless=new','--no-sandbox','--disable-gpu','--disable-background-networking',`--user-data-dir=${profile}`,`--remote-debugging-port=${debugPort}`,'about:blank'],{stdio:['ignore','ignore','pipe']});let tabs=null,stderr='';child.stderr.setEncoding('utf8');child.stderr.on('data',chunk=>stderr+=chunk);
  for(let attempt=0;attempt<160;attempt++){try{const response=await fetch(`http://127.0.0.1:${debugPort}/json/list`);if(response.ok){tabs=await response.json();if(tabs.length)break;}}catch{}await pause(100);}assert.ok(tabs?.length,stderr.slice(-1000));
  socket=new WebSocket(tabs.find(tab=>tab.type==='page')?.webSocketDebuggerUrl??tabs[0].webSocketDebuggerUrl);await new Promise((ok,fail)=>{const timer=setTimeout(()=>fail(new Error('DevTools websocket timeout')),5000);socket.addEventListener('open',()=>{clearTimeout(timer);ok();},{once:true});socket.addEventListener('error',fail,{once:true});});
  let sequence=0;const pending=new Map(),exceptions=[];socket.addEventListener('message',event=>{const message=JSON.parse(event.data);if(message.id&&pending.has(message.id)){const task=pending.get(message.id);pending.delete(message.id);message.error?task.reject(new Error(message.error.message)):task.resolve(message.result);return;}if(message.method==='Runtime.exceptionThrown')exceptions.push(message.params.exceptionDetails);});
  const send=(method,params={})=>new Promise((resolveSend,reject)=>{const id=++sequence;pending.set(id,{resolve:resolveSend,reject});socket.send(JSON.stringify({id,method,params}));});const evaluate=async expression=>{const response=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(response.exceptionDetails)throw new Error(response.exceptionDetails.exception?.description??response.exceptionDetails.text);return response.result?.value;};const waitFor=async(expression,message,attempts=120)=>{for(let attempt=0;attempt<attempts;attempt++){try{if(await evaluate(expression))return true;}catch{}await pause(50);}throw new Error(message);};
  await send('Runtime.enable');await send('Page.enable');await send('Emulation.setDeviceMetricsOverride',{width:360,height:780,deviceScaleFactor:1,mobile:true});await send('Page.navigate',{url:origin+'/'});
  await waitFor(`!!document.querySelector('#collector-launch-handle')&&!document.querySelector('#open-supply')?.disabled`,'LOADOUT did not initialize');
  async function launchVeil(){
    await evaluate(`(()=>{document.querySelector('#open-supply').click();document.querySelector('#collector-launch-handle').dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}));return true;})()`);
    await waitFor(`document.querySelector('#expedition-destinations')?.getAttribute('aria-hidden')==='false'&&!!document.querySelector('#expedition-destinations [data-region="veil"]')`,'Veil destination selector did not open');
    await evaluate(`(()=>{document.querySelector('#expedition-destinations [data-region="veil"]').click();return true;})()`);
    await waitFor(`document.querySelector('#veil-view')?.hidden===false&&!!globalThis.__forcedReturnProbe?.().run`,'FIELD did not launch');
  }
  await launchVeil();
  const armed=await evaluate(`(async()=>{const {EXPEDITION}=await import('/src/veil/config.js'),p=globalThis.__forcedReturnProbe(),run=p.run,resources=globalThis.__forcedReturnResources;globalThis.__forcedReturnFinishCalls=0;globalThis.__forcedReturnBaseTransitions=0;globalThis.__forcedReturnSettlementCalls=0;globalThis.__forcedReturnLastSettlement=null;const settle=resources.settleExpedition.bind(resources);resources.settleExpedition=(...args)=>{globalThis.__forcedReturnSettlementCalls++;const result=settle(...args);globalThis.__forcedReturnLastSettlement=result;return result;};Object.assign(run.player,{vx:0,vy:0,speed:run.config.driftSpeed});Object.assign(run.elementDust,{H:120,C:35,O:20,P:10,S:5,F:4,Cl:6});Object.assign(run.collectedElements,{H:12,C:3,O:2,P:10,S:5,F:4,Cl:6});run.carriedInsights=['methane'];run.analysis={id:'water',elapsed:2,requiredDuration:5,progress:.4};run.fuel.propellant={molecule:'hydrogen',amount:120,capacity:120};run.fuel.shock={molecule:'nitromethane',amount:1,capacity:1};run.predators=true;run.nextEaterSpawn=Infinity;run.eaters=[{id:77,x:run.player.x+EXPEDITION.eaterContactRadius*.35,y:run.player.y,angle:Math.PI,speed:EXPEDITION.eaterSpeed*.8,targetSpeed:EXPEDITION.eaterSpeed,vx:-10,vy:0,phase:.2,flank:0,lead:0,trail:[]}];globalThis.__forcedReturnPersistentBefore={methaneHint:resources.state.hints.includes('methane'),waterHint:resources.state.hints.includes('water'),methaneRecipe:resources.state.recipes.includes('methane'),waterRecipe:resources.state.recipes.includes('water')};return{captureLoss:EXPEDITION.captureLoss,base:{...resources.state.elements}};})()`);
  await waitFor(`globalThis.__forcedReturnProbe?.().returnState?.captured===true`,'Dust Eater contact did not enter forced-return presentation',80);
  const phase=await evaluate(`(()=>{const p=globalThis.__forcedReturnProbe(),run=p.run,rs=p.returnState;globalThis.__forcedReturnPhaseLoss=structuredClone(rs.lossSnapshot);const cargo={...run.elementDust},treatments={...run.treatments},eater={x:run.eaters[0].x,y:run.eaters[0].y};run.map.dust.push({id:9901,x:run.player.x,y:run.player.y,value:30,kind:'normal',ready:0,angle:0,element:'H'},{id:9902,x:run.player.x,y:run.player.y,value:1,kind:'rare',ready:0,angle:0,element:'P',rareEcology:true});globalThis.__forcedReturnPhaseBaseline={cargo,treatments,eater,propellant:run.fuel.propellant.amount,shock:run.fuel.shock.amount,triggeredAt:run.forcedReturn.triggeredAt};return{hidden:document.querySelector('#veil-view').hidden,elapsed:rs.elapsed,duration:rs.duration,cargoParticles:run.lostCargoEffects?.length??0,insightParticles:run.lostInsightEffects?.length??0,loss:rs.lossSnapshot,message:document.querySelector('#veil-message')?.getAttribute('aria-label')??'',legacyInsightLossHidden:document.querySelector('#veil-insight-loss')?.hidden!==false,anchor:p.anchorLock,presentationStarted:run.forcedReturn.presentationStarted};})()`);
  assert.equal(phase.hidden,false,'Capture must not switch immediately to BASE');assert.ok(phase.elapsed<phase.duration&&phase.duration===.65);assert.ok(phase.cargoParticles>0&&phase.cargoParticles<=36);assert.equal(phase.insightParticles,2,'carried and pending uncommitted Insights both get loss icons');assert.equal(phase.legacyInsightLossHidden,true,'Legacy anchored Insight loss HUD must stay hidden so renderer-owned 💡 is the sole loss visual');assert.equal(phase.anchor,null,'normal return must not start alongside forced return');assert.equal(phase.presentationStarted,true);assert.doesNotMatch(phase.message,/保持場破綻|回収塵.*こぼれ|FORCED RETURN|RESOURCES LOST|INSIGHT LOST/,'Capture consequence adds no explanatory loss text');

  const shot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});await mkdir(join(root,'test-results','forced-return-presentation'),{recursive:true});await writeFile(join(root,'test-results','forced-return-presentation','production-ui-360x780.png'),Buffer.from(shot.data,'base64'));
  await send('Input.dispatchKeyEvent',{type:'keyDown',key:' ',code:'Space',windowsVirtualKeyCode:32,nativeVirtualKeyCode:32});await send('Input.dispatchKeyEvent',{type:'keyUp',key:' ',code:'Space',windowsVirtualKeyCode:32,nativeVirtualKeyCode:32});await send('Input.dispatchKeyEvent',{type:'keyDown',key:'e',code:'KeyE',windowsVirtualKeyCode:69,nativeVirtualKeyCode:69});await send('Input.dispatchKeyEvent',{type:'keyUp',key:'e',code:'KeyE',windowsVirtualKeyCode:69,nativeVirtualKeyCode:69});await evaluate(`(()=>{document.querySelector('#veil-return').click();document.querySelector('#veil-boost').click();document.querySelector('#veil-shock').click();return true;})()`);await pause(120);
  const locked=await evaluate(`(()=>{const p=globalThis.__forcedReturnProbe(),run=p.run,b=globalThis.__forcedReturnPhaseBaseline;return{cargo:{...run.elementDust},treatments:{...run.treatments},eater:{x:run.eaters[0].x,y:run.eaters[0].y},propellant:run.fuel.propellant.amount,shock:run.fuel.shock.amount,triggeredAt:run.forcedReturn.triggeredAt,anchor:p.anchorLock,returnElapsed:p.returnState?.elapsed,dustReady:run.map.dust.slice(-2).map(item=>item.ready),time:run.time};})()`);
  assert.deepEqual(locked.cargo,await evaluate('globalThis.__forcedReturnPhaseBaseline.cargo'),'Pickup and Rare pickup remain locked during presentation');assert.deepEqual(locked.treatments,await evaluate('globalThis.__forcedReturnPhaseBaseline.treatments'),'Hazard treatment charge remains stable during presentation');assert.notDeepEqual(locked.eater,await evaluate('globalThis.__forcedReturnPhaseBaseline.eater'),'Dust Eater keeps moving during presentation');assert.equal(locked.propellant,await evaluate('globalThis.__forcedReturnPhaseBaseline.propellant'),'PULSE/BURST cannot fire after capture');assert.equal(locked.shock,await evaluate('globalThis.__forcedReturnPhaseBaseline.shock'),'SHOCK cannot fire after capture');assert.equal(locked.triggeredAt,await evaluate('globalThis.__forcedReturnPhaseBaseline.triggeredAt'),'Repeated contact cannot reset forced-return timing');assert.equal(locked.anchor,null);assert.deepEqual(locked.dustReady,[0,0]);

  await waitFor(`document.body.dataset.mode==='craft'&&document.querySelector('#veil-view')?.hidden===true`,'Forced return did not transition to BASE',80);
  const settled=await evaluate(`(()=>{const r=globalThis.__forcedReturnResources,last=globalThis.__forcedReturnLastSettlement,before=globalThis.__forcedReturnPersistentBefore;return{finish:globalThis.__forcedReturnFinishCalls,baseTransitions:globalThis.__forcedReturnBaseTransitions,settlements:globalThis.__forcedReturnSettlementCalls,last,phaseLoss:globalThis.__forcedReturnPhaseLoss,persistentAfter:{methaneHint:r.state.hints.includes('methane'),waterHint:r.state.hints.includes('water'),methaneRecipe:r.state.recipes.includes('methane'),waterRecipe:r.state.recipes.includes('water')},persistentBefore:before};})()`);
  assert.equal(settled.finish,1,'Forced return finishes exactly once');assert.equal(settled.baseTransitions,1,'BASE transition fires exactly once');assert.equal(settled.settlements,1,'Forced settlement executes exactly once');assert.equal(settled.last.captured,true);assert.equal(settled.last.rate,armed.captureLoss,'Loss percentage is unchanged');assert.deepEqual(settled.last.lost,settled.phaseLoss.lost,'Visual loss snapshot matches actual settlement loss');assert.deepEqual(settled.persistentAfter,settled.persistentBefore,'Forced return does not commit run-local Insight as persistent recipe/hint');

  await launchVeil();
  const reloadBaseline=await evaluate(`(async()=>{const {EXPEDITION}=await import('/src/veil/config.js'),p=globalThis.__forcedReturnProbe(),run=p.run,r=globalThis.__forcedReturnResources;Object.assign(run.elementDust,{H:240,C:60,O:30,P:20});run.carriedInsights=['methane'];run.predators=true;run.nextEaterSpawn=Infinity;run.eaters=[{id:88,x:run.player.x+EXPEDITION.eaterContactRadius*.3,y:run.player.y,angle:Math.PI,speed:EXPEDITION.eaterSpeed,targetSpeed:EXPEDITION.eaterSpeed,vx:-10,vy:0,phase:.7,flank:0,lead:0,trail:[]}];globalThis.__reloadBase={...r.state.elements};return globalThis.__reloadBase;})()`);
  await waitFor(`globalThis.__forcedReturnProbe?.().returnState?.captured===true`,'Second capture did not enter presentation',80);
  await send('Page.reload',{ignoreCache:true});await waitFor(`!!document.querySelector('#collector-launch-handle')&&!document.querySelector('#open-supply')?.disabled`,'App did not recover after presentation reload');
  const afterReload=await evaluate(`(async()=>{const {createResources}=await import('/src/veil/resources.js');const r=createResources({storage:localStorage});return {...r.state.elements};})()`);
  assert.deepEqual(afterReload,reloadBaseline,'Reload during presentation cannot duplicate or bank run-local cargo; interruption resolves safely by losing the transient run');

  assert.equal(exceptions.length,0,`Forced-return production UI must not throw: ${JSON.stringify(exceptions)}`);
}finally{try{socket?.close();}catch{}try{child?.kill('SIGKILL');}catch{}await pause(100);server.close();await rm(profile,{recursive:true,force:true});}
console.log('Dust Eater forced-return production UI passed: visual-only phase, full input/pickup lock, live Eater, one settlement/BASE transition, matching loss snapshot and reload-safe transient cargo.');
