import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {mkdir,mkdtemp,readFile,rm,writeFile} from 'node:fs/promises';
import {spawn,spawnSync} from 'node:child_process';
import {extname,join,normalize,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {fileURLToPath} from 'node:url';

const root=resolve(fileURLToPath(new URL('..',import.meta.url))),types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.json':'application/json','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.webmanifest':'application/manifest+json'};
const server=createServer(async(req,res)=>{try{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname),relative=pathname==='/'?'index.html':pathname.replace(/^\/+/,''),file=normalize(join(root,relative));if(!file.startsWith(root)){res.writeHead(403).end();return;}const body=await readFile(file);res.writeHead(200,{'content-type':types[extname(file)]??'application/octet-stream','cache-control':'no-store'});res.end(body);}catch{res.writeHead(404).end('not found');}});
await new Promise(done=>server.listen(0,'127.0.0.1',done));const {port}=server.address(),origin=`http://127.0.0.1:${port}`;
let chrome='';for(const command of ['google-chrome','chromium','chromium-browser']){const found=spawnSync('which',[command],{encoding:'utf8'});if(found.status===0&&found.stdout.trim()){chrome=found.stdout.trim();break;}}assert.ok(chrome,'Chromium is required for Dust Eater forced-return visual validation');
const profile=await mkdtemp(join(tmpdir(),'molecule-craft-forced-return-')),debugPort=9268,pause=ms=>new Promise(resolvePause=>setTimeout(resolvePause,ms));let child=null,socket=null;
try{
  child=spawn(chrome,['--headless=new','--no-sandbox','--disable-gpu','--disable-background-networking',`--user-data-dir=${profile}`,`--remote-debugging-port=${debugPort}`,'about:blank'],{stdio:['ignore','ignore','pipe']});let tabs=null,stderr='';child.stderr.setEncoding('utf8');child.stderr.on('data',chunk=>stderr+=chunk);
  for(let attempt=0;attempt<160;attempt++){try{const response=await fetch(`http://127.0.0.1:${debugPort}/json/list`);if(response.ok){tabs=await response.json();if(tabs.length)break;}}catch{}await pause(100);}assert.ok(tabs?.length,stderr.slice(-1000));
  socket=new WebSocket(tabs.find(tab=>tab.type==='page')?.webSocketDebuggerUrl??tabs[0].webSocketDebuggerUrl);await new Promise((ok,fail)=>{const timer=setTimeout(()=>fail(new Error('DevTools websocket timeout')),5000);socket.addEventListener('open',()=>{clearTimeout(timer);ok();},{once:true});socket.addEventListener('error',fail,{once:true});});
  let sequence=0;const pending=new Map(),exceptions=[];socket.addEventListener('message',event=>{const message=JSON.parse(event.data);if(message.id&&pending.has(message.id)){const task=pending.get(message.id);pending.delete(message.id);message.error?task.reject(new Error(message.error.message)):task.resolve(message.result);return;}if(message.method==='Runtime.exceptionThrown')exceptions.push(message.params.exceptionDetails);});
  const send=(method,params={})=>new Promise((resolveSend,reject)=>{const id=++sequence;pending.set(id,{resolve:resolveSend,reject});socket.send(JSON.stringify({id,method,params}));});const evaluate=async expression=>{const response=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(response.exceptionDetails)throw new Error(response.exceptionDetails.exception?.description??response.exceptionDetails.text);return response.result?.value;};
  await send('Runtime.enable');await send('Page.enable');await send('Emulation.setDeviceMetricsOverride',{width:360,height:780,deviceScaleFactor:1,mobile:true});await send('Page.navigate',{url:origin+'/'});await pause(500);
  const setup=await evaluate(`(async()=>{const [{createRun},{createVeilRenderer},{VEIL}]=await Promise.all([import('/src/veil/engine.js'),import('/src/veil/renderer.js'),import('/src/veil/config.js')]);const map={seed:71,dust:[],fields:[],labels:[],routes:[]},run=createRun(map,VEIL,{predators:false});Object.assign(run.player,{x:0,y:0,angle:0,vx:0,vy:0,speed:VEIL.driftSpeed});run.captured=true;run.captureAt=run.time;run.forcedReturn={triggeredAt:run.time,eaterId:7,presentationStarted:false};run.eaters=[{id:7,x:72,y:0,angle:Math.PI,speed:0,targetSpeed:0,vx:0,vy:0,phase:.3,flank:0,lead:0,trail:[]}];const canvas=document.createElement('canvas');canvas.id='forced-return-visual';canvas.style.cssText='position:fixed;z-index:99999;left:0;top:0;width:360px;height:780px';document.body.append(canvas);const renderer=createVeilRenderer(canvas),duration=renderer.beginForcedReturn(run,{lost:{H:80,C:25,O:12,P:5,S:2,F:1,Cl:3},insights:['methane']}),firstParticle=run.lostCargoEffects[0],firstInsight=run.lostInsightEffects[0],cargoCount=run.lostCargoEffects.length,insightCount=run.lostInsightEffects.length,again=renderer.beginForcedReturn(run,{lost:{H:999},insights:['water','oxygen']}),sameCargo=firstParticle===run.lostCargoEffects[0]&&cargoCount===run.lostCargoEffects.length,sameInsights=firstInsight===run.lostInsightEffects[0]&&insightCount===run.lostInsightEffects.length;renderer.draw(run,0,false);const first=run.lostCargoEffects[0],bulb=run.lostInsightEffects[0],target=run.eaters[0],start={cargo:Math.hypot(first.x-target.x,first.y-target.y),bulb:Math.hypot(bulb.x-target.x,bulb.y-target.y)};globalThis.__forcedReturnFixture={run,renderer,canvas,start};return{canvas:[canvas.width,canvas.height],duration,again,cargo:run.lostCargoEffects.length,insights:run.lostInsightEffects.length,sameCargo,sameInsights,presentationStarted:run.forcedReturn.presentationStarted,start};})()`);
  assert.ok(setup.canvas[0]>0&&setup.canvas[1]>0);assert.equal(setup.duration,1.35);assert.equal(setup.again,1.35);assert.equal(setup.sameCargo,true,'Repeated forced-return initialization must not replace cargo particles');assert.equal(setup.sameInsights,true,'Repeated forced-return initialization must not replace Insight particles');assert.equal(setup.presentationStarted,true);assert.ok(setup.cargo>0&&setup.cargo<=36);assert.equal(setup.insights,1);

  const mid=await evaluate(`(()=>{const f=globalThis.__forcedReturnFixture,dt=1/60;for(let i=0;i<12;i++){f.run.time+=dt;f.run.eaters[0].y+=2;f.renderer.draw(f.run,dt,false);}const cargo=f.run.lostCargoEffects[0],bulb=f.run.lostInsightEffects[0],target=f.run.eaters[0];return{eater:{x:target.x,y:target.y},cargo:Math.hypot(cargo.x-target.x,cargo.y-target.y),bulb:Math.hypot(bulb.x-target.x,bulb.y-target.y),cargoPos:{x:cargo.x,y:cargo.y},bulbPos:{x:bulb.x,y:bulb.y},hash:(()=>{const s=f.canvas.toDataURL();let h=2166136261;for(let i=0;i<s.length;i+=17)h=Math.imul(h^s.charCodeAt(i),16777619);return h>>>0;})()};})()`);
  assert.equal(mid.eater.y,24,'Visual fixture moves the Dust Eater laterally during attraction');
  assert.ok(mid.cargo<setup.start.cargo,`Cargo particle must curve toward the current moving Eater target (${setup.start.cargo} -> ${mid.cargo})`);
  assert.ok(mid.bulb<setup.start.bulb,`Insight icon must curve toward the current moving Eater target (${setup.start.bulb} -> ${mid.bulb})`);
  assert.ok(mid.hash>0);

  const screenshot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});await mkdir(join(root,'test-results','forced-return-presentation'),{recursive:true});await writeFile(join(root,'test-results','forced-return-presentation','mobile-360x780.png'),Buffer.from(screenshot.data,'base64'));
  const reduced=await evaluate(`(()=>{const f=globalThis.__forcedReturnFixture,dt=1/60;f.run.time+=dt;f.run.eaters[0].y+=2;f.renderer.draw(f.run,dt,true);return{cargo:f.run.lostCargoEffects.length,insights:f.run.lostInsightEffects.length};})()`);
  assert.ok(reduced.cargo>0&&reduced.insights===1,'Reduced motion keeps loss readable without removing the loss visuals');
  assert.equal(exceptions.length,0,`Forced-return mobile render must not throw: ${JSON.stringify(exceptions)}`);
  console.log('Dust Eater forced-return Chromium',JSON.stringify({setup,mid,reduced}));
}finally{try{socket?.close();}catch{}try{child?.kill('SIGKILL');}catch{}await pause(100);server.close();await rm(profile,{recursive:true,force:true});}
console.log('Dust Eater forced-return mobile browser passed: capped cargo and 💡 visuals remain visible while tracking a moving Eater at 360x780, with reduced-motion coverage.');
