import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {mkdtemp,readFile,rm} from 'node:fs/promises';
import {spawn,spawnSync} from 'node:child_process';
import {extname,join,normalize,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {fileURLToPath} from 'node:url';

const root=resolve(fileURLToPath(new URL('..',import.meta.url))),types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.json':'application/json','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.webmanifest':'application/manifest+json'};
const server=createServer(async(req,res)=>{try{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname),relative=pathname==='/'?'index.html':pathname.replace(/^\/+/,''),file=normalize(join(root,relative));if(!file.startsWith(root)){res.writeHead(403).end();return;}const body=await readFile(file);res.writeHead(200,{'content-type':types[extname(file)]??'application/octet-stream','cache-control':'no-store'});res.end(body);}catch{res.writeHead(404).end('not found');}});
await new Promise(done=>server.listen(0,'127.0.0.1',done));const {port}=server.address(),origin=`http://127.0.0.1:${port}`;
let chrome='';for(const command of ['google-chrome','chromium','chromium-browser']){const found=spawnSync('which',[command],{encoding:'utf8'});if(found.status===0&&found.stdout.trim()){chrome=found.stdout.trim();break;}}assert.ok(chrome,'Chromium is required for Electrical mobile validation');
const profile=await mkdtemp(join(tmpdir(),'molecule-craft-electrical-')),debugPort=9263,pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));let child=null,socket=null;
try{
  child=spawn(chrome,['--headless=new','--no-sandbox','--disable-gpu','--disable-background-networking',`--user-data-dir=${profile}`,`--remote-debugging-port=${debugPort}`,'about:blank'],{stdio:['ignore','ignore','pipe']});let tabs=null,stderr='';child.stderr.setEncoding('utf8');child.stderr.on('data',chunk=>stderr+=chunk);
  for(let attempt=0;attempt<160;attempt++){try{const response=await fetch(`http://127.0.0.1:${debugPort}/json/list`);if(response.ok){tabs=await response.json();if(tabs.length)break;}}catch{}await pause(100);}assert.ok(tabs?.length,stderr.slice(-1000));
  socket=new WebSocket(tabs.find(tab=>tab.type==='page')?.webSocketDebuggerUrl??tabs[0].webSocketDebuggerUrl);await new Promise((ok,fail)=>{const timer=setTimeout(()=>fail(new Error('DevTools websocket timeout')),5000);socket.addEventListener('open',()=>{clearTimeout(timer);ok();},{once:true});socket.addEventListener('error',fail,{once:true});});
  let sequence=0;const pending=new Map(),exceptions=[];socket.addEventListener('message',event=>{const message=JSON.parse(event.data);if(message.id&&pending.has(message.id)){const task=pending.get(message.id);pending.delete(message.id);message.error?task.reject(new Error(message.error.message)):task.resolve(message.result);return;}if(message.method==='Runtime.exceptionThrown')exceptions.push(message.params.exceptionDetails);});
  const send=(method,params={})=>new Promise((resolveSend,reject)=>{const id=++sequence;pending.set(id,{resolve:resolveSend,reject});socket.send(JSON.stringify({id,method,params}));});const evaluate=async expression=>{const response=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(response.exceptionDetails)throw new Error(response.exceptionDetails.exception?.description??response.exceptionDetails.text);return response.result?.value;};
  await send('Runtime.enable');await send('Page.enable');await send('Emulation.setDeviceMetricsOverride',{width:360,height:780,deviceScaleFactor:1,mobile:true});await send('Page.navigate',{url:origin+'/'});await pause(500);
  const result=await evaluate(`(async()=>{const {createInitialResourcesState}=await import('/src/veil/resources-persistence.js');const [{createUniverse},{createRun,stepRun},{createVeilRenderer},{flightConfig},{ELECTRICAL_FIELD,ELECTRICAL_VISUAL_SAMPLES,electricalEffectiveAt}]=await Promise.all([import('/src/veil/universe.js'),import('/src/veil/expedition-run.js'),import('/src/veil/renderer.js'),import('/src/veil/growth.js'),import('/src/veil/electrical-field.js')]);const state=createInitialResourcesState();Object.assign(state.progress,{choCompleted:true,coreFractured:true,worldAwakened:true,rareEcologyEligible:true});const capabilities={combustionDrive:true,nitrogenField:true,coreFractured:true,worldAwakened:true,rareEcologyEligible:true},map=createUniverse(73,state.elements,{capabilities}),config=flightConfig(state),run=createRun(map,config,{predators:false}),center={x:ELECTRICAL_FIELD.lobes[1].x,y:ELECTRICAL_FIELD.lobes[1].y};Object.assign(run.player,{x:center.x,y:center.y,angle:-Math.PI/2,vx:0,vy:-config.speed,speed:config.speed});const canvas=document.createElement('canvas');canvas.style.cssText='position:fixed;left:0;top:0;width:360px;height:780px';document.body.append(canvas);const renderer=createVeilRenderer(canvas);stepRun(run,{x:1,y:0},1/60,{});renderer.draw(run,1/60,false);const screen=renderer.screen(center.x,center.y),effective=electricalEffectiveAt(center,map.worldState),visualSamples=ELECTRICAL_VISUAL_SAMPLES.filter(sample=>electricalEffectiveAt(sample,map.worldState)>0).length;return{canvas:[canvas.width,canvas.height],screen,effective,visualSamples,electrical:run.currentHazards.some(item=>item.type==='electrical'),control:run.electricalControlAuthority,propulsion:run.electricalPropulsionAuthority};})()`);
  assert.ok(result.canvas[0]>0&&result.canvas[1]>0);assert.ok(result.screen.x>=0&&result.screen.x<=360&&result.screen.y>=0&&result.screen.y<=780,'Electrical field center must be renderable in mobile viewport');assert.ok(result.effective>0&&result.visualSamples>8);assert.equal(result.electrical,true);assert.ok(result.control<1&&result.propulsion<1);assert.equal(exceptions.length,0,`Electrical mobile render must not throw: ${JSON.stringify(exceptions)}`);
  console.log('Electrical mobile Chromium',JSON.stringify(result));
}finally{try{socket?.close();}catch{}try{child?.kill('SIGKILL');}catch{}await pause(100);server.close();await rm(profile,{recursive:true,force:true});}
console.log('Electrical hazard mobile browser passed: deterministic field visual, live exposure and transient control degradation fit a 360x780 viewport.');
