import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {mkdir,mkdtemp,readFile,rm,writeFile} from 'node:fs/promises';
import {spawn,spawnSync} from 'node:child_process';
import {extname,join,normalize,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {fileURLToPath} from 'node:url';

const root=resolve(fileURLToPath(new URL('..',import.meta.url))),outputDir=join(root,'test-results','encyclopedia-chemistry-visuals');
const indexHtml=await readFile(join(root,'index.html'),'utf8');
const fixtureHtml=indexHtml.replace(/\s*<script type="module" src="\.\/src\/(?:app|pwa)\.js[^\"]*"><\/script>/g,'');
const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.json':'application/json','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.webmanifest':'application/manifest+json'};
const server=createServer(async(req,res)=>{try{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(pathname==='/__chemistry_visual_fixture__'){res.writeHead(200,{'content-type':'text/html; charset=utf-8','cache-control':'no-store'});res.end(fixtureHtml);return;}const relative=pathname==='/'?'index.html':pathname.replace(/^\/+/,''),file=normalize(join(root,relative));if(!file.startsWith(root)){res.writeHead(403).end();return;}const body=await readFile(file);res.writeHead(200,{'content-type':types[extname(file)]??'application/octet-stream','cache-control':'no-store'});res.end(body);}catch{res.writeHead(404).end('not found');}});
await new Promise(done=>server.listen(0,'127.0.0.1',done));const {port}=server.address();
let chrome='';for(const command of ['google-chrome','chromium','chromium-browser']){const found=spawnSync('which',[command],{encoding:'utf8'});if(found.status===0&&found.stdout.trim()){chrome=found.stdout.trim();break;}}
assert.ok(chrome,'Chromium is required for Encyclopedia chemistry visual validation');
const profile=await mkdtemp(join(tmpdir(),'molecule-craft-chemistry-visual-')),debugPort=9244;let child=null,socket=null;const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
try{
  child=spawn(chrome,['--headless=new','--no-sandbox','--disable-gpu','--disable-background-networking',`--user-data-dir=${profile}`,`--remote-debugging-port=${debugPort}`,'about:blank'],{stdio:['ignore','ignore','pipe']});let tabs=null;
  for(let attempt=0;attempt<120;attempt++){try{const response=await fetch(`http://127.0.0.1:${debugPort}/json/list`);if(response.ok){tabs=await response.json();if(tabs.length)break;}}catch{}await pause(100);}assert.ok(tabs?.length,'DevTools endpoint did not become ready');
  socket=new WebSocket(tabs.find(tab=>tab.type==='page')?.webSocketDebuggerUrl??tabs[0].webSocketDebuggerUrl);await new Promise((ok,fail)=>{const timer=setTimeout(()=>fail(new Error('DevTools websocket timeout')),5000);socket.addEventListener('open',()=>{clearTimeout(timer);ok();},{once:true});socket.addEventListener('error',fail,{once:true});});
  let sequence=0;const pending=new Map();socket.addEventListener('message',event=>{const message=JSON.parse(event.data);if(message.id&&pending.has(message.id)){const task=pending.get(message.id);pending.delete(message.id);message.error?task.reject(new Error(message.error.message)):task.resolve(message.result);}});
  const send=(method,params={})=>new Promise((ok,fail)=>{const id=++sequence;pending.set(id,{resolve:ok,reject:fail});socket.send(JSON.stringify({id,method,params}));});
  const evaluate=async expression=>{const response=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(response.exceptionDetails)throw new Error(response.exceptionDetails.exception?.description??response.exceptionDetails.text);return response.result?.value;};
  const waitFor=async(expression,message,attempts=100)=>{for(let i=0;i<attempts;i++){try{if(await evaluate(expression))return;}catch{}await pause(100);}throw new Error(message);};
  const screenshot=async name=>{const shot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});await mkdir(outputDir,{recursive:true});await writeFile(join(outputDir,name),Buffer.from(shot.data,'base64'));};
  await send('Runtime.enable');await send('Page.enable');await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await send('Page.navigate',{url:`http://127.0.0.1:${port}/__chemistry_visual_fixture__`});await pause(150);
  const ids=['benzene','toluene','pyridine','furan','water','hydrogen-chloride','ethanol','acetone','carbon-monoxide','nitromethane','ozone','nitrobenzene','2-nitrotoluene','2-4-dinitrotoluene','2-4-6-trinitrotoluene','sulfur-dioxide','sulfur-trioxide','sulfuric-acid','dimethyl-sulfoxide','phosphoric-acid'];
  const initialized=await evaluate(`(async()=>{const chemistry=await import('/src/chemistry.js?v=20'),loaded=await chemistry.loadMoleculeDatabase();if(!loaded.ok)return{ok:false};const records=chemistry.moleculeCatalog(),ids=${JSON.stringify(ids)},save={schemaVersion:3,discoveredMolecules:ids.map((id,index)=>({id,at:1700000000000+index,order:index+1})),discoveredGroups:[],unlockedStructures:[],legacyElements:[],milestones:[]},data=new Map([['molecule-craft.collection.v1',JSON.stringify(save)]]),storage={getItem:key=>data.get(key)??null,setItem:(key,value)=>data.set(key,value),removeItem:key=>data.delete(key)};const {createCollectionUI}=await import('/src/collection-ui.js?chemistry-visual-browser=1');window.__collection=await createCollectionUI({records,storage,onPlace:()=>{},canOpen:()=>true,elementAccess:()=>true,recipeState:()=>({recipes:ids,hints:[]})});return{ok:true};})()`);assert.deepEqual(initialized,{ok:true});

  async function inspect(id,{normalShot=false,detailShot=false}={}){
    assert.equal(await evaluate(`window.__collection.openMolecule(${JSON.stringify(id)})`),true,`${id}: open`);
    await waitFor(`document.querySelector('.molecule-detail-return')?.dataset.viewerReady==='true'`,`${id}: live 3D viewer did not become ready`,120);
    if(normalShot)await screenshot(`${id}-normal-mobile.png`);
    await evaluate(`document.querySelector('.detail-extras > summary').click()`);await pause(80);
    const result=await evaluate(`(()=>{const visuals=[...document.querySelectorAll('.chemistry-concept-visual')].map(node=>({type:node.dataset.visualType,text:node.textContent,ariaLabel:node.querySelector('svg')?.getAttribute('aria-label')??'',aromatic:!!node.querySelector('[data-aromatic-circle="true"]'),aromaticAtoms:[...node.querySelectorAll('[data-aromatic-atom-element]')].map(atom=>atom.dataset.aromaticAtomElement),lonePairRoles:[...node.querySelectorAll('[data-lone-pair-role]')].map(atom=>atom.dataset.lonePairRole),arc:!!node.querySelector('[data-delocalization="three-center"]'),distributed:[...node.querySelectorAll('[data-delocalization="distributed-bond"]')].map(n=>n.dataset.resonanceBranch??n.dataset.distributedBranch),distributedRoles:[...node.querySelectorAll('[data-delocalization="distributed-bond"]')].map(n=>n.dataset.sulfurBondRole??''),distributedStyles:[...node.querySelectorAll('[data-delocalization="distributed-bond"]')].map(n=>({stroke:n.getAttribute('stroke'),width:Number(n.getAttribute('stroke-width')),opacity:Number(n.getAttribute('stroke-opacity')),dash:n.getAttribute('stroke-dasharray'),style:n.dataset.resonanceStyle??n.dataset.distributedStyle,semantics:n.dataset.distributionSemantics})),sulfurPanels:[...node.querySelectorAll('[data-sulfur-panel]')].map(panel=>panel.dataset.sulfurPanel),sulfurBonds:[...node.querySelectorAll('[data-sulfur-bond-panel]')].map(bond=>({panel:bond.dataset.sulfurBondPanel,role:bond.dataset.sulfurBondRole,order:Number(bond.dataset.sulfurBondOrder)})),formalPositions:[...node.querySelectorAll('[data-charge-kind="formal"][data-charge-role]')].map(n=>({text:n.textContent,role:n.dataset.chargeRole,x:Number(n.getAttribute('x')),y:Number(n.getAttribute('y'))})),formal:[...node.querySelectorAll('[data-charge-kind="formal"]')].map(n=>n.textContent),partial:[...node.querySelectorAll('[data-charge-kind="partial"]')].map(n=>n.textContent),arrow:node.querySelector('[data-resonance-arrow="true"]')?.textContent??'',contributorBonds:Object.fromEntries(['A','B'].map(c=>[c,Object.fromEntries(['top','bottom','left','right'].map(branch=>[branch,node.querySelectorAll('[data-resonance-contributor="'+c+'"][data-resonance-branch="'+branch+'"]').length]))]))})),detail=document.querySelector('#collection-detail');return{visuals,width:detail.clientWidth,scrollWidth:detail.scrollWidth,docWidth:document.documentElement.clientWidth,docScrollWidth:document.documentElement.scrollWidth,noteSectionCount:detail.querySelectorAll('.model-collection-notes').length,detailText:detail.innerText};})()`);
    assert(result.scrollWidth<=result.width+1,`${id}: Chemistry visual must not overflow detail on mobile`);assert(result.docScrollWidth<=result.docWidth+1,`${id}: Chemistry visual must not overflow page on mobile`);assert.equal(result.noteSectionCount,0,`${id}: repeated model/collection note section removed`);assert.doesNotMatch(result.detailText,/模型・収録について/,`${id}: note heading must not remain`);
    assert(result.visuals.every(visual=>visual.ariaLabel.trim().length>12),`${id}: every chemistry figure has meaningful accessible text`);
    if(detailShot){await evaluate(`document.querySelector('.chemistry-concept-visual:last-of-type')?.scrollIntoView({block:'center'})`);await pause(60);await screenshot(`${id}-detail-mobile.png`);}
    return result;
  }

  async function distributedGeometry(id){
    return evaluate(`(async()=>{const THREE=await import('/vendor/three/three.module.min.js'),{createPreviewModel}=await import('/src/preview-model.js?bond-geometry-browser=1'),special=await import('/src/special-bonds.js?bond-geometry-browser=1'),{displayedBondOrder}=await import('/src/aromatic-rendering.js?bond-geometry-browser=1'),records=await fetch('/data/molecules.json').then(r=>r.json()),record=records.find(item=>item.id===${JSON.stringify(id)}),model=createPreviewModel(THREE,record);for(let i=0;i<220;i++)model.step();const layout=model.snapshot(),original=JSON.stringify(layout.bonds),shared=layout.sharedGroups.find(item=>['nitro','ozone','sulfur-oxo'].includes(item.kind)),point=index=>layout.atoms[index].point,curves=shared?special.sharedBondCurves(THREE,shared,point,{mode:'encyclopedia'}):[],craft=shared?special.sharedBondCurves(THREE,shared,point,{mode:'craft'}):[],rotation=new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(1,2,3).normalize(),.7),rotated=shared?special.sharedBondCurves(THREE,shared,index=>point(index).clone().applyQuaternion(rotation)):[],visual=special.createSharedBonds(THREE);if(shared)special.updateSharedBonds(THREE,visual,shared,point,{mode:'encyclopedia'});const keys=special.specialEdgeKeys(shared?[shared]:[]),baseOrders=layout.bonds.filter(bond=>keys.has([bond.a,bond.b].sort((a,b)=>a-b).join(':'))).map(bond=>displayedBondOrder(bond,keys)),visible=visual.children.filter(mesh=>mesh.visible);return{kind:shared?.kind??null,branches:curves.length,craftBranches:craft.length,rotationFollows:curves.every((curve,branch)=>curve.every((p,index)=>p.clone().applyQuaternion(rotation).distanceTo(rotated[branch][index])<1e-8)),legacyCurvedBand:visual.children.some(mesh=>mesh.userData.sharedOxoLine||mesh.userData.resonanceVisual==='shared-oxo-band'),visibleBranches:new Set(visible.map(mesh=>mesh.userData.distributedBondBranch)).size,visibleCount:visible.length,sulfurHasResonanceMetadata:visible.some(mesh=>mesh.userData.resonanceVisual!=null)&&shared?.kind==='sulfur-oxo',baseOrders,graphUnchanged:JSON.stringify(layout.bonds)===original};})()`);
  }

  const benzene=await inspect('benzene',{detailShot:true});assert.deepEqual(benzene.visuals.map(v=>v.type),['aromaticity']);assert(benzene.visuals[0].aromatic);assert.equal(benzene.visuals[0].arrow,'↔');
  const pyridine=await inspect('pyridine',{detailShot:true});assert.deepEqual(pyridine.visuals.map(v=>v.type),['aromaticity']);assert.equal(pyridine.visuals[0].aromaticAtoms.length,6);assert.equal(pyridine.visuals[0].aromaticAtoms.filter(element=>element==='N').length,1,'pyridine diagram uses its actual six-member N-containing ring');assert(pyridine.visuals[0].lonePairRoles.includes('in-plane-not-pi'));assert.equal(pyridine.visuals[0].arrow,'','pyridine uses topology view rather than benzene Kekule contributors');assert.match(pyridine.visuals[0].text,/環面内/);assert.match(pyridine.visuals[0].text,/含まれません/);
  const furan=await inspect('furan',{detailShot:true});assert.deepEqual(furan.visuals.map(v=>v.type),['aromaticity']);assert.equal(furan.visuals[0].aromaticAtoms.length,5,'furan diagram must be five-membered');assert.equal(furan.visuals[0].aromaticAtoms.filter(element=>element==='O').length,1,'furan diagram includes its oxygen');assert(furan.visuals[0].lonePairRoles.includes('pi-contributing'));assert.match(furan.visuals[0].text,/一組がπ系へ寄与/);assert.match(furan.visuals[0].text,/6π電子/);
  const water=await inspect('water',{detailShot:true});assert.deepEqual(water.visuals.map(v=>v.type),['polarity']);assert.match(water.visuals[0].text,/δ\+/);assert.match(water.visuals[0].text,/δ−/);assert.equal(water.visuals[0].formal.length,0);
  for(const id of ['hydrogen-chloride','ethanol','acetone']){const result=await inspect(id);assert.deepEqual(result.visuals.map(v=>v.type),['polarity'],`${id}: one curated polarity diagram`);assert(result.visuals[0].partial.length>0,`${id}: δ annotations`);}
  const co=await inspect('carbon-monoxide',{detailShot:true});assert.deepEqual(co.visuals.map(v=>v.type),['formal-charge']);assert.match(co.visuals[0].text,/C|形式電荷/);assert.match(co.visuals[0].text,/−/);assert.match(co.visuals[0].text,/\+/);assert.equal(co.visuals[0].partial.length,0);
  const nitro=await inspect('nitromethane',{normalShot:true,detailShot:true});assert.deepEqual(nitro.visuals.map(v=>v.type),['resonance']);assert.equal(nitro.visuals[0].arc,false);assert.deepEqual([...nitro.visuals[0].distributed].sort(),['bottom','top']);assert(nitro.visuals[0].distributedStyles.every(style=>style.stroke==='#67e8f9'&&style.width===3&&style.opacity===.68&&style.dash&&style.style==='distributed-dashed'),'nitro hybrid uses visible cyan same-width dashed components');assert.doesNotMatch(nitro.visuals[0].text,/薄い2本目線/);assert.deepEqual(nitro.visuals[0].formalPositions.map(c=>c.role).sort(),['center','center','terminal','terminal']);assert(nitro.visuals[0].formalPositions.filter(c=>c.role==='center').every(c=>c.y<60),'nitro N+ labels stay above the N/bond junction');assert.equal(nitro.visuals[0].arrow,'↔');assert.match(nitro.visuals[0].text,/N|形式|Lewis/);assert.deepEqual(nitro.visuals[0].contributorBonds.A,{top:2,bottom:1,left:0,right:0},'nitro contributor A must be R–N+(=O)–O−');assert.deepEqual(nitro.visuals[0].contributorBonds.B,{top:1,bottom:2,left:0,right:0},'nitro contributor B must swap both bond order and O−');
  const ozone=await inspect('ozone',{normalShot:true,detailShot:true});assert.deepEqual(ozone.visuals.map(v=>v.type),['resonance']);assert.equal(ozone.visuals[0].arc,false);assert.deepEqual([...ozone.visuals[0].distributed].sort(),['left','right']);assert(ozone.visuals[0].distributedStyles.every(style=>style.stroke==='#67e8f9'&&style.width===3&&style.opacity===.68&&style.dash&&style.style==='distributed-dashed'),'ozone hybrid uses visible cyan same-width dashed components');assert.doesNotMatch(ozone.visuals[0].text,/薄い2本目線/);assert.deepEqual(ozone.visuals[0].formalPositions.map(c=>c.role).sort(),['center','center','terminal','terminal']);assert.equal(ozone.visuals[0].arrow,'↔');assert.deepEqual(ozone.visuals[0].contributorBonds.A,{top:0,bottom:0,left:1,right:2},'ozone contributor A bond orders');assert.deepEqual(ozone.visuals[0].contributorBonds.B,{top:0,bottom:0,left:2,right:1},'ozone contributor B must swap bond order with terminal O−');
  const nitrobenzene=await inspect('nitrobenzene',{normalShot:true,detailShot:true});assert.deepEqual(nitrobenzene.visuals.map(v=>v.type),['aromaticity','resonance']);assert(nitrobenzene.visuals[0].aromatic&&nitrobenzene.visuals[1].distributed.length===2&&!nitrobenzene.visuals[1].arc,'nitrobenzene must combine aromatic circle grammar and distributed nitro resonance grammar');
  for(const id of ['2-nitrotoluene','2-4-dinitrotoluene','2-4-6-trinitrotoluene']){const result=await inspect(id);assert(result.visuals.some(v=>v.type==='aromaticity')&&result.visuals.some(v=>v.type==='resonance'),`${id}: aromatic + nitro resonance visuals`);}
  for(const [id,branches]of [['sulfur-dioxide',2],['sulfur-trioxide',3],['sulfuric-acid',2]]){
    const result=await inspect(id,{normalShot:true,detailShot:true});assert.deepEqual(result.visuals.map(v=>v.type),['distributed-bond'],`${id}: dedicated sulfur auxiliary-bond visual`);const visual=result.visuals[0];
    assert.equal(visual.arrow,'',`${id}: no resonance arrow`);assert.deepEqual(visual.sulfurPanels,['canonical','model'],`${id}: canonical and model panels appear in one figure`);assert.equal(visual.distributed.length,branches,`${id}: terminal sulfur-oxo branches only`);assert.deepEqual(visual.distributedRoles,Array(branches).fill('terminal'),`${id}: only terminal S–O bonds receive cyan dashes`);assert(visual.distributedStyles.every(style=>style.stroke==='#67e8f9'&&style.dash&&style.style==='distributed-dashed'&&style.semantics==='sulfur-oxo'),`${id}: cyan dashed marks carry sulfur-oxo semantics`);assert.match(visual.text,/通常の局在した追加結合線そのものではなく/);assert.match(visual.text,/等価なLewis寄与構造の間で単結合と二重結合が交換する意味ではありません/);
    for(const panel of ['canonical','model']){const bonds=visual.sulfurBonds.filter(bond=>bond.panel===panel);assert.equal(bonds.filter(bond=>bond.role==='terminal'&&bond.order===(panel==='canonical'?2:1)).length,branches*(panel==='canonical'?2:1),`${id}: ${panel} panel terminal S–O graph`);}
    if(id==='sulfur-dioxide')assert.match(result.detailText,/曲がった/);
    if(id==='sulfur-trioxide')assert.match(result.detailText,/気相のSO₃単量体/);
    if(id==='sulfuric-acid'){assert.equal(visual.sulfurBonds.filter(bond=>bond.panel==='model'&&bond.role==='s-oh'&&bond.order===1).length,2,'neutral sulfuric acid retains two distinct S–OH bonds');assert.equal(visual.sulfurBonds.filter(bond=>bond.panel==='model'&&bond.role==='o-h').length,2,'neutral sulfuric acid retains both O–H bonds');assert.match(result.detailText,/中性H₂SO₄/);assert.match(result.detailText,/硫酸イオンや硫酸水素イオン/);}
  }
  for(const [id,branches]of [['nitromethane',2],['ozone',2],['sulfur-dioxide',2],['sulfur-trioxide',3],['sulfuric-acid',2],['dimethyl-sulfoxide',0],['phosphoric-acid',0]]){const geometry=await distributedGeometry(id);assert.equal(geometry.branches,branches,`${id}: 3D Encyclopedia branch count`);assert.equal(geometry.craftBranches,branches,`${id}: CRAFT branch count agrees`);assert.equal(geometry.visibleBranches,branches,`${id}: mobile runtime exposes all parallel branches`);assert.equal(geometry.visibleCount,branches*4,`${id}: each branch has four visible dashes`);assert.equal(geometry.rotationFollows,true,`${id}: distributed geometry follows molecule rotation`);assert.equal(geometry.legacyCurvedBand,false,`${id}: no curved shared-oxo band remains`);assert.equal(geometry.graphUnchanged,true,`${id}: renderer leaves graph/bond order untouched`);assert.equal(geometry.sulfurHasResonanceMetadata,false,`${id}: sulfur metadata stays semantic-neutral`);if(branches)assert.deepEqual(geometry.baseOrders,Array(branches).fill(1),`${id}: distributed bonds receive one solid base stroke`);}
  await evaluate(`(()=>{window.__fallbackDashPatterns=[];const originalSetLineDash=CanvasRenderingContext2D.prototype.setLineDash,originalClearRect=CanvasRenderingContext2D.prototype.clearRect;CanvasRenderingContext2D.prototype.setLineDash=function(pattern){if(this.canvas?.classList?.contains('model-canvas')&&pattern.length)window.__fallbackDashPatterns.push([...pattern]);return originalSetLineDash.call(this,pattern);};CanvasRenderingContext2D.prototype.clearRect=function(...args){if(this.canvas?.classList?.contains('model-canvas'))window.__fallbackDashPatterns=[];return originalClearRect.apply(this,args);};const originalGetContext=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){if(type==='webgl2')return null;return originalGetContext.call(this,type,...args);};return true})()`);
  assert.equal(await evaluate(`window.__collection.openMolecule('sulfur-trioxide')`),true,'SO3 opens in software rendering fallback');
  await waitFor(`document.querySelector('.collection-model[data-render-mode="software-3d"] .model-canvas')!==null&&window.__fallbackDashPatterns.length===3`,'SO3 fallback must render all three distributed branches as dashed in a single frame',120);
  const fallbackVisual=await evaluate(`({mode:document.querySelector('.collection-model')?.dataset.renderMode,dashedBranches:window.__fallbackDashPatterns.length})`);
  assert.equal(fallbackVisual.mode,'software-3d');assert.equal(fallbackVisual.dashedBranches,3,'SO3 software fallback uses distributed dashed components for all three branches in one frame');
  const toluene=await inspect('toluene');assert.deepEqual(toluene.visuals.map(v=>v.type),['aromaticity']);assert.equal(toluene.visuals.some(v=>v.partial.length),false);

  const assets=await evaluate(`(async()=>Object.fromEntries(await Promise.all(${JSON.stringify(['nitromethane','ozone','nitrobenzene','2-4-6-trinitrotoluene','sulfur-dioxide','sulfur-trioxide','sulfuric-acid','dimethyl-sulfoxide','phosphoric-acid','carbon-monoxide'])}.map(async id=>[id,await fetch('/assets/models/molecule-'+id+'.svg').then(r=>r.text())]))))()`);
  for(const [id,count] of [['nitromethane',2],['ozone',2],['nitrobenzene',2],['2-4-6-trinitrotoluene',6]]){assert.equal((assets[id].match(/data-resonance-distributed-bond=\"true\"/g)??[]).length,count,`${id}: generated normal structure needs two weak bond components per resonance group`);assert.equal((assets[id].match(/data-resonance-style=\"distributed-dashed\"/g)??[]).length,count,`${id}: normal thumbnail resonance components are dashed`);assert.match(assets[id],/stroke=\"#66d8dc\"[^>]*stroke-opacity=\"0\.68\"[^>]*stroke-width=\"[^\"]+\"[^>]*stroke-dasharray=\"[^\"]+\"/,`${id}: normal thumbnail uses readable aromatic-accent dashed components`);assert.doesNotMatch(assets[id],/data-resonance-three-center=\"true\"/,`${id}: legacy three-center arc must be absent`);assert.doesNotMatch(assets[id],/<text[^>]*>[+−]<\/text>/,`${id}: resonance hybrid asset must not pin a formal charge to one contributor`);}
  for(const [id,count]of [['sulfur-dioxide',2],['sulfur-trioxide',3],['sulfuric-acid',2]]){assert.equal((assets[id].match(/data-distributed-bond="true"/g)??[]).length,count,`${id}: generated sulfur oxo has ${count} neutral distributed branches`);assert.equal((assets[id].match(/data-distributed-style="distributed-dashed"/g)??[]).length,count,`${id}: generated sulfur branches use dashed grammar`);assert.doesNotMatch(assets[id],/data-resonance-distributed-bond="true"/,'Sulfur visual carries no resonance semantics');}
  for(const id of ['dimethyl-sulfoxide','phosphoric-acid'])assert.doesNotMatch(assets[id],/data-distributed-bond="true"|data-resonance-distributed-bond="true"/,`${id}: negative-control asset stays generic`);
  assert.match(assets['carbon-monoxide'],/<text[^>]*>[+−]<\/text>/,'CO may retain its representative formal charges outside resonance-hybrid context');

  await send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});const reduced=await inspect('nitromethane');assert(reduced.visuals[0].distributed.length===2&&!reduced.visuals[0].arc&&reduced.visuals[0].arrow==='↔','reduced motion must preserve distributed resonance meaning without animation');
  await evaluate(`document.querySelector('.molecule-detail-return').dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}))`);await waitFor(`document.body.dataset.encyclopediaMoleculeOwner==='graph'&&document.querySelector('.graph-node.focus')?.dataset.graphId==='nitromethane'`,'Detail → Graph transition did not settle after chemistry visuals',80);
}finally{try{socket?.close();}catch{}try{child?.kill('SIGKILL');}catch{}await pause(100);server.close();await rm(profile,{recursive:true,force:true});}
console.log('Encyclopedia chemistry visual browser passed: mobile benzene/heteroaromatic topology, polarity, formal-charge, nitro/ozone resonance and sulfur distributed-bond semantics; reduced-motion and Graph return.');
