import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdtemp,rm} from 'node:fs/promises';
import {spawn,spawnSync} from 'node:child_process';
import {extname,join,normalize,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {fileURLToPath} from 'node:url';

const root=resolve(fileURLToPath(new URL('..',import.meta.url)));
const indexHtml=await readFile(join(root,'index.html'),'utf8');
const fixtureHtml=indexHtml.replace(/\s*<script type="module" src="\.\/src\/(?:app|pwa)\.js[^\"]*"><\/script>/g,'');
const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.webmanifest':'application/manifest+json'};
const server=createServer(async(req,res)=>{
  try{
    const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);
    if(pathname==='/__transition_fixture__'){res.writeHead(200,{'content-type':'text/html; charset=utf-8','cache-control':'no-store'});res.end(fixtureHtml);return;}
    const relative=pathname==='/'?'index.html':pathname.replace(/^\/+/,''),file=normalize(join(root,relative));
    if(!file.startsWith(root)){res.writeHead(403).end();return;}
    const body=await readFile(file);res.writeHead(200,{'content-type':types[extname(file)]??'application/octet-stream','cache-control':'no-store'});res.end(body);
  }catch{res.writeHead(404).end('not found');}
});
await new Promise(done=>server.listen(0,'127.0.0.1',done));const {port}=server.address();
let chrome='';for(const command of ['google-chrome','chromium','chromium-browser']){const found=spawnSync('which',[command],{encoding:'utf8'});if(found.status===0&&found.stdout.trim()){chrome=found.stdout.trim();break;}}
assert.ok(chrome,'Chromium is required for Encyclopedia transition visual validation');
const profile=await mkdtemp(join(tmpdir(),'molecule-craft-encyclopedia-transition-')),debugPort=9224;let child=null,socket=null;
try{
  child=spawn(chrome,['--headless=new','--no-sandbox','--disable-gpu','--disable-background-networking',`--user-data-dir=${profile}`,`--remote-debugging-port=${debugPort}`,'about:blank'],{stdio:['ignore','ignore','pipe']});let tabs=null;
  for(let attempt=0;attempt<120;attempt++){try{const response=await fetch(`http://127.0.0.1:${debugPort}/json/list`);if(response.ok){tabs=await response.json();if(tabs.length)break;}}catch{}await new Promise(r=>setTimeout(r,100));}
  assert.ok(tabs?.length,'DevTools endpoint did not become ready');socket=new WebSocket(tabs.find(tab=>tab.type==='page')?.webSocketDebuggerUrl??tabs[0].webSocketDebuggerUrl);
  await new Promise((ok,fail)=>{const timer=setTimeout(()=>fail(new Error('DevTools websocket timeout')),5000);socket.addEventListener('open',()=>{clearTimeout(timer);ok();},{once:true});socket.addEventListener('error',fail,{once:true});});
  let sequence=0;const pending=new Map();socket.addEventListener('message',event=>{const message=JSON.parse(event.data);if(message.id&&pending.has(message.id)){const task=pending.get(message.id);pending.delete(message.id);message.error?task.reject(new Error(message.error.message)):task.resolve(message.result);}});
  const send=(method,params={})=>new Promise((ok,fail)=>{const id=++sequence;pending.set(id,{resolve:ok,reject:fail});socket.send(JSON.stringify({id,method,params}));});
  const evaluate=async expression=>{const response=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(response.exceptionDetails)throw new Error(response.exceptionDetails.text);return response.result?.value;};
  const edgeSnapshot=()=>evaluate(`(()=>{const focus=document.querySelector('.graph-node.focus')?.dataset.graphId??null,lines=[...document.querySelectorAll('.graph-edge')],chevrons=[...document.querySelectorAll('.graph-edge-chevron')].filter(node=>getComputedStyle(node).visibility!=='hidden'),lineByKey=new Map(lines.map(line=>[line.dataset.edgeSource+'→'+line.dataset.edgeTarget,line])),distance=(p,a,b)=>{const dx=b.x-a.x,dy=b.y-a.y,l2=dx*dx+dy*dy;if(l2<1e-6)return Math.hypot(p.x-a.x,p.y-a.y);const t=Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.y-a.y)*dy)/l2)),q={x:a.x+dx*t,y:a.y+dy*t};return Math.hypot(p.x-q.x,p.y-q.y);},rows=chevrons.map(node=>{const key=node.dataset.edgeSource+'→'+node.dataset.edgeTarget,line=lineByKey.get(key),points=(node.getAttribute('points')??'').trim().split(/\\s+/).filter(Boolean).map(pair=>{const [x,y]=pair.split(',').map(Number);return{x,y};}),a=line?{x:Number(line.getAttribute('x1')),y:Number(line.getAttribute('y1'))}:null,b=line?{x:Number(line.getAttribute('x2')),y:Number(line.getAttribute('y2'))}:null,base=points.length===3?{x:(points[0].x+points[2].x)/2,y:(points[0].y+points[2].y)/2}:null,tip=points[1]??null,forward=!!(a&&b&&base&&tip&&((tip.x-base.x)*(b.x-a.x)+(tip.y-base.y)*(b.y-a.y)>0));return{key,incident:node.dataset.edgeSource===focus||node.dataset.edgeTarget===focus,aligned:!!(a&&b&&points.length===3&&points.every(point=>distance(point,a,b)<=1.65)),forward,animations:node.getAnimations().length};}),keys=rows.map(row=>row.key),stage=document.querySelector('.graph-stage'),stageRect=stage?.getBoundingClientRect();return{focus,count:rows.length,incident:rows.every(row=>row.incident),aligned:rows.every(row=>row.aligned),forward:rows.every(row=>row.forward),animations:rows.reduce((sum,row)=>sum+row.animations,0),duplicates:new Set(keys).size!==keys.length,stageInside:!!stageRect&&stageRect.left>=-1&&stageRect.right<=innerWidth+1,horizontalOverflow:document.documentElement.scrollWidth>innerWidth+1};})()`);
  const motionSample=(edgeKey,nodeId)=>evaluate(`(()=>{const [source,target]=${JSON.stringify(edgeKey)}.split('→'),line=[...document.querySelectorAll('.graph-edge')].find(node=>node.dataset.edgeSource===source&&node.dataset.edgeTarget===target),chevron=[...document.querySelectorAll('.graph-edge-chevron')].find(node=>node.dataset.edgeSource===source&&node.dataset.edgeTarget===target),selected=document.querySelector('[data-graph-id="${nodeId}"]'),nodeRect=selected?.getBoundingClientRect(),lineMatrix=line?.getScreenCTM(),chevronMatrix=chevron?.getScreenCTM(),toLineScreen=(x,y)=>lineMatrix?new DOMPoint(x,y).matrixTransform(lineMatrix):null,toChevronScreen=(x,y)=>chevronMatrix?new DOMPoint(x,y).matrixTransform(chevronMatrix):null,a=line?toLineScreen(Number(line.getAttribute('x1')),Number(line.getAttribute('y1'))):null,b=line?toLineScreen(Number(line.getAttribute('x2')),Number(line.getAttribute('y2'))):null,rawPoints=(chevron?.getAttribute('points')??'').trim().split(/\\s+/).filter(Boolean).map(pair=>{const [x,y]=pair.split(',').map(Number);return{x,y};}),points=rawPoints.map(point=>toChevronScreen(point.x,point.y)).filter(Boolean),cr=chevron?.getBoundingClientRect(),visible=!!chevron&&getComputedStyle(chevron).visibility!=='hidden'&&cr.width+cr.height>0,distance=(p,s,e)=>{if(!p||!s||!e)return Infinity;const dx=e.x-s.x,dy=e.y-s.y,l2=dx*dx+dy*dy;if(l2<1e-6)return Math.hypot(p.x-s.x,p.y-s.y);const t=Math.max(0,Math.min(1,((p.x-s.x)*dx+(p.y-s.y)*dy)/l2)),q={x:s.x+dx*t,y:s.y+dy*t};return Math.hypot(p.x-q.x,p.y-q.y);},base=points.length===3?{x:(points[0].x+points[2].x)/2,y:(points[0].y+points[2].y)/2}:null,tip=points[1]??null,forward=!!(a&&b&&base&&tip&&((tip.x-base.x)*(b.x-a.x)+(tip.y-base.y)*(b.y-a.y)>0)),inside=(p,r,margin=0)=>p&&Math.hypot(p.x-(r.left+r.width/2),p.y-(r.top+r.height/2))<Math.max(0,Math.min(r.width,r.height)/2+margin),nodeRects=[...document.querySelectorAll('.graph-node')].map(node=>node.getBoundingClientRect()),center=visible?{x:cr.left+cr.width/2,y:cr.top+cr.height/2}:null,clear=visible?nodeRects.every(r=>!inside(center,r,1)&&points.every(point=>!inside(point,r,.5))):true,aligned=visible?!!(a&&b&&points.length===3&&points.every(point=>distance(point,a,b)<=2)):true;return{focus:document.querySelector('.graph-node.focus')?.dataset.graphId??null,node:nodeRect?{x:nodeRect.left+nodeRect.width/2,y:nodeRect.top+nodeRect.height/2}:null,edge:a&&b?{a:{x:a.x,y:a.y},b:{x:b.x,y:b.y}}:null,chevron:{exists:!!chevron,visible,center,points:chevron?.getAttribute('points')??null,aligned,forward:visible?forward:true,clear,animations:chevron?.getAnimations().length??0}};})()`);
  const captureMotionTrace=async({label,edgeKey,nodeId,trigger})=>{const before=await motionSample(edgeKey,nodeId);await trigger();const samples=[];let elapsed=0;for(const at of [0,80,200,400,480,520,560,600]){const wait=Math.max(0,at-elapsed);if(wait)await new Promise(r=>setTimeout(r,wait));elapsed=at;samples.push({t:at,...await motionSample(edgeKey,nodeId)});}const distance=(a,b)=>a&&b?Math.hypot(b.x-a.x,b.y-a.y):0,visible=samples.filter(row=>row.chevron.visible&&row.chevron.center);console.log('CHEVRON_MOTION_TRACE',JSON.stringify({label,edgeKey,before,samples,chevronStepPx:visible.slice(1).map((row,index)=>Number(distance(visible[index].chevron.center,row.chevron.center).toFixed(3))),nodeStepPx:samples.slice(1).map((row,index)=>Number(distance(samples[index].node,row.node).toFixed(3))),edgeStartStepPx:samples.slice(1).map((row,index)=>Number(distance(samples[index].edge?.a,row.edge?.a).toFixed(3))),edgeEndStepPx:samples.slice(1).map((row,index)=>Number(distance(samples[index].edge?.b,row.edge?.b).toFixed(3)))}));return{before,samples,visible,distance};};
  const assertTraceGeometry=(trace,label)=>{assert.ok(trace.visible.every(row=>row.chevron.aligned),`${label}: every visible sample must stay on the current edge segment`);assert.ok(trace.visible.every(row=>row.chevron.forward),`${label}: every visible sample must keep current edge direction`);assert.ok(trace.visible.every(row=>row.chevron.clear),`${label}: every visible sample must stay outside node circles`);assert.ok(trace.samples.every(row=>row.chevron.animations===0),`${label}: Chevron must never own independent WAAPI`);};
  await send('Runtime.enable');await send('Page.enable');await send('Page.navigate',{url:`http://127.0.0.1:${port}/__transition_fixture__`});await new Promise(r=>setTimeout(r,120));
  const initialized=await evaluate(`(async()=>{
    const chemistry=await import('/src/chemistry.js?v=20');const loaded=await chemistry.loadMoleculeDatabase();if(!loaded.ok)return{ok:false,reason:'db'};
    const records=chemistry.moleculeCatalog(),save={schemaVersion:3,discoveredMolecules:['hydrogen','oxygen','n-butane','isobutane'].map((id,index)=>({id,at:index+1,order:index+1})),discoveredGroups:[],unlockedStructures:[],legacyElements:[],milestones:[]},data=new Map([['molecule-craft.collection.v1',JSON.stringify(save)]]),storage={getItem:key=>data.get(key)??null,setItem:(key,value)=>data.set(key,value),removeItem:key=>data.delete(key)};
    const {createCollectionUI}=await import('/src/collection-ui.js?v=39');window.__collection=await createCollectionUI({records,storage,onPlace:()=>{},canOpen:()=>true,elementAccess:()=>true,recipeState:()=>({recipes:['ethane','propane','n-pentane'],hints:[]})});return{ok:true,count:window.__collection.state.discoveredCount,text:document.querySelector('#open-collection')?.textContent??''};
  })()`);
  assert.deepEqual(initialized,{ok:true,count:4,text:'図鑑 4/136'});
  await evaluate(`document.querySelector('#open-collection').click()`);for(let i=0;i<40;i++){await new Promise(r=>setTimeout(r,50));if(await evaluate(`!!document.querySelector('.graph-node.focus.registered .graph-focus-thumbnail')`))break;}
  let initial=await evaluate(`(()=>{const node=document.querySelector('.graph-node.focus.registered'),visual=node?.querySelector('.graph-focus-thumbnail'),r=visual?.getBoundingClientRect();return{id:node?.dataset.graphId,rect:r&&{left:r.left,top:r.top,width:r.width,height:r.height}}})()`);
  assert.equal(initial.id,'isobutane','latest registered molecule is the Graph focus');assert.ok(initial.rect?.width>0);

  const directTrace=await captureMotionTrace({label:'direct-neighbor isobutane→n-butane / propane→n-butane',edgeKey:'propane→n-butane',nodeId:'n-butane',trigger:()=>evaluate(`document.querySelector('[data-graph-id="n-butane"]').click()`)});
  assertTraceGeometry(directTrace,'direct reroot');const directVisible=directTrace.visible;assert.ok(directVisible.length>=3,'direct reroot motion trace must observe a visible Chevron at multiple frames');const directMove=Math.hypot(directVisible.at(-1).chevron.center.x-directVisible[0].chevron.center.x,directVisible.at(-1).chevron.center.y-directVisible[0].chevron.center.y);assert.ok(directMove>2,`direct reroot Chevron must visibly move in screen-space, got ${directMove.toFixed(2)}px`);
  const focusEdges=await evaluate(`(()=>{const backgroundStyled=[...document.querySelectorAll('.graph-edge:not(.direct)')].filter(edge=>[...edge.classList].some(name=>name.startsWith('relation-')));return{chainLines:document.querySelectorAll('.graph-edge.direct.relation-chain-extension').length,chainChevrons:document.querySelectorAll('.graph-edge-chevron.relation-chain-extension').length,isomerChevrons:document.querySelectorAll('.graph-edge-chevron.relation-isomer').length,backgroundStyled:backgroundStyled.length};})()`),directSnapshot=await edgeSnapshot();
  await evaluate(`document.querySelector('[data-graph-id="isobutane"]')?.click()`);await new Promise(r=>setTimeout(r,620));
  const outgoingTrace=await captureMotionTrace({label:'direct-neighbor isobutane→n-butane / n-butane→n-pentane',edgeKey:'n-butane→n-pentane',nodeId:'n-butane',trigger:()=>evaluate(`document.querySelector('[data-graph-id="n-butane"]').click()`)});assertTraceGeometry(outgoingTrace,'second direct reroot');
  console.log('CHEVRON_SECOND_DIRECT_SUMMARY',JSON.stringify({visible:outgoingTrace.visible.map(row=>({t:row.t,center:row.chevron.center,edge:row.edge,node:row.node}))}));
  assert.equal(directSnapshot.focus,'n-butane');assert.ok(focusEdges.chainLines>=2,'focused n-butane must expose both shorter and longer chain-extension edges');assert.ok(focusEdges.chainChevrons>=2,'directional chain-extension focus edges need Chevrons');assert.equal(focusEdges.isomerChevrons,0,'isomer edge must not receive a directional Chevron');assert.equal(focusEdges.backgroundStyled,0,'background edges must remain relation-neutral');assert.equal(directSnapshot.incident,true,'only current-focus incident edges may own Chevrons');assert.equal(directSnapshot.aligned,true,'direct-neighbor reroot must keep every Chevron on its currently rendered edge during motion');assert.equal(directSnapshot.forward,true,'Chevron orientation must follow the current edge tangent');assert.equal(directSnapshot.animations,0,'Chevron must not own an independent WAAPI transition');assert.equal(directSnapshot.duplicates,false,'direct reroot must not duplicate edge markers');
  await evaluate(`document.querySelector('[data-graph-id="isobutane"]')?.click()`);await new Promise(r=>setTimeout(r,620));
  const branchBefore=await motionSample('ethane→propane','propane');assert.equal(branchBefore.chevron.exists,false,'ethane→propane must not own a Chevron before propane becomes focus/direct');
  const branchTrace=await captureMotionTrace({label:'non-focused isobutane→propane / newly-direct ethane→propane',edgeKey:'ethane→propane',nodeId:'propane',trigger:()=>evaluate(`window.dispatchEvent(new CustomEvent('molecule-craft:open-molecule',{detail:{id:'propane'}}))`)});
  assertTraceGeometry(branchTrace,'newly-direct reroot');const branchVisible=branchTrace.visible;const branchMove=branchVisible.length>1?Math.hypot(branchVisible.at(-1).chevron.center.x-branchVisible[0].chevron.center.x,branchVisible.at(-1).chevron.center.y-branchVisible[0].chevron.center.y):0;console.log('CHEVRON_NEWLY_DIRECT_SUMMARY',JSON.stringify({visibleCount:branchVisible.length,branchMove}));assert.ok(branchVisible.length>=2,'newly-direct Chevron must become safely visible before final commit and remain in shared edge motion');assert.ok(branchMove>1.5,`newly-direct Chevron must visibly move once a safe gap exists, got ${branchMove.toFixed(2)}px`);
  const branchOpen=await edgeSnapshot();assert.equal(branchOpen.focus,'propane','opening a known non-focused branch must reroot the Graph');assert.equal(branchOpen.aligned,true,'non-focused branch reroot must update edge and Chevron from the same geometry snapshot');assert.equal(branchOpen.incident,true);assert.equal(branchOpen.duplicates,false);
  const focusEdgeTrace=await captureMotionTrace({label:'focus-edge propane→n-butane center/neighbor swap',edgeKey:'propane→n-butane',nodeId:'n-butane',trigger:()=>evaluate(`document.querySelector('[data-graph-id="n-butane"]').click()`)});
  assertTraceGeometry(focusEdgeTrace,'focus-edge reroot');const focusEdgeVisible=focusEdgeTrace.visible,focusEdgeMove=focusEdgeVisible.length>1?Math.hypot(focusEdgeVisible.at(-1).chevron.center.x-focusEdgeVisible[0].chevron.center.x,focusEdgeVisible.at(-1).chevron.center.y-focusEdgeVisible[0].chevron.center.y):0;console.log('CHEVRON_FOCUS_EDGE_SUMMARY',JSON.stringify({visible:focusEdgeVisible.map(row=>({t:row.t,center:row.chevron.center,edge:row.edge,node:row.node})),focusEdgeMove}));
  assert.ok(focusEdgeMove>8,`focus-edge Chevron must visibly travel with reroot instead of remaining at an invariant midpoint, got ${focusEdgeMove.toFixed(2)}px`);
  await evaluate(`document.querySelector('[data-graph-id="isobutane"]')?.click()`);await new Promise(r=>setTimeout(r,620));
  await evaluate(`document.querySelector('[data-graph-id="n-butane"]').click()`);await new Promise(r=>setTimeout(r,35));await evaluate(`document.querySelector('[data-graph-id="isobutane"]').click()`);await new Promise(r=>setTimeout(r,35));await evaluate(`document.querySelector('[data-graph-id="n-butane"]').click()`);await new Promise(r=>setTimeout(r,70));
  const rapidFocus=await edgeSnapshot();assert.equal(rapidFocus.focus,'n-butane');assert.equal(rapidFocus.incident,true,'rapid focus replacement must leave no stale Chevron from the prior focus');assert.equal(rapidFocus.aligned,true,'rapid reroot replacement must keep current Chevrons attached to current edges');assert.equal(rapidFocus.duplicates,false,'rapid reroot must not duplicate edge/Chevron state');assert.ok(rapidFocus.count>0);
  await send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});await evaluate(`document.querySelector('[data-graph-id="isobutane"]').click()`);await new Promise(r=>setTimeout(r,70));
  const reducedEdges=await evaluate(`(()=>({direct:document.querySelectorAll('.graph-edge.direct[class*="relation-"]').length,nodeAnimations:[...document.querySelectorAll('.graph-node')].flatMap(node=>node.getAnimations()).filter(animation=>animation.playState!=='finished').length}))()`),reducedSnapshot=await edgeSnapshot();assert.ok(reducedEdges.direct>0,'reduced motion must retain relation styling');assert.equal(reducedEdges.nodeAnimations,0,'reduced motion must not leave reroot node animation running');assert.equal(reducedSnapshot.animations,0,'reduced motion must keep Chevron static');assert.equal(reducedSnapshot.aligned,true,'reduced motion must commit node/edge/Chevron to one layout snapshot');
  await send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'no-preference'}]});await send('Emulation.setDeviceMetricsOverride',{width:360,height:780,deviceScaleFactor:1,mobile:true});const mobileTrace=await captureMotionTrace({label:'360x780 isobutane→n-butane',edgeKey:'propane→n-butane',nodeId:'n-butane',trigger:()=>evaluate(`document.querySelector('[data-graph-id="n-butane"]').click()`)});assertTraceGeometry(mobileTrace,'360×780 reroot');const mobileVisible=mobileTrace.visible,mobileMove=mobileVisible.length>1?Math.hypot(mobileVisible.at(-1).chevron.center.x-mobileVisible[0].chevron.center.x,mobileVisible.at(-1).chevron.center.y-mobileVisible[0].chevron.center.y):0;assert.ok(mobileMove>2,`360×780 Chevron must visibly move in screen-space, got ${mobileMove.toFixed(2)}px`);
  const mobileSnapshot=await edgeSnapshot(),mobileEdges=await evaluate(`(()=>{const nodes=[...document.querySelectorAll('.graph-node')],chevrons=[...document.querySelectorAll('.graph-edge-chevron')].filter(node=>getComputedStyle(node).visibility!=='hidden'),inside=(x,y,r,margin=0)=>Math.hypot(x-(r.left+r.width/2),y-(r.top+r.height/2))<Math.max(0,Math.min(r.width,r.height)/2+margin),screenPoints=chevron=>{const matrix=chevron.getScreenCTM();return [...chevron.points].map(point=>new DOMPoint(point.x,point.y).matrixTransform(matrix));};return{width:innerWidth,count:chevrons.length,clear:chevrons.every(node=>{const r=node.getBoundingClientRect(),anchor={x:r.left+r.width/2,y:r.top+r.height/2},points=screenPoints(node);return nodes.every(graphNode=>{const circle=graphNode.getBoundingClientRect();return !inside(anchor.x,anchor.y,circle,1)&&points.every(point=>!inside(point.x,point.y,circle,.5));});}),minTap:Math.min(...nodes.map(node=>Math.min(node.getBoundingClientRect().width,node.getBoundingClientRect().height)))}})()`);assert.equal(mobileEdges.width,360);assert.equal(mobileSnapshot.focus,'n-butane');assert.ok(mobileEdges.count>0);assert.equal(mobileSnapshot.aligned,true,'360×780 reroot must keep Chevron on current edge geometry');assert.equal(mobileEdges.clear,true,'mobile Chevron anchor and glyph vertices must remain in the visible line gap with node clearance');assert.ok(mobileEdges.minTap>=60,'mobile node tap targets must not regress');assert.equal(mobileSnapshot.stageInside,true,'mobile Graph stage must remain inside the viewport');assert.equal(mobileSnapshot.horizontalOverflow,false,'mobile reroot must not introduce horizontal overflow');
  await send('Emulation.clearDeviceMetricsOverride');await evaluate(`document.querySelector('[data-graph-id="isobutane"]').click()`);await new Promise(r=>setTimeout(r,650));initial=await evaluate(`(()=>{const node=document.querySelector('.graph-node.focus.registered'),visual=node?.querySelector('.graph-focus-thumbnail'),r=visual?.getBoundingClientRect();return{id:node?.dataset.graphId,rect:r&&{left:r.left,top:r.top,width:r.width,height:r.height}}})()`);assert.equal(initial.id,'isobutane');assert.ok(initial.rect?.width>0);

  await evaluate(`document.querySelector('.graph-node.focus.registered').click()`);await new Promise(r=>setTimeout(r,70));
  const active=await evaluate(`(()=>{const p=document.querySelector('.encyclopedia-molecule-transition'),r=p?.getBoundingClientRect();return{owner:document.body.dataset.encyclopediaMoleculeOwner,id:document.body.dataset.encyclopediaMoleculeId,proxy:!!p,rect:r&&{left:r.left,top:r.top,width:r.width,height:r.height}}})()`);
  assert.equal(active.owner,'transition');assert.equal(active.id,'isobutane');assert.equal(active.proxy,true,'selected molecule proxy must remain visible while Graph is replaced');assert.ok(active.rect.width>0);
  await new Promise(r=>setTimeout(r,300));const mid=await evaluate(`(()=>{const r=document.querySelector('.encyclopedia-molecule-transition')?.getBoundingClientRect();return r&&{left:r.left,top:r.top,width:r.width,height:r.height}})()`);
  assert.ok(mid&&Math.hypot(mid.left-initial.rect.left,mid.top-initial.rect.top)>5,'molecule must visibly travel from the measured Graph node instead of crossfading in place');
  for(let i=0;i<30;i++){
    await new Promise(r=>setTimeout(r,60));
    const lifecycle=await evaluate(`(()=>({owner:document.body.dataset.encyclopediaMoleculeOwner,proxy:!!document.querySelector('.encyclopedia-molecule-transition')}))()`);
    if(lifecycle.owner==='detail')break;
    assert.equal(lifecycle.owner,'transition');assert.equal(lifecycle.proxy,true,'transition owner must always have a visible molecule proxy');
  }
  assert.equal(await evaluate(`document.body.dataset.encyclopediaMoleculeOwner`),'detail');assert.equal(await evaluate(`document.querySelector('.molecule-detail-return')?.dataset.moleculeId`),'isobutane');

  const navigated=await evaluate(`(()=>{const buttons=[...document.querySelectorAll('.molecule-detail-navigation button')].filter(button=>!button.disabled);if(!buttons.length)return false;buttons[0].click();return true;})()`);assert.equal(navigated,true);await new Promise(r=>setTimeout(r,140));
  const currentAfterNav=await evaluate(`document.querySelector('.molecule-detail-return')?.dataset.moleculeId`);assert.ok(currentAfterNav&&currentAfterNav!=='isobutane','prev/next must change the authoritative Detail molecule');
  await evaluate(`(()=>{const host=document.querySelector('.molecule-detail-return'),r=host.getBoundingClientRect(),o={bubbles:true,pointerId:41,button:0,clientX:r.left+r.width/2,clientY:r.top+r.height/2};host.dispatchEvent(new PointerEvent('pointerdown',o));host.dispatchEvent(new PointerEvent('pointerup',o));})()`);await new Promise(r=>setTimeout(r,60));assert.equal(await evaluate(`document.body.dataset.encyclopediaMoleculeId`),currentAfterNav);let preparedCurrentReturn=null;for(let i=0;i<30;i++){preparedCurrentReturn=await evaluate(`(()=>{const node=document.querySelector('.graph-node.focus');return{id:node?.dataset.graphId,motion:node?[...node.getAnimations()].filter(a=>(a.effect?.getTiming?.().duration??0)>0&&a.playState!=='finished').length:-1};})()`);if(preparedCurrentReturn.id===currentAfterNav)break;await new Promise(r=>setTimeout(r,30));}assert.equal(preparedCurrentReturn.id,currentAfterNav);assert.equal(preparedCurrentReturn.motion,0,'prev/next Detail return must prepare the current molecule directly at final Graph focus geometry');
  for(let i=0;i<30;i++){await new Promise(r=>setTimeout(r,60));if(await evaluate(`document.body.dataset.encyclopediaMoleculeOwner`)==='graph')break;}
  assert.equal(await evaluate(`document.body.dataset.encyclopediaMoleculeOwner`),'graph');assert.equal(await evaluate(`document.querySelector('.graph-node.focus')?.dataset.graphId`),currentAfterNav,'Detail close must land on current prev/next molecule');
  const afterDetailReturn=await edgeSnapshot();assert.equal(afterDetailReturn.aligned,true,'Detail→Graph return must not leave old edge geometry under the new focus');assert.equal(afterDetailReturn.duplicates,false);
  const postReturnTarget=await evaluate(`(()=>{const preferred=document.querySelector('[data-graph-id="isobutane"].neighbor')??document.querySelector('[data-graph-id="n-butane"].neighbor')??document.querySelector('.graph-node.neighbor');if(!preferred)return null;preferred.click();return preferred.dataset.graphId;})()`);assert.ok(postReturnTarget,'Detail→Graph return fixture must expose a reroot target');await new Promise(r=>setTimeout(r,90));const postReturnReroot=await edgeSnapshot();assert.equal(postReturnReroot.focus,postReturnTarget);assert.equal(postReturnReroot.aligned,true,'reroot immediately after Detail return must keep edge/Chevron ownership coherent');assert.equal(postReturnReroot.incident,true);
  if((await evaluate(`document.querySelector('.graph-node.focus')?.dataset.graphState`))!=='registered'){await evaluate(`document.querySelector('[data-graph-id="isobutane"]')?.click()`);await new Promise(r=>setTimeout(r,620));}

  await evaluate(`document.querySelector('.graph-node.focus').click()`);for(let i=0;i<30;i++){await new Promise(r=>setTimeout(r,60));if(await evaluate(`document.body.dataset.encyclopediaMoleculeOwner`)==='detail')break;}
  const beforeIsomer=await evaluate(`document.querySelector('.molecule-detail-return')?.dataset.moleculeId`),clickedIsomer=await evaluate(`(()=>{const button=[...document.querySelectorAll('button.collection-tag')].find(node=>node.textContent.includes('イソブタン')||node.textContent.includes('n-ブタン'));if(!button)return false;button.click();return true;})()`);assert.equal(clickedIsomer,true);await new Promise(r=>setTimeout(r,140));
  const isomerId=await evaluate(`document.querySelector('.molecule-detail-return')?.dataset.moleculeId`);assert.ok(isomerId&&isomerId!==beforeIsomer,'isomer navigation must update the current Detail molecule');
  await evaluate(`(()=>{const host=document.querySelector('.molecule-detail-return'),r=host.getBoundingClientRect(),o={bubbles:true,pointerId:42,button:0,clientX:r.left+r.width/2,clientY:r.top+r.height/2};host.dispatchEvent(new PointerEvent('pointerdown',o));host.dispatchEvent(new PointerEvent('pointerup',o));})()`);let preparedIsomerReturn=null;for(let i=0;i<30;i++){preparedIsomerReturn=await evaluate(`(()=>{const node=document.querySelector('.graph-node.focus');return{id:node?.dataset.graphId,motion:node?[...node.getAnimations()].filter(a=>(a.effect?.getTiming?.().duration??0)>0&&a.playState!=='finished').length:-1};})()`);if(preparedIsomerReturn.id===isomerId)break;await new Promise(r=>setTimeout(r,30));}assert.equal(preparedIsomerReturn.id,isomerId);assert.equal(preparedIsomerReturn.motion,0,'isomer Detail return must prepare the current isomer directly at final Graph focus geometry');for(let i=0;i<30;i++){await new Promise(r=>setTimeout(r,60));if(await evaluate(`document.body.dataset.encyclopediaMoleculeOwner`)==='graph')break;}
  assert.equal(await evaluate(`document.querySelector('.graph-node.focus')?.dataset.graphId`),isomerId,'isomer Detail must zoom back to the isomer node');

  await send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});await evaluate(`document.querySelector('.graph-node.focus').click()`);await new Promise(r=>setTimeout(r,90));
  assert.equal(await evaluate(`document.body.dataset.encyclopediaMoleculeOwner`),'detail');assert.equal(await evaluate(`document.querySelector('.molecule-detail-return')?.dataset.moleculeId`),isomerId,'reduced motion keeps the same current molecule handoff');
}finally{try{socket?.close();}catch{}try{child?.kill('SIGKILL');}catch{}await new Promise(r=>setTimeout(r,100));server.close();await rm(profile,{recursive:true,force:true});}
console.log('Encyclopedia browser transition passed: focus-edge relations/Chevrons, mobile/reduced-motion safety, measured Graph origin, continuous proxy, current prev/next + isomer return.');
