import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdtemp,rm} from 'node:fs/promises';
import {spawn,spawnSync} from 'node:child_process';
import {extname,join,normalize,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {fileURLToPath} from 'node:url';

const root=resolve(fileURLToPath(new URL('..',import.meta.url))),types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.webmanifest':'application/manifest+json'};
const server=createServer(async(req,res)=>{try{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname),relative=pathname==='/'?'index.html':pathname.replace(/^\/+/,''),file=normalize(join(root,relative));if(!file.startsWith(root)){res.writeHead(403).end();return;}const body=await readFile(file);res.writeHead(200,{'content-type':types[extname(file)]??'application/octet-stream','cache-control':'no-store'});res.end(body);}catch{res.writeHead(404).end('not found');}});
await new Promise(done=>server.listen(0,'127.0.0.1',done));const {port}=server.address();
let chrome='';for(const command of ['google-chrome','chromium','chromium-browser']){const found=spawnSync('which',[command],{encoding:'utf8'});if(found.status===0&&found.stdout.trim()){chrome=found.stdout.trim();break;}}assert.ok(chrome,'Chromium is required for Encyclopedia transition visual validation');
const profile=await mkdtemp(join(tmpdir(),'molecule-craft-encyclopedia-transition-')),debugPort=9224;let child=null,socket=null;
try{
  child=spawn(chrome,['--headless=new','--no-sandbox','--disable-gpu','--disable-background-networking',`--user-data-dir=${profile}`,`--remote-debugging-port=${debugPort}`,'about:blank'],{stdio:['ignore','ignore','pipe']});let tabs=null;
  for(let attempt=0;attempt<120;attempt++){try{const response=await fetch(`http://127.0.0.1:${debugPort}/json/list`);if(response.ok){tabs=await response.json();if(tabs.length)break;}}catch{}await new Promise(r=>setTimeout(r,100));}assert.ok(tabs?.length,'DevTools endpoint did not become ready');
  socket=new WebSocket(tabs.find(tab=>tab.type==='page')?.webSocketDebuggerUrl??tabs[0].webSocketDebuggerUrl);await new Promise((ok,fail)=>{const timer=setTimeout(()=>fail(new Error('DevTools websocket timeout')),5000);socket.addEventListener('open',()=>{clearTimeout(timer);ok();},{once:true});socket.addEventListener('error',fail,{once:true});});
  let sequence=0;const pending=new Map();socket.addEventListener('message',event=>{const message=JSON.parse(event.data);if(message.id&&pending.has(message.id)){const task=pending.get(message.id);pending.delete(message.id);message.error?task.reject(new Error(message.error.message)):task.resolve(message.result);}});const send=(method,params={})=>new Promise((ok,fail)=>{const id=++sequence;pending.set(id,{resolve:ok,reject:fail});socket.send(JSON.stringify({id,method,params}));});const evaluate=async expression=>(await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true})).result?.value;
  await send('Runtime.enable');await send('Page.enable');await send('Page.navigate',{url:`http://127.0.0.1:${port}/`});
  for(let i=0;i<80;i++){await new Promise(r=>setTimeout(r,100));if((await evaluate(`document.querySelector('#open-collection')?.textContent??''`)).includes('/129'))break;}
  const save={schemaVersion:3,discoveredMolecules:['hydrogen','oxygen','n-butane','isobutane'].map((id,index)=>({id,at:index+1,order:index+1})),discoveredGroups:[],unlockedStructures:[],legacyElements:[],milestones:[]};await evaluate(`localStorage.setItem('molecule-craft.collection.v1',${JSON.stringify(JSON.stringify(save))})`);await send('Page.reload');
  for(let i=0;i<100;i++){await new Promise(r=>setTimeout(r,100));if((await evaluate(`document.querySelector('#open-collection')?.textContent??''`)).includes('4/129'))break;}assert.match(await evaluate(`document.querySelector('#open-collection')?.textContent??''`),/4\/129/);
  await evaluate(`document.querySelector('#open-collection').click()`);for(let i=0;i<40;i++){await new Promise(r=>setTimeout(r,50));if(await evaluate(`!!document.querySelector('.graph-node.focus.registered .graph-focus-thumbnail')`))break;}
  const initial=await evaluate(`(()=>{const node=document.querySelector('.graph-node.focus.registered'),visual=node?.querySelector('.graph-focus-thumbnail');const r=visual?.getBoundingClientRect();return{id:node?.dataset.graphId,rect:r&&{left:r.left,top:r.top,width:r.width,height:r.height}}})()`);assert.equal(initial.id,'isobutane');assert.ok(initial.rect?.width>0);
  await evaluate(`document.querySelector('.graph-node.focus.registered').click()`);await new Promise(r=>setTimeout(r,70));const active=await evaluate(`(()=>{const p=document.querySelector('.encyclopedia-molecule-transition'),r=p?.getBoundingClientRect();return{owner:document.body.dataset.encyclopediaMoleculeOwner,id:document.body.dataset.encyclopediaMoleculeId,proxy:!!p,rect:r&&{left:r.left,top:r.top,width:r.width,height:r.height}}})()`);assert.equal(active.owner,'transition');assert.equal(active.id,'isobutane');assert.equal(active.proxy,true,'selected molecule proxy must remain visible while Graph is replaced');assert.ok(active.rect.width>0);
  await new Promise(r=>setTimeout(r,300));const mid=await evaluate(`(()=>{const r=document.querySelector('.encyclopedia-molecule-transition')?.getBoundingClientRect();return r&&{left:r.left,top:r.top,width:r.width,height:r.height}})()`);assert.ok(mid&&Math.hypot(mid.left-initial.rect.left,mid.top-initial.rect.top)>5,'molecule must visibly travel from the measured Graph node instead of crossfading in place');
  for(let i=0;i<30;i++){await new Promise(r=>setTimeout(r,60));const owner=await evaluate(`document.body.dataset.encyclopediaMoleculeOwner`);if(owner==='detail')break;assert.equal(owner,'transition');assert.equal(await evaluate(`!!document.querySelector('.encyclopedia-molecule-transition')`),true,'transition owner must always have a visible molecule proxy');}
  assert.equal(await evaluate(`document.body.dataset.encyclopediaMoleculeOwner`),'detail');assert.equal(await evaluate(`document.querySelector('.molecule-detail-return')?.dataset.moleculeId`),'isobutane');

  // Prev/next changes current molecule. Reverse transition must land on that current ID, not the original opener.
  const nextId=await evaluate(`(()=>{const buttons=[...document.querySelectorAll('.molecule-detail-navigation button')].filter(b=>!b.disabled);if(!buttons.length)return null;buttons[0].click();return true;})()`);assert.ok(nextId);await new Promise(r=>setTimeout(r,120));const currentAfterNav=await evaluate(`document.querySelector('.molecule-detail-return')?.dataset.moleculeId`);assert.notEqual(currentAfterNav,'isobutane');
  await evaluate(`(()=>{const host=document.querySelector('.molecule-detail-return'),r=host.getBoundingClientRect(),x=r.left+r.width/2,y=r.top+r.height/2,o={bubbles:true,pointerId:41,button:0,clientX:x,clientY:y};host.dispatchEvent(new PointerEvent('pointerdown',o));host.dispatchEvent(new PointerEvent('pointerup',o));})()`);await new Promise(r=>setTimeout(r,60));assert.equal(await evaluate(`document.body.dataset.encyclopediaMoleculeId`),currentAfterNav);
  for(let i=0;i<30;i++){await new Promise(r=>setTimeout(r,60));if(await evaluate(`document.body.dataset.encyclopediaMoleculeOwner`)==='graph')break;}assert.equal(await evaluate(`document.body.dataset.encyclopediaMoleculeOwner`),'graph');assert.equal(await evaluate(`document.querySelector('.graph-node.focus')?.dataset.graphId`),currentAfterNav,'Detail close must land on current prev/next molecule');

  // Isomer navigation also becomes authoritative for the reverse landing node.
  await evaluate(`document.querySelector('.graph-node.focus').click()`);for(let i=0;i<30;i++){await new Promise(r=>setTimeout(r,60));if(await evaluate(`document.body.dataset.encyclopediaMoleculeOwner`)==='detail')break;}const beforeIsomer=await evaluate(`document.querySelector('.molecule-detail-return')?.dataset.moleculeId`);const clickedIsomer=await evaluate(`(()=>{const b=[...document.querySelectorAll('button.collection-tag')].find(node=>node.textContent.includes('イソブタン')||node.textContent.includes('n-ブタン'));if(!b)return false;b.click();return true;})()`);assert.equal(clickedIsomer,true);await new Promise(r=>setTimeout(r,120));const isomerId=await evaluate(`document.querySelector('.molecule-detail-return')?.dataset.moleculeId`);assert.ok(isomerId&&isomerId!==beforeIsomer,'isomer navigation must update the current Detail molecule');await evaluate(`(()=>{const host=document.querySelector('.molecule-detail-return'),r=host.getBoundingClientRect(),o={bubbles:true,pointerId:42,button:0,clientX:r.left+r.width/2,clientY:r.top+r.height/2};host.dispatchEvent(new PointerEvent('pointerdown',o));host.dispatchEvent(new PointerEvent('pointerup',o));})()`);for(let i=0;i<30;i++){await new Promise(r=>setTimeout(r,60));if(await evaluate(`document.body.dataset.encyclopediaMoleculeOwner`)==='graph')break;}assert.equal(await evaluate(`document.querySelector('.graph-node.focus')?.dataset.graphId`),isomerId,'isomer Detail must zoom back to the isomer node');

  // Reduced motion keeps the same state/identity handoff without the long zoom.
  await send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});await evaluate(`document.querySelector('.graph-node.focus').click()`);await new Promise(r=>setTimeout(r,80));assert.equal(await evaluate(`document.body.dataset.encyclopediaMoleculeOwner`),'detail');const reducedId=await evaluate(`document.querySelector('.molecule-detail-return')?.dataset.moleculeId`);assert.equal(reducedId,isomerId);
}finally{try{socket?.close();}catch{}try{child?.kill('SIGKILL');}catch{}await new Promise(r=>setTimeout(r,100));server.close();await rm(profile,{recursive:true,force:true});}
console.log('Encyclopedia browser transition passed: measured Graph origin, continuous proxy, current prev/next + isomer return, reduced motion.');
