import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdtemp,rm} from 'node:fs/promises';
import {spawn,spawnSync} from 'node:child_process';
import {extname,join,normalize,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {fileURLToPath} from 'node:url';

const root=resolve(fileURLToPath(new URL('..',import.meta.url)));
const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.webmanifest':'application/manifest+json'};
const server=createServer(async(req,res)=>{
  try{
    const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname),relative=pathname==='/'?'index.html':pathname.replace(/^\/+/,''),file=normalize(join(root,relative));if(!file.startsWith(root)){res.writeHead(403).end();return;}
    let body=await readFile(file);if(relative==='src/veil/ui.js'){let source=body.toString('utf8');source=source.replace('export function createVeilUI({resources,canLeave=()=>true,onBeforeLaunch=()=>true,onCraft=()=>{},onCommit=()=>{}}){',"export function createVeilUI({resources,canLeave=()=>true,onBeforeLaunch=()=>true,onCraft=()=>{},onCommit=()=>{}}){globalThis.__fieldInsightBrowserResources=resources;");source=source.replace('function frame(now){',"function frame(now){globalThis.__fieldInsightBrowserRun=run;");body=Buffer.from(source);}
    res.writeHead(200,{'content-type':types[extname(file)]??'application/octet-stream','cache-control':'no-store'});res.end(body);
  }catch{res.writeHead(404).end('not found');}
});
await new Promise(resolveListen=>server.listen(0,'127.0.0.1',resolveListen));const {port}=server.address(),origin=`http://127.0.0.1:${port}`;
const candidates=['google-chrome','chromium','chromium-browser'];let chrome='';for(const command of candidates){const found=spawnSync('which',[command],{encoding:'utf8'});if(found.status===0&&found.stdout.trim()){chrome=found.stdout.trim();break;}}assert.ok(chrome,'A Chromium browser is required for FIELD Insight browser regression');
const profile=await mkdtemp(join(tmpdir(),'molecule-craft-insight-browser-')),debugPort=9227;let child=null,socket=null;
try{
  child=spawn(chrome,['--headless=new','--no-sandbox','--disable-gpu','--disable-background-networking',`--user-data-dir=${profile}`,`--remote-debugging-port=${debugPort}`,'about:blank'],{stdio:['ignore','ignore','pipe']});let stderr='';child.stderr.setEncoding('utf8');child.stderr.on('data',chunk=>stderr+=chunk);
  let tabs=null;for(let attempt=0;attempt<160;attempt++){try{const response=await fetch(`http://127.0.0.1:${debugPort}/json/list`);if(response.ok){tabs=await response.json();if(tabs.length)break;}}catch{}await new Promise(resolveWait=>setTimeout(resolveWait,100));}assert.ok(tabs?.length,`Chromium DevTools endpoint did not become ready: ${stderr.slice(-1000)}`);
  socket=new WebSocket(tabs.find(tab=>tab.type==='page')?.webSocketDebuggerUrl??tabs[0].webSocketDebuggerUrl);await new Promise((resolveOpen,reject)=>{const timer=setTimeout(()=>reject(new Error('DevTools websocket open timed out')),5000);socket.addEventListener('open',()=>{clearTimeout(timer);resolveOpen();},{once:true});socket.addEventListener('error',reject,{once:true});});
  let sequence=0;const pending=new Map(),exceptions=[];socket.addEventListener('message',event=>{const message=JSON.parse(event.data);if(message.id&&pending.has(message.id)){const task=pending.get(message.id);pending.delete(message.id);message.error?task.reject(new Error(message.error.message)):task.resolve(message.result);return;}if(message.method==='Runtime.exceptionThrown')exceptions.push(message.params.exceptionDetails);});
  const send=(method,params={})=>new Promise((resolveSend,reject)=>{const id=++sequence;pending.set(id,{resolve:resolveSend,reject});socket.send(JSON.stringify({id,method,params}));});
  const evaluate=async expression=>{const result=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(result.exceptionDetails)throw new Error(result.exceptionDetails.exception?.description??result.exceptionDetails.text);return result.result?.value;};
  const waitFor=async(expression,message,attempts=140)=>{for(let attempt=0;attempt<attempts;attempt++){try{if(await evaluate(expression))return true;}catch{}await new Promise(resolveWait=>setTimeout(resolveWait,100));}throw new Error(message);};
  await send('Runtime.enable');await send('Page.enable');await send('Page.navigate',{url:`${origin}/`});await waitFor(`document.querySelector('#open-collection')?.textContent?.includes('/136')`,'Application did not initialize');
  const seeded=await evaluate(`(async()=>{const [{createResources},{createMoleculeGraph}]=await Promise.all([import('/src/veil/resources.js'),import('/src/molecule-graph.js')]);const [records,raw]=await Promise.all([fetch('/data/molecules.json').then(r=>r.json()),fetch('/data/molecule-graph.json').then(r=>r.json())]);const r=createResources({storage:localStorage});r.setCatalog(records);Object.assign(r.state.progress,{regions:['veil','carbon','oxygen'],checkpoint:'veil',foundElements:['H','C','O']});r.state.recipes=['hydrogen','methane','oxygen','water'];r.state.hints=[];Object.assign(r.state.elements,{H:0,C:0,O:0,N:0});r.setFrontierGraph(createMoleculeGraph(raw));return {saved:r.save(),seed:r.insightSeedDiagnostics(),history:[...r.state.progress.insightDestinationHistory]};})()`);assert.equal(seeded.saved,true);assert.ok(seeded.seed.seedId);assert.ok(seeded.seed.hotDestination);assert.deepEqual(seeded.history,[seeded.seed.hotDestination],'first seed assignment is recorded exactly once');
  await send('Page.reload',{ignoreCache:true});await waitFor(`document.querySelectorAll('#expedition-destinations button.loadout-insight-hot').length===1`,'Persistent hot destination VFX did not appear');
  const desktop=await evaluate(`(()=>{const hot=document.querySelector('#expedition-destinations button.loadout-insight-hot'),state=JSON.parse(localStorage.getItem('molecule-craft.resources.v1')),dialog=document.querySelector('#supply-dialog');return {region:hot?.dataset.region,persisted:state.progress.insightSeed?.hotDestination,history:state.progress.insightDestinationHistory,count:document.querySelectorAll('#expedition-destinations button.loadout-insight-hot').length,filter:getComputedStyle(hot).filter,ring:getComputedStyle(hot,'::after').content,forbidden:/Insight|ひらめき|おすすめ/i.test(dialog?.textContent??'')};})()`);assert.equal(desktop.count,1);assert.equal(desktop.region,desktop.persisted);assert.deepEqual(desktop.history,[desktop.persisted],'reload cannot append the existing seed twice');assert.notEqual(desktop.filter,'none');assert.notEqual(desktop.ring,'none');assert.equal(desktop.forbidden,false,'LOADOUT must not explain the logo effect with text');
  await waitFor(`!!globalThis.__fieldInsightBrowserResources`,'Browser resource probe did not initialize');
  const advanced=await evaluate(`(()=>{const r=globalThis.__fieldInsightBrowserResources,before=r.insightSeedDiagnostics(),result=r.settleExpedition({H:0,C:0,O:0,N:0},0,false,{insights:[before.seedId]}),after=r.insightSeedDiagnostics();return {committed:result?.committedInsights?.includes(before.seedId)===true,before:before.hotDestination,after:after.hotDestination,history:[...r.state.progress.insightDestinationHistory]};})()`);assert.equal(advanced.committed,true);assert.notEqual(advanced.after,advanced.before,'successful ordinary commit advances the destination rotation');assert.equal(advanced.history.length,2);
  await waitFor(`document.querySelector('#expedition-destinations button.loadout-insight-hot')?.dataset.region===JSON.parse(localStorage.getItem('molecule-craft.resources.v1')).progress.insightSeed.hotDestination`,'LOADOUT destination hint did not follow the committed seed');
  const refreshed=await evaluate(`(()=>{const hot=document.querySelector('#expedition-destinations button.loadout-insight-hot'),saved=JSON.parse(localStorage.getItem('molecule-craft.resources.v1'));return {shown:hot?.dataset.region,persisted:saved.progress.insightSeed?.hotDestination,history:saved.progress.insightDestinationHistory};})()`);assert.equal(refreshed.shown,advanced.after);assert.deepEqual(refreshed.history,advanced.history);

  await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:2,mobile:true,screenWidth:390,screenHeight:844});await waitFor(`!!document.querySelector('#open-supply')&&!document.querySelector('#open-supply').disabled`,'LOADOUT trigger did not settle at 390×844');await evaluate(`(()=>{const button=document.querySelector('#open-supply'),dialog=document.querySelector('#supply-dialog');if(!dialog?.open)button?.click();return true;})()`);await waitFor(`document.querySelector('#supply-dialog')?.open===true`,'LOADOUT dialog did not open at 390×844');
  await evaluate(`(()=>{const h=document.querySelector('#collector-launch-handle'),r=h.getBoundingClientRect();h.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,pointerId:21,button:0,clientX:r.left+r.width/2,clientY:r.top+r.height/2}));h.dispatchEvent(new PointerEvent('pointerup',{bubbles:true,pointerId:21,button:0,clientX:r.left+r.width/2,clientY:r.top+r.height/2}));})()`);
  await waitFor(`(()=>{const hot=document.querySelector('#expedition-destinations button.loadout-insight-hot');if(!hot)return false;const r=hot.getBoundingClientRect(),style=getComputedStyle(hot);return r.width>=40&&r.height>=40&&Number(style.opacity)>=.75&&style.pointerEvents==='auto';})()`,'Hot destination did not settle to its mobile hit target');
  const mobile=await evaluate(`(()=>{const hot=document.querySelector('#expedition-destinations button.loadout-insight-hot'),r=hot.getBoundingClientRect(),map=document.querySelector('#supply-dialog .collector-shell-map').getBoundingClientRect();return {w:r.width,h:r.height,opacity:getComputedStyle(hot).opacity,pointer:getComputedStyle(hot).pointerEvents,inside:r.left>=map.left-2&&r.right<=map.right+2&&r.top>=map.top-2&&r.bottom<=map.bottom+2};})()`);assert.ok(mobile.w>=40&&mobile.h>=40);assert.ok(Number(mobile.opacity)>=.75,'breathing hot destination remains visibly present');assert.equal(mobile.pointer,'auto');assert.equal(mobile.inside,true,'hot destination remains usable inside mobile LOADOUT');
  const launchContracts=await evaluate(`(()=>{const r=globalThis.__fieldInsightBrowserResources,seed=r.insightSeedDiagnostics(),other=seed.availableDestinations.find(id=>id!==seed.hotDestination),history=[...r.state.progress.insightDestinationHistory];r.prepareExpedition({region:other});const unrelated=r.frontierInsightDiagnostics();r.prepareExpedition({region:seed.hotDestination});const target=r.frontierInsightDiagnostics();return {other,hot:seed.hotDestination,unrelatedActive:unrelated.activeForRun,targetActive:target.activeForRun,historyBefore:history,historyAfter:r.state.progress.insightDestinationHistory};})()`);assert.ok(launchContracts.other);assert.equal(launchContracts.unrelatedActive,false,'unrelated FIELD launch cannot activate the persistent Insight');assert.equal(launchContracts.targetActive,true,'the seeded destination activates its existing FIELD-managed flow');assert.deepEqual(launchContracts.historyAfter,launchContracts.historyBefore,'launch evaluation cannot advance destination history');
  await send('Emulation.clearDeviceMetricsOverride');

  const launched=await evaluate(`(()=>{const hot=document.querySelector('#expedition-destinations button.loadout-insight-hot');hot.click();return hot.dataset.region;})()`);await waitFor(`document.querySelector('#veil-view')?.hidden===false&&!!globalThis.__fieldInsightBrowserRun`,'Hot destination did not launch');await waitFor(`!!globalThis.__fieldInsightBrowserRun?.frontierInsightPlan`,'Production FIELD did not initialize its normal Insight run plan');
  const immediate=await evaluate(`(()=>{const run=globalThis.__fieldInsightBrowserRun;return {time:run.time,claimable:run.map.signals.filter(s=>s.claimable&&s.insightSite).length,hot:run.frontierInsightPlan?.hotDestination,region:run.region};})()`);assert.equal(immediate.hot,launched);assert.equal(immediate.claimable,0,'normal Insight cannot appear immediately after launch');

  const earlyArmed=await evaluate(`(()=>{const run=globalThis.__fieldInsightBrowserRun,p=run.frontierInsightPlan;p.earlyEnabled=true;p.earlyActivationTime=run.time+.05;p.earlyMinimumTravel=0;return true;})()`);assert.equal(earlyArmed,true);await waitFor(`globalThis.__fieldInsightBrowserRun?.map?.signals?.filter(s=>s.claimable&&s.insightSite).length===1`,'Seeded early Insight site did not activate');const early=await evaluate(`(()=>{const run=globalThis.__fieldInsightBrowserRun,s=run.map.signals.find(x=>x.claimable&&x.insightSite);return {id:s.insightSiteId,x:s.x,y:s.y,count:run.map.signals.filter(x=>x.claimable&&x.insightSite).length};})()`);assert.equal(early.count,1);

  await evaluate(`(()=>{const run=globalThis.__fieldInsightBrowserRun;run.time=Math.max(run.time,35);run.threat=100;run.nextEaterSpawn=run.time;return true;})()`);await waitFor(`globalThis.__fieldInsightBrowserRun?.eaters?.length>0`,'Dust Eater did not actually spawn for rescue regression');const firstSpawn=await waitFor(`globalThis.__fieldInsightBrowserRun?.frontierInsightPlan?.firstEaterSpawnTime!==null`,'Insight diagnostics did not record first actual Dust Eater spawn');assert.equal(firstSpawn,true);
  const rescueTarget=await evaluate(`(()=>{const run=globalThis.__fieldInsightBrowserRun,p=run.frontierInsightPlan;run.time=p.firstEaterSpawnTime+4.6;return true;})()`);assert.equal(rescueTarget,true);await waitFor(`globalThis.__fieldInsightBrowserRun?.frontierInsightPlan?.rescueEntered===true`,'Rescue phase did not start after first Eater + grace');
  const beforeRearm=await evaluate(`(()=>{const run=globalThis.__fieldInsightBrowserRun,p=run.frontierInsightPlan,s=run.map.signals.find(x=>x.insightSiteId===p.activeSiteId);Object.assign(run.player,{x:s.x+160,y:s.y,vx:0,vy:-100});return {id:p.activeSiteId,x:s.x,y:s.y,rearms:p.rearmCount};})()`);await new Promise(resolveWait=>setTimeout(resolveWait,120));
  await evaluate(`(()=>{const run=globalThis.__fieldInsightBrowserRun,p=run.frontierInsightPlan,s=run.map.signals.find(x=>x.insightSiteId===p.activeSiteId);run.time+=3;Object.assign(run.player,{x:s.x+650,y:s.y-650,vx:0,vy:-100});return true;})()`);await waitFor(`globalThis.__fieldInsightBrowserRun?.frontierInsightPlan?.rearmCount>${beforeRearm.rearms}`,'Missed rescue site did not re-arm');const afterRearm=await evaluate(`(()=>{const run=globalThis.__fieldInsightBrowserRun,p=run.frontierInsightPlan,old=run.map.signals.find(x=>x.insightSiteId===${JSON.stringify(beforeRearm.id)});return {id:p.activeSiteId,rearms:p.rearmCount,oldX:old.x,oldY:old.y,claimable:run.map.signals.filter(x=>x.claimable&&x.insightSite).length};})()`);assert.notEqual(afterRearm.id,beforeRearm.id);assert.equal(afterRearm.oldX,beforeRearm.x);assert.equal(afterRearm.oldY,beforeRearm.y);assert.equal(afterRearm.claimable,1,'rescue re-arm keeps exactly one ordinary opportunity');

  const analysis=await evaluate(`(()=>{const run=globalThis.__fieldInsightBrowserRun,p=run.frontierInsightPlan,s=run.map.signals.find(x=>x.insightSiteId===p.activeSiteId);Object.assign(run.player,{x:s.x,y:s.y,vx:0,vy:0});return {threat:run.threat,eaters:run.eaters.length};})()`);await waitFor(`!!globalThis.__fieldInsightBrowserRun?.analysis`,'Rescue site did not start the normal five-second analysis');const during=await evaluate(`(()=>{const run=globalThis.__fieldInsightBrowserRun;return {time:run.time,threat:run.threat,eaters:run.eaters.length,elapsed:run.analysis?.elapsed??0};})()`);await new Promise(resolveWait=>setTimeout(resolveWait,700));const later=await evaluate(`(()=>{const run=globalThis.__fieldInsightBrowserRun;return {time:run.time,threat:run.threat,eaters:run.eaters.length,elapsed:run.analysis?.elapsed??5};})()`);assert.ok(later.time>during.time+.4);assert.ok(later.threat>=during.threat,'FIELD threat clock continues during analysis');assert.ok(later.elapsed>during.elapsed,'normal analysis keeps advancing while threat remains active');assert.ok(analysis.eaters>0,'Insight acquisition did not create the first Eater; rescue was already driven by normal threat');
  assert.equal(exceptions.length,0,`FIELD Insight desktop/mobile flow must not throw: ${JSON.stringify(exceptions)}`);
}finally{try{socket?.close();}catch{}try{child?.kill('SIGKILL');}catch{}await new Promise(resolveWait=>setTimeout(resolveWait,100));server.close();await rm(profile,{recursive:true,force:true});}
console.log('FIELD Insight Chromium regression passed: subtle persistent hot logo, desktop/mobile interaction, early site, post-Eater rescue, re-arm and live threat during analysis.');
