import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {mkdtemp,readFile,rm} from 'node:fs/promises';
import {spawn,spawnSync} from 'node:child_process';
import {extname,join,normalize,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {fileURLToPath} from 'node:url';

const root=resolve(fileURLToPath(new URL('..',import.meta.url))),types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.json':'application/json','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.webmanifest':'application/manifest+json'};
const server=createServer(async(req,res)=>{try{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname),relative=pathname==='/'?'index.html':pathname.replace(/^\/+/,''),file=normalize(join(root,relative));if(!file.startsWith(root)){res.writeHead(403).end();return;}const body=await readFile(file);res.writeHead(200,{'content-type':types[extname(file)]??'application/octet-stream','cache-control':'no-store'});res.end(body);}catch{res.writeHead(404).end('not found');}});
await new Promise(done=>server.listen(0,'127.0.0.1',done));const {port}=server.address(),origin=`http://127.0.0.1:${port}`;
let chrome='';for(const command of ['google-chrome','chromium','chromium-browser']){const found=spawnSync('which',[command],{encoding:'utf8'});if(found.status===0&&found.stdout.trim()){chrome=found.stdout.trim();break;}}assert.ok(chrome,'Chromium is required for treatment validation');
const profile=await mkdtemp(join(tmpdir(),'molecule-craft-treatment-')),debugPort=9257,pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));let child=null,socket=null;
try{
  child=spawn(chrome,['--headless=new','--no-sandbox','--disable-gpu','--disable-background-networking',`--user-data-dir=${profile}`,`--remote-debugging-port=${debugPort}`,'about:blank'],{stdio:['ignore','ignore','pipe']});let tabs=null;
  for(let attempt=0;attempt<160;attempt++){try{const response=await fetch(`http://127.0.0.1:${debugPort}/json/list`);if(response.ok){tabs=await response.json();if(tabs.length)break;}}catch{}await pause(100);}assert.ok(tabs?.length);
  socket=new WebSocket(tabs.find(tab=>tab.type==='page')?.webSocketDebuggerUrl??tabs[0].webSocketDebuggerUrl);await new Promise((ok,fail)=>{const timer=setTimeout(()=>fail(new Error('DevTools websocket timeout')),5000);socket.addEventListener('open',()=>{clearTimeout(timer);ok();},{once:true});socket.addEventListener('error',fail,{once:true});});
  let sequence=0;const pending=new Map();socket.addEventListener('message',event=>{const message=JSON.parse(event.data);if(message.id&&pending.has(message.id)){const task=pending.get(message.id);pending.delete(message.id);message.error?task.reject(new Error(message.error.message)):task.resolve(message.result);}});const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++sequence;pending.set(id,{resolve,reject});socket.send(JSON.stringify({id,method,params}));});const evaluate=async expression=>{const response=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(response.exceptionDetails)throw new Error(response.exceptionDetails.exception?.description??response.exceptionDetails.text);return response.result?.value;};const waitFor=async(expression,message,attempts=180)=>{for(let i=0;i<attempts;i++){try{if(await evaluate(expression))return;}catch{}await pause(100);}throw new Error(message);};
  await send('Runtime.enable');await send('Page.enable');await send('Emulation.setDeviceMetricsOverride',{width:360,height:780,deviceScaleFactor:1,mobile:true});await send('Page.navigate',{url:origin+'/'});await waitFor("!!document.querySelector('#open-dock')&&!!document.querySelector('#open-supply')",'app did not initialize');
  const seeded=await evaluate(`(async()=>{localStorage.clear();const {createResources}=await import('/src/veil/resources.js');const records=await fetch('/data/molecules.json').then(r=>r.json());const r=createResources({storage:localStorage});r.setCatalog(records);Object.assign(r.state.progress,{choCompleted:true,coreFractured:true,worldAwakeningPending:false,worldAwakened:true,rareEcologyEligible:true});for(const id of ['phosphoric-acid','sulfuric-acid','difluoromethane'])r.discover(id);Object.assign(r.state.elements,{H:30,C:8,O:30,P:6,S:6,F:12});return r.save();})()`);assert.equal(seeded,true);
  await send('Page.reload',{ignoreCache:true});await waitFor("!!document.querySelector('#open-dock')&&document.querySelector('[data-treatment-process=mechanical]')",'DOCK treatments did not restore');
  await evaluate("document.querySelector('#open-dock').click();document.querySelector('[data-treatment-process=mechanical]').click()");await waitFor("document.querySelector('#dock-dialog')?.open&&!!document.querySelector('[data-dock-treatment-execute=mechanical]')",'mechanical treatment detail missing');
  const dock=await evaluate(`(()=>{const d=document.querySelector('#dock-dialog'),r=d.getBoundingClientRect(),s=document.querySelector('[data-treatment-process=abrasive]');return{top:r.top,bottom:r.bottom,left:r.left,right:r.right,text:d.textContent,abrasiveContext:s?.dataset.context,thermalStatus:document.querySelector('[data-treatment-process=thermal]')?.dataset.status};})()`);
  assert.ok(dock.top>=0&&dock.bottom<=780&&dock.left>=0&&dock.right<=360,'Treatment DOCK must fit mobile viewport');assert.equal(dock.abrasiveContext,'true');assert.match(dock.text,/Phosphoric Acid/);assert.match(dock.text,/Surface Pretreatment/);assert.match(dock.text,/Mechanical Load Resistance/);assert.match(dock.text,/MECHANICAL −45%/);
  const before=await evaluate("JSON.parse(localStorage.getItem('molecule-craft.resources.v1')).elements.P");assert.equal(before,6);
  await evaluate("(()=>{const b=document.querySelector('[data-dock-treatment-execute=mechanical]');b.click();b.click();})()");await waitFor("JSON.parse(localStorage.getItem('molecule-craft.resources.v1')).treatments.mechanical===1",'mechanical treatment did not commit');await waitFor("document.querySelector('[data-dock-treatment-execute=mechanical]')?.textContent==='ACTIVE 100%'",'DOCK treatment UI did not settle to active state');
  const committed=await evaluate(`(()=>{const s=JSON.parse(localStorage.getItem('molecule-craft.resources.v1')),b=document.querySelector('[data-dock-treatment-execute=mechanical]');return{P:s.elements.P,H:s.elements.H,O:s.elements.O,charge:s.treatments.mechanical,disabled:b.disabled,text:b.textContent};})()`);
  assert.deepEqual(committed,{P:4,H:24,O:22,charge:1,disabled:true,text:'ACTIVE 100%'},'double tap must consume exactly one treatment batch');
  await evaluate("document.querySelector('[data-dock-close]').click();document.querySelector('#open-supply').click();document.querySelector('#collector-launch-handle').dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}))");await waitFor("document.querySelector('#expedition-destinations [data-region=veil]')?.style.pointerEvents==='auto'",'launch destinations did not open');await evaluate("document.querySelector('#expedition-destinations [data-region=veil]').click()");await waitFor("document.body.dataset.mode==='veil'",'FIELD did not launch');
  await waitFor("!document.querySelector('#veil-treatments').hidden&&!document.querySelector('[data-treatment=mechanical]').hidden",'active treatment HUD did not appear');
  const hud=await evaluate(`(()=>{const h=document.querySelector('#veil-treatments'),r=h.getBoundingClientRect(),m=h.querySelector('[data-treatment=mechanical]');return{hidden:h.hidden,left:r.left,right:r.right,top:r.top,bottom:r.bottom,text:m.textContent,thermalHidden:h.querySelector('[data-treatment=thermal]').hidden,abrasiveHidden:h.querySelector('[data-treatment=abrasive]').hidden};})()`);
  assert.equal(hud.hidden,false);assert.ok(hud.left>=0&&hud.right<=360&&hud.top>=0&&hud.bottom<=780,'active treatment HUD must fit mobile viewport');assert.match(hud.text,/100%/);assert.equal(hud.thermalHidden,true);assert.equal(hud.abrasiveHidden,true);
  console.log('Treatment Chromium acceptance',JSON.stringify({dock,committed,hud}));
}finally{try{socket?.close();}catch{}try{child?.kill('SIGKILL');}catch{}await pause(100);server.close();await rm(profile,{recursive:true,force:true});}
console.log('Advanced DOCK treatment browser passed: mobile causal UI, exact one-batch transaction, contextual abrasive treatment and compact FIELD HUD.');
