import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createInsightPresentation,criticalInsightModels,insightAnalysisProgress,playerAnchoredInsightPosition} from '../src/veil/insight-presentation.js';
import {publishCollectorShellScreenAnchor,resetCollectorShellScreenAnchor} from '../src/veil/collector-shell.js';
import {createResources} from '../src/veil/resources.js';

const memory=()=>{const data=new Map();return {getItem:key=>data.get(key)??null,setItem:(key,value)=>data.set(key,value),removeItem:key=>data.delete(key)};};
class Element{
  constructor(tag,doc){this.tagName=tag.toUpperCase();this.ownerDocument=doc;this.children=[];this.attributes=new Map();this.style={setProperty(name,value){this[name]=value;}};this.dataset={};this.hidden=false;this.className='';this.id='';this.textContent='';this.offsetWidth=0;this.offsetHeight=0;}
  append(...nodes){this.children.push(...nodes);}
  replaceChildren(...nodes){this.children=[...nodes];}
  setAttribute(name,value){this.attributes.set(name,String(value));}
  getAttribute(name){return this.attributes.get(name)??null;}
  removeAttribute(name){this.attributes.delete(name);}
}
class Document{constructor(){this.head=new Element('head',this);this.nodes=new Map();}createElement(tag){return new Element(tag,this);}getElementById(id){return this.nodes.get(id)??null;}register(id,tag='div'){const node=new Element(tag,this);node.id=id;this.nodes.set(id,node);return node;}}
const text=node=>[node.textContent,...node.children.flatMap(child=>[text(child)])].join(' ');
const resources=createResources({storage:memory()}),formula=id=>resources.record(id)?.formula??({ethane:'C₂H₆'}[id]??id),doc=new Document(),root=new Element('section',doc),sounds=[];
resources.state.hints.length=0;resources.state.recipes.length=0;
const presentation=createInsightPresentation({root,resources,formula,audio:{event:type=>sounds.push(type)},document:doc});

assert.equal(insightAnalysisProgress({progress:.4,elapsed:99,requiredDuration:5}),.4,'run.analysis.progress is the presentation source of truth');
assert.equal(insightAnalysisProgress({elapsed:2.5,requiredDuration:5}),.5,'elapsed/duration remains a canonical fallback');
assert.equal(insightAnalysisProgress({progress:2}),1);assert.equal(insightAnalysisProgress({progress:-1}),0);
const centered=playerAnchoredInsightPosition({x:200,y:300},{w:400,h:600},{width:180,height:100},38);assert.deepEqual(centered,{x:200,y:262,side:'above'});
const topEdge=playerAnchoredInsightPosition({x:3,y:12},{w:320,h:480},{width:180,height:100},38);assert.equal(topEdge.side,'below');assert.equal(topEdge.x,100);assert.ok(topEdge.y>=10,'top-edge anchor flips below and remains in-bounds');
const bottomEdge=playerAnchoredInsightPosition({x:318,y:475},{w:320,h:480},{width:180,height:100},38);assert.equal(bottomEdge.side,'above');assert.equal(bottomEdge.x,220);assert.ok(bottomEdge.y<=470,'bottom-edge anchor stays in-bounds');

const normal={time:1,analysis:{id:'ethane',elapsed:1,requiredDuration:5,progress:.2},carriedInsights:[]};
resetCollectorShellScreenAnchor();presentation.sync(normal);assert.equal(presentation.nodes.group.hidden,true,'presentation waits for the renderer-owned player anchor');publishCollectorShellScreenAnchor({x:160,y:210,w:320,h:480,scale:1});assert.equal(presentation.nodes.group.hidden,false);assert.equal(presentation.nodes.group.style.left,'160px');assert.equal(presentation.nodes.group.dataset.anchorSide,'above');assert.equal(presentation.nodes.start.hidden,false,'analysis start has a one-shot capture state');assert.equal(presentation.nodes.analysis.hidden,false);assert.equal(presentation.nodes.analysis.getAttribute('aria-valuenow'),'20');assert.equal(presentation.nodes.analysisRing.style['--insight-progress'],'72deg');assert.doesNotMatch(text(presentation.nodes.analysis),/C₂H₆|ethane/,'analysis must not reveal molecule identity before resolution');assert.equal(presentation.nodes.analysis.dataset.insightCategory,undefined,'analysis must remain category-neutral');
publishCollectorShellScreenAnchor({x:238,y:250,w:320,h:480,scale:.7});assert.notEqual(presentation.nodes.group.style.left,'160px','player/camera screen movement updates the player anchor');normal.time=1.5;presentation.sync(normal);assert.equal(presentation.nodes.start.hidden,true,'analysis start effect expires from run time, not an independent timer');

normal.analysis=null;normal.carriedInsights=['ethane'];normal.inspiration='ethane';const fieldPrompt=doc.register('veil-craft-prompt'),fieldAction=doc.register('veil-to-craft','button'),fieldLabel=doc.register('veil-to-craft-label','span'),fieldAtoms=doc.register('veil-to-craft-atoms'),goalAction=doc.register('cho-goal-action','button'),goalLabel=doc.register('cho-goal-label','span'),goalAtoms=doc.register('cho-goal-atoms');fieldPrompt.hidden=false;fieldAction.setAttribute('aria-label','C₂H₆をクラフト');fieldLabel.textContent='C₂H₆';goalAction.setAttribute('aria-label','C₂H₆をクラフト');goalLabel.textContent='C₂H₆';fieldAtoms.append(new Element('i',doc));goalAtoms.append(new Element('i',doc));assert.equal(presentation.ready({type:'insightReady',id:'ethane',critical:false},normal),true);presentation.sync(normal);assert.equal(fieldPrompt.hidden,true,'normal ready cannot expose the fixed FIELD CRAFT prompt');assert.equal(fieldAction.getAttribute('aria-label'),null);assert.equal(fieldLabel.textContent,'');assert.equal(goalAction.getAttribute('aria-label'),null);assert.equal(goalLabel.textContent,'');assert.equal(fieldAtoms.children.length,0);assert.equal(goalAtoms.children.length,0);assert.equal(normal.inspiration,'ethane','identity concealment is presentation-only and does not mutate run state');assert.equal(presentation.nodes.analysis.hidden,true);assert.equal(presentation.nodes.ready.hidden,false);assert.equal(presentation.nodes.ready.dataset.insightCategory,'fuel');assert.match(presentation.nodes.readySymbol.className,/insight-bulb/);assert.doesNotMatch(text(presentation.nodes.ready),/C₂H₆|ethane/,'normal ready is bulb-only');assert.doesNotMatch(presentation.nodes.ready.getAttribute('aria-label'),/C₂H₆|ethane/,'normal ready ARIA must conceal identity');assert.match(presentation.nodes.ready.getAttribute('aria-label'),/FUEL/);assert.deepEqual(sounds,['insight']);assert.equal(presentation.nodes.normal.hidden,true,'the just-popped normal idea is not duplicated beside the ready bulb');
normal.time=2.7;presentation.sync(normal);assert.equal(presentation.nodes.ready.hidden,true,'ready presentation expires from run time');assert.equal(presentation.nodes.normal.hidden,false,'normal carried insight remains near the Collector Shell after ready');assert.equal(presentation.nodes.normal.children.length,1);assert.doesNotMatch(text(presentation.nodes.normal),/C₂H₆|ethane/);assert.doesNotMatch(presentation.nodes.normal.getAttribute('aria-label'),/C₂H₆|ethane/,'normal carried ARIA must conceal identity');

normal.carriedInsights=['ethane','normal-a','normal-b','normal-c','normal-d'];presentation.sync(normal);assert.equal(presentation.nodes.normal.children.length,4,'normal carried row caps direct bulbs at three and uses one overflow marker');assert.equal(presentation.nodes.normal.children.at(-1).textContent,'+2');assert.doesNotMatch(text(presentation.nodes.normal),/ethane|C₂H₆/);

const criticalRun={time:10,analysis:null,carriedInsights:['hydrogen','methane','oxygen','water']},models=criticalInsightModels(criticalRun,resources,formula),expectedCategories={hydrogen:'propellant',methane:'fuel',oxygen:'oxidizer',water:'coolant'};assert.equal(models.length,4);for(const model of models){assert.equal(model.category,expectedCategories[model.id]);assert.deepEqual(Object.fromEntries(model.atoms),resources.costFor(model.id));}
presentation.ready({type:'insightReady',id:'methane',critical:true},criticalRun);publishCollectorShellScreenAnchor({x:120,y:300,w:320,h:480,scale:1});presentation.sync(criticalRun);assert.equal(presentation.nodes.analysis.hidden,true,'critical insights bypass analysis UI');assert.match(presentation.nodes.ready.getAttribute('aria-label'),new RegExp(formula('methane')),'critical ready may reveal formula');assert.equal(presentation.nodes.critical.children.length,4);for(const chip of presentation.nodes.critical.children){const id=chip.dataset.insightId,cost=resources.costFor(id),chipText=text(chip);assert.equal(chip.dataset.insightCategory,expectedCategories[id]);assert.match(chip.children[0].className,/insight-bulb/);assert.match(chip.getAttribute('aria-label'),/用途 (PULSE|FUEL|OXIDIZER|COOLANT)/);assert.match(chipText,new RegExp(`CRAFT ${formula(id)}`));for(const [element,count] of Object.entries(cost))assert.match(chipText,new RegExp(`${element} ×${count}`));}
criticalRun.time=30;publishCollectorShellScreenAnchor({x:120,y:300,w:320,h:480,scale:1});presentation.sync(criticalRun);assert.equal(presentation.nodes.critical.children.length,4,'critical CRAFT targets persist while carried');

const captured={time:31,analysis:null,carriedInsights:['ethane','methane']};publishCollectorShellScreenAnchor({x:110,y:40,w:320,h:480,scale:1});presentation.sync(captured);captured.carriedInsights=[];presentation.clear();assert.equal(presentation.nodes.lossLayer.hidden,false,'capture starts a visible loss transition after run-local discard');assert.equal(presentation.nodes.normal.hidden,true);assert.equal(presentation.nodes.critical.children.length,0);assert.doesNotMatch(text(presentation.nodes.lossLayer),/C₂H₆|ethane/,'normal identity remains concealed during loss');assert.match(text(presentation.nodes.lossLayer),/CRAFT CH₄/,'critical loss may collapse the already-visible CRAFT target');

const returnRun={time:40,analysis:null,carriedInsights:['ethane']};presentation.clear();publishCollectorShellScreenAnchor({x:160,y:240,w:320,h:480,scale:1});presentation.sync(returnRun);assert.equal(presentation.nodes.normal.hidden,false,'normal carried display remains during normal return until completion');root.hidden=true;presentation.clear();assert.equal(root.hidden,true,'normal return completion hides the FIELD root while consuming the carried snapshot');presentation.clear();assert.equal(presentation.nodes.group.hidden,true,'the next launch hard-clears the consumed loss snapshot before FIELD becomes visible');root.hidden=false;

const generic=new Element('p',doc);generic.id='veil-message';generic.textContent='DANGER';generic.hidden=false;root.append(generic);presentation.ready({type:'insightReady',id:'ethane',critical:false},{time:50,analysis:null,carriedInsights:['ethane']});assert.equal(generic.textContent,'DANGER');assert.equal(generic.hidden,false,'dedicated insight layer must not overwrite generic FIELD notices');presentation.clear();

const reducedRoot=new Element('section',doc),reduced=createInsightPresentation({root:reducedRoot,resources,formula,audio:{event:()=>{}},reduced:true,document:doc});assert.equal(reduced.nodes.group.dataset.reduced,'true');
const css=await readFile(new URL('../src/veil/insight-presentation.css',import.meta.url),'utf8'),categoryCss=await readFile(new URL('../src/insight-category.css',import.meta.url),'utf8'),ui=await readFile(new URL('../src/veil/ui.js',import.meta.url),'utf8'),renderer=await readFile(new URL('../src/veil/renderer.js',import.meta.url),'utf8'),collector=await readFile(new URL('../src/veil/collector-shell.js',import.meta.url),'utf8');assert.match(css,/\.veil-insight-hud\{[^}]*position:absolute[^}]*pointer-events:none/);assert.doesNotMatch(css,/top:max\(/,'insight presentation must not retain the viewport-fixed HUD anchor');assert.match(css,/conic-gradient/,'analysis progress uses a radial meter');assert.match(css,/@media\(prefers-reduced-motion:reduce\)/);assert.match(css,/veil-insight-loss-reduced/,'reduced motion keeps loss as an opacity-only state change');assert.doesNotMatch(css,/animation:[^;}]*(infinite|linear infinite)/i);assert.match(categoryCss,/data-insight-category="fuel"/);assert.match(categoryCss,/\.insight-bulb\{[^}]*mask:/);assert.doesNotMatch(categoryCss,/opacity:\s*\.[0-4]/,'general bulb must not look disabled');assert.match(renderer,/const q=screen\(p\.x,p\.y\)/);assert.match(renderer,/drawCollectorShell\(ctx,\{x:q\.x,y:q\.y,angle:p\.angle,scale/,'anchor uses the exact renderer-computed Collector Shell screen position');assert.match(collector,/publishCollectorShellScreenAnchor\(\{x,y,w:width,h:height,scale\}\)/,'Collector Shell draw boundary forwards renderer screen coordinates without duplicating camera math');assert.match(ui,/insightAnalysisStart'\)\{insightPresentation\.sync\(run\)/,'analysis-start event enters the dedicated presentation');assert.match(ui,/if\(captured\)\{discardRunInsights\(run\);insightPresentation\.clear\(\)/,'capture discard and loss presentation share the same lifecycle boundary');assert.doesNotMatch(ui,/insightAnalysisStart'\)\{notice\(/,'analysis must not use the generic notice layer');

console.log('FIELD insight presentation passed: renderer-owned player anchor, radial anonymous analysis, bulb-only normal carry, canonical critical CRAFT targets, capture loss and reduced motion.');
