import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdtemp,rm} from 'node:fs/promises';
import {spawn,spawnSync} from 'node:child_process';
import {extname,join,normalize,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {fileURLToPath} from 'node:url';

const root=resolve(fileURLToPath(new URL('..',import.meta.url))),types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.json':'application/json','.css':'text/css','.svg':'image/svg+xml','.webmanifest':'application/manifest+json'};
const server=createServer(async(req,res)=>{try{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname),relative=pathname==='/'?'index.html':pathname.replace(/^\/+/,''),file=normalize(join(root,relative));if(!file.startsWith(root)){res.writeHead(403).end();return;}let body=await readFile(file);if(relative==='src/veil/ui.js'){let source=body.toString('utf8');source=source.replace('function frame(now){',"function frame(now){globalThis.__legacyFrontierRun=run;globalThis.__legacyFrontierResources=resources;");body=Buffer.from(source);}res.writeHead(200,{'content-type':types[extname(file)]??'application/octet-stream','cache-control':'no-store'});res.end(body);}catch{res.writeHead(404).end('not found');}});
await new Promise(done=>server.listen(0,'127.0.0.1',done));const {port}=server.address(),origin=`http://127.0.0.1:${port}`;
let chrome='';for(const command of ['google-chrome','chromium','chromium-browser']){const found=spawnSync('which',[command],{encoding:'utf8'});if(found.status===0&&found.stdout.trim()){chrome=found.stdout.trim();break;}}assert.ok(chrome,'A Chromium browser is required for legacy frontier regression');
const profile=await mkdtemp(join(tmpdir(),'molecule-craft-legacy-frontier-')),debugPort=9226;let child=null,socket=null;
try{
 child=spawn(chrome,['--headless=new','--no-sandbox','--disable-gpu','--disable-background-networking',`--user-data-dir=${profile}`,`--remote-debugging-port=${debugPort}`,'about:blank'],{stdio:['ignore','ignore','pipe']});let stderr='';child.stderr.setEncoding('utf8');child.stderr.on('data',chunk=>stderr+=chunk);
 let tabs=null;for(let i=0;i<160;i++){try{const response=await fetch(`http://127.0.0.1:${debugPort}/json/list`);if(response.ok){tabs=await response.json();if(tabs.length)break;}}catch{}await new Promise(r=>setTimeout(r,100));}assert.ok(tabs?.length,`Chromium DevTools endpoint did not become ready: ${stderr.slice(-1000)}`);
 socket=new WebSocket(tabs.find(tab=>tab.type==='page')?.webSocketDebuggerUrl??tabs[0].webSocketDebuggerUrl);await new Promise((resolveOpen,reject)=>{const timer=setTimeout(()=>reject(new Error('DevTools websocket open timed out')),5000);socket.addEventListener('open',()=>{clearTimeout(timer);resolveOpen();},{once:true});socket.addEventListener('error',reject,{once:true});});
 let sequence=0;const pending=new Map(),exceptions=[];socket.addEventListener('message',event=>{const message=JSON.parse(event.data);if(message.id&&pending.has(message.id)){const task=pending.get(message.id);pending.delete(message.id);message.error?task.reject(new Error(message.error.message)):task.resolve(message.result);return;}if(message.method==='Runtime.exceptionThrown')exceptions.push(message.params.exceptionDetails);});
 const send=(method,params={})=>new Promise((resolveSend,reject)=>{const id=++sequence;pending.set(id,{resolve:resolveSend,reject});socket.send(JSON.stringify({id,method,params}));});const evaluate=async expression=>{const result=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(result.exceptionDetails)throw new Error(result.exceptionDetails.exception?.description??result.exceptionDetails.text);return result.result?.value;};const waitFor=async(expression,message,attempts=120)=>{for(let i=0;i<attempts;i++){try{if(await evaluate(expression))return;}catch{}await new Promise(r=>setTimeout(r,100));}throw new Error(message);};
 await send('Runtime.enable');await send('Page.enable');await send('Page.navigate',{url:origin+'/'});await waitFor("document.querySelector('#open-collection')?.textContent?.includes('0/129')",'Application did not initialize');
 const seeded=await evaluate(`(async()=>{const {createResources}=await import('/src/veil/resources.js');const records=await fetch('/data/molecules.json').then(r=>r.json());const r=createResources({storage:localStorage});r.setCatalog(records);r.state.progress.choCompleted=true;r.state.progress.regions=['veil','carbon','oxygen','frontier'];r.state.progress.checkpoint='frontier';r.state.progress.frontier=true;r.state.progress.foundElements=['H','C','O'];r.state.recipes=['hydrogen','methane','oxygen','water'];Object.assign(r.state.elements,{H:500,C:500,O:500,N:0});return r.save();})()`);assert.equal(seeded,true);
 await send('Page.reload',{ignoreCache:true});await waitFor("(()=>{try{return JSON.parse(localStorage.getItem('molecule-craft.resources.v1')).progress.checkpoint==='oxygen'}catch{return false}})()",'legacy frontier save did not normalize during application startup');
 const normalized=await evaluate("JSON.parse(localStorage.getItem('molecule-craft.resources.v1')).progress.checkpoint");assert.equal(normalized,'oxygen','legacy frontier save must normalize at load');
 await evaluate("document.querySelector('#open-supply').click()");await waitFor("document.querySelectorAll('#expedition-destinations [data-region]').length>=4",'LOADOUT destinations did not render');
 const destinations=await evaluate("[...document.querySelectorAll('#expedition-destinations [data-region]')].map(node=>({id:node.dataset.region,tabIndex:node.tabIndex,label:node.getAttribute('aria-label')}))");assert.deepEqual(destinations.map(row=>row.id),['veil','carbon','oxygen','nitrogen']);assert.equal(destinations.some(row=>row.id==='frontier'||/Inner Horizon/i.test(row.label??'')),false,'swipe/pointer/keyboard/a11y candidates must exclude legacy frontier');
 const keyboard=await evaluate("(()=>{const handle=document.querySelector('#collector-launch-handle');handle.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}));return [...document.querySelectorAll('#expedition-destinations [data-region]')].filter(node=>node.tabIndex===0).map(node=>node.dataset.region);})()");assert.deepEqual(keyboard,['veil','carbon','oxygen','nitrogen']);
 await evaluate("document.querySelector('#expedition-destinations [data-region=veil]').click()");await waitFor("document.querySelector('#veil-view')?.hidden===false&&!!globalThis.__legacyFrontierRun",'H FIELD did not launch');exceptions.length=0;
 const hSignal=await evaluate("(()=>{const s=globalThis.__legacyFrontierRun.map.signals.find(signal=>signal.region==='veil');return s&&{id:s.id,region:s.region,insightRoll:Number.isFinite(s.roll),insightChoice:Number.isFinite(s.choice),hasWarp:Object.hasOwn(s,'warp'),hasDestination:Object.hasOwn(s,'destination')};})()");assert.deepEqual(hSignal,{id:'veil',region:'veil',insightRoll:true,insightChoice:true,hasWarp:false,hasDestination:false},'H-area ring-like entity is the current Insight signal, not a warp point');
 const hBehavior=await evaluate("(()=>{const run=globalThis.__legacyFrontierRun,s=run.map.signals.find(signal=>signal.region==='veil');run.predators=false;Object.assign(run.player,{x:s.x,y:s.y,angle:-Math.PI/2,vx:0,vy:0,speed:0});return {x:s.x,y:s.y};})()");await evaluate("new Promise(resolve=>setTimeout(resolve,300))");const afterH=await evaluate(`(()=>{const p=globalThis.__legacyFrontierRun.player;return Math.hypot(p.x-(${hBehavior.x}),p.y-(${hBehavior.y}));})()`);assert.ok(afterH<180,'H Insight marker contact must not teleport the player');
 const checkpointBeforeFrontier=await evaluate("globalThis.__legacyFrontierResources.state.progress.checkpoint");const frontierProbe=await evaluate("(()=>{const run=globalThis.__legacyFrontierRun;for(const signal of run.map.signals){signal.claimable=false;signal.ready=true;}Object.assign(run.player,{x:100,y:-11920,angle:-Math.PI/2,vx:0,vy:0,speed:0});return true;})()");assert.equal(frontierProbe,true);await waitFor("globalThis.__legacyFrontierRun.region==='frontier'",'Continuous traversal did not enter Inner Horizon spatial region',80);const noWarp=await evaluate("(()=>{const run=globalThis.__legacyFrontierRun,p=run.player,r=globalThis.__legacyFrontierResources;return {distance:Math.hypot(p.x-100,p.y+11920),checkpoint:r.state.progress.checkpoint,frontier:r.state.progress.frontier,boundsTop:run.config.bounds.top,nitrogenRoute:run.map.routes.some(route=>route.id==='nitrogen-main'),warpKeys:Object.keys(run.map).filter(key=>/warp|teleport/i.test(key))};})()");assert.ok(noWarp.distance<220,'old frontier launch coordinate must be ordinary traversable FIELD space with no teleport');assert.equal(noWarp.checkpoint,checkpointBeforeFrontier,'crossing frontier must not create or change a hidden relaunch checkpoint');assert.equal(noWarp.frontier,true);assert.ok(noWarp.boundsTop<-12750);assert.equal(noWarp.nitrogenRoute,true);assert.deepEqual(noWarp.warpKeys,[]);
 assert.equal(exceptions.length,0,`legacy frontier Chromium flow must not throw: ${JSON.stringify(exceptions)}`);
}finally{try{socket?.close();}catch{}try{child?.kill('SIGKILL');}catch{}await new Promise(r=>setTimeout(r,100));server.close();await rm(profile,{recursive:true,force:true});}
console.log('Legacy frontier Chromium regression passed: LOADOUT has no frontier candidate, legacy saves fall back safely, H marker is Insight, and old frontier coordinates are ordinary continuous FIELD space.');
