import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {mkdtemp,readFile,rm} from 'node:fs/promises';
import {spawn,spawnSync} from 'node:child_process';
import {extname,join,normalize,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {fileURLToPath} from 'node:url';

const root=resolve(fileURLToPath(new URL('..',import.meta.url)));
const indexHtml=await readFile(join(root,'index.html'),'utf8');
const fixtureHtml=indexHtml.replace(/\s*<script type="module" src="\.\/src\/(?:app|pwa)\.js[^\"]*"><\/script>/g,'');
const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.json':'application/json','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.webmanifest':'application/manifest+json'};
const server=createServer(async(req,res)=>{try{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(pathname==='/__loadout_transfer_fixture__'){res.writeHead(200,{'content-type':'text/html; charset=utf-8','cache-control':'no-store'});res.end(fixtureHtml);return;}const relative=pathname==='/'?'index.html':pathname.replace(/^\/+/,''),file=normalize(join(root,relative));if(!file.startsWith(root)){res.writeHead(403).end();return;}const body=await readFile(file);res.writeHead(200,{'content-type':types[extname(file)]??'application/octet-stream','cache-control':'no-store'});res.end(body);}catch{res.writeHead(404).end('not found');}});
await new Promise(done=>server.listen(0,'127.0.0.1',done));const {port}=server.address();
let chrome='';for(const command of ['google-chrome','chromium','chromium-browser']){const found=spawnSync('which',[command],{encoding:'utf8'});if(found.status===0&&found.stdout.trim()){chrome=found.stdout.trim();break;}}assert.ok(chrome,'Chromium is required for LOADOUT transfer validation');
const profile=await mkdtemp(join(tmpdir(),'molecule-craft-loadout-transfer-')),debugPort=9231;let child=null,socket=null;const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
try{
  child=spawn(chrome,['--headless=new','--no-sandbox','--disable-gpu','--disable-background-networking',`--user-data-dir=${profile}`,`--remote-debugging-port=${debugPort}`,'about:blank'],{stdio:['ignore','ignore','pipe']});let tabs=null;
  for(let attempt=0;attempt<120;attempt++){try{const response=await fetch(`http://127.0.0.1:${debugPort}/json/list`);if(response.ok){tabs=await response.json();if(tabs.length)break;}}catch{}await pause(100);}assert.ok(tabs?.length,'DevTools endpoint did not become ready');socket=new WebSocket(tabs.find(tab=>tab.type==='page')?.webSocketDebuggerUrl??tabs[0].webSocketDebuggerUrl);await new Promise((ok,fail)=>{const timer=setTimeout(()=>fail(new Error('DevTools websocket timeout')),5000);socket.addEventListener('open',()=>{clearTimeout(timer);ok();},{once:true});socket.addEventListener('error',fail,{once:true});});
  let sequence=0;const pending=new Map();socket.addEventListener('message',event=>{const message=JSON.parse(event.data);if(message.id&&pending.has(message.id)){const task=pending.get(message.id);pending.delete(message.id);message.error?task.reject(new Error(message.error.message)):task.resolve(message.result);}});const send=(method,params={})=>new Promise((ok,fail)=>{const id=++sequence;pending.set(id,{resolve:ok,reject:fail});socket.send(JSON.stringify({id,method,params}));});const evaluate=async expression=>{const response=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(response.exceptionDetails)throw new Error(response.exceptionDetails.text);return response.result?.value;};
  await send('Runtime.enable');await send('Page.enable');await send('Emulation.setDeviceMetricsOverride',{width:900,height:760,deviceScaleFactor:1,mobile:false});await send('Page.navigate',{url:`http://127.0.0.1:${port}/__loadout_transfer_fixture__`});await pause(120);
    // This legacy transfer fixture intentionally uses the canvas preview fallback;
    // the production LOADOUT path supplies complete flight-preview metadata.
    const initialized=await evaluate(`(async()=>{const mod=await import('/src/veil/loadout-workstation.js');const shell=await import('/src/veil/collector-shell.js');document.querySelector('#supply-dialog').showModal();const resources={state:{elements:{H:12,C:0,O:7,N:3,Cl:9,S:0,P:0,F:0}},canUseElement:symbol=>['H','C','O','N'].includes(symbol)};mod.syncLoadoutElementStock(resources,document);shell.drawCollectorShellPreview(document.querySelector('#collector-shell-preview'));const map=document.querySelector('#supply-dialog .collector-shell-map');delete map._loadoutFlightCraftPreview;mod.syncLaunchIntakeAnchor(map);window.__loadoutTransfer={mod,resources};return true;})()`);assert.equal(initialized,true);
  const inspect=()=>evaluate(`(()=>{const rect=node=>{const r=node?.getBoundingClientRect();return r&&{left:r.left,top:r.top,right:r.right,bottom:r.bottom,width:r.width,height:r.height,x:r.left+r.width/2,y:r.top+r.height/2}};const map=document.querySelector('#supply-dialog .collector-shell-map'),canvas=document.querySelector('#collector-shell-preview'),intake=document.querySelector('[data-launch-intake-anchor]'),stock=document.querySelector('#loadout-element-stock'),tokens=Object.fromEntries([...document.querySelectorAll('[data-loadout-stock-element]')].map(node=>[node.dataset.loadoutStockElement,{hidden:node.hidden,count:node.dataset.stockCount,tag:node.tagName,pointer:getComputedStyle(node).pointerEvents,rect:rect(node),atom:rect(node.querySelector('.atom-preview'))}]));const cr=rect(canvas),ir=rect(intake);return{viewport:{w:innerWidth,h:innerHeight},map:rect(map),canvas:cr,intake:ir,expected:{x:cr.left+cr.width*.39,y:cr.top+cr.height*.52},stock:rect(stock),tokens};})()`);
    let desktop=await inspect();assert.deepEqual([desktop.tokens.H.count,desktop.tokens.C.count,desktop.tokens.O.count,desktop.tokens.N.count],['12','0','7','3']);assert.equal(desktop.tokens.C.hidden,false,'unlocked zero-stock C remains visible');assert.equal(desktop.tokens.N.hidden,false,'unlocked N is visible');assert.equal(desktop.tokens.Cl.hidden,true,'locked rare element stays hidden');assert.equal(desktop.tokens.H.tag,'DIV');assert.equal(desktop.tokens.H.pointer,'none');assert(Math.abs(desktop.intake.x-desktop.expected.x)<1.5&&Math.abs(desktop.intake.y-desktop.expected.y)<1.5,`intake anchor must sit on the rendered machine center: ${JSON.stringify(desktop)}`);
  await evaluate(`(()=>{window.__loadoutTransfer.promise=window.__loadoutTransfer.mod.animateLoadoutElementTransfer({cost:{H:8,O:2},root:document,reduced:false});return true;})()`);await pause(55);const flight=await evaluate(`(()=>{const atoms=[...document.querySelectorAll('.loadout-transfer-atom')];return atoms.map(atom=>({element:atom.dataset.element,startX:+atom.dataset.startX,startY:+atom.dataset.startY,targetX:+atom.dataset.targetX,targetY:+atom.dataset.targetY,left:parseFloat(atom.style.left),top:parseFloat(atom.style.top)}));})()`);assert.equal(flight.length,6,'actual committed element kinds determine the visible transfer particles');assert.deepEqual([...new Set(flight.map(item=>item.element))].sort(),['H','O']);for(const atom of flight){const source=desktop.tokens[atom.element].atom;assert(Math.abs(atom.startX-source.x)<1&&Math.abs(atom.startY-source.y)<1,'atom starts at its rendered BASE STOCK atom');assert(Math.abs(atom.targetX-desktop.intake.x)<1&&Math.abs(atom.targetY-desktop.intake.y)<1,'atom ends at the rendered machine intake');assert(Math.abs(atom.left+11-atom.startX)<1&&Math.abs(atom.top+11-atom.startY)<1);}await evaluate(`window.__loadoutTransfer.promise`);
  const reduced=await evaluate(`window.__loadoutTransfer.mod.animateLoadoutElementTransfer({cost:{H:2},root:document,reduced:true})`);assert.equal(reduced.animated,false);assert.equal(reduced.reason,'reduced-motion');assert.equal(await evaluate(`document.querySelectorAll('.loadout-transfer-layer').length`),0);
  await send('Emulation.setDeviceMetricsOverride',{width:320,height:640,deviceScaleFactor:1,mobile:true});await pause(120);await evaluate(`window.__loadoutTransfer.mod.syncLaunchIntakeAnchor(document.querySelector('#supply-dialog .collector-shell-map'));(async()=>{const shell=await import('/src/veil/collector-shell.js');shell.drawCollectorShellPreview(document.querySelector('#collector-shell-preview'));window.__loadoutTransfer.mod.syncLaunchIntakeAnchor(document.querySelector('#supply-dialog .collector-shell-map'));})()`);await pause(40);const mobile=await inspect();assert.equal(mobile.viewport.w,320);assert(mobile.stock.left>=-1&&mobile.stock.right<=321,'BASE STOCK stays inside portrait viewport');assert(Math.abs(mobile.intake.x-mobile.expected.x)<1.5&&Math.abs(mobile.intake.y-mobile.expected.y)<1.5,'portrait intake follows responsive machine geometry');for(const symbol of ['H','C','O','N'])assert(mobile.tokens[symbol].rect.left>=mobile.stock.left-1&&mobile.tokens[symbol].rect.right<=mobile.stock.right+1,'visible stock tokens remain within LOADOUT stock panel');
  await send('Emulation.setDeviceMetricsOverride',{width:1000,height:520,deviceScaleFactor:1,mobile:false});await pause(100);await evaluate(`window.__loadoutTransfer.mod.syncLaunchIntakeAnchor(document.querySelector('#supply-dialog .collector-shell-map'))`);const wide=await inspect();assert.equal(wide.viewport.w,1000);assert(Math.abs(wide.intake.x-wide.expected.x)<1.5&&Math.abs(wide.intake.y-wide.expected.y)<1.5,'wide viewport intake remains bound to machine geometry');
}finally{try{socket?.close();}catch{}try{child?.kill('SIGKILL');}catch{}await pause(100);server.close();await rm(profile,{recursive:true,force:true});}
console.log('LOADOUT transfer browser validation passed: read-only H/C/O/N stock, zero stock, actual H/O transfer origins, machine intake endpoint, portrait/wide responsiveness and reduced motion.');
