import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {mkdtemp,readFile,rm,mkdir,writeFile} from 'node:fs/promises';
import {spawn,spawnSync} from 'node:child_process';
import {extname,join,normalize,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {fileURLToPath} from 'node:url';

const root=resolve(fileURLToPath(new URL('..',import.meta.url))),routes=JSON.parse(await readFile(join(root,'data/polymerization-routes.json'),'utf8')).routes,polymers=JSON.parse(await readFile(join(root,'data/polymers.json'),'utf8'));
const viewport=process.env.MATERIAL_PROGRESS_DESKTOP==='1'?{width:1280,height:900,mobile:false}:{width:390,height:844,mobile:true};
const evidenceDir=resolve(process.env.TASK10_EVIDENCE_DIR??join(root,'test-results/material-progression'));
const hardRouteIds=['polybutadiene-coordination-1-4','polyacrylonitrile-radical','phenol-formaldehyde-resole','polyvinyl-chloride-radical'];
const hardRoutes=hardRouteIds.map(id=>routes.find(route=>route.routeId===id));assert.equal(hardRoutes.filter(Boolean).length,4);
// This browser resumes a checkpoint earned by production flight, pickup and CRAFT APIs.
// It never seeds polymer discovery, engineering.fabricated or activeApplications.
import {preCoreCheckpoint,awaken,acquireRare,craftInputs} from './helpers/material-progression-fixture.mjs';
const {resources,storage}=preCoreCheckpoint(),checkpointBefore={worldAwakening:resources.worldAwakeningState(),engineering:resources.engineeringState(),collectorShell:resources.collectorShellState()},awakening=awaken(resources);
const rareAcquisitions=[];for(const [element,region] of [['P','veil'],['S','carbon'],['Cl','nitrogen']])rareAcquisitions.push(acquireRare(resources,element,region));
const requiredMolecules=['1-3-butadiene','acrylonitrile','phenol','formaldehyde','vinyl-chloride','phosphoric-acid','water'];craftInputs(resources,storage,requiredMolecules);resources.save();
const checkpoint=Object.fromEntries(storage.values);
const journeyEvidence=[{step:0,action:'Earn world awakening, rare-element stock, and required molecule access through production progression APIs',beforeState:checkpointBefore,result:{awakening,rareAcquisitions,requiredMolecules},afterState:{worldAwakening:resources.worldAwakeningState(),elements:{P:resources.state.elements.P,S:resources.state.elements.S,Cl:resources.state.elements.Cl},savedKeys:Object.keys(checkpoint)},persistentAuthority:'molecule-craft.resources.v1 + existing molecule Collection save',expectedInvariant:'Prerequisites are legitimately earned; polymer discovery, fabricated applications, and active application state remain unset.'}];
assert.equal(Object.values(resources.engineeringState().fabricated).some(Boolean),false);assert.equal(Object.values(resources.collectorShellState().activeApplications).some(Boolean),false);
const indexHtml=await readFile(join(root,'index.html'),'utf8'),mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.json':'application/json','.css':'text/css; charset=utf-8','.svg':'image/svg+xml'};
const server=createServer(async(req,res)=>{try{
  const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname),file=normalize(join(root,pathname==='/'?'index.html':pathname.replace(/^\/+/,'')));if(!file.startsWith(root)){res.writeHead(403).end();return;}
  res.writeHead(200,{'content-type':mime[extname(file)]??'application/octet-stream','cache-control':'no-store'});let body=await readFile(file);
  if(pathname==='/src/veil/ui.js')body=Buffer.from(body.toString().replace('function frame(now){','function frame(now){globalThis.__materialFieldProbe=()=>({run,renderer});'));
  if(pathname==='/src/reaction-lab-viewer.js'){
    const source=body.toString(),marker='      polymerDockPlan(instanceId){';assert.ok(source.includes(marker),'test-only polymer docking probe injection point remains present');
    const diagnosticMethod=`      polymerDockDiagnostics(instanceId){const item=instanceById(instanceId);if(!item)throw Error('Missing polymer Feed molecule '+instanceId);const preview=polymerInteraction(item);if(!preview.ok)throw Error('Polymer interaction is not available: '+preview.reason);const interaction=preview.interaction,target=polymerTargetWorld(interaction),withinRange=polymerDockPoses(item,interaction)??[],unbounded=polymerDockPoses(item,interaction,{maxDistance:Infinity})??[];return{instanceId,species:item.species,interaction,currentPosition:item.group.position.toArray(),orientation:item.group.quaternion.toArray(),targetWorld:target?.toArray()??null,actualDockPose:polymerDockPose(item,interaction)?.toArray()??null,withinRangeDockPoses:withinRange.map(position=>({position:position.toArray(),distance:position.distanceTo(item.group.position)})),unboundedSafeDockPoses:unbounded.map(position=>({position:position.toArray(),distance:position.distanceTo(item.group.position)}))};},\n`;
    body=Buffer.from(source.replace(marker,diagnosticMethod+marker));
  }
  res.end(body);
}catch{res.writeHead(404).end('not found');}});
await new Promise(done=>server.listen(0,'127.0.0.1',done));const {port}=server.address();
let chrome=process.env.CHROMIUM_PATH??'';if(!chrome)for(const command of ['google-chrome','chromium','chromium-browser']){const found=spawnSync('which',[command],{encoding:'utf8'});if(found.status===0&&found.stdout.trim()){chrome=found.stdout.trim();break;}}
assert.ok(chrome,'Chromium is required for Reaction Lab polymer pointer validation');
const profile=await mkdtemp(join(tmpdir(),'molecule-craft-polymer-lab-')),debugPort=9264,pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));let child=null,socket=null;
try{
  child=spawn(chrome,['--headless=new','--no-sandbox','--disable-background-networking','--use-gl=angle','--use-angle=swiftshader','--enable-webgl','--ignore-gpu-blocklist',`--user-data-dir=${profile}`,`--remote-debugging-port=${debugPort}`,'about:blank'],{stdio:'ignore'});
  let tabs=null;for(let attempt=0;attempt<180;attempt++){try{const response=await fetch(`http://127.0.0.1:${debugPort}/json/list`);if(response.ok){tabs=await response.json();if(tabs.length)break;}}catch{}await pause(100);}assert.ok(tabs?.length,'Polymer Reaction Lab DevTools endpoint did not become ready');
  socket=new WebSocket(tabs.find(tab=>tab.type==='page')?.webSocketDebuggerUrl??tabs[0].webSocketDebuggerUrl);await new Promise((ok,fail)=>{const timer=setTimeout(()=>fail(Error('DevTools websocket timeout')),5000);socket.addEventListener('open',()=>{clearTimeout(timer);ok();},{once:true});socket.addEventListener('error',fail,{once:true});});
  let sequence=0;const pending=new Map(),browserErrors=[],failedLocalRequests=[],badLocalResponses=[];socket.addEventListener('message',event=>{const message=JSON.parse(event.data);if(message.id&&pending.has(message.id)){const task=pending.get(message.id);pending.delete(message.id);message.error?task.reject(Error(message.error.message)):task.resolve(message.result);}if(message.method==='Runtime.exceptionThrown')browserErrors.push(message.params.exceptionDetails.exception?.description??message.params.exceptionDetails.text);if(message.method==='Runtime.consoleAPICalled'&&message.params.type==='error')browserErrors.push(message.params.args?.map(item=>item.value??item.description??'').join(' '));if(message.method==='Network.loadingFailed'&&!/ERR_ABORTED|canceled/i.test(message.params.errorText??''))failedLocalRequests.push({requestId:message.params.requestId,error:message.params.errorText});if(message.method==='Network.responseReceived'&&message.params.response.status>=400)badLocalResponses.push({url:message.params.response.url,status:message.params.response.status});});
  const send=(method,params={})=>new Promise((ok,fail)=>{const id=++sequence;pending.set(id,{resolve:ok,reject:fail});socket.send(JSON.stringify({id,method,params}));});
  const evaluate=async expression=>{const result=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(result.exceptionDetails)throw Error(result.exceptionDetails.exception?.description??result.exceptionDetails.text);return result.result?.value;};
  const browserVersion=await send('Browser.getVersion');
  const saveJourneyEvidence=async()=>{await mkdir(evidenceDir,{recursive:true});await writeFile(join(evidenceDir,`journey-${viewport.width}.json`),JSON.stringify({schemaVersion:1,sourceSha:process.env.POLYMER_SOURCE_SHA??null,browser:{product:browserVersion.product,revision:browserVersion.revision,protocolVersion:browserVersion.protocolVersion},viewport:{...viewport,deviceScaleFactor:1},steps:journeyEvidence,browserErrors,failedLocalRequests,badLocalResponses},null,2));};
  const captureEvidence=async name=>{await mkdir(evidenceDir,{recursive:true});const image=await send('Page.captureScreenshot',{format:'png'});const path=join(evidenceDir,`${name}-${viewport.width}.png`);await writeFile(path,Buffer.from(image.data,'base64'));return path;};
  const waitFor=async(expression,label,timeout=16000)=>{for(let index=0;index<timeout/50;index++){try{const value=await evaluate(expression);if(value)return value;}catch{}await pause(50);}const state=await evaluate(`(()=>{const button=document.querySelector('#open-collection'),r=button?.getBoundingClientRect(),hit=r&&document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return{url:location.href,title:document.title,dialog:document.querySelector('#reaction-lab-dialog')?.open,collection:document.querySelector('#collection-dialog')?.open,collectionClass:document.body.classList.contains('collection-open'),collectionTrigger:button?{disabled:button.disabled,rect:r&&{x:r.x,y:r.y,width:r.width,height:r.height},hit:hit?{tag:hit.tagName,id:hit.id,className:String(hit.className??'')}:null}:null,partial:document.querySelector('#partial-fill-confirm')?.hidden,supply:document.querySelector('#supply-dialog')?.open,field:document.querySelector('#veil-view')?.hidden,batch:window.__reactionLabProbe?.snapshot().batch,polymerization:window.__reactionLabProbe?.snapshot().polymerization,events:window.__polymerSampleEvents??[]}})()`);throw Error(`${label}: ${JSON.stringify({state,browserErrors})}`);};
  const tap=async selector=>{
    const point=await evaluate(`(()=>{const node=document.querySelector(${JSON.stringify(selector)});if(!node)throw Error('Missing pointer target');node.scrollIntoView({block:'center'});const r=node.getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2,w:r.width,h:r.height,disabled:node.disabled};})()`);
    assert.ok(point.w>0&&point.h>0&&point.x>=0&&point.x<=viewport.width&&point.y>=0&&point.y<=viewport.height&&!point.disabled,`${selector}: visible enabled ${viewport.width}×${viewport.height} target ${JSON.stringify(point)}`);
    await send('Input.dispatchMouseEvent',{type:'mousePressed',x:point.x,y:point.y,button:'left',buttons:1,clickCount:1});await send('Input.dispatchMouseEvent',{type:'mouseReleased',x:point.x,y:point.y,button:'left',buttons:0,clickCount:1});
  };
  const snapshot=()=>evaluate('window.__reactionLabProbe.snapshot()');
  const wireDiscoveryEvents=()=>evaluate(`(()=>{window.__polymerSampleEvents=[];window.__polymerPresentEvents=[];window.__polymerDismissEvents=[];window.addEventListener('molecule-craft:reaction-lab-polymer-sample',event=>window.__polymerSampleEvents.push({detail:event.detail,snapshot:window.__reactionLabProbe?.snapshot()??null}));window.addEventListener('molecule-craft:reaction-lab-polymer-sample-present',event=>window.__polymerPresentEvents.push({detail:event.detail,snapshot:window.__reactionLabProbe?.snapshot()??null}));window.addEventListener('molecule-craft:reaction-lab-polymer-sample-dismiss',event=>window.__polymerDismissEvents.push(event.detail));return true})()`);
  const openLab=async()=>{await waitFor("!!document.querySelector('#open-reaction-lab')&&!document.querySelector('#open-reaction-lab').disabled&&!!window.__reactionLabProbe",'Reaction Lab app did not initialize');await tap('#open-reaction-lab');await waitFor("document.querySelector('#reaction-lab-dialog').open",'Reaction Lab did not open');};
  const seedPage=await send('Page.addScriptToEvaluateOnNewDocument',{source:`for(const [key,value] of Object.entries(${JSON.stringify(checkpoint)}))localStorage.setItem(key,value);`});
  await send('Runtime.enable');await send('Page.enable');await send('Network.enable');await send('Emulation.setDeviceMetricsOverride',{...viewport,deviceScaleFactor:1});
  await send('Page.navigate',{url:`http://127.0.0.1:${port}/?reactionLabTest=1&reactionLabPhysics=stage-b`});
  await waitFor("!!document.querySelector('#open-collector-applications')&&!document.querySelector('#open-supply').disabled",'post-Awakening application startup');
  await send('Page.removeScriptToEvaluateOnNewDocument',{identifier:seedPage.identifier});
  await tap('#open-supply');await tap('#open-collector-applications');assert.equal(await evaluate("document.querySelectorAll('[data-collector-application][data-state=locked]:disabled').length"),3);await tap('#collector-applications-dialog .sheet-header button');
  await tap('#collector-launch-handle');await waitFor("document.querySelector('#expedition-destinations').getAttribute('aria-hidden')==='false'",'Rare expedition selector');await tap('#expedition-destinations [data-region=veil]');await pause(100);if(await evaluate("!!document.querySelector('#partial-fill-confirm')&&!document.querySelector('#partial-fill-confirm').hidden"))await tap('#partial-fill-confirm .primary');await waitFor("!!window.__materialFieldProbe?.().run&&!document.querySelector('#veil-view').hidden",'Rare FIELD entry');
  assert.equal(await evaluate("window.__materialFieldProbe().run.config.worldAwakened"),true);
  const pad=await evaluate("(()=>{const r=document.querySelector('#veil-pad').getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2}})()");
  const steerTo=async(target,radius,{element=null}={})=>{
    // Stop at the acquisition event, and slow down before a point target. The
    // pilot must not orbit an already-collected socket while waiting for one
    // exact 50 ms position sample on a differently paced CI browser.
    await send('Input.dispatchMouseEvent',{type:'mousePressed',...pad,button:'left',buttons:1,clickCount:1});
    let reached=false,driving=false,lastState;
    for(let n=0;n<600;n++){
      const p=await evaluate("(()=>{const r=window.__materialFieldProbe().run;return{x:r.player.x,y:r.player.y,vx:r.player.vx,vy:r.player.vy,captured:r.captured,time:r.time,cargo:r.elementDust,fuel:r.fuel,driveHeld:r.driveHeld}})()");lastState=p;
      const dx=target.x-p.x,dy=target.y-p.y,d=Math.hypot(dx,dy);
      assert.equal(p.captured,false,`pointer pilot captured: ${JSON.stringify({target,radius,d,state:p,pad})}`);
      if(d<radius||element&&p.cargo[element]>0){reached=true;break;}
      const shouldDrive=d>400;if(shouldDrive!==driving){await send('Input.dispatchKeyEvent',{type:shouldDrive?'rawKeyDown':'keyUp',key:'Shift',code:'ShiftLeft',windowsVirtualKeyCode:16});driving=shouldDrive;}
      const magnitude=shouldDrive?1:Math.max(.2,Math.min(1,d/250));
      await send('Input.dispatchMouseEvent',{type:'mouseMoved',x:pad.x+dx/d*48*magnitude,y:pad.y+dy/d*48*magnitude,button:'left',buttons:1});await pause(50);
    }
    await send('Input.dispatchMouseEvent',{type:'mouseReleased',...pad,button:'left',buttons:0});await send('Input.dispatchKeyEvent',{type:'keyUp',key:'Shift',code:'ShiftLeft',windowsVirtualKeyCode:16});assert.ok(reached,`normal pointer flight reaches waypoint: ${JSON.stringify({target,state:lastState})}`);
  };
  const rare=await evaluate("(()=>{const r=window.__materialFieldProbe().run;const d=r.map.dust.filter(x=>x.rareEcology&&x.element==='P').sort((a,b)=>Math.hypot(a.x-r.player.x,a.y-r.player.y)-Math.hypot(b.x-r.player.x,b.y-r.player.y))[0];return{x:d.x,y:d.y}})()");
  await steerTo(rare,25,{element:'P'});await waitFor("window.__materialFieldProbe().run.elementDust.P>0",'pointer flight collects Rare P');
  const site=await evaluate("(()=>{const r=window.__materialFieldProbe().run;const s=r.map.safeExtractionSites.sort((a,b)=>Math.hypot(a.x-r.player.x,a.y-r.player.y)-Math.hypot(b.x-r.player.x,b.y-r.player.y))[0];return{x:s.x,y:s.y,radius:s.radius}})()");await steerTo(site,site.radius*.7);
  await waitFor("document.querySelector('#veil-status-panel').dataset.state==='site-ready'",'safe return ready');
  const ship=await evaluate("(()=>{const {run,renderer}=window.__materialFieldProbe(),r=document.querySelector('#veil-canvas').getBoundingClientRect(),p=renderer.screen(run.player.x,run.player.y);return{x:r.x+p.x,y:r.y+p.y}})()");await send('Input.dispatchMouseEvent',{type:'mousePressed',...ship,button:'left',buttons:1,clickCount:1});await send('Input.dispatchMouseEvent',{type:'mouseReleased',...ship,button:'left',buttons:0});await waitFor("document.querySelector('#veil-view').hidden",'normal return settles Rare inventory');
  console.log('Mobile Rare acquisition / normal return PASS');
  await openLab();await evaluate(`(()=>{const dialog=document.querySelector('#reaction-lab-dialog');window.__task10LabCloseEvents=[];dialog.addEventListener('close',()=>window.__task10LabCloseEvents.push(performance.now()));return true})()`);await wireDiscoveryEvents();
  assert.equal((await snapshot()).physicsMode,'stage-b','the browser gate uses production Stage B');
  const setDraftSlots=async ids=>{
    for(let index=0;index<3;index++){
      const state=await snapshot(),current=state.batch.draftSlots[index]??'',next=ids[index]??'';if(current===next)continue;
      await waitFor("!window.__reactionLabProbe.snapshot().pickerOpen&&!window.__reactionLabProbe.snapshot().batch.transitionKind",'Feed Rack is still transitioning');
      await tap(`[data-lab-slot="${index}"]`);await waitFor("!document.querySelector('[data-lab-picker]').hidden",'Species picker did not open');
      if(next)await evaluate(`(()=>{const input=document.querySelector('[data-lab-search]');input.value=${JSON.stringify(next)};input.dispatchEvent(new Event('input',{bubbles:true}));const option=document.querySelector('[data-lab-picker-list] [data-species="${next}"]');if(!option)throw Error('Feed picker lacks '+${JSON.stringify(next)});})()`);
      if(next)await tap(`[data-lab-picker-list] [data-species="${next}"]`);
      else await tap('[data-lab-disconnect]');
      await waitFor("document.querySelector('[data-lab-picker]').hidden",'Species picker did not close');
    }
  };
  const setEnvironment=async route=>{
    const requiredHeat=route.environment.requires.includes('heat'),requiredMedium=route.environment.requires.includes('basic')?'basic':route.environment.requires.includes('acidic')?'acidic':'neutral';
    let state=await snapshot();if(state.environment.light)await tap('[data-lab-light]');
    if(state.environment.heat!==requiredHeat)await tap('[data-lab-heat]');
    state=await snapshot();if(state.environment.medium!==requiredMedium){await tap('[data-lab-medium-port]');await waitFor("!document.querySelector('[data-lab-medium-selector]').hidden",'Existing pH equipment did not open');await tap(`[data-lab-medium-option="${requiredMedium}"] input`);}
  };
  const feedRoute=async(route,expectPurge)=>{
    await setDraftSlots(route.feedSpecies);const before=await snapshot();assert.deepEqual(before.batch.draftSlots.filter(Boolean).sort(),[...route.feedSpecies].sort(),`${route.routeId}: exact Feed slots are set`);
    await waitFor("!document.querySelector('[data-lab-feed]').disabled",`${route.routeId}: FEED is unavailable`);
    await tap('[data-lab-feed]');
    if(expectPurge)await waitFor("window.__reactionLabProbe.snapshot().purging.some(item=>item.species==='PolymerSample')",`${route.routeId}: next FEED did not PURGE prior PolymerSample`,5000);
    await waitFor(`(()=>{const s=window.__reactionLabProbe.snapshot();return s.batch.phase==='ACTIVE'&&s.polymerization.routeId===${JSON.stringify(route.routeId)}&&['WAITING','AUTO_PENDING','SAMPLE'].includes(s.polymerization.state)})()`,`${route.routeId}: polymer route did not own its exact Feed batch`,22000);
    await setEnvironment(route);
    await waitFor(`window.__reactionLabProbe.snapshot().polymerization.waitReason!=='conditions'`,`${route.routeId}: route conditions did not become valid`);
  };
  const pointerDrag=async(instanceId,routeId,manualIndex)=>{
    const before=await snapshot(),candidateBefore=before.instances.find(item=>item.id===instanceId),captureEvidenceForGesture=routeId==='polybutadiene-coordination-1-4'&&manualIndex===2&&!viewport.mobile;
    const beforeScreenshot=captureEvidenceForGesture?await captureEvidence('polybutadiene-desktop-step-2-before'):null;
    const planRequestedAt=Date.now(),plan=await evaluate(`window.__reactionLabProbe.polymerDockPlan(${JSON.stringify(instanceId)})`),planReturnedAt=Date.now();
    const rect=await evaluate(`(()=>{const r=document.querySelector('#reaction-lab canvas').getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height,documentWidth:document.documentElement.clientWidth,documentScroll:document.documentElement.scrollWidth}})()`);
    assert.ok(plan.start.x>=rect.x&&plan.start.x<=rect.x+rect.width&&plan.start.y>=rect.y&&plan.start.y<=rect.y+rect.height,`${routeId} manual step ${manualIndex}: reactive site is visible in the ${viewport.width}×${viewport.height} chamber: ${JSON.stringify(plan)}`);
    assert.ok(plan.end.x>=rect.x&&plan.end.x<=rect.x+rect.width&&plan.end.y>=rect.y&&plan.end.y<=rect.y+rect.height,`${routeId} manual step ${manualIndex}: projected target remains visible: ${JSON.stringify(plan)}`);
    assert.ok(rect.documentScroll<=rect.documentWidth+1,`${routeId} manual step ${manualIndex}: no horizontal overflow`);
    const pointerStartAt=Date.now();
    await send('Input.dispatchMouseEvent',{type:'mouseMoved',x:plan.start.x,y:plan.start.y});await send('Input.dispatchMouseEvent',{type:'mousePressed',x:plan.start.x,y:plan.start.y,button:'left',buttons:1,clickCount:1});await pause(40);
    assert.equal((await snapshot()).draggedInstanceId,instanceId,`${routeId} manual step ${manualIndex} acquires the intended real monomer on the first pointer target`);
    for(let step=1;step<=12;step++){const t=step/12;await send('Input.dispatchMouseEvent',{type:'mouseMoved',x:plan.start.x+(plan.end.x-plan.start.x)*t,y:plan.start.y+(plan.end.y-plan.start.y)*t,button:'left',buttons:1});await pause(20);}
    await send('Input.dispatchMouseEvent',{type:'mouseReleased',x:plan.end.x,y:plan.end.y,button:'left',buttons:0});
    let committed=false,after=null;for(let attempt=0;attempt<180;attempt++){after=await snapshot();const p=after.polymerization;if(p.manualStepCount===manualIndex&&p.state!=='TRANSFORMING'){committed=true;break;}await pause(50);}
    if(!committed){
      const afterCanvas=await evaluate(`(()=>{const r=document.querySelector('#reaction-lab canvas').getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height,documentWidth:document.documentElement.clientWidth,documentScroll:document.documentElement.scrollWidth}})()`);
      let afterPlan=null,dockGeometry=null;try{afterPlan=await evaluate(`window.__reactionLabProbe.polymerDockPlan(${JSON.stringify(instanceId)})`);}catch(error){afterPlan={error:String(error)}}try{dockGeometry=await evaluate(`window.__reactionLabProbe.polymerDockDiagnostics(${JSON.stringify(instanceId)})`);}catch(error){dockGeometry={error:String(error)}}
      const afterScreenshot=await captureEvidence('polybutadiene-desktop-step-2-after'),diagnostic={sourceSha:process.env.POLYMER_SOURCE_SHA??null,routeId,manualStepIndex:manualIndex,viewport:{...viewport,deviceScaleFactor:1},candidateInstanceId:instanceId,candidateBefore,actualGesture:{start:plan.start,end:plan.end,sequence:['mouseMoved(start)','mousePressed(start)',...Array.from({length:12},(_,index)=>`mouseMoved(interpolated-${index+1}/12)`),'mouseReleased(end)'],pressHoldMs:40,interMoveDelayMs:20,planRequestMs:planRequestedAt,planReadyMs:planReturnedAt,pointerStartMs:pointerStartAt,planToPointerStartMs:pointerStartAt-planReturnedAt},dockPlanBefore:plan,targetProjectionBefore:before.polymerization.siteTarget,canvasBoundsBefore:rect,cameraBefore:before.camera,beforeSnapshot:before,beforeScreenshot,afterSnapshot:after,dockAttempt:after.polymerization.dockAttempt,dockPlanAfter:afterPlan,dockGeometry,canvasBoundsAfter:afterCanvas,cameraAfter:after.camera,afterScreenshot,browserErrors:[...browserErrors]};
      await mkdir(evidenceDir,{recursive:true});await writeFile(join(evidenceDir,`pointer-dock-failure-${routeId}-${manualIndex}-${viewport.width}.json`),JSON.stringify(diagnostic,null,2));
      console.log('POLYMER_POINTER_DOCK_DIAGNOSTIC',JSON.stringify(diagnostic));
      throw Error(`${routeId} manual step ${manualIndex} did not commit from the actual pointer gesture; diagnostics and before/after screenshots were saved.`);
    }
    assert.equal((await snapshot()).pointerActive,false,`${routeId} manual gesture releases pointer capture`);
    if(captureEvidenceForGesture){
      const after=await snapshot(),success={sourceSha:process.env.POLYMER_SOURCE_SHA??null,routeId,manualStepIndex:manualIndex,viewport:{...viewport,deviceScaleFactor:1},candidateInstanceId:instanceId,candidateBefore,actualGesture:{start:plan.start,end:plan.end,sequence:['mouseMoved(start)','mousePressed(start)',...Array.from({length:12},(_,index)=>`mouseMoved(interpolated-${index+1}/12)`),'mouseReleased(end)'],pressHoldMs:40,interMoveDelayMs:20,planToPointerStartMs:pointerStartAt-planReturnedAt},dockPlan:plan,targetProjectionBefore:before.polymerization.siteTarget,canvasBounds:rect,camera:before.camera,beforeSnapshot:before,beforeScreenshot,afterSnapshot:after,dockAttempt:after.polymerization.dockAttempt,browserErrors:[...browserErrors]};
      await mkdir(evidenceDir,{recursive:true});await writeFile(join(evidenceDir,`pointer-dock-success-${routeId}-${manualIndex}-${viewport.width}.json`),JSON.stringify(success,null,2));console.log('POLYMER_POINTER_DOCK_SUCCESS',JSON.stringify(success));
    }
    await pause(360);
  };
  const runManualSteps=async route=>{
    for(let manualIndex=1;manualIndex<=route.interactionCadence.manualSteps;manualIndex++){
      await waitFor("!!window.__reactionLabProbe.snapshot().polymerization.siteTarget",`${route.routeId} manual step ${manualIndex}: stable reactive site is presented`);
      const state=await snapshot(),consumed=state.polymerization.consumedInstanceIds,reserved=new Set(state.polymerization.reservedInstanceIds),species=route.representativeSequence[consumed.length],candidate=state.instances.find(item=>reserved.has(item.id)&&item.species===species&&!consumed.includes(item.id));
      assert.ok(candidate,`${route.routeId} manual step ${manualIndex}: representative incoming monomer is reserved and draggable`);
      await pointerDrag(candidate.id,route.routeId,manualIndex);
      assert.equal((await snapshot()).polymerization.manualStepCount,manualIndex,`${route.routeId}: exactly one manual chemistry step was committed`);
    }
  };
  const finishPvcContinuation=async route=>{
    if(route.routeId!=='polyvinyl-chloride-radical')return 'route-automatic';
    await waitFor(`(()=>{const p=window.__reactionLabProbe.snapshot().polymerization;return p.state==='SAMPLE'||(p.state==='WAITING'&&p.consumedInstanceIds.length===3&&!!p.siteTarget)})()`,`${route.routeId}: continuation did not become available`,20000);
    const state=await snapshot();if(state.polymerization.state==='SAMPLE')return 'route-automatic';
    const consumed=state.polymerization.consumedInstanceIds,reserved=new Set(state.polymerization.reservedInstanceIds),species=route.representativeSequence[consumed.length],candidate=state.instances.find(item=>reserved.has(item.id)&&item.species===species&&!consumed.includes(item.id));
    assert.ok(candidate,`${route.routeId}: final reserved monomer remains draggable after automatic geometry fallback`);
    const manualIndex=state.polymerization.manualStepCount+1;await pointerDrag(candidate.id,route.routeId,manualIndex);
    return 'actual-pointer-continuation';
  };
  const inspectSample=async route=>{
    await waitFor(`(()=>{const p=window.__reactionLabProbe.snapshot().polymerization;return p.state==='SAMPLE'&&!!p.sampleId&&p.samplePhase==='completion'})()`,`${route.routeId}: finite PolymerSample completion did not start`,20000);
    const state=await snapshot(),p=state.polymerization,events=await evaluate('window.__polymerSampleEvents.slice()');
    assert.equal(p.routeId,route.routeId);assert.equal(p.polymerId,route.polymerId);assert.equal(p.sampleDurationMs,650);assert.equal(p.sampleEvidence.unitCount,route.completionEvidence.unitCount);
    assert.equal(p.sampleEvidence.interUnitLinks,route.completionEvidence.interUnitLinks);assert.equal(p.sampleEvidence.ringOpenings,route.completionEvidence.ringOpenings);
    assert.equal(p.displayGraph.unitCount,route.completionEvidence.unitCount);assert.equal(p.displayGraph.layoutUnitCount,route.completionEvidence.unitCount);assert.equal(p.displayGraph.atomOriginCount,p.displayGraph.atomCount);assert.equal(p.displayGraph.bondsResolveToRenderedAtoms,true);
    assert.equal(state.instances.some(item=>item.species==='PolymerSample'),false,'PolymerSample is outside Stage B instances');assert.ok(p.sourceMeshCount>0,'actual sample atoms remain in the Reaction Lab');
    assert.equal(await evaluate("!!document.querySelector('[data-polymer-sample-bay]')"),false,'Sample Bay overlay is removed');assert.equal(await evaluate("document.querySelector('[data-polymer-completion]').hidden"),false,'bounded completion feedback is shown');
    assert.equal(events.length,1);assert.equal(events[0].detail.sampleId,p.sampleId);assert.equal(events[0].detail.routeId,route.routeId);assert.equal(events[0].snapshot.polymerization.sampleReady,false,'sample registration begins the bounded completion state');
    const saved=await evaluate(`JSON.parse(localStorage.getItem('molecule-craft.polymer-collection.v1')||'{}').discoveredPolymers`);assert.ok(saved.some(item=>item.id===route.polymerId));
    await waitFor(`window.__reactionLabProbe.snapshot().polymerization.sampleReady`,`${route.routeId}: bounded completion feedback did not finish`);
    const ready=await snapshot();assert.equal(ready.polymerization.layoutCallsAtReady,ready.polymerRuntimeMetrics.finiteLayoutCalls);assert.equal(ready.polymerRuntimeMetrics.completionLayoutCallsAfterReady,0);
    assert.equal((await evaluate('window.__polymerPresentEvents.slice()')).length,1,'sample-present follows completion readiness');
    await waitFor("document.querySelector('#collection-dialog').open&&!!document.querySelector('#collection-detail [data-discovery-session-action]')&&!document.querySelector('#collection-detail [data-discovery-session-action]').disabled",`${route.routeId}: Collection NEW ENTRY did not complete`);
    const reveal=await evaluate(`(()=>({entry:document.querySelector('#collection-detail h3')?.textContent,marker:document.querySelector('[data-registration-marker]')?.textContent??'',action:document.querySelector('#collection-detail [data-discovery-session-action]')?.textContent,waterKnown:JSON.parse(localStorage.getItem('molecule-craft.collection.v1')||'{}').discoveredMolecules.some(item=>item.id==='water')}))()`);
    assert.equal(reveal.entry,polymers.find(item=>item.id===route.polymerId).nameJa);assert.match(reveal.marker,/REGISTERED|NEW ENTRY/);assert.equal(reveal.action,'REACTION LABへ戻る');assert.equal(reveal.waterKnown,true,'pre-discovered molecular byproduct does not add a second reveal');
    await tap('#collection-detail [data-discovery-session-action]');await waitFor("document.querySelector('#reaction-lab-dialog').open&&!document.querySelector('#collection-dialog').open",`${route.routeId}: NEW ENTRY did not return to the Lab`);
    const returned=await snapshot();assert.equal(returned.polymerization.sampleId,p.sampleId,'finite sample remains displayed after discovery presentation');assert.equal(returned.polymerization.sampleReady,true);return p.sampleEvidence;
  };
  const openPolymer=async id=>{
    const closeEventCount=await evaluate('window.__task10LabCloseEvents.length');
    await tap('[data-lab-close]');
    await waitFor(`!document.querySelector('#reaction-lab-dialog').open&&!document.querySelector('#collection-dialog').open&&!document.body.classList.contains('collection-open')&&window.__task10LabCloseEvents.length>${closeEventCount}`,'Lab and prior Collection close event completes');
    await waitFor("(()=>{const button=document.querySelector('#open-collection');if(!button||button.disabled)return false;button.scrollIntoView({block:'center'});const r=button.getBoundingClientRect(),hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return r.width>0&&r.height>0&&(hit===button||button.contains(hit));})()",'Collection pointer target is unobstructed');
    await tap('#open-collection');await waitFor("document.querySelector('#collection-dialog').open",'Collection open');await tap('[data-book-tab=polymers]');await tap(`[data-entry-id="${id}"]`);await waitFor(`document.querySelector('#collection-detail').dataset.detailId===${JSON.stringify(id)}`,'polymer detail');
  };
  let previousSample=false;const evidence=[];
  for(const route of hardRoutes){
    console.log(`${viewport.width}×${viewport.height} route`,route.routeId);
    const routeBefore=await evaluate("(()=>{const saved=JSON.parse(localStorage.getItem('molecule-craft.polymer-collection.v1')||'{}');return{batch:window.__reactionLabProbe.snapshot().batch,polymerization:window.__reactionLabProbe.snapshot().polymerization,discoveredPolymers:(saved.discoveredPolymers??[]).map(item=>item.id)}})()");
    await evaluate('window.__polymerSampleEvents=[];window.__polymerPresentEvents=[];window.__polymerDismissEvents=[];true');await feedRoute(route,previousSample);await runManualSteps(route);const continuationMode=await finishPvcContinuation(route),sampleEvidence=await inspectSample(route);evidence.push(sampleEvidence);previousSample=true;
    const actualSample=await snapshot(),afterDiscovery=await evaluate("JSON.parse(localStorage.getItem('molecule-craft.polymer-collection.v1')||'{}').discoveredPolymers");
    journeyEvidence.push({step:journeyEvidence.length,action:'Exact FEED and actual pointer polymerization produce a finite PolymerSample and register discovery',beforeState:routeBefore,result:{routeId:route.routeId,polymerId:route.polymerId,sampleId:actualSample.polymerization.sampleId,batchGeneration:actualSample.batch.generation,continuationMode,manualStepCount:actualSample.polymerization.manualStepCount,automaticStepCount:actualSample.polymerization.automaticStepCount,consumedInstanceIds:actualSample.polymerization.consumedInstanceIds,sampleEvidence},afterState:{sampleReady:actualSample.polymerization.sampleReady,displayGraph:actualSample.polymerization.displayGraph,discoveredPolymerIds:afterDiscovery.map(item=>item.id),discoveryOrder:afterDiscovery.map(item=>item.order)},persistentAuthority:'molecule-craft.polymer-collection.v1',expectedInvariant:'The finite graph/evidence matches the selected route and the newly discovered polymer ID is saved once.'});
    const sampleId=(await snapshot()).polymerization.sampleId;
    await openPolymer(route.polymerId);
    await waitFor("(()=>{const image=document.querySelector('#collection-detail img');return !!image&&image.complete&&image.naturalWidth>0})()",`${route.polymerId}: Encyclopedia SVG did not load`);
    const encyclopediaEntry=await evaluate("(()=>{const image=document.querySelector('#collection-detail img');return{detailId:document.querySelector('#collection-detail').dataset.detailId,title:document.querySelector('#collection-detail h3')?.textContent,imageSource:image?.getAttribute('src')??null,imageLoaded:!!image&&image.complete&&image.naturalWidth>0}})()");
    assert.equal(encyclopediaEntry.imageLoaded,true,`${route.polymerId}: the encyclopedia structural SVG loads`);
    const encyclopediaScreenshot=await captureEvidence(`encyclopedia-${route.polymerId}`);
    journeyEvidence.push({step:journeyEvidence.length,action:'Open the discovered polymer Encyclopedia entry',beforeState:{discoveredPolymerIds:afterDiscovery.map(item=>item.id),reactionLabOpen:false,collectionOpen:true},result:encyclopediaEntry,afterState:{detailId:encyclopediaEntry.detailId,title:encyclopediaEntry.title},persistentAuthority:'molecule-craft.polymer-collection.v1 + assets/models/polymer-{id}.svg',screenshot:encyclopediaScreenshot,expectedInvariant:'The new discovery navigates to its own entry and the authoritative SVG is loaded.'});
    const recipe={'polybutadiene':'br-sulfur-wear','polyacrylonitrile':'pan-phenolic-thermal','phenol-formaldehyde-resin':'pan-phenolic-thermal','polyvinyl-chloride':'pvc-insulation'}[route.polymerId];
    await waitFor(`!!document.querySelector('[data-fabricate-recipe="${recipe}"]')`,'fabrication surface');
    const eligibility=await evaluate(`(()=>{const button=document.querySelector('[data-fabricate-recipe="${recipe}"]');return{disabled:button.disabled,label:button.textContent.trim(),reason:button.dataset.reason??button.getAttribute('aria-description')??null}})()`),engineeringBefore=await evaluate("JSON.parse(localStorage.getItem('molecule-craft.resources.v1'))");
    if(route.polymerId==='polyacrylonitrile'){
      assert.equal(eligibility.disabled,true,'phenolic resin is still required');
      const eligibilityScreenshot=await captureEvidence(`fabrication-blocked-${route.polymerId}`);
      journeyEvidence.push({step:journeyEvidence.length,action:`Check ${recipe} fabrication eligibility`,beforeState:{discoveredPolymerIds:afterDiscovery.map(item=>item.id),elements:engineeringBefore.elements,fabricated:engineeringBefore.engineering.fabricated},result:{eligible:false,blockedByMissingPhenolicResin:true,button:eligibility},afterState:{fabricated:engineeringBefore.engineering.fabricated},persistentAuthority:'molecule-craft.resources.v1 + molecule-craft.polymer-collection.v1',screenshot:eligibilityScreenshot,expectedInvariant:'Polymer discovery alone cannot bypass a missing recipe requirement.'});
    }else{
      assert.equal(eligibility.disabled,false,`${recipe} becomes eligible only after required discoveries and stock exist`);
      const before=engineeringBefore.elements;await tap(`[data-fabricate-recipe="${recipe}"]`);assert.equal(await evaluate(`document.querySelector('[data-fabricate-recipe="${recipe}"]').disabled`),true);
      const afterResources=await evaluate("JSON.parse(localStorage.getItem('molecule-craft.resources.v1'))"),after=afterResources.elements,cost=recipe==='br-sulfur-wear'?{S:1}:recipe==='pan-phenolic-thermal'?{P:1,H:3,O:4}:{};for(const key of Object.keys(before))assert.equal(after[key],before[key]-(cost[key]??0));
      const fabricationScreenshot=await captureEvidence(`fabrication-${recipe}`);
      journeyEvidence.push({step:journeyEvidence.length,action:`Fabricate ${recipe} through the Engineering UI`,beforeState:{discoveredPolymerIds:afterDiscovery.map(item=>item.id),elements:before,fabricated:engineeringBefore.engineering.fabricated,eligibility},result:{committed:true,consumed:cost},afterState:{elements:after,fabricated:afterResources.engineering.fabricated,activeApplications:afterResources.collectorShell.activeApplications},persistentAuthority:'molecule-craft.resources.v1',screenshot:fabricationScreenshot,expectedInvariant:'The recipe consumes exactly its BASE STOCK cost, persists one application unlock, and does not consume the transient PolymerSample.'});
    }
    await tap('#close-collection');await waitFor("!document.querySelector('#collection-dialog').open&&!document.body.classList.contains('collection-open')",'Collection close completes');await pause(100);await openLab();assert.equal((await snapshot()).polymerization.sampleId,sampleId,'fabrication leaves the finite PolymerSample displayed');
  }
  const persistenceBeforeReload=await evaluate("(()=>({polymerDiscoveries:JSON.parse(localStorage.getItem('molecule-craft.polymer-collection.v1')||'{}').discoveredPolymers,moleculeCollection:localStorage.getItem('molecule-craft.collection.v1'),fabricated:JSON.parse(localStorage.getItem('molecule-craft.resources.v1')).engineering.fabricated,activeApplications:JSON.parse(localStorage.getItem('molecule-craft.resources.v1')).collectorShell.activeApplications,transientSampleId:window.__reactionLabProbe.snapshot().polymerization.sampleId}))()");
  assert.equal(persistenceBeforeReload.polymerDiscoveries.length,4);
  await send('Page.reload',{ignoreCache:true});await waitFor("!!document.querySelector('#open-collector-applications')&&!document.querySelector('#open-supply').disabled",'checkpoint D reload');
  const persistenceAfterReload=await evaluate("(()=>({polymerDiscoveries:JSON.parse(localStorage.getItem('molecule-craft.polymer-collection.v1')||'{}').discoveredPolymers,moleculeCollection:localStorage.getItem('molecule-craft.collection.v1'),fabricated:JSON.parse(localStorage.getItem('molecule-craft.resources.v1')).engineering.fabricated,activeApplications:JSON.parse(localStorage.getItem('molecule-craft.resources.v1')).collectorShell.activeApplications,transientSampleId:window.__reactionLabProbe?.snapshot().polymerization.sampleId??null}))()");
  assert.deepEqual(persistenceAfterReload.polymerDiscoveries,persistenceBeforeReload.polymerDiscoveries);assert.equal(persistenceAfterReload.moleculeCollection,persistenceBeforeReload.moleculeCollection,'unrelated molecule Collection state is unchanged on reload');assert.equal(persistenceAfterReload.transientSampleId,null,'transient PolymerSample is not restored from save');
  journeyEvidence.push({step:journeyEvidence.length,action:'Save and reload after discovery and fabrication',beforeState:persistenceBeforeReload,result:{reloadCompleted:true},afterState:persistenceAfterReload,persistentAuthority:'molecule-craft.polymer-collection.v1 + molecule-craft.collection.v1 + molecule-craft.resources.v1',expectedInvariant:'Polymer discovery order, unrelated molecule Collection data, and engineering unlocks persist; the runtime-only finite Sample does not.'});
  const fabricated=await evaluate("JSON.parse(localStorage.getItem('molecule-craft.resources.v1')).engineering.fabricated");assert.deepEqual(fabricated,{WEAR_SKIN:true,THERMAL_SHELL:true,CONTROL_INSULATION:true});
  await tap('#open-supply');await tap('#open-collector-applications');assert.equal(await evaluate("document.querySelectorAll('[data-collector-application][data-state=available]').length"),3);
  journeyEvidence.push({step:journeyEvidence.length,action:'Check Collector Shell eligibility after Engineering fabrication',beforeState:{fabricated,activeApplications:persistenceAfterReload.activeApplications},result:{availableApplications:await evaluate("[...document.querySelectorAll('[data-collector-application][data-state=available]')].map(node=>node.dataset.collectorApplication)")},afterState:{fabricated,activeApplications:persistenceAfterReload.activeApplications},persistentAuthority:'molecule-craft.resources.v1',expectedInvariant:'All three fabricated applications are available, while active state remains independently controlled.'});
  const stock=await evaluate("JSON.parse(localStorage.getItem('molecule-craft.resources.v1')).elements"),activationTransitions=[];
  for(const id of Object.keys(fabricated)){for(let toggle=0;toggle<3;toggle++){await tap(`[data-collector-application=${id}]`);activationTransitions.push({id,active:await evaluate(`JSON.parse(localStorage.getItem('molecule-craft.resources.v1')).collectorShell.activeApplications.${id}`)});}}
  assert.deepEqual(await evaluate("JSON.parse(localStorage.getItem('molecule-craft.resources.v1')).elements"),stock);const activeBeforeReload=await evaluate("JSON.parse(localStorage.getItem('molecule-craft.resources.v1')).collectorShell.activeApplications");assert.deepEqual(activeBeforeReload,fabricated);
  const shellScreenshot=await captureEvidence('collector-shell-active');
  journeyEvidence.push({step:journeyEvidence.length,action:'Activate each fabricated Collector Shell application and save selection',beforeState:{activeApplications:persistenceAfterReload.activeApplications,elements:stock},result:{activationTransitions},afterState:{activeApplications:activeBeforeReload,elements:await evaluate("JSON.parse(localStorage.getItem('molecule-craft.resources.v1')).elements")},persistentAuthority:'molecule-craft.resources.v1.collectorShell.activeApplications',screenshot:shellScreenshot,expectedInvariant:'Fabrication unlock and active selection are separate; toggling consumes no stock.'});
  await send('Page.reload',{ignoreCache:true});await waitFor("!!document.querySelector('#open-collector-applications')&&!document.querySelector('#open-supply').disabled",'checkpoint F reload');await tap('#open-supply');await tap('#open-collector-applications');assert.equal(await evaluate("document.querySelectorAll('[data-collector-application][data-state=active]').length"),3);
  const activeAfterReload=await evaluate("JSON.parse(localStorage.getItem('molecule-craft.resources.v1')).collectorShell.activeApplications");assert.deepEqual(activeAfterReload,activeBeforeReload);journeyEvidence.push({step:journeyEvidence.length,action:'Reload Collector Shell selection',beforeState:{activeApplications:activeBeforeReload},result:{reloadCompleted:true},afterState:{activeApplications:activeAfterReload},persistentAuthority:'molecule-craft.resources.v1.collectorShell.activeApplications',expectedInvariant:'All active application selections persist across reload.'});
  const bounds=await evaluate("(()=>{const d=document.querySelector('#collector-applications-dialog'),r=d.getBoundingClientRect();return{left:r.left,right:r.right,top:r.top,bottom:r.bottom,overflow:d.scrollWidth-d.clientWidth}})()");assert.ok(bounds.left>=0&&bounds.right<=viewport.width&&bounds.top>=0&&bounds.bottom<=viewport.height&&bounds.overflow<=1);
  const shellBeforeLaunch=await evaluate("JSON.parse(localStorage.getItem('molecule-craft.resources.v1')).collectorShell.activeApplications");await tap('#collector-applications-dialog .sheet-header button');await tap('#collector-launch-handle');await waitFor("document.querySelector('#expedition-destinations').getAttribute('aria-hidden')==='false'",'destination selector');await tap('#expedition-destinations [data-region=veil]');await pause(100);if(await evaluate("!!document.querySelector('#partial-fill-confirm')&&!document.querySelector('#partial-fill-confirm').hidden"))await tap('#partial-fill-confirm .primary');await waitFor("!!window.__materialFieldProbe?.().run&&!document.querySelector('#veil-view').hidden",'FIELD entry');
  const launchedApplications=await evaluate("window.__materialFieldProbe().run.collectorMaterial.activeApplications");assert.deepEqual(launchedApplications,fabricated);
  journeyEvidence.push({step:journeyEvidence.length,action:'Launch FIELD with persisted Collector Shell applications',beforeState:{activeApplications:shellBeforeLaunch},result:{region:'veil',launchedApplications},afterState:{fieldVisible:await evaluate("!document.querySelector('#veil-view').hidden"),activeApplications:launchedApplications},persistentAuthority:'molecule-craft.resources.v1.collectorShell.activeApplications → FIELD launch cache',expectedInvariant:'FIELD launch receives the saved active selection, which remains distinct from fabrication.'});
  // Controlled, authored exposure positions compare actual FIELD feedback; normal flight/pickup is tested by the checkpoint producer.
  for(const [position,label] of [[{x:105,y:-6535},'摩耗軽減'],[{x:760,y:-11300},'熱伝達軽減'],[{x:660,y:-5370},'制御低下軽減']]){
    const before=await evaluate("(()=>({subtitle:document.querySelector('#veil-region-subtitle').textContent,activeApplications:window.__materialFieldProbe().run.collectorMaterial.activeApplications,player:{x:window.__materialFieldProbe().run.player.x,y:window.__materialFieldProbe().run.player.y}}))()");
    await evaluate(`Object.assign(window.__materialFieldProbe().run.player,${JSON.stringify(position)},{vx:0,vy:0})`);await waitFor(`document.querySelector('#veil-region-subtitle').textContent.includes(${JSON.stringify(label)})`,'FIELD feedback '+label);
    const after=await evaluate("(()=>({subtitle:document.querySelector('#veil-region-subtitle').textContent,activeApplications:window.__materialFieldProbe().run.collectorMaterial.activeApplications,player:{x:window.__materialFieldProbe().run.player.x,y:window.__materialFieldProbe().run.player.y}}))()");journeyEvidence.push({step:journeyEvidence.length,action:`Expose the active shell to the ${label} FIELD segment`,beforeState:before,result:{position,label,feedbackMatched:after.subtitle.includes(label)},afterState:after,persistentAuthority:'FIELD launch cache derived from molecule-craft.resources.v1.collectorShell.activeApplications',expectedInvariant:'The production FIELD identifies the intended targeted mitigation; 0.5 factor and non-target behavior are independently asserted by engineering fabrication tests.'});
  }
  assert.deepEqual(browserErrors,[],`No browser console errors: ${JSON.stringify(browserErrors)}`);assert.deepEqual(failedLocalRequests,[],`No local production asset request failed: ${JSON.stringify(failedLocalRequests)}`);assert.deepEqual(badLocalResponses,[],`No local production asset returned HTTP error: ${JSON.stringify(badLocalResponses)}`);const fieldScreenshot=await captureEvidence('field-application-effect');
  journeyEvidence.push({step:journeyEvidence.length,action:'Capture FIELD after targeted polymer application effects',beforeState:{activeApplications:launchedApplications},result:{targetFeedback:['摩耗軽減','熱伝達軽減','制御低下軽減'],consoleErrors:browserErrors,failedLocalRequests,badLocalResponses},afterState:{fieldVisible:true,activeApplications:launchedApplications},persistentAuthority:'FIELD launch cache derived from molecule-craft.resources.v1.collectorShell.activeApplications',screenshot:fieldScreenshot,expectedInvariant:'All targeted FIELD feedback is observed with no browser console or local asset errors.'});
  const summary={routeIds:hardRouteIds,samples:evidence.length,bounds,browserErrors,failedLocalRequests,badLocalResponses};await saveJourneyEvidence();console.log(`Material progression ${viewport.width}×${viewport.height} pointer closure`,JSON.stringify(summary));
}finally{try{socket?.close();}catch{}try{child?.kill('SIGKILL');}catch{}await pause(100);server.close();await rm(profile,{recursive:true,force:true});}
console.log(`${viewport.width}×${viewport.height} material progression: actual FEED, 4 polymer routes, fabrication, free toggles, reload, FIELD cache and feedback PASS.`);
