import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {mkdtemp,readFile,rm} from 'node:fs/promises';
import {spawn,spawnSync} from 'node:child_process';
import {extname,join,normalize,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {fileURLToPath} from 'node:url';

const root=resolve(fileURLToPath(new URL('..',import.meta.url))),types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.json':'application/json','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.webmanifest':'application/manifest+json'};
const server=createServer(async(req,res)=>{try{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname),relative=pathname==='/'?'index.html':pathname.replace(/^\/+/,''),file=normalize(join(root,relative));if(!file.startsWith(root)){res.writeHead(403).end();return;}const body=await readFile(file);res.writeHead(200,{'content-type':types[extname(file)]??'application/octet-stream','cache-control':'no-store'});res.end(body);}catch{res.writeHead(404).end('not found');}});
await new Promise(done=>server.listen(0,'127.0.0.1',done));const {port}=server.address(),origin=`http://127.0.0.1:${port}`;
let chrome='';for(const command of ['google-chrome','chromium','chromium-browser']){const found=spawnSync('which',[command],{encoding:'utf8'});if(found.status===0&&found.stdout.trim()){chrome=found.stdout.trim();break;}}assert.ok(chrome,'Chromium is required for Nitrogen LOADOUT validation');
const profile=await mkdtemp(join(tmpdir(),'molecule-craft-nitrogen-loadout-')),debugPort=9239,pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));let child=null,socket=null;
try{
  child=spawn(chrome,['--headless=new','--no-sandbox','--disable-gpu','--disable-background-networking',`--user-data-dir=${profile}`,`--remote-debugging-port=${debugPort}`,'about:blank'],{stdio:['ignore','ignore','pipe']});let tabs=null;
  for(let attempt=0;attempt<160;attempt++){try{const response=await fetch(`http://127.0.0.1:${debugPort}/json/list`);if(response.ok){tabs=await response.json();if(tabs.length)break;}}catch{}await pause(100);}assert.ok(tabs?.length,'DevTools endpoint did not become ready');
  socket=new WebSocket(tabs.find(tab=>tab.type==='page')?.webSocketDebuggerUrl??tabs[0].webSocketDebuggerUrl);await new Promise((ok,fail)=>{const timer=setTimeout(()=>fail(new Error('DevTools websocket timeout')),5000);socket.addEventListener('open',()=>{clearTimeout(timer);ok();},{once:true});socket.addEventListener('error',fail,{once:true});});
  let sequence=0;const pending=new Map();socket.addEventListener('message',event=>{const message=JSON.parse(event.data);if(message.id&&pending.has(message.id)){const task=pending.get(message.id);pending.delete(message.id);message.error?task.reject(new Error(message.error.message)):task.resolve(message.result);}});const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++sequence;pending.set(id,{resolve,reject});socket.send(JSON.stringify({id,method,params}));});const evaluate=async expression=>{const response=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(response.exceptionDetails)throw new Error(response.exceptionDetails.exception?.description??response.exceptionDetails.text);return response.result?.value;};const waitFor=async(expression,message,attempts=140)=>{for(let i=0;i<attempts;i++){try{if(await evaluate(expression))return;}catch{}await pause(100);}throw new Error(message);};
  await send('Runtime.enable');await send('Page.enable');await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await send('Page.navigate',{url:origin+'/'});await waitFor("document.querySelector('#open-collection')?.textContent?.includes('/135')",'Application did not initialize');
  const seeded=await evaluate(`(async()=>{const {createResources}=await import('/src/veil/resources.js');const records=await fetch('/data/molecules.json').then(r=>r.json());const r=createResources({storage:localStorage});r.setCatalog(records);r.state.progress.choCompleted=true;r.state.progress.regions=['veil','carbon','oxygen','nitrogen'];r.state.progress.checkpoint='nitrogen';r.state.progress.foundElements=['H','C','O','N'];r.state.recipes=['hydrogen','methane','oxygen','water','nitrogen','ammonia','ethylene-glycol'];Object.assign(r.state.elements,{H:5000,C:2000,O:5000,N:2000});for(const [use,id] of [['propellant','hydrogen'],['fuel','methane'],['oxidizer','oxygen'],['coolant','water']])if(!r.setLoadoutTank(use,id))return false;return r.save();})()`);assert.equal(seeded,true);
  await send('Page.reload',{ignoreCache:true});await waitFor("!!document.querySelector('#collector-launch-handle')&&!document.querySelector('#open-supply')?.disabled",'LOADOUT UI did not become ready');await evaluate("document.querySelector('#open-supply').click()");await waitFor("document.querySelector('#supply-dialog')?.open",'LOADOUT did not open');await pause(250);
  const select=async(use,id)=>{const selector=`#tank-molecules [data-molecule-id="${id}"]`;await evaluate(`document.querySelector(${JSON.stringify(`#shell-${use}`)}).click()`);await waitFor(`!!document.querySelector(${JSON.stringify(selector)})`,`${id} was not exposed for ${use}`);await evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);await waitFor(`document.querySelector(${JSON.stringify(selector)})?.getAttribute('aria-pressed')==='true'`,`${id} did not become selected`);await pause(80);};
  const pulsePreview=()=>evaluate(`(()=>{const host=document.querySelector('#tank-comparison'),row=host?.querySelector('.loadout-stat'),labels=[...host.querySelectorAll('.loadout-stat>span')].map(n=>n.textContent);return{kind:host?.dataset.previewKind,dots:host?.querySelectorAll('.loadout-charges i').length??0,burst:row?.querySelector('b')?.style.transform??'',labels};})()`);
  const pulses={};for(const id of ['hydrogen','ammonia','nitrogen']){await select('propellant',id);pulses[id]=await pulsePreview();}
  assert.deepEqual(Object.fromEntries(Object.entries(pulses).map(([id,row])=>[id,row.dots])),{hydrogen:3,ammonia:6,nitrogen:8},'PULSE dots must expose peak-force / balanced / repeated-pulse roles');
  assert.equal(pulses.hydrogen.kind,'propellant');assert.deepEqual(pulses.nitrogen.labels,['BURST']);
  const transformScale=value=>Number(/scaleX\(([^)]+)\)/.exec(value)?.[1]??0);assert.ok(transformScale(pulses.hydrogen.burst)>transformScale(pulses.ammonia.burst)&&transformScale(pulses.ammonia.burst)>transformScale(pulses.nitrogen.burst),'BURST bars must preserve H2 > NH3 > N2 peak force');
  const coolantPreview=()=>evaluate(`(()=>{const rows=[...document.querySelectorAll('#tank-comparison .loadout-stat')];return Object.fromEntries(rows.map(row=>[row.querySelector('span')?.textContent,row.querySelector('b')?.style.transform??'']));})()`);
  await select('coolant','nitrogen');const n2Coolant=await coolantPreview();await select('coolant','water');const waterCoolant=await coolantPreview();await select('coolant','ethylene-glycol');const glycolCoolant=await coolantPreview();
  assert.ok(transformScale(n2Coolant['冷却'])>transformScale(waterCoolant['冷却']),'N2 must visibly lead immediate cooling');assert.ok(transformScale(n2Coolant['持続'])<transformScale(waterCoolant['持続'])&&transformScale(n2Coolant['持続'])<transformScale(glycolCoolant['持続']),'N2 must visibly trade endurance for cooling');assert.ok(transformScale(n2Coolant['熱余裕'])<transformScale(glycolCoolant['熱余裕']),'glycol must visibly retain thermal-tolerance advantage');
  const fit=await evaluate(`(()=>{const d=document.querySelector('#supply-dialog');return{overflowY:Math.max(0,d.scrollHeight-d.clientHeight),overflowX:Math.max(0,d.scrollWidth-d.clientWidth),stockN:document.querySelector('[data-loadout-stock-element="N"]')?.hidden===false};})()`);assert.ok(fit.overflowY<=1&&fit.overflowX<=1,'Nitrogen options must preserve 390x844 mobile LOADOUT fit');assert.equal(fit.stockN,true,'unlocked N BASE STOCK must remain visible');
  console.log('Nitrogen LOADOUT browser preview',JSON.stringify({pulses,n2Coolant,waterCoolant,glycolCoolant,fit}));
}finally{try{socket?.close();}catch{}try{child?.kill('SIGKILL');}catch{}await pause(100);server.close();await rm(profile,{recursive:true,force:true});}
console.log('Nitrogen LOADOUT Chromium regression passed: H2/NH3/N2 PULSE roles, coolant roles and mobile fit are player-visible.');
