import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdtemp,rm} from 'node:fs/promises';
import {spawn,spawnSync} from 'node:child_process';
import {extname,join,normalize,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {fileURLToPath} from 'node:url';
import {NITROGEN_ROUTE,NITROGEN_ZONES,NITROGEN_INSIGHT_ANCHORS,NITROGEN_INSIGHT_AREA,NITROGEN_PULSE_FIELD,NITROGEN_RECOVERY_AREA,NITROGEN_CORE_FRACTURE_DURATION} from '../src/veil/nitrogen-routes.js';

const root=resolve(fileURLToPath(new URL('..',import.meta.url)));
const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.webmanifest':'application/manifest+json'};
const server=createServer(async(req,res)=>{
  try{
    const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname),relative=pathname==='/'?'index.html':pathname.replace(/^\/+/,''),file=normalize(join(root,relative));
    if(!file.startsWith(root)){res.writeHead(403).end();return;}
    let body=await readFile(file);
    if(relative==='src/veil/ui.js'){
      let source=body.toString('utf8');
      source=source.replace('function frame(now){',"function frame(now){globalThis.__nitrogenChapterRun=run;globalThis.__nitrogenChapterResources=resources;globalThis.__nitrogenChapterRenderer=renderer;globalThis.__nitrogenChapterKeys=keys;");
      body=Buffer.from(source);
    }
    res.writeHead(200,{'content-type':types[extname(file)]??'application/octet-stream','cache-control':'no-store'});res.end(body);
  }catch{res.writeHead(404).end('not found');}
});
await new Promise(done=>server.listen(0,'127.0.0.1',done));
const {port}=server.address(),origin=`http://127.0.0.1:${port}`;
let chrome='';for(const command of ['google-chrome','chromium','chromium-browser']){const found=spawnSync('which',[command],{encoding:'utf8'});if(found.status===0&&found.stdout.trim()){chrome=found.stdout.trim();break;}}
assert.ok(chrome,'A Chromium browser is required for Nitrogen chapter acceptance');
const profile=await mkdtemp(join(tmpdir(),'molecule-craft-nitrogen-chapter-browser-')),debugPort=9231;let child=null,socket=null;
try{
  child=spawn(chrome,['--headless=new','--no-sandbox','--disable-gpu','--disable-background-networking',`--user-data-dir=${profile}`,`--remote-debugging-port=${debugPort}`,'about:blank'],{stdio:['ignore','ignore','pipe']});
  let stderr='';child.stderr.setEncoding('utf8');child.stderr.on('data',chunk=>stderr+=chunk);
  let tabs=null;for(let attempt=0;attempt<160;attempt++){try{const response=await fetch(`http://127.0.0.1:${debugPort}/json/list`);if(response.ok){tabs=await response.json();if(tabs.length)break;}}catch{}await new Promise(done=>setTimeout(done,100));}
  assert.ok(tabs?.length,`Chromium DevTools endpoint did not become ready: ${stderr.slice(-1000)}`);
  socket=new WebSocket(tabs.find(tab=>tab.type==='page')?.webSocketDebuggerUrl??tabs[0].webSocketDebuggerUrl);await new Promise((done,fail)=>{const timer=setTimeout(()=>fail(new Error('DevTools websocket open timed out')),5000);socket.addEventListener('open',()=>{clearTimeout(timer);done();},{once:true});socket.addEventListener('error',fail,{once:true});});
  let sequence=0;const pending=new Map(),exceptions=[];socket.addEventListener('message',event=>{const message=JSON.parse(event.data);if(message.id&&pending.has(message.id)){const task=pending.get(message.id);pending.delete(message.id);message.error?task.reject(new Error(message.error.message)):task.resolve(message.result);return;}if(message.method==='Runtime.exceptionThrown')exceptions.push(message.params.exceptionDetails);});
  const send=(method,params={})=>new Promise((done,fail)=>{const id=++sequence;pending.set(id,{resolve:done,reject:fail});socket.send(JSON.stringify({id,method,params}));});
  const evaluate=async expression=>{const result=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(result.exceptionDetails)throw new Error(result.exceptionDetails.exception?.description??result.exceptionDetails.text);return result.result?.value;};
  const waitFor=async(expression,message,attempts=140)=>{for(let attempt=0;attempt<attempts;attempt++){try{if(await evaluate(expression))return;}catch{}await new Promise(done=>setTimeout(done,100));}throw new Error(message);};
  const canvasHash=`(()=>{const canvas=document.querySelector('#veil-canvas');if(!canvas?.width)return 0;const s=canvas.toDataURL();let h=2166136261;for(let i=0;i<s.length;i+=19)h=Math.imul(h^s.charCodeAt(i),16777619);return h>>>0;})()`;
  const keyCode={w:87,a:65,s:83,d:68};let held=new Set();
  async function setKeys(next){for(const key of held)if(!next.has(key))await send('Input.dispatchKeyEvent',{type:'keyUp',key,code:`Key${key.toUpperCase()}`,windowsVirtualKeyCode:keyCode[key],nativeVirtualKeyCode:keyCode[key]});for(const key of next)if(!held.has(key))await send('Input.dispatchKeyEvent',{type:'keyDown',key,code:`Key${key.toUpperCase()}`,windowsVirtualKeyCode:keyCode[key],nativeVirtualKeyCode:keyCode[key]});held=next;}

  await send('Runtime.enable');await send('Page.enable');await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true,screenWidth:390,screenHeight:844});await send('Page.navigate',{url:`${origin}/`});await waitFor(`document.querySelector('#open-collection')?.textContent?.includes('0/136')`,'Application did not initialize');
  const seeded=await evaluate(`(async()=>{const {createResources}=await import('/src/veil/resources.js');const records=await fetch('/data/molecules.json').then(r=>r.json());const r=createResources({storage:localStorage});r.setCatalog(records);r.state.progress.choCompleted=true;r.state.progress.regions=['veil','carbon','oxygen','frontier','nitrogen'];r.state.progress.checkpoint='nitrogen';r.state.progress.foundElements=['H','C','O','N'];r.state.recipes=['hydrogen','methane','oxygen','water'];Object.assign(r.state.elements,{H:1200,C:1200,O:1200,N:1200,P:0,S:0,F:0,Cl:0});return r.save();})()`);assert.equal(seeded,true);
  await send('Page.reload',{ignoreCache:true});await waitFor(`!!document.querySelector('#collector-launch-handle')&&!document.querySelector('#open-supply')?.disabled`,'LOADOUT UI did not become ready');await evaluate(`(()=>{document.querySelector('#open-supply').click();document.querySelector('#collector-launch-handle').dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}));return true;})()`);await waitFor(`document.querySelector('#expedition-destinations')?.getAttribute('aria-hidden')==='false'&&!!document.querySelector('#expedition-destinations [data-region=\"nitrogen\"]')`,'Nitrogen destination unavailable');
  await evaluate(`document.querySelector('#expedition-destinations [data-region="nitrogen"]').click()`);await waitFor(`document.querySelector('#veil-view')?.hidden===false&&!!globalThis.__nitrogenChapterRun`,'Nitrogen FIELD launch failed');exceptions.length=0;
  await evaluate(`(()=>{globalThis.__nitrogenChapterRun.predators=false;return true;})()`);
  const authored=await evaluate(`(()=>{const run=globalThis.__nitrogenChapterRun,route=run.map.routes.find(r=>r.id==='nitrogen-main'),side=run.map.routes.find(r=>r.id==='nitrogen-side-pocket'),signals=run.map.signals.filter(s=>s.nitrogenCritical);return {zones:run.map.nitrogenZones?.map(z=>({id:z.id,kind:z.kind,width:z.width,points:z.points.length}))??[],hazards:run.map.nitrogenHazards?.map(h=>({id:h.id,type:h.type,subtype:h.subtype,baseIntensity:h.baseIntensity}))??[],visualCount:run.map.nitrogenVisuals?.length??0,legacyPulses:run.map.fields.filter(f=>f.kind==='nitrogen-pulse').length,pulseField:run.map.fields.find(f=>f.id==='${NITROGEN_PULSE_FIELD.id}'),routeLength:route?.length,sideLength:side?.length,safeSite:run.map.safeExtractionSites.find(s=>s.id==='nitrogen-side-recovery-extraction'),core:run.map.nitrogenCore?{x:run.map.nitrogenCore.x,y:run.map.nitrogenCore.y,radius:run.map.nitrogenCore.radius,fractured:run.map.nitrogenCore.fractured}:null,signals:signals.map(s=>({id:s.id,x:s.x,y:s.y,captureRadius:s.captureRadius,claimable:s.claimable})),ambient:[...new Set(run.map.dust.filter(d=>String(d.route??'').startsWith('nitrogen-ambient-')).map(d=>d.element))],legacyRare:{survey:Object.hasOwn(run,'rareSurvey'),specimens:Object.hasOwn(run,'rareSpecimens'),cargo:Object.hasOwn(run,'rareCargo'),dust:run.map.dust.filter(d=>d.rareAnomaly||['P','S','F','Cl'].includes(d.element)).length}};})()`);
  assert.deepEqual(authored.zones.map(z=>z.id),NITROGEN_ZONES.map(z=>z.id));assert.deepEqual(authored.zones.map(z=>z.width),[720,760,700,520,680,720]);assert.equal(authored.hazards.length,6);assert.ok(authored.hazards.some(h=>h.type==='mechanical')&&authored.hazards.some(h=>h.type==='thermal'));assert.ok(authored.visualCount>50);assert.equal(authored.legacyPulses,0);assert.ok(authored.core&&!authored.core.fractured);assert.ok(authored.pulseField&&authored.pulseField.kind==='burst-advantage'&&authored.pulseField.radius===180);assert.ok(Math.abs(authored.routeLength-5347)<100);assert.ok(Math.abs(authored.sideLength-1760)<40);assert.equal(authored.safeSite.x,NITROGEN_RECOVERY_AREA.x);assert.equal(authored.signals.length,3);assert.ok(authored.signals.every(s=>s.captureRadius===160&&!s.claimable));assert.ok(authored.ambient.some(element=>element!=='N'));assert.deepEqual(authored.legacyRare,{survey:false,specimens:false,cargo:false,dust:0},'legacy Rare Survey runtime must be absent');
  const viewport=await evaluate(`({width:innerWidth,height:innerHeight,scrollWidth:document.documentElement.scrollWidth,scrollHeight:document.documentElement.scrollHeight,canvas:document.querySelector('#veil-canvas')?.getBoundingClientRect().toJSON()})`);assert.equal(viewport.width,390);assert.equal(viewport.height,844);assert.ok(viewport.scrollWidth<=390,`mobile horizontal overflow ${viewport.scrollWidth}`);assert.ok(viewport.scrollHeight<=844,`mobile vertical overflow ${viewport.scrollHeight}`);
  const earlyView=await evaluate(`(()=>{const run=globalThis.__nitrogenChapterRun,r=globalThis.__nitrogenChapterRenderer,size=r.size,visible=run.map.dust.filter(d=>d.element==='N').filter(d=>{const p=r.screen(d.x,d.y);return p.x>=0&&p.x<=size.w&&p.y>=0&&p.y<=size.h});return {count:visible.length,signalCount:run.map.signals.filter(s=>s.nitrogenCritical).length,coreDistance:Math.hypot(run.map.nitrogenCore.x-run.player.x,run.map.nitrogenCore.y-run.player.y),viewport:size};})()`);assert.ok(earlyView.count>0,'entry N group must be visible immediately');assert.ok(earlyView.coreDistance>=4700&&earlyView.coreDistance<=4900);assert.equal(earlyView.signalCount,3);
  const distantCuePixels=await evaluate(`(()=>{const run=globalThis.__nitrogenChapterRun,renderer=globalThis.__nitrogenChapterRenderer,canvas=document.querySelector('#veil-canvas'),ctx=canvas.getContext('2d'),core=run.map.nitrogenCore;renderer.reset();renderer.draw(run,.016,true);const withCue=ctx.getImageData(0,0,canvas.width,canvas.height).data.slice();run.map.nitrogenCore=null;renderer.reset();renderer.draw(run,.016,true);const withoutCue=ctx.getImageData(0,0,canvas.width,canvas.height).data;run.map.nitrogenCore=core;let changed=0;for(let y=0;y<Math.min(canvas.height,Math.floor(canvas.height*.28));y++)for(let x=Math.floor(canvas.width*.35);x<Math.floor(canvas.width*.65);x++){const i=(y*canvas.width+x)*4;if(Math.abs(withCue[i]-withoutCue[i])+Math.abs(withCue[i+1]-withoutCue[i+1])+Math.abs(withCue[i+2]-withoutCue[i+2])>18)changed++;}return changed;})()`);assert.ok(distantCuePixels>20,`entry distant Core anomaly must alter its bearing region; changed pixels=${distantCuePixels}`);

  const entryGeometry=await evaluate(`(()=>{const run=globalThis.__nitrogenChapterRun,renderer=globalThis.__nitrogenChapterRenderer,canvas=document.querySelector('#veil-canvas'),ctx=canvas.getContext('2d'),routes=run.map.routes,started=run.time;renderer.reset();renderer.draw(run,.016,true);const a=ctx.getImageData(0,0,canvas.width,canvas.height).data.slice();run.map.routes=routes.filter(r=>r.nitrogen!==true);renderer.reset();renderer.draw(run,.016,true);const b=ctx.getImageData(0,0,canvas.width,canvas.height).data;run.map.routes=routes;run.time=started;let changed=0;for(let i=0;i<a.length;i+=4)if(Math.abs(a[i]-b[i])+Math.abs(a[i+1]-b[i+1])+Math.abs(a[i+2]-b[i+2])>10)changed++;const startN=run.map.dust.filter(d=>d.element==='N').find(d=>Math.hypot(d.x-run.player.x,d.y-run.player.y)<500);return {routeDelta:changed,startN:!!startN};})()`);assert.equal(entryGeometry.routeDelta,0,'mainline and optional Nitrogen routes must not render as belts');assert.ok(entryGeometry.startN,'entry N pocket is within immediate collection range');
  const pickup=await evaluate(`(async()=>{const run=globalThis.__nitrogenChapterRun,d=run.map.dust.find(item=>item.element==='N'),{stepRun}=await import('/src/veil/expedition-run.js');Object.assign(run.player,{x:d.x,y:d.y,vx:0,vy:0,speed:0});const before=run.collectedElements.N;stepRun(run,{x:0,y:0},1/60,{});const result=run.collectedElements.N>before;Object.assign(run.player,{x:280,y:-12920,vx:0,vy:0,speed:run.config.driftSpeed});return result;})()`);assert.equal(pickup,true,'early N is immediately collectible');
  const driveVisual=await evaluate(`(()=>{const run=globalThis.__nitrogenChapterRun,renderer=globalThis.__nitrogenChapterRenderer,canvas=document.querySelector('#veil-canvas'),ctx=canvas.getContext('2d'),visuals=run.map.nitrogenVisuals;Object.assign(run.player,{x:-175,y:-14450,vx:0,vy:0,speed:0});renderer.reset();renderer.draw(run,.016,true);const a=ctx.getImageData(0,0,canvas.width,canvas.height).data.slice();run.map.nitrogenVisuals=[];renderer.reset();renderer.draw(run,.016,true);const b=ctx.getImageData(0,0,canvas.width,canvas.height).data;run.map.nitrogenVisuals=visuals;let changed=0;for(let i=0;i<a.length;i+=4)if(Math.abs(a[i]-b[i])+Math.abs(a[i+1]-b[i+1])+Math.abs(a[i+2]-b[i+2])>14)changed++;return changed;})()`);assert.ok(driveVisual>100,`DRIVE pressure channel should visibly render local environmental wisps; changed pixels=${driveVisual}`);
  const pulseVisual=await evaluate(`(()=>{const run=globalThis.__nitrogenChapterRun,renderer=globalThis.__nitrogenChapterRenderer,canvas=document.querySelector('#veil-canvas'),ctx=canvas.getContext('2d'),fields=run.map.fields;Object.assign(run.player,{x:${NITROGEN_PULSE_FIELD.x},y:${NITROGEN_PULSE_FIELD.y},vx:0,vy:0,speed:0});renderer.reset();renderer.draw(run,.016,true);const a=ctx.getImageData(0,0,canvas.width,canvas.height).data.slice();run.map.fields=fields.filter(f=>f.id!=='${NITROGEN_PULSE_FIELD.id}');renderer.reset();renderer.draw(run,.016,true);const b=ctx.getImageData(0,0,canvas.width,canvas.height).data;run.map.fields=fields;let changed=0;for(let i=0;i<a.length;i+=4)if(Math.abs(a[i]-b[i])+Math.abs(a[i+1]-b[i+1])+Math.abs(a[i+2]-b[i+2])>14)changed++;return changed;})()`);assert.ok(pulseVisual>100,`PULSE lip must have its own visible compact field; changed pixels=${pulseVisual}`);
  const nearCorePixels=await evaluate(`(()=>{const run=globalThis.__nitrogenChapterRun,renderer=globalThis.__nitrogenChapterRenderer,canvas=document.querySelector('#veil-canvas'),ctx=canvas.getContext('2d'),core=run.map.nitrogenCore;Object.assign(run.player,{x:0,y:-17100,vx:0,vy:0,speed:0});renderer.reset();renderer.draw(run,.016,true);const a=ctx.getImageData(0,0,canvas.width,canvas.height).data.slice();run.map.nitrogenCore=null;renderer.reset();renderer.draw(run,.016,true);const b=ctx.getImageData(0,0,canvas.width,canvas.height).data;run.map.nitrogenCore=core;let changed=0;for(let i=0;i<a.length;i+=4)if(Math.abs(a[i]-b[i])+Math.abs(a[i+1]-b[i+1])+Math.abs(a[i+2]-b[i+2])>14)changed++;return changed;})()`);assert.ok(nearCorePixels>1000,`solid Core within 600 units must be visually unmistakable; changed pixels=${nearCorePixels}`);

  // Exercise the Core's production renderer at both acceptance viewports. The
  // map metadata remains present after fracture; only the player-facing object
  // disappears when fracturedAt reaches the end of its animation.
  const savedCoreView=await evaluate(`(()=>{const run=globalThis.__nitrogenChapterRun,core=run.map.nitrogenCore;return {time:run.time,player:{x:run.player.x,y:run.player.y,angle:run.player.angle,vx:run.player.vx,vy:run.player.vy,speed:run.player.speed},fractured:core.fractured,fracturedAt:core.fracturedAt};})()`);
  async function coreViewportAcceptance(width,height,mobile){
    await send('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile,screenWidth:width,screenHeight:height});
    await evaluate(`new Promise(done=>requestAnimationFrame(()=>requestAnimationFrame(done)))`);
    await evaluate(`(()=>{window.dispatchEvent(new Event('resize'));globalThis.__nitrogenChapterRenderer.resize();globalThis.__nitrogenChapterRenderer.reset();})()`);
    const result=await evaluate(`(()=>{const run=globalThis.__nitrogenChapterRun,renderer=globalThis.__nitrogenChapterRenderer,canvas=document.querySelector('#veil-canvas'),ctx=canvas.getContext('2d'),core=run.map.nitrogenCore,sites=run.map.safeExtractionSites,read=()=>ctx.getImageData(0,0,canvas.width,canvas.height).data,draw=()=>{renderer.reset();renderer.draw(run,0,false);return read();},changed=(a,b)=>{let n=0;for(let i=0;i<a.length;i+=4)if(Math.abs(a[i]-b[i])+Math.abs(a[i+1]-b[i+1])+Math.abs(a[i+2]-b[i+2])>14)n++;return n;},same=(a,b)=>{for(let i=0;i<a.length;i++)if(a[i]!==b[i])return false;return true;};run.map.safeExtractionSites=[];core.fractured=false;delete core.fracturedAt;run.time=30;Object.assign(run.player,{x:0,y:-17100,vx:0,vy:0,speed:0});const intact=draw();run.map.nitrogenCore=null;const absent=draw();run.map.nitrogenCore=core;const nearPixels=changed(intact,absent),center=renderer.screen(core.x,core.y),pixelRadius=core.radius*renderer.size.scale,pixelScaleX=canvas.width/renderer.size.w,pixelScaleY=canvas.height/renderer.size.h;let bodyPixels=0;for(let y=-pixelRadius*.58;y<=pixelRadius*.58;y+=2)for(let x=-pixelRadius*.58;x<=pixelRadius*.58;x+=2)if(x*x+y*y<(pixelRadius*.58)**2){const ix=Math.round((center.x+x)*pixelScaleX),iy=Math.round((center.y+y)*pixelScaleY);if(ix<0||ix>=canvas.width||iy<0||iy>=canvas.height)continue;const i=(iy*canvas.width+ix)*4;if(Math.abs(intact[i]-absent[i])+Math.abs(intact[i+1]-absent[i+1])+Math.abs(intact[i+2]-absent[i+2])>14)bodyPixels++;}core.fractured=true;core.fracturedAt=30;run.time=30.06;const impact=draw();run.time=30.34;const rupture=draw();run.time=30.72;const disperse=draw();run.time=30+${NITROGEN_CORE_FRACTURE_DURATION}+0.01;const gone=draw();run.map.nitrogenCore=null;const goneAbsent=draw();run.map.nitrogenCore=core;const goneMatchesAbsence=same(gone,goneAbsent);core.fractured=true;delete core.fracturedAt;run.time=31;const revisitNear=draw();run.map.nitrogenCore=null;const revisitNearAbsent=draw();run.map.nitrogenCore=core;const revisitNearPixels=changed(revisitNear,revisitNearAbsent);Object.assign(run.player,{x:280,y:-12920,vx:0,vy:0,speed:0});run.time=32;const revisitDistant=draw();run.map.nitrogenCore=null;const revisitDistantAbsent=draw();run.map.nitrogenCore=core;const revisitDistantPixels=changed(revisitDistant,revisitDistantAbsent);run.map.safeExtractionSites=sites;return {size:renderer.size,canvas:{width:canvas.width,height:canvas.height,pixelScaleX,pixelScaleY},center,pixelRadius,nearPixels,bodyPixels,phaseHashes:[impact,rupture,disperse].map(data=>{let hash=2166136261;for(let i=0;i<data.length;i+=29)hash=Math.imul(hash^data[i],16777619);return hash>>>0;}),goneMatchesAbsence,revisitNearPixels,revisitDistantPixels};})()`);
    assert.ok(result.nearPixels>1000,`${width}x${height}: intact close Core should dominate the view; pixels=${result.nearPixels}`);
    assert.ok(result.bodyPixels>80,`${width}x${height}: the Core has a filled body rather than only surrounding lines; interior pixels=${result.bodyPixels}; sampling=${JSON.stringify({size:result.size,canvas:result.canvas,center:result.center,pixelRadius:result.pixelRadius})}`);
    assert.ok(new Set(result.phaseHashes).size>=2,`${width}x${height}: Core impact, rupture and disperse must visibly change the object`);
    assert.equal(result.goneMatchesAbsence,true,`${width}x${height}: completed fracture must render exactly like no Core`);
    assert.equal(result.revisitNearPixels,0,`${width}x${height}: revisited fractured Core has no close render`);
    assert.equal(result.revisitDistantPixels,0,`${width}x${height}: revisited fractured Core has no distant cue`);
    await evaluate(`(()=>{const run=globalThis.__nitrogenChapterRun,core=run.map.nitrogenCore;core.fractured=${savedCoreView.fractured};${savedCoreView.fracturedAt===undefined?'delete core.fracturedAt;':`core.fracturedAt=${savedCoreView.fracturedAt};`}run.time=${savedCoreView.time};Object.assign(run.player,${JSON.stringify(savedCoreView.player)});globalThis.__nitrogenChapterRenderer.reset();})()`);
    return result;
  }
  const mobileCoreAcceptance=await coreViewportAcceptance(390,844,true),desktopCoreAcceptance=await coreViewportAcceptance(1280,800,false);console.log('Nitrogen Core renderer acceptance',JSON.stringify({mobile:mobileCoreAcceptance,desktop:desktopCoreAcceptance}));
  await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true,screenWidth:390,screenHeight:844});await evaluate(`window.dispatchEvent(new Event('resize'))`);

  // Player-facing phase identity: render the production canvas from each authored
  // phase midpoint. Hazard composition and landmarks must produce distinct open-space views.
  const hashes=[];for(const zone of NITROGEN_ZONES){const progress=(zone.start+zone.end)/2,point=NITROGEN_ROUTE.points[Math.round(progress*(NITROGEN_ROUTE.points.length-1))];const hash=await evaluate(`(()=>{const run=globalThis.__nitrogenChapterRun,p=${JSON.stringify({x:point.x,y:point.y,angle:point.angle})};Object.assign(run.player,{x:p.x,y:p.y,angle:p.angle,vx:0,vy:0,speed:run.config.driftSpeed});globalThis.__nitrogenChapterRenderer.reset();globalThis.__nitrogenChapterRenderer.draw(run,.016,false);return ${canvasHash};})()`);hashes.push(hash);}assert.ok(new Set(hashes).size>=4,`Nitrogen sections must render as spatially distinct views: ${hashes.join(',')}`);

  // Real browser input validates that the open Entry → Mid field remains readable
  // without a painted corridor. Deep/Core round-trip capability is covered by the
  // deterministic loadout balance test rather than forcing an unprepared browser run.
  const start=NITROGEN_ROUTE.points[0],goalIndex=Math.round((NITROGEN_ROUTE.points.length-1)*.17),goal=NITROGEN_ROUTE.points[goalIndex];await evaluate(`Object.assign(globalThis.__nitrogenChapterRun.player,{x:${start.x},y:${start.y},angle:${start.angle},vx:0,vy:0,speed:globalThis.__nitrogenChapterRun.config.driftSpeed})`);
  let targetIndex=3,reached=false;for(let tick=0;tick<340&&!reached;tick++){
    const position=await evaluate(`(()=>{const p=globalThis.__nitrogenChapterRun.player;return {x:p.x,y:p.y,time:globalThis.__nitrogenChapterRun.time,N:globalThis.__nitrogenChapterRun.collectedElements.N};})()`),target=NITROGEN_ROUTE.points[Math.min(targetIndex,goalIndex)],dx=target.x-position.x,dy=target.y-position.y,d=Math.hypot(dx,dy),next=new Set();
    if(d<120&&targetIndex<goalIndex)targetIndex=Math.min(goalIndex,targetIndex+4);
    const activeTarget=NITROGEN_ROUTE.points[Math.min(targetIndex,goalIndex)],ax=activeTarget.x-position.x,ay=activeTarget.y-position.y;if(Math.abs(ax)>22)next.add(ax>0?'d':'a');if(Math.abs(ay)>22)next.add(ay>0?'s':'w');await setKeys(next);await new Promise(done=>setTimeout(done,80));reached=Math.hypot(position.x-goal.x,position.y-goal.y)<170&&targetIndex>=goalIndex;
  }await setKeys(new Set());
  const travelled=await evaluate(`(()=>{const run=globalThis.__nitrogenChapterRun,goal=${JSON.stringify({x:goal.x,y:goal.y})};return {distance:Math.hypot(run.player.x-goal.x,run.player.y-goal.y),N:run.collectedElements.N,time:run.time,hidden:document.querySelector('#veil-view').hidden,hash:${canvasHash}};})()`);assert.ok(travelled.distance<190,`real WASD traversal must enter the sustained DRIVE channel; distance=${travelled.distance}`);assert.ok(travelled.N>0,'real traversal must collect renewable N');assert.equal(travelled.hidden,false);

  // Verify the natural Critical Insight side pocket remains spatially
  // attached to its authored environment. The lifecycle itself is covered by the dedicated Critical browser test.
  const insight=await evaluate(`(()=>{const run=globalThis.__nitrogenChapterRun;return {count:run.map.signals.filter(s=>s.nitrogenCritical).length,claimable:run.map.signals.filter(s=>s.nitrogenCritical&&s.claimable).length,visible:run.map.signals.filter(s=>s.nitrogenCritical&&s.claimable).length>0};})()`);assert.equal(insight.count,3);assert.equal(insight.claimable,0,'no Insight appears before the current FIELD eligibility gate');
  const nearestInsight=await evaluate(`(async()=>{const run=globalThis.__nitrogenChapterRun,resources=globalThis.__nitrogenChapterResources,{syncFieldInsightMarkerClaimability}=await import('/src/veil/signal-claimability.js');Object.assign(run.player,{x:${NITROGEN_INSIGHT_ANCHORS[1].x},y:${NITROGEN_INSIGHT_ANCHORS[1].y}});run.time=20;run.insightEngagementMaxDistance=1200;run.insightEngagementSatisfied=true;run.collectedElements.N=1;if(!run.foundElements.includes('N'))run.foundElements.push('N');const selected=syncFieldInsightMarkerClaimability(run,s=>resources.signalClaimability(s.region,s.roll,s.choice,{runContext:run}));return {id:selected?.signal.id??null,claimable:run.map.signals.filter(s=>s.nitrogenCritical&&s.claimable).map(s=>s.id)};})()`);assert.equal(nearestInsight.id,NITROGEN_INSIGHT_ANCHORS[1].id);assert.deepEqual(nearestInsight.claimable,[NITROGEN_INSIGHT_ANCHORS[1].id],'eligible Insight displays only the nearest v3 anchor');
  await evaluate(`(()=>{const run=globalThis.__nitrogenChapterRun,renderer=globalThis.__nitrogenChapterRenderer,site=run.map.safeExtractionSites.find(site=>site.id==='nitrogen-side-recovery-extraction');Object.assign(run.player,{x:site.x,y:site.y,vx:0,vy:0,speed:0,boost:0,combustion:false});run.driveHeld=false;renderer.reset();})()`);await waitFor(`document.querySelector('#veil-status-panel')?.dataset.state==='site-ready'`,'Nitrogen chapter side-pocket Safe Site did not become ready');await evaluate(`(()=>{const canvas=document.querySelector('#veil-canvas'),renderer=globalThis.__nitrogenChapterRenderer,run=globalThis.__nitrogenChapterRun,rect=canvas.getBoundingClientRect(),screen=renderer.screen(run.player.x,run.player.y),point={bubbles:true,pointerId:9,pointerType:'touch',button:0,clientX:rect.left+screen.x,clientY:rect.top+screen.y};canvas.dispatchEvent(new PointerEvent('pointerdown',point));canvas.dispatchEvent(new PointerEvent('pointerup',point));})()`);await waitFor(`document.querySelector('#veil-view')?.hidden===true`,'Nitrogen chapter side-pocket Safe Site extraction did not complete',160);
  const saved=await evaluate(`(()=>{const state=JSON.parse(localStorage.getItem('molecule-craft.resources.v1'));return {rareEcologyEligible:state.progress.rareEcologyEligible,rareStocks:['P','S','F','Cl'].map(element=>state.elements[element]??0)};})()`);assert.deepEqual(saved.rareStocks,[0,0,0,0],'retired Rare Survey must not mint Rare stock');
  await waitFor(`!!document.querySelector('#collector-launch-handle')&&!document.querySelector('#open-supply')?.disabled`,'LOADOUT UI did not become ready');await evaluate(`(()=>{document.querySelector('#open-supply').click();document.querySelector('#collector-launch-handle').dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}));return true;})()`);await waitFor(`document.querySelector('#expedition-destinations')?.getAttribute('aria-hidden')==='false'&&!!document.querySelector('#expedition-destinations [data-region="nitrogen"]')`,'Nitrogen destination unavailable');await evaluate(`document.querySelector('#expedition-destinations [data-region="nitrogen"]').click()`);await waitFor(`document.querySelector('#veil-view')?.hidden===false&&!!globalThis.__nitrogenChapterRun`,'Nitrogen relaunch failed');const relaunch=await evaluate(`(()=>{const run=globalThis.__nitrogenChapterRun;return {legacyRare:Object.hasOwn(run,'rareSurvey')||Object.hasOwn(run,'rareSpecimens')||Object.hasOwn(run,'rareCargo'),rareDust:run.map.dust.some(d=>d.rareAnomaly||['P','S','F','Cl'].includes(d.element))};})()`);assert.deepEqual(relaunch,{legacyRare:false,rareDust:false});
  assert.equal(exceptions.length,0,`Nitrogen chapter browser acceptance must not throw: ${JSON.stringify(exceptions)}`);
  assert.ok((await evaluate(`({width:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight})`)).width<=390,'normal return keeps mobile layout within viewport');
  console.log('Nitrogen chapter Chromium acceptance',JSON.stringify({viewport,earlyView,distantCuePixels,driveVisual,pulseVisual,nearCorePixels,zones:authored.zones.map(z=>({kind:z.kind,width:z.width})),hazards:authored.hazards.length,sectionHashes:hashes,travelled:{time:travelled.time,N:travelled.N,distance:+travelled.distance.toFixed(1)},legacyRareRemoved:true}));
}finally{try{await setKeys?.(new Set());}catch{}try{socket?.close();}catch{}try{child?.kill('SIGKILL');}catch{}await new Promise(done=>setTimeout(done,100));server.close();await rm(profile,{recursive:true,force:true});}
console.log('Nitrogen chapter Chromium regression passed: six compact rendered sections, hazard-composition presentation, real WASD Entry-to-DRIVE traversal, N collection, N2 side pocket, normal return/relaunch, and no legacy Rare Survey runtime.');
