import test from 'node:test';
import assert from 'node:assert/strict';
import {createResources} from '../src/veil/resources.js';
import {createInitialResourcesState,RESOURCE_KEY} from '../src/veil/resources-persistence.js';
import {flightConfig} from '../src/veil/growth.js';
import {createUniverse,environmentAt} from '../src/veil/universe.js';
import {beginBurst,beginShock,createRun,stepRun} from '../src/veil/engine.js';
import {HAZARD_WORLD_MULTIPLIERS} from '../src/veil/hazards.js';
import {NITROGEN_CORE,NITROGEN_CORE_COLLISION_RADIUS,NITROGEN_CORE_FRACTURE_DURATION,NITROGEN_CORE_REPULSION_RADIUS,NITROGEN_HAZARDS,NITROGEN_ROUTE,nitrogenCoreInRange,nitrogenCoreIsFracturing,nitrogenCoreIsGone,nitrogenCoreRepulsionAt,nitrogenHazardEffectiveAt,resolveNitrogenCoreCollision} from '../src/veil/nitrogen-routes.js';
import {worldAwakeningState,DUST_EATER_WORLD_TUNING} from '../src/veil/world-awakening.js';
const memory=raw=>{let value=raw??null;return{getItem:key=>key===RESOURCE_KEY?value:null,setItem:(key,next)=>{if(key===RESOURCE_KEY)value=next;},removeItem:key=>{if(key===RESOURCE_KEY)value=null;},raw:()=>value};};
function ready(){const storage=memory(),r=createResources({storage});r.state.progress.choCompleted=true;return {r,storage};}
function coreRun(material='nitromethane',amount=1,{worldAwakened=false,coreFractured=false}={}){const state={progress:{choCompleted:true,coreFractured,worldAwakeningPending:false,worldAwakened,rareEcologyEligible:worldAwakened},elements:{N:0}},config=flightConfig(state),map=createUniverse(77,{H:0,C:0,N:0,O:0},{capabilities:{nitrogenField:true,coreFractured,worldAwakened}}),run=createRun(map,config,{predators:false,fuel:{shock:{molecule:material,amount,capacity:amount}}});Object.assign(run.player,{x:NITROGEN_CORE.x,y:NITROGEN_CORE.y,angle:-Math.PI/2,vx:0,vy:0});return run;}

test('hazard authority separates deterministic spatial field, base intensity and world multiplier',()=>{const item=NITROGEN_HAZARDS.find(h=>h.type==='mechanical'),probe={x:item.x,y:item.y},a=nitrogenHazardEffectiveAt(item,probe,.5,77,{worldState:'base'}),b=nitrogenHazardEffectiveAt(item,probe,.5,77,{worldState:'base'}),awakened=nitrogenHazardEffectiveAt(item,probe,.5,77,{worldState:'awakened'});assert.deepEqual(a,b);assert.ok(a.spatial>0&&a.scale>0);assert.ok(awakened.scale>a.scale);assert.ok(HAZARD_WORLD_MULTIPLIERS.awakened.mechanical>1);});
test('Nitromethane and TNT each fracture Core with one SHOCK while zero charge stays returnable',()=>{for(const material of ['nitromethane','2-4-6-trinitrotoluene']){const run=coreRun(material,1),event=beginShock(run,()=>true);assert.equal(event.coreFractured,true);assert.equal(run.fuel.shock.amount,0);assert.equal(run.map.nitrogenCore.fractured,true);}const empty=coreRun('nitromethane',0),approach=stepRun(empty,{x:0,y:0},1/60,{});assert.ok(approach.some(event=>event.type==='coreApproach'&&event.shockAvailable===false),'Core proximity must explain the zero-SHOCK learning loop even when the SHOCK control is unavailable');assert.equal(beginShock(empty,()=>true),false);assert.equal(empty.map.nitrogenCore.fractured,false);assert.equal(empty.captured,false);});
test('Core lifecycle is intact, briefly fracturing from fracturedAt, then fully gone',()=>{const core={...NITROGEN_CORE,fractured:true,fracturedAt:2};assert.equal(nitrogenCoreIsFracturing(core,2),true);assert.equal(nitrogenCoreIsFracturing(core,2+NITROGEN_CORE_FRACTURE_DURATION*.99),true);assert.equal(nitrogenCoreIsGone(core,2+NITROGEN_CORE_FRACTURE_DURATION),true);assert.equal(nitrogenCoreIsGone({...core,fracturedAt:undefined},0),true);assert.equal(nitrogenCoreInRange({map:{nitrogenCore:core},time:2}),false);});
test('intact Core swept collision blocks entry, removes inward velocity and preserves tangent slide',()=>{const core={...NITROGEN_CORE,fractured:false},from={x:-270,y:core.y-40},to={x:-180,y:core.y+90},velocity={x:120,y:65},resolved=resolveNitrogenCoreCollision(core,from,to,velocity),distance=Math.hypot(resolved.x-core.x,resolved.y-core.y),normal={x:(resolved.x-core.x)/distance,y:(resolved.y-core.y)/distance};assert.equal(resolved.collided,true);assert.ok(distance>=NITROGEN_CORE_COLLISION_RADIUS);assert.ok(resolved.vx*normal.x+resolved.vy*normal.y>=-1e-8,'remaining velocity may not point into the Core');assert.ok(resolved.vy>0,'tangential velocity remains available to slide around the Core');});
test('swept Core collision prevents a high-speed full-diameter tunnel',()=>{const core={...NITROGEN_CORE,fractured:false},resolved=resolveNitrogenCoreCollision(core,{x:-500,y:core.y},{x:500,y:core.y},{x:12000,y:0});assert.equal(resolved.collided,true);assert.ok(Math.hypot(resolved.x-core.x,resolved.y-core.y)>=NITROGEN_CORE_COLLISION_RADIUS);assert.ok(resolved.x<0,'the player must remain on the entry side instead of emerging opposite the Core');});
test('Core repulsion increases inward and propulsion can still enter SHOCK range',()=>{const core={...NITROGEN_CORE,fractured:false},outside=nitrogenCoreRepulsionAt(core,{x:NITROGEN_CORE_REPULSION_RADIUS,y:core.y}),far=nitrogenCoreRepulsionAt(core,{x:300,y:core.y}),near=nitrogenCoreRepulsionAt(core,{x:260,y:core.y}),closer=nitrogenCoreRepulsionAt(core,{x:230,y:core.y});assert.equal(outside.magnitude,0);assert.ok(far.magnitude>0&&near.magnitude>far.magnitude&&closer.magnitude>near.magnitude);const run=coreRun();run.fuel.propellant={molecule:'hydrogen',amount:1000,capacity:1000};Object.assign(run.player,{x:0,y:core.y+620,angle:-Math.PI/2,vx:0,vy:-164,speed:164});assert.equal(beginBurst(run,()=>true),true);let minimum=Infinity;for(let i=0;i<80;i++){stepRun(run,{x:0,y:-1},1/60,{});minimum=Math.min(minimum,Math.hypot(run.player.x-core.x,run.player.y-core.y));}assert.ok(minimum<=260,`PULSE propulsion must enter SHOCK range; closest distance=${minimum.toFixed(2)}`);assert.ok(minimum>=NITROGEN_CORE_COLLISION_RADIUS,`flight must stay outside the hard body; closest distance=${minimum.toFixed(2)}`);});
test('fracture immediately disables Core physics and revisits start with no Core interaction',()=>{const fractured=coreRun();Object.assign(fractured.player,{x:0,y:NITROGEN_CORE.y-NITROGEN_CORE.fractureRadius,vx:0,vy:0});assert.equal(beginShock(fractured,()=>true).coreFractured,true);assert.equal(nitrogenCoreRepulsionAt(fractured.map.nitrogenCore,{x:0,y:NITROGEN_CORE.y-260}).magnitude,0);assert.equal(resolveNitrogenCoreCollision(fractured.map.nitrogenCore,{x:-500,y:NITROGEN_CORE.y},{x:500,y:NITROGEN_CORE.y}).collided,false);assert.equal(nitrogenCoreInRange(fractured),false);assert.equal(stepRun(fractured,{x:0,y:0},1/60,{}).some(event=>event.type==='coreApproach'),false,'a same-run fracture suppresses later Core approach events');const state={progress:{choCompleted:true,coreFractured:true,worldAwakeningPending:true},elements:{N:0}},config=flightConfig(state),map=createUniverse(78,{H:0,C:0,N:0,O:0},{capabilities:{nitrogenField:true,coreFractured:true}}),revisit=createRun(map,config,{predators:false,fuel:{shock:{molecule:'nitromethane',amount:1,capacity:1}}});assert.equal(revisit.map.nitrogenCore.fractured,true,'persisted destruction metadata remains available');assert.equal(nitrogenCoreIsGone(revisit.map.nitrogenCore,revisit.time),true);Object.assign(revisit.player,{x:0,y:NITROGEN_CORE.y,vx:0,vy:0,speed:0});assert.equal(nitrogenCoreInRange(revisit),false);const events=stepRun(revisit,{x:0,y:0},1/60,{});assert.equal(events.some(event=>event.type==='coreApproach'),false);assert.equal(beginShock(revisit,()=>true).coreFractured,false,'a revisited Core cannot be fractured again');});
test('fracture persists pending, forced return does not awaken, normal return commits next-run awakening',()=>{const {r}=ready(),run=coreRun(),event=beginShock(run,()=>true);assert.equal(event.coreFractured,true);const pending=r.recordCoreFracture();assert.ok(pending,r.message||'recordCoreFracture returned null');assert.equal(pending.stage,'pending');assert.equal(run.config.worldAwakened,false);assert.equal(run.map.worldState,'base');assert.deepEqual(run.eaterTuning,DUST_EATER_WORLD_TUNING.base);const forced=r.settleExpedition({H:0,C:0,N:0,O:0},0,true);assert.equal(forced.worldAwakenedNow,false);assert.equal(r.worldAwakeningState().stage,'pending');assert.equal(flightConfig(r.state).worldAwakened,false);const normal=r.settleExpedition({H:0,C:0,N:0,O:0},0,false);assert.equal(normal.worldAwakenedNow,true);assert.equal(r.worldAwakeningState().stage,'awakened');assert.equal(r.state.progress.rareEcologyEligible,true);assert.equal(flightConfig(r.state).worldAwakened,true);});
test('post-Core world raises effective intensity and Eater activity without changing Nitrogen geometry',()=>{const preMap=createUniverse(91,{H:0,C:0,N:0,O:0},{capabilities:{nitrogenField:true}}),postMap=createUniverse(91,{H:0,C:0,N:0,O:0},{capabilities:{nitrogenField:true,worldAwakened:true,coreFractured:true}});assert.deepEqual(preMap.nitrogenHazards.map(h=>[h.id,h.x,h.y,h.radius]),postMap.nitrogenHazards.map(h=>[h.id,h.x,h.y,h.radius]));const item=NITROGEN_HAZARDS.find(h=>h.type==='mechanical'),pre=environmentAt({x:item.x,y:item.y},.4,preMap),post=environmentAt({x:item.x,y:item.y},.4,postMap);assert.ok(post.pressure>pre.pressure||Math.hypot(post.flowX,post.flowY)>Math.hypot(pre.flowX,pre.flowY));assert.ok(DUST_EATER_WORLD_TUNING.awakened.speedMultiplier>1&&DUST_EATER_WORLD_TUNING.awakened.thresholdMultiplier<1&&DUST_EATER_WORLD_TUNING.awakened.earlyEncounterCount>0);const config=flightConfig({progress:{choCompleted:true,coreFractured:true,worldAwakeningPending:false,worldAwakened:true,rareEcologyEligible:true},elements:{N:0}}),run=createRun(postMap,config,{predators:true}),start=NITROGEN_ROUTE.points[0];Object.assign(run.player,{x:start.x,y:start.y});for(let n=0;n<8*60;n++)stepRun(run,{x:0,y:-1},1/60,{});assert.ok(run.eaters.length>=1);});
test('schema-v8 saves normalize missing world fields without resetting Nitrogen, O2 or SHOCK state',()=>{const legacy=createInitialResourcesState();legacy.progress.choCompleted=true;legacy.progress.regions.push('nitrogen');legacy.progress.checkpoint='nitrogen';legacy.recipes.push('nitrogen');legacy.hints.push('ammonia');legacy.upgrades.oxygenTank=2;legacy.tanks.shock={molecule:'nitromethane',amount:2};delete legacy.progress.coreFractured;delete legacy.progress.worldAwakeningPending;delete legacy.progress.worldAwakened;delete legacy.progress.rareEcologyEligible;const r=createResources({storage:memory(JSON.stringify(legacy))});assert.equal(r.state.progress.checkpoint,'nitrogen');assert.equal(r.state.upgrades.oxygenTank,2);assert.deepEqual(r.state.tanks.shock,{molecule:'nitromethane',amount:2});assert.deepEqual(worldAwakeningState(r.state.progress),{coreFractured:false,worldAwakeningPending:false,worldAwakened:false,rareEcologyEligible:false,stage:'intact'});});
