import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdtemp,rm} from 'node:fs/promises';
import {spawn,spawnSync} from 'node:child_process';
import {extname,join,normalize,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {fileURLToPath} from 'node:url';

const root=resolve(fileURLToPath(new URL('..',import.meta.url))),types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.json':'application/json','.css':'text/css','.svg':'image/svg+xml'};
const server=createServer(async(req,res)=>{try{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname),relative=pathname==='/'?'index.html':pathname.replace(/^\/+/,''),file=normalize(join(root,relative));if(!file.startsWith(root)){res.writeHead(403).end();return;}const body=await readFile(file);res.writeHead(200,{'content-type':types[extname(file)]??'application/octet-stream','cache-control':'no-store'});res.end(body);}catch{res.writeHead(404).end('not found');}});
await new Promise(done=>server.listen(0,'127.0.0.1',done));const {port}=server.address();
let chrome='';for(const command of ['google-chrome','chromium','chromium-browser']){const found=spawnSync('which',[command],{encoding:'utf8'});if(found.status===0&&found.stdout.trim()){chrome=found.stdout.trim();break;}}assert.ok(chrome,'Chromium is required for Rare ecology mobile regression');
const profile=await mkdtemp(join(tmpdir(),'molecule-craft-rare-ecology-browser-')),debugPort=9237;let child=null,socket=null;
try{
  child=spawn(chrome,['--headless=new','--no-sandbox','--disable-gpu','--disable-background-networking',`--user-data-dir=${profile}`,`--remote-debugging-port=${debugPort}`,'about:blank'],{stdio:['ignore','ignore','pipe']});
  let tabs=null,stderr='';child.stderr.setEncoding('utf8');child.stderr.on('data',chunk=>stderr+=chunk);for(let attempt=0;attempt<160;attempt++){try{const response=await fetch(`http://127.0.0.1:${debugPort}/json/list`);if(response.ok){tabs=await response.json();if(tabs.length)break;}}catch{}await new Promise(done=>setTimeout(done,100));}assert.ok(tabs?.length,stderr.slice(-1000));
  socket=new WebSocket(tabs.find(tab=>tab.type==='page')?.webSocketDebuggerUrl??tabs[0].webSocketDebuggerUrl);await new Promise((resolveOpen,reject)=>{const timer=setTimeout(()=>reject(new Error('DevTools websocket timeout')),5000);socket.addEventListener('open',()=>{clearTimeout(timer);resolveOpen();},{once:true});socket.addEventListener('error',reject,{once:true});});
  let sequence=0;const pending=new Map(),exceptions=[];socket.addEventListener('message',event=>{const message=JSON.parse(event.data);if(message.id&&pending.has(message.id)){const task=pending.get(message.id);pending.delete(message.id);message.error?task.reject(new Error(message.error.message)):task.resolve(message.result);return;}if(message.method==='Runtime.exceptionThrown')exceptions.push(message.params.exceptionDetails);});
  const send=(method,params={})=>new Promise((resolveSend,reject)=>{const id=++sequence;pending.set(id,{resolve:resolveSend,reject});socket.send(JSON.stringify({id,method,params}));});
  const evaluate=async expression=>{const result=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(result.exceptionDetails)throw new Error(result.exceptionDetails.exception?.description??result.exceptionDetails.text);return result.result?.value;};
  await send('Runtime.enable');await send('Page.enable');await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:2,mobile:true});await send('Page.navigate',{url:`http://127.0.0.1:${port}/`});await new Promise(done=>setTimeout(done,500));
  const result=await evaluate(`(async()=>{const [{createUniverse},{createRun,stepRun},{createVeilRenderer},{createResources},{flightConfig}]=await Promise.all([import('/src/veil/universe.js'),import('/src/veil/expedition-run.js'),import('/src/veil/renderer.js'),import('/src/veil/resources.js'),import('/src/veil/growth.js')]);const resources=createResources({storage:null});Object.assign(resources.state.progress,{choCompleted:true,coreFractured:true,worldAwakened:true,rareEcologyEligible:true});const capabilities={combustionDrive:true,nitrogenField:true,coreFractured:true,worldAwakened:true,rareEcologyEligible:true},map=createUniverse(41,resources.state.elements,{capabilities}),config=flightConfig(resources.state),run=createRun(map,config,{predators:false}),canvas=document.createElement('canvas');canvas.style.cssText='position:fixed;inset:0;width:390px;height:844px';document.body.append(canvas);const renderer=createVeilRenderer(canvas),rare=map.dust.filter(item=>item.rareEcology),elements=[...new Set(rare.map(item=>item.element))];let frames=0,start=performance.now();for(const item of rare){Object.assign(run.player,{x:item.x,y:item.y,vx:0,vy:0,speed:0});renderer.reset();renderer.draw(run,1/60,false);frames++;}const p=rare.find(item=>item.element==='P');Object.assign(run.player,{x:p.x,y:p.y,vx:0,vy:0,speed:0});stepRun(run,{x:0,y:0},.05,{});const settlement=resources.settleExpedition(run.elementDust,0,false);return {elements,frames,elapsed:performance.now()-start,pCargo:run.elementDust.P,pStock:resources.state.elements.P,pSettled:settlement.atoms.P,canvas:[canvas.width,canvas.height],legacy:Object.hasOwn(run,'rareSurvey')||rare.some(item=>item.rareAnomaly),hPure:map.dust.some(item=>item.kind==='rare'&&(item.element??'H')==='H')};})()`);
  assert.deepEqual(new Set(result.elements),new Set(['P','S','F','Cl']));assert.ok(result.frames>=4);assert.ok(result.elapsed<3000,`Rare particle rendering is unexpectedly expensive: ${result.elapsed}ms`);assert.ok(result.pCargo>=1&&result.pStock>=1&&result.pSettled>=1);assert.ok(result.canvas[0]>0&&result.canvas[1]>0);assert.equal(result.legacy,false);assert.equal(exceptions.length,0,`Rare ecology mobile browser must not throw: ${JSON.stringify(exceptions)}`);
  console.log('Rare ecology mobile Chromium',JSON.stringify(result));
}finally{try{socket?.close();}catch{}try{child?.kill('SIGKILL');}catch{}await new Promise(done=>setTimeout(done,100));server.close();await rm(profile,{recursive:true,force:true});}
