import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile} from 'node:fs/promises';
import {extname,join,normalize,resolve} from 'node:path';
import {spawn,spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
const root=resolve(fileURLToPath(new URL('..',import.meta.url))),mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.webmanifest':'application/manifest+json'};
const server=createServer(async(req,res)=>{try{const relative=new URL(req.url,'http://localhost').pathname==='/'?'index.html':decodeURIComponent(new URL(req.url,'http://localhost').pathname).replace(/^\/+/,''),file=normalize(join(root,relative));if(!file.startsWith(root))throw Error();res.writeHead(200,{'content-type':mime[extname(file)]??'application/octet-stream','cache-control':'no-store'});res.end(await readFile(file));}catch{res.writeHead(404).end();}});await new Promise(done=>server.listen(0,'127.0.0.1',done));const {port}=server.address();
let chrome='';for(const command of ['google-chrome','chromium','chromium-browser']){const found=spawnSync('which',[command],{encoding:'utf8'});if(found.status===0&&found.stdout.trim()){chrome=found.stdout.trim();break;}}assert.ok(chrome,'Chromium is required for Reaction Lab mobile validation');
const debugPort=9237,profile=`/tmp/molecule-craft-reaction-lab-${process.pid}`;let child,socket;
try{
 child=spawn(chrome,['--headless=new','--no-sandbox','--disable-background-networking','--use-gl=angle','--use-angle=swiftshader','--enable-webgl','--ignore-gpu-blocklist',`--user-data-dir=${profile}`,`--remote-debugging-port=${debugPort}`,'about:blank'],{stdio:'ignore'});
 let tabs;for(let i=0;i<180;i++){try{const response=await fetch(`http://127.0.0.1:${debugPort}/json/list`);if(response.ok){tabs=await response.json();if(tabs.length)break;}}catch{}await new Promise(r=>setTimeout(r,100));}assert.ok(tabs?.length,'Chromium DevTools endpoint not ready');socket=new WebSocket(tabs.find(tab=>tab.type==='page')?.webSocketDebuggerUrl??tabs[0].webSocketDebuggerUrl);await new Promise((ok,fail)=>{socket.addEventListener('open',ok,{once:true});socket.addEventListener('error',fail,{once:true});});
 let sequence=0;const pending=new Map();socket.addEventListener('message',event=>{const message=JSON.parse(event.data);if(message.id&&pending.has(message.id)){const task=pending.get(message.id);pending.delete(message.id);message.error?task.reject(Error(message.error.message)):task.resolve(message.result);}});const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++sequence;pending.set(id,{resolve,reject});socket.send(JSON.stringify({id,method,params}));});
 const evaluate=async expression=>{const response=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(response.exceptionDetails)throw Error(response.exceptionDetails.exception?.description??response.exceptionDetails.text);return response.result?.value;};
 const waitFor=async(expression,label)=>{for(let i=0;i<200;i++){const value=await evaluate(expression);if(value)return value;await new Promise(r=>setTimeout(r,50));}throw Error(label);};
 await send('Runtime.enable');await send('Page.enable');await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
 await send('Page.addScriptToEvaluateOnNewDocument',{source:`localStorage.setItem('molecule-craft.collection.v1',JSON.stringify({schemaVersion:3,discoveredMolecules:['water','ethanol','acetic-anhydride','acetic-acid'].map((id,index)=>({id,at:index+1,order:index+1})),discoveredGroups:[],unlockedStructures:[],legacyElements:[],milestones:[]}));`});
 await send('Page.navigate',{url:`http://127.0.0.1:${port}/`});await waitFor("document.querySelector('#open-reaction-lab')&&!document.querySelector('#open-reaction-lab').disabled",'Reaction Lab entry did not initialize');
 await evaluate("document.querySelector('#open-reaction-lab').click()");await waitFor("document.querySelector('#reaction-lab-dialog').open",'Reaction Lab dialog did not open');
 const initial=await evaluate("(()=>{const r=document.querySelector('#reaction-lab-dialog').getBoundingClientRect(),c=document.querySelector('#reaction-lab canvas').getBoundingClientRect();return{dialog:[r.width,r.height],canvas:[c.width,c.height],slots:document.querySelectorAll('[data-lab-slot]').length}})()");assert.deepEqual(initial.slots,3);assert.ok(initial.dialog[0]>=389&&initial.dialog[1]>=843,`Dialog must fill the 390x844 mobile screen: ${JSON.stringify(initial)}`);
 await evaluate("(()=>{const s=document.querySelectorAll('[data-lab-slot]');s[0].value='water';s[0].dispatchEvent(new Event('change',{bubbles:true}));})()");await waitFor("document.querySelector('[data-lab-status]').textContent.includes('4 個')",'Single species did not create representative particles');
 await evaluate("(()=>{const s=document.querySelectorAll('[data-lab-slot]');s[1].value='ethanol';s[1].dispatchEvent(new Event('change',{bubbles:true}));})()");await waitFor("document.querySelector('[data-lab-status]').textContent.includes('4 個')",'Two species did not create four particles');
 await evaluate("(()=>{const s=document.querySelectorAll('[data-lab-slot]');s[2].value='acetic-acid';s[2].dispatchEvent(new Event('change',{bubbles:true}));})()");await waitFor("document.querySelector('[data-lab-status]').textContent.includes('6 個')",'Three species did not create six particles');
 const duplicate=await evaluate("(()=>{const s=document.querySelectorAll('[data-lab-slot]');s[2].add(new Option('水','water'));s[2].value='water';s[2].dispatchEvent(new Event('change',{bubbles:true}));return s[2].value})()");assert.equal(duplicate,'acetic-acid','Duplicate species must be rejected');
 await evaluate("document.querySelector('[data-lab-mode=rotate]').click()");assert.equal(await evaluate("document.querySelector('[data-lab-mode=rotate]').getAttribute('aria-pressed')"),'true');await evaluate("document.querySelector('[data-lab-mode=view]').click()");assert.equal(await evaluate("document.querySelector('[data-lab-mode=view]').getAttribute('aria-pressed')"),'true');
 console.log('Reaction Lab mobile browser passed: 390x844 three-slot layout, 1/2/3 species populations, empty slot, duplicate rejection and operation modes.');
}finally{try{socket?.close();}catch{}try{child?.kill('SIGKILL');}catch{}server.close();}
