import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {mkdtemp,readFile,rm,mkdir,writeFile} from 'node:fs/promises';
import {spawn,spawnSync} from 'node:child_process';
import {extname,join,normalize,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {fileURLToPath} from 'node:url';

const root=resolve(process.env.POLYMER_ROOT??fileURLToPath(new URL('..',import.meta.url))),routes=JSON.parse(await readFile(join(root,'data/polymerization-routes.json'),'utf8')).routes,polymers=JSON.parse(await readFile(join(root,'data/polymers.json'),'utf8'));
const viewport=process.env.POLYMER_DESKTOP==='1'?{width:1280,height:900,mobile:false}:{width:390,height:844,mobile:true},evidence=[],performanceEvidence=[];
const hardRouteIds=['polyethylene-coordination','ethylene-propylene-coordination','polyethylene-oxide-anionic-ring-opening','polyethylene-terephthalate-direct-polycondensation','phenol-formaldehyde-resole','styrene-butadiene-radical','butyl-rubber-cationic','nylon-6-6-direct-polycondensation'];
const hardRoutes=hardRouteIds.map(id=>routes.find(route=>route.routeId===id));assert.equal(hardRoutes.filter(Boolean).length,8);hardRoutes.push(routes.find(r=>r.polymerId==='polystyrene'));
const moleculeIds=[...new Set([...routes.flatMap(route=>route.feedSpecies),'water'])],moleculeSave={schemaVersion:3,discoveredMolecules:moleculeIds.map((id,index)=>({id,at:index+1,order:index+1})),discoveredGroups:[],unlockedStructures:[],legacyElements:[],milestones:[]};
const indexHtml=await readFile(join(root,'index.html'),'utf8'),mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.json':'application/json','.css':'text/css; charset=utf-8','.svg':'image/svg+xml'};
const server=createServer(async(req,res)=>{try{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname),file=normalize(join(root,pathname==='/'?'index.html':pathname.replace(/^\/+/,'')));if(!file.startsWith(root)){res.writeHead(403).end();return;}let body=await readFile(file);if(pathname==='/src/app.js'){const source=body.toString(),target='reactionLabViewer=createReactionLabViewer({';assert.ok(source.includes(target),'test-only viewer disposal hook target remains present');body=Buffer.from(source.replace(target,'reactionLabViewer=window.__reactionLabViewer=createReactionLabViewer({'));}res.writeHead(200,{'content-type':mime[extname(file)]??'application/octet-stream','cache-control':'no-store'});res.end(body);}catch{res.writeHead(404).end('not found');}});
await new Promise(done=>server.listen(0,'127.0.0.1',done));const {port}=server.address();
let chrome=process.env.CHROMIUM_PATH??'';if(!chrome)for(const command of ['google-chrome','chromium','chromium-browser']){const found=spawnSync('which',[command],{encoding:'utf8'});if(found.status===0&&found.stdout.trim()){chrome=found.stdout.trim();break;}}
assert.ok(chrome,'Chromium is required for Reaction Lab polymer pointer validation');
const profile=await mkdtemp(join(tmpdir(),'molecule-craft-polymer-lab-')),debugPort=Number(process.env.POLYMER_DEBUG_PORT??9262),pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));let child=null,socket=null;
try{
  child=spawn(chrome,['--headless=new','--no-sandbox','--disable-background-networking','--disable-background-timer-throttling','--disable-renderer-backgrounding','--disable-backgrounding-occluded-windows','--use-gl=angle','--use-angle=swiftshader','--enable-webgl','--ignore-gpu-blocklist','--force-device-scale-factor=1',`--user-data-dir=${profile}`,`--remote-debugging-port=${debugPort}`,'about:blank'],{stdio:'ignore'});
  let tabs=null;for(let attempt=0;attempt<180;attempt++){try{const response=await fetch(`http://127.0.0.1:${debugPort}/json/list`);if(response.ok){tabs=await response.json();if(tabs.length)break;}}catch{}await pause(100);}assert.ok(tabs?.length,'Polymer Reaction Lab DevTools endpoint did not become ready');
  socket=new WebSocket(tabs.find(tab=>tab.type==='page')?.webSocketDebuggerUrl??tabs[0].webSocketDebuggerUrl);await new Promise((ok,fail)=>{const timer=setTimeout(()=>fail(Error('DevTools websocket timeout')),5000);socket.addEventListener('open',()=>{clearTimeout(timer);ok();},{once:true});socket.addEventListener('error',fail,{once:true});});
  const browserVersion=await new Promise((ok,fail)=>{const timer=setTimeout(()=>fail(Error('Browser version query timeout')),5000);const id=0;const handler=event=>{const message=JSON.parse(event.data);if(message.id!==id)return;socket.removeEventListener('message',handler);clearTimeout(timer);message.error?fail(Error(message.error.message)):ok(message.result);};socket.addEventListener('message',handler);socket.send(JSON.stringify({id,method:'Browser.getVersion'}));});
  let sequence=0;const pending=new Map(),browserErrors=[];socket.addEventListener('message',event=>{const message=JSON.parse(event.data);if(message.id&&pending.has(message.id)){const task=pending.get(message.id);pending.delete(message.id);message.error?task.reject(Error(message.error.message)):task.resolve(message.result);}if(message.method==='Runtime.exceptionThrown')browserErrors.push(message.params.exceptionDetails.exception?.description??message.params.exceptionDetails.text);if(message.method==='Runtime.consoleAPICalled'&&message.params.type==='error')browserErrors.push(message.params.args?.map(item=>item.value??item.description??'').join(' '));});
  const send=(method,params={})=>new Promise((ok,fail)=>{const id=++sequence;pending.set(id,{resolve:ok,reject:fail});socket.send(JSON.stringify({id,method,params}));});
  const evaluate=async expression=>{const result=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(result.exceptionDetails)throw Error(result.exceptionDetails.exception?.description??result.exceptionDetails.text);return result.result?.value;};
  const waitFor=async(expression,label,timeout=16000)=>{for(let index=0;index<timeout/50;index++){try{const value=await evaluate(expression);if(value)return value;}catch{}await pause(50);}const state=await evaluate(`(()=>({url:location.href,title:document.title,labButton:{present:!!document.querySelector('#open-reaction-lab'),disabled:document.querySelector('#open-reaction-lab')?.disabled},viewerUnavailable:document.querySelector('#viewer-unavailable')?.hidden,status:document.querySelector('#status')?.textContent,dialog:document.querySelector('#reaction-lab-dialog')?.open,collection:document.querySelector('#collection-dialog')?.open,batch:window.__reactionLabProbe?.snapshot().batch,polymerization:window.__reactionLabProbe?.snapshot().polymerization,events:window.__polymerSampleEvents??[]}))()`);throw Error(`${label}: ${JSON.stringify({state,browserErrors})}`);};
  const snapshot=()=>evaluate('window.__reactionLabProbe.snapshot()'),resetPolymerEvents=()=>evaluate('window.__polymerSampleEvents=[];window.__polymerPresentEvents=[];window.__polymerDismissEvents=[];window.__closeBeforeReadyOnNextSample=false;true'),routeCameraDistances=new Map();
  const wireDiscoveryEvents=()=>evaluate(`(()=>{window.__polymerSampleEvents=[];window.__polymerPresentEvents=[];window.__polymerDismissEvents=[];window.__closeBeforeReadyOnNextSample=false;const record=event=>({detail:event.detail,receivedAt:performance.now(),snapshot:window.__reactionLabProbe?.snapshot()??null,completionUi:{hidden:document.querySelector('[data-polymer-completion]')?.hidden??true,status:document.querySelector('[data-polymer-completion-status]')?.textContent??'',encyclopediaHidden:document.querySelector('[data-polymer-encyclopedia]')?.hidden??true,encyclopediaDisabled:document.querySelector('[data-polymer-encyclopedia]')?.disabled??true}});window.addEventListener('molecule-craft:reaction-lab-polymer-sample',event=>{window.__polymerSampleEvents.push(record(event));if(window.__closeBeforeReadyOnNextSample){window.__closeBeforeReadyOnNextSample=false;document.querySelector('#reaction-lab-dialog')?.close();}});window.addEventListener('molecule-craft:reaction-lab-polymer-sample-present',event=>window.__polymerPresentEvents.push(record(event)));window.addEventListener('molecule-craft:reaction-lab-polymer-sample-dismiss',event=>window.__polymerDismissEvents.push(record(event)));return true})()`);
  const openLab=async()=>{await waitFor("!!document.querySelector('#open-reaction-lab')&&!document.querySelector('#open-reaction-lab').disabled&&!!window.__reactionLabProbe",'Reaction Lab app did not initialize');await evaluate("document.querySelector('#open-reaction-lab').click()");await waitFor("document.querySelector('#reaction-lab-dialog').open",'Reaction Lab did not open');};
  const seedPage=await send('Page.addScriptToEvaluateOnNewDocument',{source:`localStorage.setItem('molecule-craft.collection.v1',${JSON.stringify(JSON.stringify(moleculeSave))});localStorage.setItem('molecule-craft.polymer-collection.v1',JSON.stringify({schemaVersion:1,discoveredPolymers:[]}));`});
  const frameProbePage=await send('Page.addScriptToEvaluateOnNewDocument',{source:`(()=>{const samples=[];let active=null;const pct=(values,q)=>{if(!values.length)return null;const sorted=[...values].sort((a,b)=>a-b);return sorted[Math.max(0,Math.ceil(q*sorted.length)-1)];};const summarize=record=>{const frames=record.frames.filter(value=>value>=record.startedAt&&value<=record.presentedAt),intervals=frames.slice(1).map((value,index)=>value-frames[index]),firstFrameOffsetMs=frames.length?frames[0]-record.startedAt:null,lastFrameOffsetMs=frames.length?frames[frames.length-1]-record.startedAt:null;return{sampleId:record.sampleId,routeId:record.routeId,startedAt:record.startedAt,presentedAt:record.presentedAt,completionElapsedMs:record.presentedAt-record.startedAt,targetDurationMs:record.targetDurationMs,frameIntervalsMs:{count:intervals.length,frameCount:frames.length,firstFrameOffsetMs:firstFrameOffsetMs===null?null:Number(firstFrameOffsetMs.toFixed(3)),lastFrameOffsetMs:lastFrameOffsetMs===null?null:Number(lastFrameOffsetMs.toFixed(3)),sampledFrameSpanMs:frames.length>1?Number((frames[frames.length-1]-frames[0]).toFixed(3)):0,trailingGapMs:lastFrameOffsetMs===null?null:Number((record.presentedAt-frames[frames.length-1]).toFixed(3)),p50:pct(intervals,.5),p95:pct(intervals,.95),max:intervals.length?Math.max(...intervals):null,values:intervals.map(value=>Number(value.toFixed(3)))}};};addEventListener('molecule-craft:reaction-lab-polymer-sample',event=>{if(active&&!active.presentedAt)active.abandoned=true;const duration=window.__reactionLabProbe?.snapshot().polymerization.sampleDurationMs??null;active={sampleId:event.detail.sampleId,routeId:event.detail.routeId,startedAt:performance.now(),presentedAt:null,targetDurationMs:duration,frames:[]};samples.push(active);});addEventListener('molecule-craft:reaction-lab-polymer-sample-present',event=>{const record=samples.find(item=>item.sampleId===event.detail.sampleId);if(record&&!record.presentedAt){record.presentedAt=performance.now();if(active===record)active=null;}});const tick=now=>{if(active&&!active.presentedAt)active.frames.push(now);requestAnimationFrame(tick);};requestAnimationFrame(tick);window.__polymerFrameProbe={summary:id=>{const record=samples.find(item=>item.sampleId===id);return record?.presentedAt?summarize(record):null;}};})();`});
  await send('Runtime.enable');await send('Page.enable');await send('Network.enable');await send('Emulation.setDeviceMetricsOverride',{...viewport,deviceScaleFactor:1});
  await send('Page.navigate',{url:`http://127.0.0.1:${port}/?reactionLabTest=1&reactionLabPhysics=stage-b`});await openLab();await wireDiscoveryEvents();
  assert.equal((await snapshot()).physicsMode,'stage-b','the browser gate uses production Stage B');
  const retiredModuleRequests=await evaluate("performance.getEntriesByType('resource').map(entry=>entry.name).filter(name=>/reaction-lab-polymer-cinematic|polymer-growth-plan|polymer-morphology-(?:authority|plan|renderer|bridge)/.test(name))");assert.deepEqual(retiredModuleRequests,[],'production completion does not fetch retired visualization modules');
  const setDraftSlots=async ids=>{
    for(let index=0;index<3;index++){
      const state=await snapshot(),current=state.batch.draftSlots[index]??'',next=ids[index]??'';if(current===next)continue;
      await waitFor("!window.__reactionLabProbe.snapshot().pickerOpen&&!window.__reactionLabProbe.snapshot().batch.transitionKind",'Feed Rack is still transitioning');
      await evaluate(`document.querySelectorAll('[data-lab-slot]')[${index}].click()`);await waitFor("!document.querySelector('[data-lab-picker]').hidden",'Species picker did not open');
      if(next)await evaluate(`(()=>{const input=document.querySelector('[data-lab-search]');input.value=${JSON.stringify(next)};input.dispatchEvent(new Event('input',{bubbles:true}));const option=document.querySelector('[data-lab-picker-list] [data-species="${next}"]');if(!option)throw Error('Feed picker lacks '+${JSON.stringify(next)});option.click()})()`);
      else await evaluate("document.querySelector('[data-lab-disconnect]').click()");
      await waitFor("document.querySelector('[data-lab-picker]').hidden",'Species picker did not close');
    }
  };
  const setEnvironment=async route=>{
    const requiredHeat=route.environment.requires.includes('heat'),requiredMedium=route.environment.requires.includes('basic')?'basic':route.environment.requires.includes('acidic')?'acidic':'neutral';
    let state=await snapshot();if(state.environment.light)await evaluate("document.querySelector('[data-lab-light]').click()");
    if(state.environment.heat!==requiredHeat)await evaluate("document.querySelector('[data-lab-heat]').click()");
    state=await snapshot();if(state.environment.medium!==requiredMedium){await evaluate("document.querySelector('[data-lab-medium-port]').click()");await waitFor("!document.querySelector('[data-lab-medium-selector]').hidden",'Existing pH equipment did not open');await evaluate(`document.querySelector('[data-lab-medium-option="${requiredMedium}"] input').click()`);}
  };
  const feedRoute=async(route,expectPurge)=>{
    await setDraftSlots(route.feedSpecies);const before=await snapshot();assert.deepEqual(before.batch.draftSlots.filter(Boolean).sort(),[...route.feedSpecies].sort(),`${route.routeId}: exact Feed slots are set`);
    await waitFor("!document.querySelector('[data-lab-feed]').disabled",`${route.routeId}: FEED is unavailable`);
    await evaluate("document.querySelector('[data-lab-feed]').click()");
    if(expectPurge)await waitFor("window.__reactionLabProbe.snapshot().purging.some(item=>item.species==='PolymerSample')",`${route.routeId}: next FEED did not PURGE prior PolymerSample`,5000);
    await waitFor(`(()=>{const s=window.__reactionLabProbe.snapshot();return s.batch.phase==='ACTIVE'&&s.polymerization.routeId===${JSON.stringify(route.routeId)}&&['WAITING','AUTO_PENDING','SAMPLE'].includes(s.polymerization.state)})()`,`${route.routeId}: polymer route did not own its exact Feed batch`,22000);
    if(expectPurge){await waitFor(`(()=>{const s=window.__reactionLabProbe.snapshot();return !s.purging.some(item=>item.species==='PolymerSample')&&s.polymerResources.disposals.geometryDisposals>${before.polymerResources.disposals.geometryDisposals}})()`,`${route.routeId}: prior finite graph resources are disposed by the purge`,5000);const state=await snapshot();assert.equal(state.purging.some(item=>item.species==='PolymerSample'),false,`${route.routeId}: prior finite graph resources leave purge ownership before the new route proceeds`);assert.equal(state.polymerization.sampleId,null,`${route.routeId}: prior PolymerSample identity is cleared before the next reaction`);}
    routeCameraDistances.set(route.routeId,(await snapshot()).camera.distance);
    await setEnvironment(route);
    await waitFor(`window.__reactionLabProbe.snapshot().polymerization.waitReason!=='conditions'`,`${route.routeId}: route conditions did not become valid`);
  };
  const pointerDrag=async(plan,instanceId,routeId,manualIndex)=>{
    const rect=await evaluate(`(()=>{const r=document.querySelector('#reaction-lab canvas').getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height,documentWidth:document.documentElement.clientWidth,documentScroll:document.documentElement.scrollWidth}})()`);
    assert.ok(plan.start.x>=rect.x&&plan.start.x<=rect.x+rect.width&&plan.start.y>=rect.y&&plan.start.y<=rect.y+rect.height,`${routeId} manual step ${manualIndex}: reactive site is visible in the ${viewport.width}×${viewport.height} chamber: ${JSON.stringify(plan)}`);
    assert.ok(plan.end.x>=rect.x&&plan.end.x<=rect.x+rect.width&&plan.end.y>=rect.y&&plan.end.y<=rect.y+rect.height,`${routeId} manual step ${manualIndex}: projected target remains visible: ${JSON.stringify(plan)}`);
    assert.ok(rect.documentScroll<=rect.documentWidth+1,`${routeId} manual step ${manualIndex}: no horizontal overflow`);
    await send('Input.dispatchMouseEvent',{type:'mouseMoved',x:plan.start.x,y:plan.start.y});await send('Input.dispatchMouseEvent',{type:'mousePressed',x:plan.start.x,y:plan.start.y,button:'left',buttons:1,clickCount:1});await pause(40);
    assert.equal((await snapshot()).draggedInstanceId,instanceId,`${routeId} manual step ${manualIndex} acquires the intended real monomer on the first pointer target`);
    for(let step=1;step<=12;step++){const t=step/12;await send('Input.dispatchMouseEvent',{type:'mouseMoved',x:plan.start.x+(plan.end.x-plan.start.x)*t,y:plan.start.y+(plan.end.y-plan.start.y)*t,button:'left',buttons:1});await pause(20);}
    await send('Input.dispatchMouseEvent',{type:'mouseReleased',x:plan.end.x,y:plan.end.y,button:'left',buttons:0});
    await waitFor(`(()=>{const p=window.__reactionLabProbe.snapshot().polymerization;return p.manualStepCount===${manualIndex}&&p.state!=='TRANSFORMING'})()`,`${routeId} manual step ${manualIndex} did not commit from a pointer gesture`,9000);
    const committed=await snapshot();assert.equal(committed.pointerActive,false,`${routeId} manual gesture releases pointer capture`);
    if(routeId==='polyethylene-coordination'&&manualIndex===1){assert.ok(committed.polymerization.displayGraph?.unitCount>=2&&committed.polymerization.displayGraph.bondsResolveToRenderedAtoms,'actual finite graph and rendered bond endpoints stay connected during polymerization');await capture('actual-reaction');}
    const bondAllocations=committed.polymerRuntimeMetrics.bondVisualAllocations;await pause(360);assert.equal((await snapshot()).polymerRuntimeMetrics.bondVisualAllocations,bondAllocations,`${routeId} graph animation reuses bond geometry/materials after commit`);
  };
  const runManualSteps=async route=>{
    for(let manualIndex=1;manualIndex<=route.interactionCadence.manualSteps;manualIndex++){
      await waitFor("!!window.__reactionLabProbe.snapshot().polymerization.siteTarget",`${route.routeId} manual step ${manualIndex}: stable reactive site is presented`);
      const state=await snapshot(),consumed=state.polymerization.consumedInstanceIds,reserved=new Set(state.polymerization.reservedInstanceIds),species=route.representativeSequence[consumed.length],candidate=state.instances.find(item=>reserved.has(item.id)&&item.species===species&&!consumed.includes(item.id));
      assert.ok(candidate,`${route.routeId} manual step ${manualIndex}: representative incoming monomer is reserved and draggable`);
      const plan=await evaluate(`window.__reactionLabProbe.polymerDockPlan(${JSON.stringify(candidate.id)})`);await pointerDrag(plan,candidate.id,route.routeId,manualIndex);
      assert.equal((await snapshot()).polymerization.manualStepCount,manualIndex,`${route.routeId}: exactly one manual chemistry step was committed`);
    }
  };
  const completeAutomaticStep=async route=>{
    await waitFor("(()=>{const p=window.__reactionLabProbe.snapshot().polymerization;return p.state==='SAMPLE'||p.waitReason==='auto-fallback'})()",`${route.routeId}: automatic step completes or uses its existing pointer fallback`,18000);
    const state=await snapshot();if(state.polymerization.waitReason==='auto-fallback'){
      const p=state.polymerization,reserved=new Set(p.reservedInstanceIds),species=route.representativeSequence[p.consumedInstanceIds.length],candidate=state.instances.find(item=>reserved.has(item.id)&&item.species===species&&!p.consumedInstanceIds.includes(item.id));
      assert.ok(candidate,`${route.routeId}: existing pointer fallback keeps its actual final Feed monomer`);const plan=await evaluate(`window.__reactionLabProbe.polymerDockPlan(${JSON.stringify(candidate.id)})`);await pointerDrag(plan,candidate.id,route.routeId,p.manualStepCount+1);
    }
    await waitFor("window.__reactionLabProbe.snapshot().polymerization.state==='SAMPLE'",`${route.routeId}: final actual-pointer Feed completes`,18000);
  };
  const artifactDir=resolve(process.env.POLYMER_EVIDENCE_DIR??join(root,'test-results/reaction-lab-polymer-simplification'));
  const capture=async name=>{const image=await send('Page.captureScreenshot',{format:'png'});await mkdir(artifactDir,{recursive:true});await writeFile(join(artifactDir,`${name}-${viewport.width}.png`),Buffer.from(image.data,'base64'));};
  const inspectCompletion=async(route,{newDiscovery=false,expectedDuration=650}={})=>{
    const state=await snapshot(),p=state.polymerization,events=await evaluate('window.__polymerSampleEvents.slice()'),presentEvents=await evaluate('window.__polymerPresentEvents.slice()');
    assert.equal(state.camera.distance,routeCameraDistances.get(route.routeId),`${route.routeId}: finite completion leaves the basic camera scale unchanged`);
    assert.equal(p.state,'SAMPLE');assert.equal(p.routeId,route.routeId);assert.equal(p.polymerId,route.polymerId);assert.ok(p.sampleId);
    assert.equal(p.sampleDurationMs,expectedDuration);assert.equal(p.sampleEvidence.unitCount,route.completionEvidence.unitCount);assert.equal(p.sampleEvidence.interUnitLinks,route.completionEvidence.interUnitLinks);assert.equal(p.sampleEvidence.ringOpenings,route.completionEvidence.ringOpenings);
    assert.equal(p.displayGraph.unitCount,route.completionEvidence.unitCount);assert.equal(p.displayGraph.layoutUnitCount,route.completionEvidence.unitCount);assert.equal(p.displayGraph.atomOriginCount,p.displayGraph.atomCount);assert.equal(p.displayGraph.visibleAtomCount,p.displayGraph.atomCount);assert.equal(p.displayGraph.continuationCount,0,'no visual continuation markers or repeat units are added');assert.equal(p.displayGraph.bondsResolveToRenderedAtoms,true);assert.equal(p.displayedUnitCount,route.completionEvidence.unitCount);
    assert.equal(p.fit?.unitCount,route.completionEvidence.unitCount);assert.ok(p.fit.scale>0&&p.fit.scale<=1);assert.equal(state.instances.some(item=>item.species==='PolymerSample'),false,'PolymerSample is not inserted into the Stage B feed instances');
    assert.ok(state.polymerResources.geometryCount>0&&state.polymerResources.materialCount>0,`${route.routeId}: the visible finite fragment owns geometry and materials`);assert.equal(state.polymerResources.geometryCount,p.displayGraph.atomCount+p.displayGraph.visibleBondMeshCount,`${route.routeId}: only finite fragment atoms and bonds own render geometry`);assert.equal(state.polymerResources.materialCount,state.polymerResources.geometryCount,`${route.routeId}: each finite graph mesh has one current material`);
    assert.equal(events.length,1,'one sample registration event is emitted for each completion');assert.equal(events[0].detail.sampleId,p.sampleId);assert.equal(events[0].detail.routeId,route.routeId);assert.equal(events[0].detail.batchGeneration,state.batch.generation);assert.ok(events[0].detail.sourceInstanceIds.length>0);
    assert.equal(events[0].snapshot.polymerization.sampleReady,false,'registration occurs during bounded feedback');assert.equal(events[0].snapshot.polymerization.samplePhase,'completion');assert.equal(events[0].completionUi.hidden,false);assert.match(events[0].completionUi.status,/重合完了/);assert.equal(events[0].completionUi.encyclopediaDisabled,true,'Encyclopedia remains disabled until presentation is ready');
    assert.ok(presentEvents.length<=1);if(presentEvents.length)assert.ok(presentEvents[0].receivedAt>events[0].receivedAt&&presentEvents[0].snapshot.polymerization.sampleReady,'sample-present follows registration and readiness');
    const bounds=await evaluate('window.__reactionLabProbe.polymerDisplayBounds()');assert.ok(bounds?.depthVisible,`${route.routeId}: each actual atom remains within camera depth`);assert.ok(bounds?.insideSafeRegion,`${route.routeId}: finite fragment fits its work-area safe region: ${JSON.stringify(bounds)}`);
    return{state,events,presentEvents,bounds};
  };
  const finishCompletion=async(route,{newDiscovery=false,captureReady=false,captureName='completion-ready',expectedDuration=650}={})=>{
    await waitFor('window.__reactionLabProbe.snapshot().polymerization.sampleReady',`${route.routeId}: bounded completion feedback did not become ready`,5000);
    await waitFor("(()=>{const state=window.__reactionLabProbe.snapshot();return state.dialogOpen?state.polymerResources.activeGroupCount===1:state.polymerResources.geometryCount===0})()",`${route.routeId}: finite resources settle to the Reaction Lab open/closed state`,2000);
    const state=await snapshot(),p=state.polymerization,presentEvents=await evaluate('window.__polymerPresentEvents.slice()');
    assert.equal(state.camera.distance,routeCameraDistances.get(route.routeId),`${route.routeId}: readiness adds no camera transition`);
    assert.equal(p.sampleReady,true);assert.equal(p.samplePhase,'ready');assert.equal(p.layoutCallsAtReady,state.polymerRuntimeMetrics.finiteLayoutCalls);assert.equal(state.polymerRuntimeMetrics.completionLayoutCallsAfterReady,0);
    const expectedActiveGroups=state.dialogOpen?1:0;assert.equal(state.polymerResources.activeGroupCount,expectedActiveGroups,`${route.routeId}: finite sample resources exist only while the Reaction Lab is open`);assert.equal(state.polymerResources.geometryCount,state.dialogOpen?p.displayGraph.atomCount+p.displayGraph.visibleBondMeshCount:0,`${route.routeId}: finite graph resources are disposed when discovery closes the Lab`);assert.equal(state.polymerResources.materialCount,state.polymerResources.geometryCount);
    assert.equal(presentEvents.length,1,'sample-present fires exactly once after readiness');assert.equal(presentEvents[0].detail.sampleId,p.sampleId);assert.equal(presentEvents[0].detail.batchGeneration,state.batch.generation);
    const registrationEvents=await evaluate('window.__polymerSampleEvents.slice()'),delay=presentEvents[0].receivedAt-registrationEvents[0].receivedAt;
    assert.ok(delay>=expectedDuration-30&&delay<expectedDuration+(expectedDuration===250?750:850),`${route.routeId}: sample-present follows ${expectedDuration} ms bounded feedback (${delay} ms)`);
    const frameProfile=await evaluate(`window.__polymerFrameProbe.summary(${JSON.stringify(p.sampleId)})`);
    assert.ok(frameProfile?.frameIntervalsMs.count>0,`${route.routeId}: frame sampler captured the completion interval`);
    const motion=expectedDuration===250?'reduced':'normal',trialIndex=performanceEvidence.filter(item=>item.motion===motion).length;
    const moduleUrls=await evaluate("[...new Set(performance.getEntriesByType('resource').map(entry=>entry.name).filter(name=>/\\.m?js(?:$|[?#])/.test(name)))]");
    performanceEvidence.push({sourceSha:process.env.POLYMER_SOURCE_SHA??null,browser:browserVersion.product,viewport:{width:viewport.width,height:viewport.height,deviceScaleFactor:1},runtimeFlags:['--headless=new','--no-sandbox','--disable-background-networking','--disable-background-timer-throttling','--disable-renderer-backgrounding','--disable-backgrounding-occluded-windows','--use-gl=angle','--use-angle=swiftshader','--enable-webgl','--ignore-gpu-blocklist','--force-device-scale-factor=1'],routeId:route.routeId,polymerId:route.polymerId,motion,trialIndex,warmup:trialIndex===0,completionElapsedMs:frameProfile.completionElapsedMs,targetDurationMs:frameProfile.targetDurationMs,frameIntervalsMs:frameProfile.frameIntervalsMs,jsUpdateTimeMs:'NOT_MEASURED',renderSubmissionTimeMs:'NOT_MEASURED',gpuExecutionTimeMs:'NOT_MEASURED',moduleFetchCount:moduleUrls.length,retiredModuleFetchCount:retiredModuleRequests.length,polymerResources:state.polymerResources,polymerRuntimeMetrics:state.polymerRuntimeMetrics,reportedPresentDelayMs:delay});
    assert.equal(await evaluate("document.querySelector('[data-polymer-completion]').hidden"),false);assert.equal(await evaluate("document.querySelector('[data-polymer-completion-status]').textContent"),'重合完了 · 次のFeedまたは図鑑へ進めます');
    assert.equal(await evaluate("document.querySelector('[data-polymer-completion-name]').textContent"),polymers.find(item=>item.id===route.polymerId).nameJa,'completion UI uses the catalog polymer name');
    assert.equal(await evaluate("document.querySelector('[data-lab-feed]').disabled"),false,'FEED is available after readiness');
    const known=await evaluate(`document.querySelector('[data-polymer-encyclopedia]').hidden===false`);
    if(known){assert.equal(await evaluate("document.querySelector('[data-polymer-encyclopedia]').disabled"),false,'known polymer has an enabled Encyclopedia action');assert.equal(await evaluate("document.querySelector('[data-polymer-encyclopedia]').textContent"),'図鑑を開く');}
    const completionGeometry=await evaluate(`(()=>{const footer=document.querySelector('[data-polymer-completion]').getBoundingClientRect(),feed=document.querySelector('[data-lab-command-state]').parentElement.getBoundingClientRect(),action=document.querySelector('[data-polymer-encyclopedia]').getBoundingClientRect();return{footer:{left:footer.left,right:footer.right,top:footer.top,bottom:footer.bottom},feed:{left:feed.left,right:feed.right,top:feed.top,bottom:feed.bottom},action:{hidden:document.querySelector('[data-polymer-encyclopedia]').hidden,width:action.width,height:action.height}}})()`);
    assert.ok(completionGeometry.footer.left>=0&&completionGeometry.footer.right<=viewport.width&&completionGeometry.footer.top>=0&&completionGeometry.footer.bottom<=viewport.height,`${route.routeId}: completion UI remains inside the viewport: ${JSON.stringify(completionGeometry)}`);assert.ok(completionGeometry.footer.bottom<=completionGeometry.feed.top||completionGeometry.footer.top>=completionGeometry.feed.bottom,`${route.routeId}: completion UI does not overlap FEED controls`);if(known&&viewport.mobile&&!newDiscovery)assert.ok(completionGeometry.action.height>=44,`${route.routeId}: visible mobile Encyclopedia target is at least 44 px high`);
    if(captureReady)await capture(captureName);
    await pause(350);
    const settled=await snapshot();assert.equal(settled.polymerRuntimeMetrics.finiteLayoutCalls,state.polymerRuntimeMetrics.finiteLayoutCalls,'ready fragment does not recompute its layout');assert.equal(settled.polymerRuntimeMetrics.bondVisualAllocations,state.polymerRuntimeMetrics.bondVisualAllocations,'ready fragment does not allocate bond visuals');assert.equal(settled.polymerRuntimeMetrics.completionLayoutCallsAfterReady,0,'ready state performs no completion layout');assert.equal(settled.polymerResources.geometryCount,state.polymerResources.geometryCount,'ready fragment resource ownership remains stable');
    if(newDiscovery){
      await waitFor("document.querySelector('#collection-dialog').open&&!!document.querySelector('#collection-detail [data-discovery-session-action]')&&!document.querySelector('#collection-detail [data-discovery-session-action]').disabled",`${route.routeId}: existing discovery reveal did not complete`);
      const reveal=await evaluate(`(()=>({entry:document.querySelector('#collection-detail h3')?.textContent,marker:document.querySelector('[data-registration-marker]')?.textContent??'',action:document.querySelector('#collection-detail [data-discovery-session-action]')?.textContent}))()`);
      assert.equal(reveal.entry,polymers.find(item=>item.id===route.polymerId).nameJa);assert.match(reveal.marker,/REGISTERED|NEW ENTRY/);assert.equal(reveal.action,'REACTION LABへ戻る');
      await evaluate("document.querySelector('#collection-detail [data-discovery-session-action]').click()");await waitFor("document.querySelector('#reaction-lab-dialog').open&&!document.querySelector('#collection-dialog').open",`${route.routeId}: discovery return did not restore the Lab`);
      const returned=await snapshot();assert.equal(returned.polymerization.sampleId,p.sampleId);assert.equal(returned.polymerization.sampleReady,true);assert.equal(returned.polymerResources.activeGroupCount,1,'returning from Collection restores one finite graph group');assert.equal(returned.polymerResources.geometryCount,returned.polymerization.displayGraph.atomCount+returned.polymerization.displayGraph.visibleBondMeshCount,'returning from Collection reconstructs exactly the finite graph resource set');
      if(route.polymerId==='polyethylene')await capture('final-finite-fragment');
    }
    return{state:await snapshot(),delay};
  };
  let viewerDisposalEvidence=null;
  const saveEvidence=async()=>{await mkdir(artifactDir,{recursive:true});await writeFile(join(artifactDir,`browser-${viewport.width}.json`),JSON.stringify(evidence,null,2));await writeFile(join(artifactDir,`performance-${viewport.width}.json`),JSON.stringify({schemaVersion:1,sourceSha:process.env.POLYMER_SOURCE_SHA??null,browser:{product:browserVersion.product,revision:browserVersion.revision,protocolVersion:browserVersion.protocolVersion},viewport:{...viewport,deviceScaleFactor:1},warmupPolicy:'First completion for each motion mode is retained but excluded from aggregate regression statistics.',measurements:performanceEvidence,viewerDisposal:viewerDisposalEvidence,notMeasured:['per-frame JavaScript update duration','WebGL submission CPU duration','GPU execution time','device memory']},null,2));};
  let previousSample=false;const normalEvidence=[];
  if(process.env.POLYMER_PROFILE_ONLY==='1'){
    const route=hardRoutes[0],runProfileTrial=async(motion,trialIndex)=>{
      const reduced=motion==='reduced',expectedDuration=reduced?250:650,newDiscovery=motion==='normal'&&trialIndex===0;
      await resetPolymerEvents();await feedRoute(route,previousSample);await runManualSteps(route);await completeAutomaticStep(route);
      await inspectCompletion(route,{newDiscovery,expectedDuration});
      const result=await finishCompletion(route,{newDiscovery,expectedDuration});
      const measurement=performanceEvidence.at(-1);assert.equal(measurement.motion,motion);assert.equal(measurement.trialIndex,trialIndex);assert.equal(measurement.targetDurationMs,expectedDuration);console.log(`POLYMER_PROFILE_TRIAL ${JSON.stringify({sourceSha:measurement.sourceSha,viewport:measurement.viewport,motion,trialIndex,warmup:measurement.warmup,completionElapsedMs:measurement.completionElapsedMs,targetDurationMs:measurement.targetDurationMs,frameIntervalsMs:measurement.frameIntervalsMs,reportedPresentDelayMs:measurement.reportedPresentDelayMs,polymerRuntimeMetrics:measurement.polymerRuntimeMetrics,polymerResources:measurement.polymerResources,moduleFetchCount:measurement.moduleFetchCount,retiredModuleFetchCount:measurement.retiredModuleFetchCount,runtimeFlags:measurement.runtimeFlags})}`);await saveEvidence();assert.ok(measurement.frameIntervalsMs.count>0,`${motion} trial ${trialIndex} captured no frame intervals`);
      previousSample=true;return result;
    };
    for(let trial=0;trial<5;trial++)await runProfileTrial('normal',trial);
    await send('Page.removeScriptToEvaluateOnNewDocument',{identifier:seedPage.identifier});
    await send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});await send('Page.reload',{ignoreCache:true});
    await waitFor("!!document.querySelector('#open-reaction-lab')&&!document.querySelector('#open-reaction-lab').disabled&&!!window.__reactionLabProbe",'Reduced-motion profile reload did not initialize');await openLab();await wireDiscoveryEvents();previousSample=false;
    for(let trial=0;trial<5;trial++)await runProfileTrial('reduced',trial);
    const final=await snapshot();assert.equal(final.instances.some(item=>item.species==='PolymerSample'),false);assert.deepEqual(browserErrors,[],'No browser console error or exception occurs during performance profiling');
    assert.equal(performanceEvidence.filter(item=>item.motion==='normal'&&!item.warmup).length,4);assert.equal(performanceEvidence.filter(item=>item.motion==='reduced'&&!item.warmup).length,4);
    console.log(`Polymer completion profile passed at ${viewport.width}×${viewport.height}: 1 warm-up + 4 measured PE trials for normal and reduced motion.`);
  }else{
  for(const route of hardRoutes){
    await resetPolymerEvents();await feedRoute(route,previousSample);await runManualSteps(route);await completeAutomaticStep(route);
    const preReady=await inspectCompletion(route,{newDiscovery:true}),ready=await finishCompletion(route,{newDiscovery:true});
    const row={routeId:route.routeId,polymerId:route.polymerId,viewport,durationMs:preReady.state.polymerization.sampleDurationMs,presentDelayMs:ready.delay,unitCount:ready.state.polymerization.displayGraph.unitCount,atomCount:ready.state.polymerization.displayGraph.atomCount,bondCount:ready.state.polymerization.displayGraph.bondCount,visibleBondMeshCount:ready.state.polymerization.displayGraph.visibleBondMeshCount,fit:ready.state.polymerization.fit,readyLayoutCalls:ready.state.polymerization.layoutCallsAtReady,finiteLayoutCalls:ready.state.polymerRuntimeMetrics.finiteLayoutCalls,completionLayoutCallsAfterReady:ready.state.polymerRuntimeMetrics.completionLayoutCallsAfterReady,polymerResources:ready.state.polymerResources,retiredModuleRequests,metrics:ready.state.polymerRuntimeMetrics};
    evidence.push(row);normalEvidence.push(ready.state.polymerization.sampleEvidence);previousSample=true;
  }
  const discoveries=await evaluate(`JSON.parse(localStorage.getItem('molecule-craft.polymer-collection.v1')||'{}').discoveredPolymers`);assert.equal(discoveries.length,9);assert.deepEqual(discoveries.map(item=>item.order),[1,2,3,4,5,6,7,8,9]);
  {
    const pe=hardRoutes[0];
    // A previously discovered polymer opens through the existing closeAndWait → collection API path.
    await resetPolymerEvents();await feedRoute(pe,true);await runManualSteps(pe);await completeAutomaticStep(pe);await inspectCompletion(pe);await finishCompletion(pe,{captureReady:true,captureName:'completion-ready-known'});
    assert.equal(await evaluate("document.querySelector('[data-polymer-encyclopedia]').hidden"),false);
    const resourcesBeforeClose=await evaluate('window.__reactionLabProbe.polymerResourceSnapshot()'),transformBeforeClose=await evaluate(`(()=>{const graph=window.__reactionLabProbe.snapshot().polymerization.displayGraph;return{position:graph.groupPosition,scale:graph.groupScale}})()`);
    await evaluate("document.querySelector('[data-polymer-encyclopedia]').click()");await waitFor("!document.querySelector('#reaction-lab-dialog').open&&document.querySelector('#collection-dialog').open",'known Encyclopedia action safely closes the Lab and opens the collection');
    await waitFor('window.__reactionLabProbe.polymerResourceSnapshot().geometryCount===0','closing the Lab disposes finite fragment resources');const resourcesWhileClosed=await evaluate('window.__reactionLabProbe.polymerResourceSnapshot()');assert.ok(resourcesWhileClosed.disposals.geometryDisposals-resourcesBeforeClose.disposals.geometryDisposals>=resourcesBeforeClose.geometryCount,'Lab close disposes every finite fragment geometry');assert.ok(resourcesWhileClosed.disposals.materialDisposals-resourcesBeforeClose.disposals.materialDisposals>=resourcesBeforeClose.materialCount,'Lab close disposes every finite fragment material');
    assert.equal(await evaluate("document.querySelector('#collection-detail h3')?.textContent"),polymers.find(item=>item.id===pe.polymerId).nameJa,'known action opens the corresponding polymer entry');
    await capture('encyclopedia-entry');
    await evaluate("document.querySelector('#close-collection').click()");await waitFor("!document.querySelector('#collection-dialog').open&&!document.body.classList.contains('collection-open')",'known entry closes cleanly');await pause(120);await openLab();assert.equal((await evaluate('window.__reactionLabProbe.polymerResourceSnapshot()')).geometryCount,resourcesBeforeClose.geometryCount,'reopening the Lab restores the same finite sample geometry');const reopenedState=await snapshot();assert.deepEqual(reopenedState.polymerization.displayGraph.groupPosition,transformBeforeClose.position,'reopening preserves the finite sample fit position');assert.deepEqual(reopenedState.polymerization.displayGraph.groupScale,transformBeforeClose.scale,'reopening preserves the finite sample fit scale');assert.ok((await evaluate('window.__reactionLabProbe.polymerDisplayBounds()')).insideSafeRegion,'reopened finite sample remains in its fitted work area');
    // Closing before readiness emits one dismiss, pauses the feedback, and cannot register a presentation while closed.
    await resetPolymerEvents();await feedRoute(pe,true);await runManualSteps(pe);await evaluate('window.__closeBeforeReadyOnNextSample=true');await completeAutomaticStep(pe);
    const beforeClose=await snapshot();assert.equal(beforeClose.polymerization.sampleReady,false);await waitFor("!document.querySelector('#reaction-lab-dialog').open&&window.__polymerDismissEvents.length===1",'Lab closes at sample registration and emits one pre-ready dismiss');
    await waitFor('window.__reactionLabProbe.polymerResourceSnapshot().geometryCount===0','closing before readiness disposes finite fragment resources');
    const dismissed=await evaluate('window.__polymerDismissEvents.slice()');assert.equal(dismissed.length,1);assert.equal(dismissed[0].detail.sampleId,beforeClose.polymerization.sampleId);
    await pause(800);assert.equal((await evaluate('window.__polymerPresentEvents.slice()')).length,0,'closed-before-ready sample does not emit sample-present');
    await openLab();await waitFor('window.__reactionLabProbe.snapshot().polymerization.sampleReady','dismissed sample can become ready after reopening',5000);assert.ok((await evaluate('window.__reactionLabProbe.polymerResourceSnapshot()')).geometryCount>0,'reopening restores the finite graph after close-before-ready');
    assert.equal((await evaluate('window.__polymerPresentEvents.slice()')).length,0,'dismissed sample never emits a late present event');assert.equal((await evaluate('window.__polymerDismissEvents.slice()')).length,1,'sample-dismiss is emitted once');
    await resetPolymerEvents();await feedRoute(pe,true);await runManualSteps(pe);await completeAutomaticStep(pe);await inspectCompletion(pe);await finishCompletion(pe,{captureReady:true});
    const afterPurge=await snapshot();assert.equal(afterPurge.polymerization.displayGraph.unitCount,pe.completionEvidence.unitCount);assert.ok(afterPurge.polymerResources.geometryCount>0);
  }
  // Keep the discovered collection through reload so reduced motion exercises the known-polymer path.
  await send('Page.removeScriptToEvaluateOnNewDocument',{identifier:seedPage.identifier});
  await send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});await send('Page.reload',{ignoreCache:true});
  await waitFor("!!document.querySelector('#open-reaction-lab')&&!document.querySelector('#open-reaction-lab').disabled&&!!window.__reactionLabProbe",'Reduced-motion reload did not initialize');await openLab();await wireDiscoveryEvents();
  {
    const pe=hardRoutes[0];await resetPolymerEvents();await feedRoute(pe,false);await runManualSteps(pe);await completeAutomaticStep(pe);
    const reduced=await inspectCompletion(pe,{expectedDuration:250});assert.equal(reduced.state.polymerization.sampleDurationMs,250,'reduced motion uses 250 ms bounded completion feedback');await capture('reduced-motion-feedback');
    const done=await finishCompletion(pe,{captureReady:true,captureName:'completion-ready-reduced',expectedDuration:250});const present=await evaluate('window.__polymerPresentEvents.slice()'),registration=await evaluate('window.__polymerSampleEvents.slice()'),delay=present[0].receivedAt-registration[0].receivedAt;
    assert.ok(delay>=230&&delay<1000,`reduced-motion sample-present follows 250 ms feedback (${delay} ms)`);assert.equal(done.state.polymerization.sampleEvidence.unitCount,normalEvidence[0].unitCount);assert.equal(done.state.polymerization.displayGraph.unitCount,pe.completionEvidence.unitCount);assert.equal(done.state.polymerization.sampleReady,true);
    assert.equal(await evaluate("document.querySelector('[data-polymer-encyclopedia]').disabled"),false);evidence.push({routeId:'polyethylene-reduced-motion',viewport,durationMs:250,presentDelayMs:delay,unitCount:done.state.polymerization.displayGraph.unitCount,atomCount:done.state.polymerization.displayGraph.atomCount,visibleBondMeshCount:done.state.polymerization.displayGraph.visibleBondMeshCount,readyLayoutCalls:done.state.polymerization.layoutCallsAtReady,finiteLayoutCalls:done.state.polymerRuntimeMetrics.finiteLayoutCalls,completionLayoutCallsAfterReady:done.state.polymerRuntimeMetrics.completionLayoutCallsAfterReady,polymerResources:done.state.polymerResources,retiredModuleRequests,metrics:done.state.polymerRuntimeMetrics});
  }
  const final=await snapshot();assert.equal(final.instances.some(item=>item.species==='PolymerSample'),false);assert.deepEqual(browserErrors,[],'No browser console error or exception occurs during polymer gameplay');
  }
  const resourcesBeforeDispose=await evaluate('window.__reactionLabProbe.polymerResourceSnapshot()');assert.equal(resourcesBeforeDispose.activeGroupCount,1,'the ready finite Sample is owned before viewer disposal');
  await evaluate('window.__reactionLabViewer.dispose()');
  await waitFor('window.__reactionLabProbe.polymerResourceSnapshot().activeGroupCount===0&&window.__reactionLabProbe.polymerResourceSnapshot().geometryCount===0&&window.__reactionLabProbe.polymerResourceSnapshot().materialCount===0','viewer.dispose() did not release all finite Sample render resources',5000);
  const resourcesAfterDispose=await evaluate('window.__reactionLabProbe.polymerResourceSnapshot()'),afterDispose=await snapshot();
  assert.ok(resourcesAfterDispose.disposals.geometryDisposals-resourcesBeforeDispose.disposals.geometryDisposals>=resourcesBeforeDispose.geometryCount,'viewer disposal releases every finite Sample geometry');
  assert.ok(resourcesAfterDispose.disposals.materialDisposals-resourcesBeforeDispose.disposals.materialDisposals>=resourcesBeforeDispose.materialCount,'viewer disposal releases every finite Sample material');
  await pause(100);const settledAfterDispose=await snapshot();assert.deepEqual(settledAfterDispose.polymerRuntimeMetrics,afterDispose.polymerRuntimeMetrics,'disposed viewer does not resume runtime work');
  viewerDisposalEvidence={before:resourcesBeforeDispose,after:resourcesAfterDispose,runtimeStableAfterDispose:true,rendererDisposeCalled:true,eventControllerAbortedByProductionDispose:true};
  await saveEvidence();assert.deepEqual(browserErrors,[],'No browser console error or exception occurs through viewer disposal');
}finally{try{socket?.close();}catch{}try{child?.kill('SIGKILL');}catch{}await pause(500);server.close();await rm(profile,{recursive:true,force:true,maxRetries:8,retryDelay:100});}
console.log(`Reaction Lab finite-polymer completion validation passed at ${viewport.width}×${viewport.height}; 9 representative actual-pointer routes, 650/250 ms feedback, discovery/known entry, next Feed/purge, close/reopen resource disposal, close-before-ready, and retired module fetches=0.`);
