import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile} from 'node:fs/promises';
import {extname,join,normalize,resolve} from 'node:path';
import {spawn,spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';

const root=resolve(fileURLToPath(new URL('..',import.meta.url)));
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.webmanifest':'application/manifest+json'};
const server=createServer(async(request,response)=>{
  try{const path=new URL(request.url,'http://localhost').pathname==='/'?'index.html':decodeURIComponent(new URL(request.url,'http://localhost').pathname).replace(/^\/+/,''),file=normalize(join(root,path));if(!file.startsWith(root))throw Error();response.writeHead(200,{'content-type':mime[extname(file)]??'application/octet-stream','cache-control':'no-store'});response.end(await readFile(file));}
  catch{response.writeHead(404).end();}
});
await new Promise(done=>server.listen(0,'127.0.0.1',done));
const {port}=server.address();
let chrome='';
for(const command of ['google-chrome','chromium','chromium-browser']){const found=spawnSync('which',[command],{encoding:'utf8'});if(found.status===0&&found.stdout.trim()){chrome=found.stdout.trim();break;}}
assert.ok(chrome,'Chromium is required for Reaction Lab mobile validation');
const debugPort=9237,profile=`/tmp/molecule-craft-reaction-lab-${process.pid}`;let child,socket;

try{
  child=spawn(chrome,['--headless=new','--no-sandbox','--disable-background-networking','--use-gl=angle','--use-angle=swiftshader','--enable-webgl','--ignore-gpu-blocklist',`--user-data-dir=${profile}`,`--remote-debugging-port=${debugPort}`,'about:blank'],{stdio:'ignore'});
  let tabs;
  for(let index=0;index<180;index++){try{const response=await fetch(`http://127.0.0.1:${debugPort}/json/list`);if(response.ok){tabs=await response.json();if(tabs.length)break;}}catch{}await new Promise(resolve=>setTimeout(resolve,100));}
  assert.ok(tabs?.length,'Chromium DevTools endpoint not ready');
  socket=new WebSocket(tabs.find(tab=>tab.type==='page')?.webSocketDebuggerUrl??tabs[0].webSocketDebuggerUrl);
  await new Promise((resolve,reject)=>{socket.addEventListener('open',resolve,{once:true});socket.addEventListener('error',reject,{once:true});});
  let sequence=0;const pending=new Map(),browserErrors=[];
  socket.addEventListener('message',event=>{const message=JSON.parse(event.data);if(message.id&&pending.has(message.id)){const task=pending.get(message.id);pending.delete(message.id);message.error?task.reject(Error(message.error.message)):task.resolve(message.result);}});
  socket.addEventListener('message',event=>{const message=JSON.parse(event.data);if(message.method==='Runtime.exceptionThrown')browserErrors.push({type:'exception',text:message.params.exceptionDetails.exception?.description??message.params.exceptionDetails.text});else if(message.method==='Runtime.consoleAPICalled'&&message.params.type==='error')browserErrors.push({type:'console',text:message.params.args?.map(arg=>arg.value??arg.description).join(' ')});else if(message.method==='Network.loadingFailed')browserErrors.push({type:'network',error:message.params.errorText});});
  const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++sequence;pending.set(id,{resolve,reject});socket.send(JSON.stringify({id,method,params}));});
  const evaluate=async expression=>{const result=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(result.exceptionDetails)throw Error(result.exceptionDetails.exception?.description??result.exceptionDetails.text);return result.result?.value;};
  const waitFor=async(expression,label,timeout=8000)=>{for(let index=0;index<timeout/40;index++){const value=await evaluate(expression);if(value)return value;await new Promise(resolve=>setTimeout(resolve,40));}const state=await evaluate("({readyState:document.readyState,title:document.title,button:!!document.querySelector('#open-reaction-lab'),disabled:document.querySelector('#open-reaction-lab')?.disabled,dialog:!!document.querySelector('#reaction-lab-dialog'),probe:!!window.__reactionLabProbe})");throw Error(`${label}: ${JSON.stringify({state,browserErrors})}`);};
  const setDraftSlots=async ids=>{
    for(let index=0;index<3;index++){
      const current=await evaluate(`window.__reactionLabProbe.snapshot().batch.draftSlots[${index}]??''`),next=ids[index]??'';if(current===next)continue;
      await evaluate(`document.querySelectorAll('[data-lab-slot]')[${index}].click()`);await waitFor("!document.querySelector('[data-lab-picker]').hidden",'Species picker did not open');
      if(next){await evaluate(`(()=>{const input=document.querySelector('[data-lab-search]');input.value=${JSON.stringify(next)};input.dispatchEvent(new Event('input',{bubbles:true}));document.querySelector('[data-lab-picker-list] [data-species="${next}"]').click();})()`);}
      else await evaluate("document.querySelector('[data-lab-disconnect]').click()");
      await waitFor("document.querySelector('[data-lab-picker]').hidden",'Species picker did not close');
    }
  };
  const feedCurrent=async({double=false}={})=>{
    const before=await snapshot(),next=before.batch.draftSlots,count=next.filter(Boolean).length,expected=count===1?4:count===2?4:count===3?6:0;
    if(expected===0&&before.batch.phase==='IDLE'&&!before.instances.length)return before;
    await evaluate(`(()=>{const button=document.querySelector('[data-lab-feed]');button.click();${double?'button.click();':''}})()`);
    if(expected){await waitFor(`(()=>{const s=window.__reactionLabProbe.snapshot();return s.batch.phase==='ACTIVE'&&s.batch.activeSlots.every((id,index)=>id===${JSON.stringify(next)}[index])&&s.instances.length===${expected}})()`,'FEED batch did not reach ACTIVE',12000);}
    else await waitFor("(()=>{const s=window.__reactionLabProbe.snapshot();return s.batch.phase==='IDLE'&&!s.instances.length&&!s.purging.length&&!s.batch.transitionKind})()",'Empty FEED did not finish purging',12000);
    return snapshot();
  };
  const setSlots=async ids=>{await setDraftSlots(ids);return feedCurrent();};
  const snapshot=()=>evaluate('window.__reactionLabProbe.snapshot()');
  const waitForPopulation=async(species,total,label)=>waitFor(`(()=>{const state=window.__reactionLabProbe?.snapshot();const rows=state?.instances??[];return state?.batch.phase==='ACTIVE'&&rows.length===${total}&&${JSON.stringify(species)}.every(id=>rows.some(row=>row.species===id))})()`,label,12000);
  const pointer=async(type,id,x,y)=>evaluate(`document.querySelector('#reaction-lab canvas').dispatchEvent(new PointerEvent('${type}',{pointerId:${id},pointerType:'touch',clientX:${x},clientY:${y},button:0,buttons:${type==='pointerup'||type==='pointercancel'?0:1},bubbles:true,cancelable:true}))`);
  const drag=async(plan,{steps=12,stepDelay=20,hold=720,duringHold=null}={})=>{
    await send('Input.dispatchMouseEvent',{type:'mouseMoved',x:plan.start.x,y:plan.start.y});
    await send('Input.dispatchMouseEvent',{type:'mousePressed',x:plan.start.x,y:plan.start.y,button:'left',buttons:1,clickCount:1});
    for(let step=1;step<=steps;step++){const progress=step/steps;await send('Input.dispatchMouseEvent',{type:'mouseMoved',x:plan.start.x+(plan.end.x-plan.start.x)*progress,y:plan.start.y+(plan.end.y-plan.start.y)*progress,button:'left',buttons:1});await new Promise(resolve=>setTimeout(resolve,stepDelay));}
    if(duringHold)await duringHold();else if(hold)await new Promise(resolve=>setTimeout(resolve,hold));
    await send('Input.dispatchMouseEvent',{type:'mouseReleased',x:plan.end.x,y:plan.end.y,button:'left',buttons:0});
  };
  const runReaction=async(ruleId,products)=>{
    await evaluate('window.__labReactionEvents=[]');
    const plan=await evaluate(`window.__reactionLabProbe.prepareReactionApproach('${ruleId}',4.2)`);
    assert.ok(plan.initialSiteDistance>1.18&&plan.initialDepthDelta>2,`reactive atoms begin separated in depth and distance: ${JSON.stringify(plan)}`);
    let heldState=null;
    await drag(plan,{steps:14,stepDelay:18,hold:360,duringHold:async()=>{
      await new Promise(resolve=>setTimeout(resolve,600));heldState=await snapshot();
      assert.equal(heldState.draggedInstanceId,plan.left);assert.equal(heldState.depthTargetId,plan.right,`${ruleId} acquired the molecule under the pointer`);
      assert.equal(heldState.simulationTimeScale,.15);assert.ok(heldState.pointerAnchorErrorPx<=3,`pointer anchor drifted ${heldState.pointerAnchorErrorPx}px`);
      assert.ok(Math.abs(heldState.instances.find(item=>item.id===plan.left).position[2]-plan.before[2])>.35,'the drag docks through hidden depth');
      assert.equal(await evaluate('window.__labReactionEvents.length'),0,'Slow manipulation does not satisfy a 520ms dwell in 520ms real time');
    }});
    assert.equal((await snapshot()).simulationTimeScale,1,'Releasing the drag restores normal simulation time');
    const contact=await evaluate(`window.__reactionLabProbe.reactionContactDiagnostics('${ruleId}').filter(item=>item.ids.includes('${plan.left}')&&item.ids.includes('${plan.right}')).map(({ids,distance,maxDistance,isolationEligible})=>({ids,distance,maxDistance,isolationEligible}))`);
    assert.ok(contact.some(item=>item.isolationEligible&&item.distance<item.maxDistance),`visual docking must establish actual 3D reaction-site contact: ${JSON.stringify(contact)}`);
    await evaluate(`window.__reactionLabProbe.settlePair('${plan.left}','${plan.right}')`);
    await evaluate("document.querySelectorAll('[data-lab-slot]')[2].click()");await waitFor("!document.querySelector('[data-lab-picker]').hidden",'Reaction contact pause picker did not open');
    const pauseStart=await snapshot(),pauseClock=pauseStart.simulationClockSeconds;await new Promise(resolve=>setTimeout(resolve,700));const pauseEnd=await snapshot();assert.equal(pauseEnd.simulationClockSeconds,pauseClock,'Picker time is excluded from the simulation clock');assert.equal(await evaluate('window.__labReactionEvents.length'),0,'Contact dwell cannot commit while the picker suspends the Chamber');
    await evaluate("document.querySelector('[data-lab-picker-close]').click()");assert.equal(await evaluate("document.activeElement===document.querySelectorAll('[data-lab-slot]')[2]"),true,'Closing picker restores focus to the invoking feed tile');
    await new Promise(resolve=>setTimeout(resolve,560));const state=await snapshot();assert.equal(state.dialogOpen,true,'Reaction commit must not close the Lab');
    try{await waitFor("document.querySelector('[data-lab-status]').textContent.startsWith('反応完了')",`${ruleId} did not complete after continuous simulation-time contact`,9000);}catch(error){const contact=await evaluate(`window.__reactionLabProbe.reactionContactDiagnostics('${ruleId}').filter(item=>item.ids.includes('${plan.left}')&&item.ids.includes('${plan.right}')).map(({ids,distance,maxDistance,contactPairActive,busy,isolationEligible})=>({ids,distance,maxDistance,contactPairActive,busy,isolationEligible}))`);throw Error(`${error.message}; reaction contact=${JSON.stringify(contact)}`);}
    await waitFor(`window.__labReactionEvents.at(-1)?.ruleId==='${ruleId}'`,'Reaction product event was not emitted',2000);
    const result=await evaluate('window.__labReactionEvents.at(-1)');
    assert.deepEqual(result.products,products);
    let remaining=await snapshot();assert.equal(remaining.pointerActive,false,'Reaction completion clears stale drag/pointer state');for(const product of products)assert.ok(remaining.instances.some(item=>item.species===product),`3D product instance missing: ${product}`);
    assert.equal(remaining.instances.filter(item=>products.includes(item.species)).length,products.length,'Reaction must spawn the correct product instance count');
    assert.equal(remaining.instances.length,4,'Finite batch products remain alongside only the unconsumed reactant instances');assert.deepEqual(result.temporarySupply,undefined,'Reaction event creates no virtual supply');assert.ok(remaining.instances.every(item=>item.batchGeneration===remaining.batch.generation),'Products remain in the current batch generation');
    const reactantSpecies=ruleId==='anhydride-hydrolysis'?['acetic-anhydride','water']:['acetic-anhydride','ethanol'];for(const species of reactantSpecies)assert.equal(remaining.instances.filter(item=>item.species===species).length,1,`Consumed ${species} is not automatically replenished from the feed rack`);
    assert.equal(remaining.instances.some(item=>item.busy),false,'products and remaining species become manipulable after commitment');
    const productInstances=remaining.instances.filter(item=>products.includes(item.species));await evaluate(`window.__reactionLabProbe.setGeometry(${JSON.stringify(productInstances.map((item,index)=>({id:item.id,positionAngstrom:[index?2:-2,0,0],orientation:[0,0,0,1]})))})`);remaining=await snapshot();
    const product=remaining.instances.find(item=>products.includes(item.species)),movePlan=await evaluate(`window.__reactionLabProbe.dragPlan('${product.id}',0,[0.32,0,0])`),before=product.position;
    await drag(movePlan,{steps:4,stepDelay:16,hold:0});const moved=await snapshot(),after=moved.instances.find(item=>item.id===product.id).position;
    assert.ok(Math.hypot(...after.map((value,index)=>value-before[index]))>.15,'Generated products remain individually movable');const productIds=moved.instances.filter(item=>products.includes(item.species)).map(item=>item.id);await new Promise(resolve=>setTimeout(resolve,300));remaining=await snapshot();assert.ok(productIds.every(id=>remaining.instances.some(item=>item.id===id)),'Products persist in the same batch without a timer cleanup');return remaining;
  };

  await send('Runtime.enable');await send('Page.enable');await send('Network.enable');
  await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
  await send('Page.addScriptToEvaluateOnNewDocument',{source:`localStorage.setItem('molecule-craft.collection.v1',JSON.stringify({schemaVersion:3,discoveredMolecules:${JSON.stringify(['water','ethanol','acetic-anhydride','acetic-acid','ethyl-acetate','oxygen','hydrogen','acetone','pyridine','methane','carbon-dioxide','carbonic-acid','hexamethylenediamine','isoamyl-acetate','methylcyclohexane'].map((id,index)=>({id,at:index+1,order:index+1})))},discoveredGroups:[],unlockedStructures:[],legacyElements:[],milestones:[]}));`});
  await send('Page.navigate',{url:`http://127.0.0.1:${port}/?reactionLabTest=1`});
  await waitFor("!!document.querySelector('#open-reaction-lab')&&!document.querySelector('#open-reaction-lab').disabled&&!!window.__reactionLabProbe",'Reaction Lab entry did not initialize');
  await evaluate("window.__labReactionEvents=[];window.addEventListener('molecule-craft:reaction-lab-product',event=>window.__labReactionEvents.push(event.detail));document.querySelector('#open-reaction-lab').click()");
  await waitFor("document.querySelector('#reaction-lab-dialog').open",'Reaction Lab dialog did not open');
  const initial=await evaluate("(()=>{const d=document.querySelector('#reaction-lab-dialog').getBoundingClientRect(),c=document.querySelector('#reaction-lab canvas').getBoundingClientRect();return{dialog:[d.width,d.height],canvas:[c.width,c.height],slots:document.querySelectorAll('[data-lab-slot]').length,modes:document.querySelectorAll('[data-lab-mode]').length,selectors:document.querySelectorAll('#reaction-lab select').length,ports:document.querySelectorAll('.reaction-lab-feed-conduits i').length,hint:document.querySelector('.reaction-lab-space p').textContent}})()");
  assert.equal(initial.slots,3);assert.equal(initial.modes,0);assert.equal(initial.selectors,0,'Native species selectors are retired');assert.equal(initial.ports,3);assert.ok(initial.hint.includes('ドラッグ')&&!initial.hint.includes('回転')&&!initial.hint.includes('視点'));assert.ok(initial.canvas[1]>300,`The Feed Rack leaves a large Chamber surface: ${JSON.stringify(initial)}`);assert.ok(initial.dialog[0]>=389&&initial.dialog[1]>=843,`390x844 scene did not fill the mobile viewport: ${JSON.stringify(initial)}`);
  const layout=await evaluate("(()=>{const rect=s=>{const r=document.querySelector(s).getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height}};return{tiles:[...document.querySelectorAll('[data-lab-slot]')].map(x=>{const r=x.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height}}),feed:rect('[data-lab-feed]'),canvas:rect('#reaction-lab canvas'),purge:rect('.reaction-lab-purge-outlet')}})()");assert.equal(layout.tiles.length,3);assert.ok(layout.tiles[0].x<layout.tiles[1].x&&layout.tiles[1].x<layout.tiles[2].x);assert.ok(layout.feed.width>=90);assert.ok(layout.canvas.height>=300);assert.ok(layout.purge.y>layout.canvas.y+layout.canvas.height-35,'Purge outlet is visible at the Chamber bottom');
  const firstBatchGeneration=(await snapshot()).batch.generation;await setDraftSlots(['water','','']);await feedCurrent({double:true});await waitFor("document.querySelector('[data-lab-status]').textContent.includes('4 個')",'Water-only population did not create four molecules');
  let productionState=await snapshot();assert.equal(productionState.batch.generation,firstBatchGeneration+1,'Rapid double FEED creates one batch generation');assert.equal(productionState.batch.phase,'ACTIVE');assert.deepEqual(productionState.batch.activeSlots,['water','','']);assert.equal(productionState.physicsMode,'stage-b');assert.equal(productionState.qA,.15);assert.equal('bonds' in productionState,false,'Production has no H-bond lifecycle state');assert.equal(productionState.instances.every(item=>item.renderedObjectCount===item.expectedRealObjectCount),true,'Stage B sites remain invisible');assert.ok(productionState.instances.every(item=>Math.abs(item.initialPositionAtSpawn?.[2]??Infinity)<1e-12),'All handoff centers begin on the common z=0 plane');const feedProbe=productionState.instances.map(({id,feedPhase,feedHandoff,originPortIndex,kinematic})=>({id,feedPhase,feedHandoff,originPortIndex,kinematic}));assert.ok(feedProbe.every(item=>item.feedPhase==='dynamic'&&item.feedHandoff&&item.originPortIndex===0&&!item.kinematic),`Each real instance hands off from slot A as a dynamic Stage B body: ${JSON.stringify(feedProbe)}`);assert.ok(new Set(productionState.instances.map(item=>item.orientation.join(','))).size>1,'Same-species feed copies receive distinct deterministic orientations');
  const thumb=await evaluate("(()=>{const tile=document.querySelector('[data-lab-slot]');return{src:tile.querySelector('img')?.getAttribute('src'),name:tile.querySelector('[data-slot-name]').textContent,formula:tile.querySelector('[data-slot-formula]').textContent,emptyImage:document.querySelectorAll('[data-lab-slot]')[1].querySelector('img'),emptyLabel:document.querySelectorAll('[data-lab-slot]')[1].getAttribute('aria-label')}})()");assert.ok(thumb.src.includes('assets/models/molecule-water.svg'));assert.equal(thumb.formula,'H2O');assert.equal(thumb.name,'水');assert.equal(thumb.emptyImage,null);assert.ok(thumb.emptyLabel.includes('未接続'));
  await evaluate("document.querySelectorAll('[data-lab-slot]')[1].click()");await waitFor("!document.querySelector('[data-lab-picker]').hidden",'Picker did not open from a feed tile');const pickerState=await evaluate("(()=>({focusSearch:document.activeElement===document.querySelector('[data-lab-search]'),waterDisabled:document.querySelector('[data-lab-picker-list] [data-species=water]').disabled,searchType:document.querySelector('[data-lab-search]').type}))()");assert.equal(pickerState.focusSearch,false,'Opening the picker does not autofocus the keyboard search input');assert.equal(pickerState.waterDisabled,true,'A species already selected in another draft slot is unavailable');assert.equal(pickerState.searchType,'search');const searchMatches=await evaluate("(()=>{const input=document.querySelector('[data-lab-search]');input.value='water';input.dispatchEvent(new Event('input',{bubbles:true}));return[...document.querySelectorAll('[data-lab-picker-list] [data-species]')].filter(option=>!option.hidden).map(option=>option.dataset.species)})()");assert.deepEqual(searchMatches,['water'],'Picker search filters the 142-species list');await evaluate("document.querySelector('[data-lab-picker-close]').dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true,cancelable:true}))");await waitFor("document.querySelector('[data-lab-picker]').hidden",'Escape did not close the species picker');assert.equal(await evaluate("document.activeElement===document.querySelectorAll('[data-lab-slot]')[1]"),true,'Escape restores focus to the feed tile');
  const productionWaters=productionState.instances.filter(item=>item.species==='water');assert.equal(productionWaters.length,4);
  const isolatedPoses=productionWaters.map((item,index)=>({id:item.id,positionAngstrom:index===0?[0,0,0]:[240+index*50,240,0],orientation:[0,0,0,1]}));await evaluate(`window.__reactionLabProbe.setGeometry(${JSON.stringify(isolatedPoses)})`);productionState=await snapshot();
  const singleWater=productionState.instances[0],singlePlan=await evaluate(`window.__reactionLabProbe.dragPlan('${singleWater.id}',0,[.42,.18,0])`),cameraBefore=productionState.camera,orientationBefore=[...singleWater.orientation];
  await drag(singlePlan,{steps:5,stepDelay:18,hold:0});productionState=await snapshot();const movedSingle=productionState.instances.find(item=>item.id===singleWater.id);
  assert.ok(Math.hypot(...movedSingle.position.map((value,index)=>value-singleWater.position[index]))>.2,'An isolated molecule follows one-finger direct drag');assert.ok(Math.hypot(...movedSingle.orientation.map((value,index)=>value-orientationBefore[index]))<1e-5,'With no nearby molecule, drag does not rotate the molecule');assert.equal(productionState.manipulationActive,false);assert.equal(productionState.simulationTimeMode,'NORMAL');assert.equal(productionState.simulationTimeScale,1);assert.ok(Math.hypot(...movedSingle.velocityAngstromPerPs)<1e-12,'Release removes linear throw momentum');
  const canvasRect=await evaluate("(()=>{const r=document.querySelector('#reaction-lab canvas').getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height}})()"),backgroundStart={x:canvasRect.x+3,y:canvasRect.y+3},backgroundEnd={x:backgroundStart.x+55,y:backgroundStart.y+40};
  await send('Input.dispatchMouseEvent',{type:'mouseMoved',x:backgroundStart.x,y:backgroundStart.y});await send('Input.dispatchMouseEvent',{type:'mousePressed',x:backgroundStart.x,y:backgroundStart.y,button:'left',buttons:1,clickCount:1});await send('Input.dispatchMouseEvent',{type:'mouseMoved',x:backgroundEnd.x,y:backgroundEnd.y,button:'left',buttons:1});await send('Input.dispatchMouseEvent',{type:'mouseReleased',x:backgroundEnd.x,y:backgroundEnd.y,button:'left',buttons:0});
  const cameraAfterBackground=(await snapshot()).camera;assert.equal(cameraAfterBackground.azimuth,cameraBefore.azimuth);assert.equal(cameraAfterBackground.elevation,cameraBefore.elevation,'Background drag leaves camera look direction fixed');
  const pinchPlan=await evaluate(`window.__reactionLabProbe.dragPlan('${singleWater.id}',0,[0,0,0])`),pinchDistanceBefore=(await snapshot()).camera.distance;
  await pointer('pointerdown',101,pinchPlan.start.x,pinchPlan.start.y);productionState=await snapshot();assert.equal(productionState.simulationTimeMode,'MANIPULATING');assert.equal(productionState.simulationTimeScale,.15,'One-finger drag activates manipulation slow-time');assert.equal(await evaluate("[...document.querySelectorAll('[data-lab-slot]')].every(tile=>tile.disabled)"),true,'Feed slot editing locks during molecule drag');assert.equal(await evaluate("document.querySelector('[data-lab-feed]').disabled"),true,'FEED locks during molecule drag');const draftDuringDrag=[...productionState.batch.draftSlots];await evaluate("document.querySelector('[data-lab-feed]').click()");assert.deepEqual((await snapshot()).batch.draftSlots,draftDuringDrag,'A drag cannot queue a batch transition');
  await pointer('pointerdown',102,pinchPlan.start.x+150,pinchPlan.start.y);productionState=await snapshot();assert.equal(productionState.manipulationActive,false);assert.equal(productionState.depthTargetId,null);assert.equal(productionState.simulationTimeScale,1,'Second pointer ends drag and restores normal time');
  await pointer('pointermove',102,pinchPlan.start.x+240,pinchPlan.start.y);await new Promise(resolve=>setTimeout(resolve,80));productionState=await snapshot();assert.ok(productionState.camera.distance<pinchDistanceBefore,'Two pointers pinch to zoom');assert.equal(productionState.camera.azimuth,cameraBefore.azimuth);assert.equal(productionState.camera.elevation,cameraBefore.elevation);
  await pointer('pointerup',101,pinchPlan.start.x,pinchPlan.start.y);await pointer('pointermove',102,pinchPlan.start.x+280,pinchPlan.start.y);await pointer('pointerup',102,pinchPlan.start.x+280,pinchPlan.start.y);productionState=await snapshot();assert.equal(productionState.pointerActive,false);assert.equal(productionState.draggedInstanceId,null,'Pinch end cannot create a ghost drag');assert.equal(await evaluate("[...document.querySelectorAll('[data-lab-slot]')].some(tile=>tile.disabled)"),false,'Feed rack unlocks after pointer gesture release');
  const highZPoses=productionWaters.map((item,index)=>({id:item.id,positionAngstrom:index===0?[0,0,5]:[240+index*50,240,0],orientation:[0,0,0,1]}));await evaluate(`window.__reactionLabProbe.setGeometry(${JSON.stringify(highZPoses)})`);productionState=await snapshot();const highZ=productionState.instances[0],highZPlan=await evaluate(`window.__reactionLabProbe.dragPlan('${highZ.id}',0,[.3,.1,0])`);
  await drag(highZPlan,{steps:4,stepDelay:18,hold:0});productionState=await snapshot();const highZAfter=productionState.instances.find(item=>item.id===highZ.id);assert.ok(Math.abs(highZAfter.position[2]-highZ.position[2])<.08,'A targetless drag preserves depth beyond the former ±2.5 clamp');
  const closeState=await snapshot(),closeIds=closeState.instances.map(item=>item.id),closeClock=closeState.simulationClockSeconds;await setDraftSlots(['water','ethanol','']);productionState=await snapshot();assert.deepEqual(productionState.instances.map(item=>item.id),closeIds,'Editing multiple draft slots leaves the active batch in the Chamber');assert.deepEqual(productionState.batch.activeSlots,['water','','']);
  await evaluate("document.querySelector('[data-lab-close]').click()");await waitFor("!document.querySelector('#reaction-lab-dialog').open",'Reaction Lab did not close');await new Promise(resolve=>setTimeout(resolve,350));const closedState=await snapshot();assert.equal(closedState.simulationClockSeconds,closeClock,'Closing Reaction Lab pauses its simulation clock');assert.deepEqual(closedState.instances.map(item=>item.id),closeIds);assert.deepEqual(closedState.batch.draftSlots,['water','ethanol','']);
  await evaluate("document.querySelector('#open-reaction-lab').click()");await waitFor("document.querySelector('#reaction-lab-dialog').open",'Reaction Lab did not reopen');productionState=await snapshot();assert.deepEqual(productionState.instances.map(item=>item.id),closeIds);assert.deepEqual(productionState.batch.draftSlots,['water','ethanol',''],'Uncommitted feed rack draft survives close and reopen');await setDraftSlots(['water','','']);
  const waterPairPoses=[{id:productionWaters[0].id,positionAngstrom:[0,0,0],orientation:[0,0,0,1]},{id:productionWaters[1].id,positionAngstrom:[8,0,0],orientation:[0,0,0,1]}];
  const waterPair=await evaluate(`(()=>{window.__reactionLabProbe.setGeometry(${JSON.stringify(waterPairPoses)});return window.__reactionLabProbe.decomposePair('${productionWaters[0].id}','${productionWaters[1].id}')})()`);assert.equal(waterPair.overlapGuardActivationCount,0);assert.ok(waterPair.pairs.every(pair=>[pair.coulombEnergyKcalMol,pair.ljEnergyKcalMol,pair.totalEnergyKcalMol,...pair.forceOnA,...pair.torqueOnA].every(Number.isFinite)));
  const sameWaterPair=await evaluate(`(()=>{window.__reactionLabProbe.advanceDeterministic(2);window.__reactionLabProbe.setGeometry(${JSON.stringify(waterPairPoses)});return window.__reactionLabProbe.decomposePair('${productionWaters[0].id}','${productionWaters[1].id}')})()`);
  assert.deepEqual(sameWaterPair.bodies,waterPair.bodies,'The same Stage B geometry has the same force and torque independent of prior history');
  const hiddenDepthPlan=await evaluate("window.__reactionLabProbe.preparePairApproach('water','water',4.2,3.4)");assert.ok(hiddenDepthPlan.initialDepthDelta>3);
  const targetHistory=[];
  await drag(hiddenDepthPlan,{steps:14,stepDelay:18,hold:300,duringHold:async()=>{for(let index=0;index<4;index++){await new Promise(resolve=>setTimeout(resolve,70));const state=await snapshot();targetHistory.push(state.depthTargetId);assert.ok(['docking','contact'].includes(state.depthDockingState),`4-water docking state: ${JSON.stringify({target:state.depthTargetId,state:state.depthDockingState,anchor:state.pointerAnchorErrorPx,positions:state.instances.filter(item=>[hiddenDepthPlan.left,hiddenDepthPlan.right].includes(item.id)).map(item=>item.position)})}`);assert.ok(state.pointerAnchorErrorPx<=3);assert.equal(state.simulationTimeScale,.15);}}});
  assert.ok(targetHistory.length&&targetHistory.every(id=>id===hiddenDepthPlan.right),`Four-water cluster retains the intended target: ${JSON.stringify(targetHistory)}`);
  const dockedState=await snapshot();assert.equal(dockedState.depthTargetId,null,'Pointer release clears the target indicator');assert.ok(Math.abs(dockedState.instances.find(item=>item.id===hiddenDepthPlan.left).position[2]-hiddenDepthPlan.before[2])>.5,'Automatic depth docking resolves hidden Z');const dockedGap=await evaluate(`window.__reactionLabProbe.currentSurfaceGap('${hiddenDepthPlan.left}','${hiddenDepthPlan.right}')`);assert.ok(dockedGap>=-.071,`Depth docking prevents deep visual atom penetration; gap=${dockedGap}, poses=${JSON.stringify(dockedState.instances.filter(item=>[hiddenDepthPlan.left,hiddenDepthPlan.right].includes(item.id)).map(item=>item.position))}`);assert.equal(dockedState.simulationTimeScale,1);
  await evaluate("window.__reactionLabProbe.placeSpeciesPair('water','water',4.8)");productionState=await snapshot();const waterTorqueBefore=productionState.instances.find(item=>item.species==='water').orientation,waterTorqueTarget=productionState.instances.filter(item=>item.species==='water')[1];await evaluate(`window.__reactionLabProbe.decomposePair('${productionState.instances[0].id}','${waterTorqueTarget.id}')`);await evaluate('window.__reactionLabProbe.advanceDeterministic(600)');productionState=await snapshot();const waterTorqueAfter=productionState.instances.find(item=>item.id===productionState.instances[0].id).orientation;assert.ok(Math.hypot(...waterTorqueAfter.map((value,index)=>value-waterTorqueBefore[index]))>1e-8,'Water-water orientation changes under natural Stage B torque');
  await setSlots(['hydrogen','','']);await waitForPopulation(['hydrogen'],4,'Small hydrogen molecules did not spawn');let hydrogenState=await snapshot();const hydrogens=hydrogenState.instances;await evaluate(`window.__reactionLabProbe.setGeometry(${JSON.stringify(hydrogens.map((item,index)=>({id:item.id,positionAngstrom:index===0?[0,0,0]:[240+index*50,240,0],orientation:[0,0,0,1]})))})`);hydrogenState=await snapshot();const hydrogen=hydrogenState.instances[0],hydrogenHit=await evaluate(`window.__reactionLabProbe.dragPlan('${hydrogen.id}',0,[0,0,0])`);
  await pointer('pointerdown',111,hydrogenHit.start.x+26,hydrogenHit.start.y);assert.equal((await snapshot()).draggedInstanceId,hydrogen.id,'A small molecule can be acquired within the 44px touch fallback');await pointer('pointercancel',111,hydrogenHit.start.x+26,hydrogenHit.start.y);hydrogenState=await snapshot();assert.equal(hydrogenState.pointerActive,false);assert.equal(hydrogenState.simulationTimeScale,1,'pointercancel safely exits slow-time');
  await setSlots(['water','acetone','']);await waitForPopulation(['water','acetone'],4,'Production water/acetone scene did not spawn');
  await evaluate("window.__reactionLabProbe.placeSpeciesPair('water','acetone',8)");productionState=await snapshot();const productionWater=productionState.instances.find(item=>item.species==='water'),productionAcetone=productionState.instances.find(item=>item.species==='acetone');
  const productionAcetonePair=await evaluate(`window.__reactionLabProbe.decomposePair('${productionWater.id}','${productionAcetone.id}')`);assert.ok(productionAcetonePair.pairs.some(pair=>Math.abs(pair.stageBAnisotropyCoulombEnergyKcalMol)>0),'Production carbonyl anisotropy contributes through fixed virtual charges');assert.equal(productionAcetonePair.overlapGuardActivationCount,0);
  await setSlots(['water','pyridine','']);await waitForPopulation(['water','pyridine'],4,'Production water/pyridine scene did not spawn');await evaluate("window.__reactionLabProbe.placeSpeciesPair('water','pyridine',4.8)");productionState=await snapshot();const productionPyridine=productionState.instances.find(item=>item.species==='pyridine'),productionPyridineWater=productionState.instances.find(item=>item.species==='water'),pyridineOrientationBefore=[...productionPyridine.orientation],pyridinePair=await evaluate(`window.__reactionLabProbe.decomposePair('${productionPyridineWater.id}','${productionPyridine.id}')`);assert.ok(pyridinePair.pairs.every(pair=>[pair.stageACoulombEnergyKcalMol,pair.stageBAnisotropyCoulombEnergyKcalMol,pair.ljEnergyKcalMol].every(Number.isFinite)));await evaluate('window.__reactionLabProbe.advanceDeterministic(600)');productionState=await snapshot();const pyridineOrientationAfter=productionState.instances.find(item=>item.id===productionPyridine.id).orientation;assert.ok(Math.hypot(...pyridineOrientationAfter.map((value,index)=>value-pyridineOrientationBefore[index]))>1e-8,'Water-pyridine orientation changes under natural Stage B torque');
  await setSlots(['water','methane','']);await waitForPopulation(['water','methane'],4,'Production water/methane scene did not spawn');await evaluate("window.__reactionLabProbe.placeSpeciesPair('water','methane',8)");productionState=await snapshot();const productionMethane=productionState.instances.find(item=>item.species==='methane'),methaneWater=productionState.instances.find(item=>item.species==='water'),methanePair=await evaluate(`window.__reactionLabProbe.decomposePair('${methaneWater.id}','${productionMethane.id}')`);assert.equal(methanePair.overlapGuardActivationCount,0);assert.ok(methanePair.pairs.every(pair=>Number.isFinite(pair.totalEnergyKcalMol)));
  await setSlots(['acetic-anhydride','water','']);
  await waitForPopulation(['acetic-anhydride','water'],4,'Hydrolysis reactant population did not initialize');
  const hydrolysisBatch=await runReaction('anhydride-hydrolysis',['acetic-acid','acetic-acid']);
  const oldHydrolysisIds=hydrolysisBatch.instances.map(item=>item.id),oldProductIds=hydrolysisBatch.instances.filter(item=>item.species==='acetic-acid').map(item=>item.id),restartGeneration=hydrolysisBatch.batch.generation;
  await evaluate("document.querySelector('[data-lab-feed]').click()");await waitFor(`(()=>{const s=window.__reactionLabProbe.snapshot();return s.batch.phase==='FLUSHING'&&s.purging.some(item=>${JSON.stringify(oldProductIds)}.includes(item.id))})()`,'Same-config FEED did not put the prior product in the purge route');
  const purgeStart=await snapshot(),oldProduct=purgeStart.purging.find(item=>oldProductIds.includes(item.id));await new Promise(resolve=>setTimeout(resolve,180));const purgeMoving=await snapshot();assert.ok(purgeMoving.purging.find(item=>item.id===oldProduct.id).position[1]<oldProduct.position[1],'Old product travels down toward the chamber purge outlet');
  await waitForPopulation(['acetic-anhydride','water'],4,'Same-config restart did not feed a fresh hydrolysis batch');const restartedHydrolysis=await snapshot();assert.equal(restartedHydrolysis.batch.generation,restartGeneration+1);assert.ok(restartedHydrolysis.instances.every(item=>!oldHydrolysisIds.includes(item.id)),'Same-config FEED replaces moved reactants and products with fresh instance IDs');
  await setSlots(['acetic-anhydride','ethanol','']);
  await waitForPopulation(['acetic-anhydride','ethanol'],4,'Alcoholysis reactant population did not initialize');
  await runReaction('anhydride-alcoholysis',['ethyl-acetate','acetic-acid']);

  for(const ids of [['oxygen','ethanol',''],['hydrogen','acetic-acid','']]){
    await setSlots(ids);await waitForPopulation(ids.slice(0,2),4,`Negative control scene did not spawn: ${ids.join('+')}`);
    await evaluate('window.__labReactionEvents=[]');
    const assistPlan=await evaluate(`window.__reactionLabProbe.preparePairApproach('${ids[0]}','${ids[1]}',4.2,3.4)`);assert.ok(assistPlan.initialDepthDelta>3);await drag(assistPlan,{steps:12,stepDelay:18,hold:100,duringHold:async()=>{const state=await snapshot();assert.equal(state.depthTargetId,assistPlan.right,`${ids.join('+')} receives chemistry-independent target assist`);assert.ok(state.pointerAnchorErrorPx<=3);}});assert.equal((await snapshot()).simulationTimeScale,1);
    const arranged=await evaluate(`window.__reactionLabProbe.placeSpeciesPair('${ids[0]}','${ids[1]}',.82)`);assert.ok(arranged.distance<1.18,`Negative control pair should be in reactive-site contact: ${JSON.stringify(arranged)}`);
    const snapshotBefore=await snapshot();
    await new Promise(resolve=>setTimeout(resolve,900));
    assert.equal(await evaluate('window.__labReactionEvents.length'),0,`${ids.join('+')} must not create a reaction`);
    assert.equal((await snapshot()).instances.length,snapshotBefore.instances.length,'Negative controls leave the scene population unchanged');
  }
  const beforeAtomic=await snapshot(),beforeAtomicIds=beforeAtomic.instances.map(item=>item.id);await setDraftSlots(['hexamethylenediamine','isoamyl-acetate','methylcyclohexane']);const draftedAtomic=await snapshot();assert.deepEqual(draftedAtomic.instances.map(item=>item.id),beforeAtomicIds,'Multiple slot edits keep the old batch visible until FEED');assert.deepEqual(draftedAtomic.batch.activeSlots,beforeAtomic.batch.activeSlots);assert.deepEqual(draftedAtomic.batch.draftSlots,['hexamethylenediamine','isoamyl-acetate','methylcyclohexane']);
  await evaluate("(()=>{window.__feedFrameSample=new Promise(resolve=>{let first=0,last=0,count=0,maxGap=0;function frame(now){if(!first)first=now;if(last)maxGap=Math.max(maxGap,now-last);last=now;count++;if(now-first>=1600)resolve({count,maxGap,elapsed:now-first});else requestAnimationFrame(frame)}requestAnimationFrame(frame)});return true})()");
  await evaluate("document.querySelector('[data-lab-feed]').click()");await waitFor("(()=>{const s=window.__reactionLabProbe.snapshot();return s.batch.phase==='FLUSHING'&&s.purging.length===4&&s.instances.length===0})()",'Atomic FEED did not terminate the old batch before loading the new one');
  const flushing=await snapshot();assert.ok(flushing.batch.transitionGeneration>beforeAtomic.batch.generation);await waitFor("(()=>{const s=window.__reactionLabProbe.snapshot();return s.batch.phase==='FEEDING'&&s.batch.feedEntriesHandedOff>0&&s.batch.feedEntriesHandedOff<s.batch.feedEntryCount})()",'Three feed ports did not overlap during FEEDING',12000);const partialFeed=await snapshot();assert.equal(partialFeed.batch.reactionEnabled,false,'Reaction detection stays off until all feed handoffs complete');assert.ok(partialFeed.instances.some(item=>item.feedPhase==='feeding'&&item.kinematic),'A real incoming molecule remains kinematic before chamber handoff');assert.ok(partialFeed.instances.some(item=>item.feedPhase==='dynamic'&&!item.kinematic),'An earlier real instance is handed to Stage B while later feed entries continue');assert.deepEqual(new Set(partialFeed.instances.map(item=>item.originPortIndex)),new Set([0,1,2]));
  await waitForPopulation(['hexamethylenediamine','isoamyl-acetate','methylcyclohexane'],6,'Three-species scene did not create six molecules');
  const feedFrameSample=await evaluate('window.__feedFrameSample');assert.ok(feedFrameSample.count>=10&&feedFrameSample.maxGap<260,`Six-large-molecule purge/feed transition caused a visible frame stall: ${JSON.stringify(feedFrameSample)}`);
  const largeScene=await snapshot();assert.equal(largeScene.instances.length,6);assert.ok(Math.max(...largeScene.instances.map(item=>item.atomCount))>=24,'Large DB molecules participate in the six-particle performance case');assert.equal(largeScene.batch.reactionEnabled,true);assert.ok(largeScene.instances.every(item=>item.feedPhase==='dynamic'&&item.feedHandoff));
  const frameSample=await evaluate(`new Promise(resolve=>{let first=0,last=0,count=0,maxGap=0;function frame(now){if(!first)first=now;if(last)maxGap=Math.max(maxGap,now-last);last=now;count++;if(now-first>=900)resolve({count,elapsed:now-first,maxGap,mean:(now-first)/Math.max(1,count-1)});else requestAnimationFrame(frame)}requestAnimationFrame(frame)})`);
  assert.ok(frameSample.count>=10,`Six-molecule interaction scene stalled: ${JSON.stringify(frameSample)}`);assert.ok(frameSample.maxGap<260,`Six-molecule interaction caused a visible frame stall: ${JSON.stringify(frameSample)}`);
  const sixRect=await evaluate("(()=>{const r=document.querySelector('#reaction-lab canvas').getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height}})()"),sixBounds=await evaluate('window.__reactionLabProbe.projectedBounds()');
  assert.ok(sixBounds.every(row=>row.bounds.left>=sixRect.x-2&&row.bounds.right<=sixRect.x+sixRect.width+2&&row.bounds.top>=sixRect.y-2&&row.bounds.bottom<=sixRect.y+sixRect.height+2),`The complete six-molecule scene fits the 390×844 canvas: ${JSON.stringify(sixBounds.map(row=>row.bounds))}`);
  const sixCameraBefore=largeScene.camera,sixDragPlan=await evaluate(`window.__reactionLabProbe.dragPlan('${largeScene.instances[0].id}',0,[.28,0,0])`);
  await drag(sixDragPlan,{steps:5,stepDelay:18,hold:100,duringHold:async()=>{const state=await snapshot();assert.ok(state.draggedInstanceId);assert.equal(state.simulationTimeScale,.15);}});let sixAfterDrag=await snapshot();assert.equal(sixAfterDrag.simulationTimeScale,1);assert.equal(sixAfterDrag.pointerActive,false);
  const sixBackground={x:sixRect.x+3,y:sixRect.y+3};await send('Input.dispatchMouseEvent',{type:'mouseMoved',x:sixBackground.x,y:sixBackground.y});await send('Input.dispatchMouseEvent',{type:'mousePressed',x:sixBackground.x,y:sixBackground.y,button:'left',buttons:1,clickCount:1});await send('Input.dispatchMouseEvent',{type:'mouseMoved',x:sixBackground.x+42,y:sixBackground.y+18,button:'left',buttons:1});await send('Input.dispatchMouseEvent',{type:'mouseReleased',x:sixBackground.x+42,y:sixBackground.y+18,button:'left',buttons:0});sixAfterDrag=await snapshot();assert.equal(sixAfterDrag.camera.azimuth,sixCameraBefore.azimuth);assert.equal(sixAfterDrag.camera.elevation,sixCameraBefore.elevation,'Six-molecule background drag cannot orbit the camera');
  const distanceBeforeWheel=sixAfterDrag.camera.distance;await evaluate("document.querySelector('#reaction-lab canvas').dispatchEvent(new WheelEvent('wheel',{deltaY:-60,bubbles:true,cancelable:true}))");assert.notEqual((await snapshot()).camera.distance,distanceBeforeWheel,'Desktop wheel input retains zoom');

  await send('Emulation.setDeviceMetricsOverride',{width:1280,height:900,deviceScaleFactor:1,mobile:false});await new Promise(resolve=>setTimeout(resolve,100));const desktopLayout=await evaluate("(()=>({dialog:(()=>{const r=document.querySelector('#reaction-lab-dialog').getBoundingClientRect();return[r.width,r.height]})(),tiles:[...document.querySelectorAll('[data-lab-slot]')].map(x=>{const r=x.getBoundingClientRect();return[r.width,r.height]}),canvas:(()=>{const r=document.querySelector('#reaction-lab canvas').getBoundingClientRect();return[r.width,r.height]})()}))()");assert.ok(desktopLayout.dialog[0]>=800&&desktopLayout.tiles.every(([width,height])=>width>150&&height>=80)&&desktopLayout.canvas[0]>700,`Desktop Feed Rack layout regressed: ${JSON.stringify(desktopLayout)}`);
  await evaluate("document.querySelectorAll('[data-lab-slot]')[1].click()");await waitFor("!document.querySelector('[data-lab-picker]').hidden",'Desktop species picker did not open');await evaluate("document.querySelector('[data-lab-picker-close]').click()");const desktopDistanceBefore=(await snapshot()).camera.distance;await evaluate("document.querySelector('#reaction-lab canvas').dispatchEvent(new WheelEvent('wheel',{deltaY:-80,bubbles:true,cancelable:true}))");assert.notEqual((await snapshot()).camera.distance,desktopDistanceBefore,'Desktop wheel input changes chamber zoom');const desktopDrag=await evaluate(`window.__reactionLabProbe.dragPlan('${largeScene.instances[0].id}',0,[.3,0,0])`);await drag(desktopDrag,{steps:4,stepDelay:20,hold:0});const desktopAfter=await snapshot();assert.ok(desktopAfter.instances.some(item=>item.id===desktopDrag.instanceId));await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await new Promise(resolve=>setTimeout(resolve,100));
  const idsBeforeEmpty=(await snapshot()).instances.map(item=>item.id);await setDraftSlots(['','','']);assert.deepEqual((await snapshot()).instances.map(item=>item.id),idsBeforeEmpty,'Draft disconnect does not clear the current batch');await evaluate("document.querySelector('[data-lab-feed]').click()");await waitFor("(()=>{const s=window.__reactionLabProbe.snapshot();return s.batch.phase==='FLUSHING'&&s.instances.length===0})()",'Empty FEED did not purge the active batch');await waitFor("(()=>{const s=window.__reactionLabProbe.snapshot();return s.batch.phase==='IDLE'&&!s.instances.length&&!s.purging.length&&!s.batch.activeSlots.some(Boolean)})()",'Empty FEED did not leave the Chamber empty',12000);

  await send('Page.navigate',{url:`http://127.0.0.1:${port}/?reactionLabTest=1&reactionLabPhysics=stage-a`});
  await waitFor("!!document.querySelector('#open-reaction-lab')&&!document.querySelector('#open-reaction-lab').disabled&&!!window.__reactionLabProbe&&window.__reactionLabProbe.physicsMode==='stage-a'",'Stateless Stage A localhost probe did not initialize');
  await evaluate("window.__stageAReactionEvents=[];window.addEventListener('molecule-craft:reaction-lab-product',event=>window.__stageAReactionEvents.push(event.detail));document.querySelector('#open-reaction-lab').click()");
  await waitFor("document.querySelector('#reaction-lab-dialog').open",'Stage A Reaction Lab dialog did not open');
  const stageInitial=await evaluate("(()=>{const d=document.querySelector('#reaction-lab-dialog').getBoundingClientRect();return{dialog:[d.width,d.height],mode:window.__reactionLabProbe.physicsMode,step:window.__reactionLabProbe.physicalPsPerGameSecond}})()");
  assert.ok(stageInitial.dialog[0]>=389&&stageInitial.dialog[1]>=843,`Stage A did not start at 390×844: ${JSON.stringify(stageInitial)}`);assert.equal(stageInitial.mode,'stage-a');assert.equal(stageInitial.step,.1);
  await setSlots(['water','','']);await waitFor("document.querySelector('[data-lab-status]').textContent.includes('4 個')",'Stage A water population did not spawn');
  let stageState=await snapshot();assert.equal(stageState.physicsMode,'stage-a');assert.equal(stageState.instances.length,4);assert.ok(stageState.instances.every(item=>Number.isFinite(item.massAmu)&&item.inertiaTensorAmuAngstrom2.length===3));assert.equal('bonds' in stageState,false,'Stage A exposes no H-bond tracker lifecycle');
  const waterFixture=stageState.instances.map((item,index)=>({id:item.id,positionAngstrom:index===0?[0,0,0]:[240+index*50,240,0],orientation:[0,0,0,1]}));await evaluate(`window.__reactionLabProbe.setGeometry(${JSON.stringify(waterFixture)})`);
  const selectedWater=(await snapshot()).instances[0],stageDragPlan=await evaluate(`window.__reactionLabProbe.dragPlan('${selectedWater.id}',0,[.55,0,0])`),stageOrientationBefore=[...selectedWater.orientation];
  await drag(stageDragPlan,{steps:5,stepDelay:18,hold:0});stageState=await snapshot();
  const movedWater=stageState.instances.find(item=>item.id===selectedWater.id);assert.ok(Math.hypot(...movedWater.position.map((value,index)=>value-selectedWater.position[index]))>.15,'Direct Stage A pointer drag moves the selected rigid body');assert.ok(Math.hypot(...movedWater.orientation.map((value,index)=>value-stageOrientationBefore[index]))<1e-5,'A single isolated molecule has no manual drag rotation');assert.equal(stageState.simulationTimeScale,1);
  await setSlots(['water','carbon-dioxide','']);await waitFor("document.querySelector('[data-lab-status]').textContent.includes('4 個')",'Stage A multi-species scene did not spawn');
  stageState=await snapshot();const water=stageState.instances.find(item=>item.species==='water'),carbonDioxide=stageState.instances.find(item=>item.species==='carbon-dioxide');
  await evaluate(`window.__reactionLabProbe.setGeometry([${JSON.stringify({id:water.id,positionAngstrom:[0,0,0]})},${JSON.stringify({id:carbonDioxide.id,positionAngstrom:[8,0,0]})}])`);
  const stagePair=await evaluate(`window.__reactionLabProbe.decomposePair('${water.id}','${carbonDioxide.id}')`);assert.ok(stagePair.pairs.length>0);assert.ok(stagePair.pairs.every(pair=>[pair.coulombEnergyKcalMol,pair.ljEnergyKcalMol,pair.totalEnergyKcalMol,...pair.forceOnA,...pair.torqueOnA].every(Number.isFinite)));assert.equal(stagePair.overlapGuardActivationCount,0,'Separated Stage A acceptance fixture must not activate the overlap guard');
  await setSlots(['acetic-anhydride','water','']);await waitFor("document.querySelector('[data-lab-status]').textContent.includes('4 個')",'Stage A reaction fixture population did not spawn');
  const stageContact=await evaluate("window.__reactionLabProbe.prepareReactionApproach('anhydride-hydrolysis',4.2)");assert.ok(stageContact.initialSiteDistance>1.18&&stageContact.initialDepthDelta>2);
  await drag(stageContact,{steps:14,stepDelay:18,hold:340});assert.equal((await snapshot()).simulationTimeScale,1);
  const stageSiteContact=await evaluate(`window.__reactionLabProbe.reactionContactDiagnostics('anhydride-hydrolysis').filter(item=>item.ids.includes('${stageContact.left}')&&item.ids.includes('${stageContact.right}')).some(item=>item.distance<item.maxDistance)`);assert.equal(stageSiteContact,true,'Stage A pointer movement plus visual depth docking creates actual 3D site contact');await evaluate(`window.__reactionLabProbe.settlePair('${stageContact.left}','${stageContact.right}')`);
  try{await waitFor("document.querySelector('[data-lab-status]').textContent.startsWith('反応完了')",'Simulation-time reaction contact did not execute in Stage A',10000);}catch(error){const diagnostic=await evaluate("window.__reactionLabProbe.reactionContactDiagnostics('anhydride-hydrolysis')");throw Error(`${error.message}; contact diagnostics=${JSON.stringify(diagnostic)}`);}
  assert.equal((await evaluate('window.__stageAReactionEvents.at(-1)?.ruleId')),'anhydride-hydrolysis','Registered reaction contact remains active alongside Stage A interactions');
  await setSlots(['hexamethylenediamine','isoamyl-acetate','methylcyclohexane']);await waitFor("document.querySelector('[data-lab-status]').textContent.includes('6 個')",'Six-large-molecule Stage A performance scene did not spawn');
  stageState=await snapshot();assert.equal(stageState.instances.length,6);assert.ok(Math.max(...stageState.instances.map(item=>item.atomCount))>=24);
  const largePoses=stageState.instances.map((item,index)=>({id:item.id,positionAngstrom:[index*25,0,0]}));await evaluate(`window.__reactionLabProbe.setGeometry(${JSON.stringify(largePoses)})`);
  const stageFrame=await evaluate(`(()=>{const started=performance.now();const state=window.__reactionLabProbe.advanceDeterministic(1);return{elapsed:performance.now()-started,state}})()`);
  assert.ok(stageFrame.elapsed<500,`Six-large-molecule Stage A force evaluation exceeded 500ms: ${stageFrame.elapsed}ms`);assert.ok(stageFrame.state.instances.every(item=>item.positionAngstrom.every(Number.isFinite)&&item.velocityAngstromPerPs.every(Number.isFinite)),'Six-body Stage A step remains finite');assert.ok(stageFrame.state.diagnostics.fixedSteps>0);assert.ok(Number.isFinite(stageFrame.state.diagnostics.lastPhysicsDurationMs));
  const stageCameraBefore=stageState.camera,stageCanvas=await evaluate("(()=>{const r=document.querySelector('#reaction-lab canvas').getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height}})()"),stageBackground={x:stageCanvas.x+3,y:stageCanvas.y+3};
  await send('Input.dispatchMouseEvent',{type:'mouseMoved',x:stageBackground.x,y:stageBackground.y});await send('Input.dispatchMouseEvent',{type:'mousePressed',x:stageBackground.x,y:stageBackground.y,button:'left',buttons:1,clickCount:1});await send('Input.dispatchMouseEvent',{type:'mouseMoved',x:stageBackground.x+35,y:stageBackground.y+18,button:'left',buttons:1});await send('Input.dispatchMouseEvent',{type:'mouseReleased',x:stageBackground.x+35,y:stageBackground.y+18,button:'left',buttons:0});
  assert.equal((await snapshot()).camera.azimuth,stageCameraBefore.azimuth,'Stage A keeps camera orientation fixed');
  await send('Page.navigate',{url:`http://127.0.0.1:${port}/?reactionLabTest=1&reactionLabPhysics=stage-b`});
  await waitFor("!!document.querySelector('#open-reaction-lab')&&!document.querySelector('#open-reaction-lab').disabled&&!!window.__reactionLabProbe&&window.__reactionLabProbe.physicsMode==='stage-b'",'Carbonyl anisotropy Stage B localhost probe did not initialize');
  await evaluate("document.querySelector('#open-reaction-lab').click()");await waitFor("document.querySelector('#reaction-lab-dialog').open",'Stage B Reaction Lab dialog did not open');
  const stageBDialog=await evaluate("(()=>{const d=document.querySelector('#reaction-lab-dialog').getBoundingClientRect();return[d.width,d.height]})()");assert.ok(stageBDialog[0]>=389&&stageBDialog[1]>=843,`Stage B changed the 390×844 layout: ${JSON.stringify(stageBDialog)}`);
  await setSlots(['water','acetone','']);await waitFor("document.querySelector('[data-lab-status]').textContent.includes('4 個')",'Stage B water/acetone scene did not spawn');
  let stageBState=await snapshot();assert.equal(stageBState.physicsMode,'stage-b');assert.ok(stageBState.qA>=0&&stageBState.qA<=.2);const acetoneInstances=stageBState.instances.filter(item=>item.species==='acetone');assert.equal(acetoneInstances.flatMap(item=>item.carbonylSites).length,acetoneInstances.length,'Each acetone carbonyl virtual charge geometry is exposed to the test probe');assert.ok(stageBState.instances.filter(item=>item.species==='water').every(item=>item.carbonylSites.length===0),'Water atoms are excluded from carbonyl correction');assert.ok(stageBState.instances.every(item=>item.renderedObjectCount===item.expectedRealObjectCount),'Virtual charge sites must not render as Three.js objects');assert.equal('bonds' in stageBState,false,'Stage B exposes no persistent H-bond tracker');
  await evaluate("window.__reactionLabProbe.placeSpeciesPair('water','acetone',8)");stageBState=await snapshot();const stageBWater=stageBState.instances.find(item=>item.species==='water'),stageBAcetone=stageBState.instances.find(item=>item.species==='acetone');
  const stageBPair=await evaluate(`window.__reactionLabProbe.decomposePair('${stageBWater.id}','${stageBAcetone.id}')`);assert.ok(stageBPair.pairs.some(pair=>Math.abs(pair.stageBAnisotropyCoulombEnergyKcalMol)>0));assert.ok(stageBPair.pairs.every(pair=>[pair.stageACoulombEnergyKcalMol,pair.stageBAnisotropyCoulombEnergyKcalMol,pair.ljEnergyKcalMol,pair.totalEnergyKcalMol,...pair.stageBAnisotropyForceOnA,...pair.stageBAnisotropyTorqueOnA].every(Number.isFinite)));assert.equal(stageBPair.overlapGuardActivationCount,0);
  const stageBPlan=await evaluate(`window.__reactionLabProbe.dragPlan('${stageBWater.id}',0,[.32,0,0])`),stageBOrientationBefore=[...stageBState.instances.find(item=>item.id===stageBWater.id).orientation];
  await drag(stageBPlan,{steps:5,stepDelay:18,hold:100});stageBState=await snapshot();assert.ok(stageBState.instances.find(item=>item.id===stageBWater.id).positionAngstrom.every(Number.isFinite),'Stage B direct drag leaves rigid-body state finite');assert.ok(stageBState.instances.find(item=>item.id===stageBWater.id).angularVelocityRadPerPs.every(Number.isFinite),'Stage B keeps finite physics-driven angular velocity on release');assert.equal(stageBState.simulationTimeScale,1);assert.ok(stageBState.instances.find(item=>item.id===stageBAcetone.id).carbonylSites[0].lpPlusWorldPositionAngstrom.every(Number.isFinite),'Stage B virtual sites follow the natural rigid-body orientation');
  await evaluate('window.__reactionLabProbe.advanceDeterministic(360)');stageBState=await snapshot();const stageBOrientationAfter=stageBState.instances.find(item=>item.id===stageBWater.id).orientation;assert.ok(Math.hypot(...stageBOrientationAfter.map((value,index)=>value-stageBOrientationBefore[index]))>1e-8,'Stage B torque can rotate a molecule without a manual rotation gesture');
  const stageBCanvas=await evaluate("(()=>{const r=document.querySelector('#reaction-lab canvas').getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height}})()"),stageBCameraBefore=stageBState.camera,stageBBackground={x:stageBCanvas.x+3,y:stageBCanvas.y+3};
  await send('Input.dispatchMouseEvent',{type:'mouseMoved',x:stageBBackground.x,y:stageBBackground.y});await send('Input.dispatchMouseEvent',{type:'mousePressed',x:stageBBackground.x,y:stageBBackground.y,button:'left',buttons:1,clickCount:1});await send('Input.dispatchMouseEvent',{type:'mouseMoved',x:stageBBackground.x+35,y:stageBBackground.y+18,button:'left',buttons:1});await send('Input.dispatchMouseEvent',{type:'mouseReleased',x:stageBBackground.x+35,y:stageBBackground.y+18,button:'left',buttons:0});stageBState=await snapshot();assert.equal(stageBState.camera.azimuth,stageBCameraBefore.azimuth);assert.equal(stageBState.camera.elevation,stageBCameraBefore.elevation,'Stage B has no manual camera orbit');
  assert.equal(browserErrors.length,0,`Browser reported errors: ${JSON.stringify(browserErrors)}`);
  console.log('Reaction Lab 390×844 browser regression passed: fixed camera, direct drag, hidden-depth docking, pinch, slow-time, Stage B torque, and registered contact.');
}finally{try{socket?.close();}catch{}try{child?.kill('SIGKILL');}catch{}server.close();}
