import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {inspectRepository} from '../scripts/check-repository-hygiene.mjs';

const result=await inspectRepository(new URL('../',import.meta.url));
assert.deepEqual(result.errors,[]);
assert.deepEqual(result.warnings,[],'Current repository should not carry ignored hygiene warnings');

async function createFixture(){
  const root=await mkdtemp(join(tmpdir(),'molecule-craft-hygiene-'));
  for(const directory of ['src','scripts','docs'])await mkdir(join(root,directory),{recursive:true});
  await writeFile(join(root,'index.html'),'<script type="module" src="./src/app.js?v=1"></script>\n');
  await writeFile(join(root,'README.md'),'# Fixture\n\n`node scripts/current.mjs`\n');
  await writeFile(join(root,'AGENTS.md'),'# Fixture rules\n');
  await writeFile(join(root,'docs/architecture.md'),'# Current code map\n');
  await writeFile(join(root,'scripts/current.mjs'),'console.log("current");\n');
  await writeFile(join(root,'precache-manifest.js'),'// Generated by scripts/build-precache.mjs; do not edit.\n');
  await writeFile(join(root,'src/app.js'),"import './live.js';\nimport('./lazy.js');\n");
  await writeFile(join(root,'src/live.js'),"export {value} from './leaf.js';\n");
  await writeFile(join(root,'src/leaf.js'),'export const value=1;\n');
  await writeFile(join(root,'src/lazy.js'),'export const lazy=true;\n');
  return root;
}

const root=await createFixture();
try{
  let check=await inspectRepository(root);
  assert.deepEqual(check.errors,[],'Static, re-export and dynamic-import production paths are reachable');
  assert.deepEqual(check.warnings,[],'Documented current tooling is owned');

  await writeFile(join(root,'src/orphan.js'),'export const stale=true;\n');
  check=await inspectRepository(root);
  assert.ok(check.errors.some(message=>message.includes('Unreachable production module(s): src/orphan.js')),'Unreachable production source must fail');
  await rm(join(root,'src/orphan.js'));

  await writeFile(join(root,'scripts/unowned.mjs'),'console.log("manual");\n');
  check=await inspectRepository(root);
  assert.ok(check.warnings.some(message=>message.includes('Unowned tooling script: scripts/unowned.mjs')),'Unexplained tooling should warn');
  await writeFile(join(root,'README.md'),'# Fixture\n\n`node scripts/current.mjs`\n`node scripts/unowned.mjs`\n');
  check=await inspectRepository(root);
  assert.ok(!check.warnings.some(message=>message.includes('scripts/unowned.mjs')),'Documented manual tooling is valid ownership');

  await mkdir(join(root,'docs/handoffs'),{recursive:true});
  await writeFile(join(root,'docs/handoffs/completed.md'),'# Completed handoff\n');
  check=await inspectRepository(root);
  assert.ok(check.errors.some(message=>message.includes('Transient handoff/progress document detected')),'Completed handoff residue must fail');

  await mkdir(join(root,'legacy'),{recursive:true});
  await writeFile(join(root,'legacy/stale.js'),'export const old=true;\n');
  check=await inspectRepository(root);
  assert.ok(check.errors.some(message=>message.includes('Historical-code directory detected')),'Historical copied code must fail');
}finally{
  await rm(root,{recursive:true,force:true});
}

console.log(`Repository hygiene passed: ${result.fileCount} files, ${result.productionModuleCount} production modules reachable, fixture failures detected.`);
