import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {mkdir,mkdtemp,readFile,rm,writeFile} from 'node:fs/promises';
import {spawn,spawnSync} from 'node:child_process';
import {extname,join,normalize,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {fileURLToPath} from 'node:url';

const root=resolve(fileURLToPath(new URL('..',import.meta.url)));
const html=await readFile(join(root,'index.html'),'utf8');
const encyclopediaFixture=html.replace(/\s*<script type="module" src="\.\/src\/(?:app|pwa)\.js[^\"]*"><\/script>/g,'');
const craftFixture=html.replace(/\s*<script type="module" src="\.\/src\/pwa\.js[^\"]*"><\/script>/g,'');
const records=JSON.parse(await readFile(join(root,'data/molecules.json'),'utf8'));
const nitromethane=records.find(record=>record.id==='nitromethane');
assert.ok(nitromethane,'nitromethane record missing');
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.webmanifest':'application/manifest+json'};
const server=createServer(async(req,res)=>{try{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(pathname==='/__resonance_encyclopedia__'){res.writeHead(200,{'content-type':mime['.html'],'cache-control':'no-store'});res.end(encyclopediaFixture);return;}if(pathname==='/__resonance_craft__'){res.writeHead(200,{'content-type':mime['.html'],'cache-control':'no-store'});res.end(craftFixture);return;}const relative=pathname==='/'?'index.html':pathname.replace(/^\/+/,''),file=normalize(join(root,relative));if(!file.startsWith(root)){res.writeHead(403).end();return;}res.writeHead(200,{'content-type':mime[extname(file)]??'application/octet-stream','cache-control':'no-store'});res.end(await readFile(file));}catch{res.writeHead(404).end('not found');}});
await new Promise(done=>server.listen(0,'127.0.0.1',done));const {port}=server.address();
let chrome='';for(const command of ['google-chrome','chromium','chromium-browser']){const found=spawnSync('which',[command],{encoding:'utf8'});if(found.status===0&&found.stdout.trim()){chrome=found.stdout.trim();break;}}
assert.ok(chrome,'Chromium is required for resonance visual validation');
const profile=await mkdtemp(join(tmpdir(),'molecule-craft-resonance-visual-')),debugPort=9231,captureDir=join(root,'test-results','resonance-visual');let child=null,socket=null;
await mkdir(captureDir,{recursive:true});
try{
  child=spawn(chrome,['--headless=new','--no-sandbox','--disable-gpu','--disable-background-networking',`--user-data-dir=${profile}`,`--remote-debugging-port=${debugPort}`,'about:blank'],{stdio:['ignore','ignore','pipe']});
  let tabs=null;for(let i=0;i<160;i++){try{const response=await fetch(`http://127.0.0.1:${debugPort}/json/list`);if(response.ok){tabs=await response.json();if(tabs.length)break;}}catch{}await new Promise(r=>setTimeout(r,100));}assert.ok(tabs?.length,'Chromium DevTools endpoint did not become ready');
  socket=new WebSocket(tabs.find(tab=>tab.type==='page')?.webSocketDebuggerUrl??tabs[0].webSocketDebuggerUrl);await new Promise((ok,fail)=>{const timer=setTimeout(()=>fail(new Error('DevTools websocket timeout')),5000);socket.addEventListener('open',()=>{clearTimeout(timer);ok();},{once:true});socket.addEventListener('error',fail,{once:true});});
  let seq=0;const pending=new Map();socket.addEventListener('message',event=>{const message=JSON.parse(event.data);if(message.id&&pending.has(message.id)){const task=pending.get(message.id);pending.delete(message.id);message.error?task.reject(new Error(message.error.message)):task.resolve(message.result);}});const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++seq;pending.set(id,{resolve,reject});socket.send(JSON.stringify({id,method,params}));});
  const evaluate=async expression=>{const response=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(response.exceptionDetails)throw new Error(response.exceptionDetails.exception?.description??response.exceptionDetails.text);return response.result?.value;};
  const waitFor=async(expression,message,{attempts=180,delay=50}={})=>{for(let i=0;i<attempts;i++){const value=await evaluate(expression);if(value)return value;await new Promise(r=>setTimeout(r,delay));}assert.fail(message);};
  const capture=async name=>{const shot=await send('Page.captureScreenshot',{format:'png',fromSurface:true});await writeFile(join(captureDir,`${name}.png`),Buffer.from(shot.data,'base64'));};
  await send('Runtime.enable');await send('Page.enable');await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});

  await send('Page.navigate',{url:`http://127.0.0.1:${port}/__resonance_encyclopedia__`});await new Promise(r=>setTimeout(r,150));
  const count=await evaluate(`(async()=>{const chemistry=await import('/src/chemistry.js');const loaded=await chemistry.loadMoleculeDatabase();if(!loaded.ok)return null;const ids=['ozone','nitromethane','nitrobenzene','2-nitrotoluene','2-4-dinitrotoluene','2-4-6-trinitrotoluene'];const save={schemaVersion:3,discoveredMolecules:ids.map((id,index)=>({id,at:index+1,order:index+1})),discoveredGroups:[],unlockedStructures:[],legacyElements:[],milestones:[]},data=new Map([['molecule-craft.collection.v1',JSON.stringify(save)]]),storage={getItem:key=>data.get(key)??null,setItem:(key,value)=>data.set(key,value),removeItem:key=>data.delete(key)};const {createCollectionUI}=await import('/src/collection-ui.js');window.__resonanceCollection=await createCollectionUI({records:chemistry.moleculeCatalog(),storage,onPlace:()=>{},canOpen:()=>true,elementAccess:()=>true,recipeState:()=>({recipes:ids,hints:[]})});return window.__resonanceCollection.state.discoveredCount;})()`);assert.equal(count,6);
  const returnToGraph=async id=>{assert.equal(await evaluate(`(()=>{const host=document.querySelector('.molecule-detail-return[data-molecule-id=${JSON.stringify(id)}]');if(!host)return false;const r=host.getBoundingClientRect(),o={bubbles:true,pointerId:77,button:0,clientX:r.left+r.width/2,clientY:r.top+r.height/2};host.dispatchEvent(new PointerEvent('pointerdown',o));host.dispatchEvent(new PointerEvent('pointerup',o));return true;})()`),true,`${id}: Detail return surface missing`);await waitFor(`document.querySelector('.graph-node.focus')?.dataset.graphId===${JSON.stringify(id)}`,`${id}: Graph focus missing after return`);await waitFor(`!document.querySelector('.encyclopedia-molecule-transition')`,`${id}: transition did not settle`);};
  const graphState=()=>evaluate(`(()=>{const node=document.querySelector('.graph-node.focus'),img=node?.querySelector('.graph-focus-thumbnail'),identity=document.querySelector('.graph-focus-identity'),dialog=document.querySelector('#collection-dialog');if(!node||!img||!identity||!dialog)return null;const nr=node.getBoundingClientRect(),ir=identity.getBoundingClientRect(),dr=dialog.getBoundingClientRect();return{id:node.dataset.graphId,imageReady:img.complete&&img.naturalWidth>0,node:[nr.left,nr.right],identity:[ir.left,ir.right,identity.scrollWidth,identity.clientWidth],dialog:[dr.left,dr.right]};})()`);
  for(const id of ['ozone','nitrobenzene','2-4-6-trinitrotoluene']){
    await waitFor(`!document.querySelector('.encyclopedia-molecule-transition')`,`${id}: prior transition still active`);
    assert.equal(await evaluate(`window.__resonanceCollection.openMolecule(${JSON.stringify(id)})`),true,`${id}: public Encyclopedia open failed`);
    await waitFor(`document.querySelector('.molecule-detail-return[data-molecule-id=${JSON.stringify(id)}]')?.dataset.viewerReady==='true'`,`${id}: Detail viewer did not become ready`);
    const detail=await evaluate(`(()=>{const host=document.querySelector('.molecule-detail-return[data-molecule-id=${JSON.stringify(id)}]'),canvas=host?.querySelector('canvas');if(!host||!canvas)return null;const c=canvas.getBoundingClientRect();return{canvas:[c.width,c.height],text:document.querySelector('#collection-detail')?.innerText??''};})()`);assert.ok(detail?.canvas[0]>100&&detail.canvas[1]>100,`${id}: Detail canvas not visible`);assert.ok(detail.text.includes(id==='ozone'?'オゾン':id==='nitrobenzene'?'ニトロベンゼン':'2,4,6-トリニトロトルエン'),`${id}: Detail identity missing`);await capture(`mobile-detail-${id}`);
    await returnToGraph(id);const state=await graphState();assert.equal(state?.id,id);assert.equal(state.imageReady,true,`${id}: Graph thumbnail not loaded`);assert.ok(state.node[0]>=state.dialog[0]-1&&state.node[1]<=state.dialog[1]+1,`${id}: Graph node clipped`);assert.ok(state.identity[0]>=state.dialog[0]-1&&state.identity[1]<=state.dialog[1]+1,`${id}: external label clipped`);assert.ok(state.identity[2]<=state.identity[3]+2,`${id}: external label horizontally overflows`);await capture(`mobile-graph-${id}`);
  }

  const positions=[[-1.15,0,0],[0.05,0,0],[.9,.78,0],[.9,-.78,0],[-1.7,.78,.15],[-1.75,-.7,.2],[-1.65,0,-.8]];assert.equal(nitromethane.atoms.length,positions.length);
  const workspace={schemaVersion:2,atoms:nitromethane.atoms.map((element,index)=>({element,position:positions[index]})),bonds:nitromethane.bonds,selected:null,focus:1,pivot:null,targetMoleculeId:'nitromethane',camera:{position:[0,0,7],target:[-.25,0,0],up:[0,1,0]}};
  await evaluate(`localStorage.clear();localStorage.setItem('molecule-craft.workspace.v1',${JSON.stringify(JSON.stringify(workspace))});true`);await send('Page.navigate',{url:`http://127.0.0.1:${port}/__resonance_craft__`});
  const craft=await waitFor(`(()=>{const canvas=[...document.querySelectorAll('canvas')].find(item=>{const r=item.getBoundingClientRect();return r.width>250&&r.height>250;});if(!canvas)return null;const r=canvas.getBoundingClientRect();return{width:r.width,height:r.height};})()`,'CRAFT WebGL canvas did not become ready',{attempts:220});assert.ok(craft.width>250&&craft.height>250);await new Promise(r=>setTimeout(r,900));await capture('mobile-craft-nitromethane');
  console.log('Resonance visual browser passed: mobile Graph/Detail for ozone, nitrobenzene and TNT plus real CRAFT nitromethane canvas.');
}finally{try{socket?.close();}catch{}try{child?.kill('SIGKILL');}catch{}await new Promise(r=>setTimeout(r,120));server.close();await rm(profile,{recursive:true,force:true});}
