import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {mkdir,mkdtemp,readFile,rm,writeFile} from 'node:fs/promises';
import {spawn,spawnSync} from 'node:child_process';
import {extname,join,normalize,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {fileURLToPath} from 'node:url';

const root=resolve(fileURLToPath(new URL('..',import.meta.url)));
const html=await readFile(join(root,'index.html'),'utf8');
const craftHtml=html.replace(/\s*<script type="module" src="\.\/src\/pwa\.js[^\"]*"><\/script>/g,'');
const seedHtml='<!doctype html><meta charset="utf-8"><title>resonance seed</title>';
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.webmanifest':'application/manifest+json'};
const debugSource=`\nglobalThis.__resonanceCraftDebug={\n  snapshot:()=>({\n    atoms:molecule.atoms.map(atom=>({id:atom.id,element:atom.element})),\n    bonds:molecule.bonds.map(bond=>({a:bond.a,b:bond.b,order:bond.order})),\n    recognized:molecule.recognizedMolecule()?.id??null,\n    validation:molecule.validation().level,\n    locked:interactionLocked(),\n    settling:!!relaxation||!!bondTransition||!!frameTransition,\n    shared:sharedVisuals.length,\n    chargeIds:[...atomVisuals.entries()].filter(([,visual])=>!!visual.charge).map(([id])=>id),\n    states:Object.fromEntries(molecule.atoms.map(atom=>[atom.id,atomBondState(molecule,atom.id)]))\n  }),\n  electrons:()=>electronVisuals.filter(item=>item.visible.visible).map(item=>{const screen=worldToScreen(item.visible.position);return{atomId:item.atomId,index:item.index,kind:item.kind,partnerId:item.partnerId??null,x:screen.x,y:screen.y,depth:screen.depth};})\n};\n`;
const server=createServer(async(req,res)=>{try{
  const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);
  if(pathname==='/__resonance_seed__'){res.writeHead(200,{'content-type':mime['.html'],'cache-control':'no-store'});res.end(seedHtml);return;}
  if(pathname==='/__resonance_craft__'){res.writeHead(200,{'content-type':mime['.html'],'cache-control':'no-store'});res.end(craftHtml);return;}
  const relative=pathname==='/'?'index.html':pathname.replace(/^\/+/,''),file=normalize(join(root,relative));if(!file.startsWith(root)){res.writeHead(403).end();return;}
  let body=await readFile(file);if(relative==='src/app.js'){let source=body.toString('utf8');const marker='function stateFor(id){';assert.equal(source.split(marker).length-1,1,'CRAFT debug injection marker changed');source=source.replace(marker,debugSource+marker);body=Buffer.from(source);}
  res.writeHead(200,{'content-type':mime[extname(file)]??'application/octet-stream','cache-control':'no-store'});res.end(body);
}catch(error){res.writeHead(500).end(String(error?.stack??error));}});
await new Promise(done=>server.listen(0,'127.0.0.1',done));const {port}=server.address(),origin=`http://127.0.0.1:${port}`;
let chrome='';for(const command of ['google-chrome','chromium','chromium-browser']){const found=spawnSync('which',[command],{encoding:'utf8'});if(found.status===0&&found.stdout.trim()){chrome=found.stdout.trim();break;}}assert.ok(chrome,'Chromium is required for resonance CRAFT interaction regression');
const profile=await mkdtemp(join(tmpdir(),'molecule-craft-resonance-craft-')),debugPort=9233,captureDir=join(root,'test-results','resonance-craft-interaction');let child=null,socket=null;await mkdir(captureDir,{recursive:true});
try{
  child=spawn(chrome,['--headless=new','--no-sandbox','--disable-gpu','--disable-background-networking',`--user-data-dir=${profile}`,`--remote-debugging-port=${debugPort}`,'about:blank'],{stdio:['ignore','ignore','pipe']});
  let stderr='';child.stderr.setEncoding('utf8');child.stderr.on('data',chunk=>stderr+=chunk);let tabs=null;for(let attempt=0;attempt<180;attempt++){try{const response=await fetch(`http://127.0.0.1:${debugPort}/json/list`);if(response.ok){tabs=await response.json();if(tabs.length)break;}}catch{}await new Promise(r=>setTimeout(r,100));}assert.ok(tabs?.length,`Chromium DevTools endpoint did not become ready: ${stderr.slice(-1000)}`);
  socket=new WebSocket(tabs.find(tab=>tab.type==='page')?.webSocketDebuggerUrl??tabs[0].webSocketDebuggerUrl);await new Promise((ok,fail)=>{const timer=setTimeout(()=>fail(new Error('DevTools websocket timeout')),5000);socket.addEventListener('open',()=>{clearTimeout(timer);ok();},{once:true});socket.addEventListener('error',fail,{once:true});});
  let seq=0;const pending=new Map(),exceptions=[];socket.addEventListener('message',event=>{const message=JSON.parse(event.data);if(message.id&&pending.has(message.id)){const task=pending.get(message.id);pending.delete(message.id);message.error?task.reject(new Error(message.error.message)):task.resolve(message.result);return;}if(message.method==='Runtime.exceptionThrown')exceptions.push(message.params.exceptionDetails);});
  const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++seq;pending.set(id,{resolve,reject});socket.send(JSON.stringify({id,method,params}));});
  const evaluate=async expression=>{const response=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(response.exceptionDetails)throw new Error(response.exceptionDetails.exception?.description??response.exceptionDetails.text);return response.result?.value;};
  const waitFor=async(expression,message,{attempts=160,delay=50}={})=>{for(let i=0;i<attempts;i++){try{const value=await evaluate(expression);if(value)return value;}catch{}await new Promise(r=>setTimeout(r,delay));}assert.fail(message);};
  const snapshot=()=>evaluate(`globalThis.__resonanceCraftDebug?.snapshot()`),electrons=()=>evaluate(`globalThis.__resonanceCraftDebug?.electrons()??[]`);
  const capture=async name=>{const shot=await send('Page.captureScreenshot',{format:'png',fromSurface:true});await writeFile(join(captureDir,`${name}.png`),Buffer.from(shot.data,'base64'));};
  await send('Runtime.enable');await send('Page.enable');await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});

  const openSeed=async()=>{await send('Page.navigate',{url:`${origin}/__resonance_seed__`});await waitFor(`location.pathname==='/__resonance_seed__'`,'Seed page did not load');};
  await openSeed();
  const seeded=await evaluate(`(async()=>{localStorage.clear();const {createResources}=await import('/src/veil/resources.js');const records=await fetch('/data/molecules.json').then(r=>r.json());const r=createResources({storage:localStorage});r.setCatalog(records);r.state.progress.choCompleted=true;r.state.progress.regions=['veil','carbon','oxygen','frontier','nitrogen'];r.state.progress.checkpoint='nitrogen';r.state.progress.foundElements=['H','C','O','N'];Object.assign(r.state.elements,{H:500,C:500,O:500,N:500});return r.save();})()`);assert.equal(seeded,true,'Resource seed failed');

  const openEmptyCraft=async()=>{await openSeed();await evaluate(`localStorage.removeItem('molecule-craft.workspace.v1');true`);await send('Page.navigate',{url:`${origin}/__resonance_craft__`});await waitFor(`!!globalThis.__resonanceCraftDebug`,'CRAFT debug surface did not initialize',{attempts:220});await waitFor(`document.querySelector('#viewer canvas')?.getBoundingClientRect().width>250`,'CRAFT canvas did not become visible',{attempts:220});await waitFor(`globalThis.__resonanceCraftDebug.snapshot().atoms.length===0`,'CRAFT workspace was not empty');await waitFor(`globalThis.__resonanceCraftDebug.snapshot().locked===false`,'CRAFT did not become interactive after empty-workspace load',{attempts:220});exceptions.length=0;};
  const addAtom=async symbol=>{const before=(await snapshot()).atoms.length;const button=await evaluate(`(()=>{const b=document.querySelector('#element-palette [data-element=${JSON.stringify(symbol)}]');if(!b)return null;return{hidden:b.hidden,disabled:b.disabled};})()`);assert.ok(button,`${symbol}: palette button missing`);assert.equal(button.disabled,false,`${symbol}: palette button disabled`);assert.equal(await evaluate(`document.querySelector('#element-palette [data-element=${JSON.stringify(symbol)}]').click();true`),true);const next=await waitFor(`(()=>{const s=globalThis.__resonanceCraftDebug.snapshot();return s.atoms.length===${before+1}?s.atoms[s.atoms.length-1]:null;})()`,`${symbol}: palette click did not add atom`);await waitFor(`globalThis.__resonanceCraftDebug.snapshot().locked===false`,`${symbol}: CRAFT did not unlock after atom placement`,{attempts:220});return next.id;};
  const bondOrder=async(a,b)=>{const s=await snapshot(),bond=s.bonds.find(item=>(item.a===a&&item.b===b)||(item.a===b&&item.b===a));return bond?.order??0;};
  const findElectron=async(atomId,{kind='electron',partnerId=null}={})=>waitFor(`(()=>globalThis.__resonanceCraftDebug.electrons().find(item=>item.atomId===${atomId}&&item.kind===${JSON.stringify(kind)}${partnerId==null?'':`&&item.partnerId===${partnerId}`}&&item.depth>=-1&&item.depth<=1)||null)()`,`${atomId}: ${kind} handle missing`);
  const dragElectron=async(source,target,expectedOrder)=>{await send('Input.dispatchMouseEvent',{type:'mouseMoved',x:source.x,y:source.y,button:'none'});await send('Input.dispatchMouseEvent',{type:'mousePressed',x:source.x,y:source.y,button:'left',buttons:1,clickCount:1});await send('Input.dispatchMouseEvent',{type:'mouseMoved',x:(source.x+target.x)/2,y:(source.y+target.y)/2,button:'left',buttons:1});await send('Input.dispatchMouseEvent',{type:'mouseMoved',x:target.x,y:target.y,button:'left',buttons:1});await send('Input.dispatchMouseEvent',{type:'mouseReleased',x:target.x,y:target.y,button:'left',buttons:0,clickCount:1});await waitFor(`(()=>{const s=globalThis.__resonanceCraftDebug.snapshot(),b=s.bonds.find(item=>(item.a===${source.atomId}&&item.b===${target.atomId})||(item.a===${target.atomId}&&item.b===${source.atomId}));return b?.order===${expectedOrder};})()`,`${source.atomId}-${target.atomId}: pointer drag did not reach order ${expectedOrder}`,{attempts:220});if(expectedOrder===2)await waitFor(`globalThis.__resonanceCraftDebug.snapshot().settling===false`,`${source.atomId}-${target.atomId}: resonance settlement did not finish`,{attempts:220});else await waitFor(`globalThis.__resonanceCraftDebug.snapshot().locked===false`,`${source.atomId}-${target.atomId}: CRAFT did not unlock after bond formation`,{attempts:220});};
  const connectSingle=async(a,b)=>{assert.equal(await bondOrder(a,b),0,`${a}-${b}: expected no initial bond`);const source=await findElectron(a),target=await findElectron(b);await dragElectron(source,target,1);};
  const completeResonance=async(center,end)=>{const precursor=await snapshot(),sites=precursor.states[center]?.sites?.filter(site=>site?.kind==='resonance')??[];assert.ok(sites.some(site=>site.partnerId===end),`${center}: resonance completion affordance for ${end} missing`);const source=await findElectron(end),target=await findElectron(center,{kind:'resonance',partnerId:end});await dragElectron(source,target,2);};

  // Nitromethane: empty workspace -> palette atoms -> all ordinary single bonds -> resonance completion pointer drag.
  await openEmptyCraft();
  const c=await addAtom('C'),h1=await addAtom('H'),h2=await addAtom('H'),h3=await addAtom('H'),n=await addAtom('N'),no1=await addAtom('O'),no2=await addAtom('O');
  await connectSingle(c,h1);await connectSingle(c,h2);await connectSingle(c,h3);await connectSingle(c,n);await connectSingle(n,no1);await connectSingle(n,no2);
  let pre=await snapshot();assert.equal(pre.recognized,null,'Neutral all-single nitromethane precursor must not already recognize');assert.equal(pre.states[n].sites.filter(site=>site?.kind==='resonance').length,2,'Nitro precursor must expose two resonance handles');await capture('nitromethane-precursor');
  await completeResonance(n,no1);const nitro=await waitFor(`(()=>{const s=globalThis.__resonanceCraftDebug.snapshot();return s.recognized==='nitromethane'&&s.shared>0&&s.chargeIds.length===2?s:null;})()`,'Nitromethane did not hand off to existing shared resonance/formal-charge visual',{attempts:220});assert.equal(nitro.validation,'ok');assert.equal(nitro.states[n].sites.some(site=>site?.kind==='resonance'),false,'Completion affordance must disappear after nitro completion');await capture('nitromethane-complete');

  // Ozone: reload to a genuinely empty workspace, then use the same player-facing pointer path.
  await openEmptyCraft();
  const o1=await addAtom('O'),oc=await addAtom('O'),o2=await addAtom('O');await connectSingle(o1,oc);await connectSingle(oc,o2);
  pre=await snapshot();assert.equal(pre.recognized,null,'All-single ozone precursor must not already recognize');assert.equal(pre.states[oc].sites.filter(site=>site?.kind==='resonance').length,2,'Ozone precursor must expose two resonance handles');await capture('ozone-precursor');
  await completeResonance(oc,o2);const ozone=await waitFor(`(()=>{const s=globalThis.__resonanceCraftDebug.snapshot();return s.recognized==='ozone'&&s.shared>0&&s.chargeIds.length===2?s:null;})()`,'Ozone did not hand off to existing shared resonance/formal-charge visual',{attempts:220});assert.equal(ozone.validation,'ok');assert.equal(ozone.states[oc].sites.some(site=>site?.kind==='resonance'),false,'Completion affordance must disappear after ozone completion');await capture('ozone-complete');
  assert.equal(exceptions.length,0,`CRAFT resonance browser flow threw: ${JSON.stringify(exceptions)}`);
  console.log('Resonance CRAFT interaction Chromium regression passed: empty-workspace nitromethane and ozone completed through real palette + canvas pointer interactions, then handed off to shared resonance/formal-charge visuals.');
}finally{try{socket?.close();}catch{}try{child?.kill('SIGKILL');}catch{}await new Promise(r=>setTimeout(r,120));server.close();await rm(profile,{recursive:true,force:true});}
