import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {spawnSync,spawn} from 'node:child_process';
import {readFile,mkdtemp,rm} from 'node:fs/promises';
import {extname,join,normalize,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {fileURLToPath} from 'node:url';

const root=resolve(fileURLToPath(new URL('..',import.meta.url))),types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.json':'application/json','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.webmanifest':'application/manifest+json'};
const server=createServer(async(req,res)=>{try{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname),relative=pathname==='/'?'index.html':pathname.replace(/^\/+/,''),file=normalize(join(root,relative));if(!file.startsWith(root)){res.writeHead(403).end();return;}let body=await readFile(file);if(relative==='src/veil/ui.js'){const source=body.toString('utf8').replace('function frame(now){',"function frame(now){globalThis.__returnFlowProbe=()=>({run,returnState,active});globalThis.__returnFlowResources=resources;");body=Buffer.from(source);}res.writeHead(200,{'content-type':types[extname(file)]??'application/octet-stream','cache-control':'no-store'});res.end(body);}catch{res.writeHead(404).end('not found');}});
await new Promise(done=>server.listen(0,'127.0.0.1',done));const {port}=server.address(),origin=`http://127.0.0.1:${port}`;
let chrome='';for(const command of ['google-chrome','chromium','chromium-browser']){const found=spawnSync('which',[command],{encoding:'utf8'});if(found.status===0&&found.stdout.trim()){chrome=found.stdout.trim();break;}}assert.ok(chrome,'Chromium is required for Safe Extraction browser integration');
const profile=await mkdtemp(join(tmpdir(),'molecule-craft-safe-extraction-')),debugPort=9270,pause=ms=>new Promise(resolvePause=>setTimeout(resolvePause,ms));let child=null,socket=null;
try{
  child=spawn(chrome,['--headless=new','--no-sandbox','--disable-gpu','--disable-background-networking',`--user-data-dir=${profile}`,`--remote-debugging-port=${debugPort}`,'about:blank'],{stdio:['ignore','ignore','pipe']});let tabs=null,stderr='';child.stderr.setEncoding('utf8');child.stderr.on('data',chunk=>stderr+=chunk);
  for(let attempt=0;attempt<160;attempt++){try{const response=await fetch(`http://127.0.0.1:${debugPort}/json/list`);if(response.ok){tabs=await response.json();if(tabs.length)break;}}catch{}await pause(100);}assert.ok(tabs?.length,stderr.slice(-1000));
  socket=new WebSocket(tabs.find(tab=>tab.type==='page')?.webSocketDebuggerUrl??tabs[0].webSocketDebuggerUrl);await new Promise((ok,fail)=>{const timer=setTimeout(()=>fail(new Error('DevTools websocket timeout')),5000);socket.addEventListener('open',()=>{clearTimeout(timer);ok();},{once:true});socket.addEventListener('error',fail,{once:true});});
  let sequence=0;const pending=new Map(),exceptions=[];socket.addEventListener('message',event=>{const message=JSON.parse(event.data);if(message.id&&pending.has(message.id)){const task=pending.get(message.id);pending.delete(message.id);message.error?task.reject(new Error(message.error.message)):task.resolve(message.result);return;}if(message.method==='Runtime.exceptionThrown')exceptions.push(message.params.exceptionDetails);});
  const send=(method,params={})=>new Promise((resolveSend,reject)=>{const id=++sequence;pending.set(id,{resolve:resolveSend,reject});socket.send(JSON.stringify({id,method,params}));});const evaluate=async expression=>{const response=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(response.exceptionDetails)throw new Error(response.exceptionDetails.exception?.description??response.exceptionDetails.text);return response.result?.value;};const waitFor=async(expression,message,attempts=120)=>{for(let attempt=0;attempt<attempts;attempt++){try{if(await evaluate(expression))return true;}catch{}await pause(50);}throw new Error(message);};
  await send('Runtime.enable');await send('Page.enable');await send('Emulation.setDeviceMetricsOverride',{width:360,height:780,deviceScaleFactor:1,mobile:true});await send('Page.navigate',{url:origin+'/'});
  await waitFor(`!!document.querySelector('#collector-launch-handle')&&!document.querySelector('#open-supply')?.disabled`,'LOADOUT did not initialize');
  async function launchVeil(){await evaluate(`(()=>{document.querySelector('#open-supply').click();document.querySelector('#collector-launch-handle').dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}));return true;})()`);await waitFor(`document.querySelector('#expedition-destinations')?.getAttribute('aria-hidden')==='false'&&!!document.querySelector('#expedition-destinations [data-region="veil"]')`,'Veil destination selector did not open');await evaluate(`document.querySelector('#expedition-destinations [data-region="veil"]').click()`);await waitFor(`document.querySelector('#veil-view')?.hidden===false&&!!globalThis.__returnFlowProbe?.().run`,'FIELD did not launch');}
  await launchVeil();
  await evaluate(`(()=>{const r=globalThis.__returnFlowResources;globalThis.__returnFlowSettlements=0;const settle=r.settleExpedition.bind(r);r.settleExpedition=(...args)=>{globalThis.__returnFlowSettlements++;return settle(...args)};})()`);
  assert.equal(await evaluate(`document.querySelector('#veil-return').disabled`),true,'Insight-less sortie cannot return at its spawn');
  await evaluate(`(()=>{const run=globalThis.__returnFlowProbe().run,site=run.map.safeExtractionSite;Object.assign(run.player,{x:site.x,y:site.y,vx:0,vy:0,boost:0,combustion:false});run.driveHeld=false;})()`);
  await waitFor(`document.querySelector('#veil-return')?.dataset.returnState==='site-ready'`,'Safe Extraction Site did not enable its explicit return control');
  assert.equal(await evaluate(`document.querySelector('#veil-view').hidden`),false,'Arriving at the site does not extract automatically');
  await evaluate(`(()=>{const run=globalThis.__returnFlowProbe().run,p=run.player;run.elementDust={H:12,C:4,O:2};run.predators=true;run.map.dust.push({id:run.map.dust.length,x:p.x,y:p.y,angle:0,element:'H',kind:'normal',value:1,ready:0});run.eaters=[{id:77,x:p.x+65,y:p.y,angle:Math.PI,speed:178,targetSpeed:178,vx:0,vy:0,phase:.2,lead:0,flank:0,trail:[]}];globalThis.__returnFlowBaseline={time:run.time,x:p.x,y:p.y,eaterX:run.eaters[0].x};})()`);
  const siteButton=await evaluate(`(()=>{const b=document.querySelector('#veil-return'),r=b.getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2,width:r.width,height:r.height};})()`);assert.ok(siteButton.width>=44&&siteButton.height>=44,'Safe Site return control has a mobile touch target');
  await send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:siteButton.x,y:siteButton.y,radiusX:3,radiusY:3,force:1,id:1}]});await send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  await waitFor(`globalThis.__returnFlowProbe()?.returnState?.phase==='normal-extraction-pending'`,'Tapping the Safe Site control did not start extraction');
  assert.equal(await evaluate(`globalThis.__returnFlowProbe().returnState.phase`),'normal-extraction-pending');
  const extractionOrigin=await evaluate(`(()=>{const {run}=globalThis.__returnFlowProbe();return{x:run.player.x,y:run.player.y,radius:run.map.safeExtractionSite.radius,site:{x:run.map.safeExtractionSite.x,y:run.map.safeExtractionSite.y}};})()`);assert.ok(Math.hypot(extractionOrigin.x-extractionOrigin.site.x,extractionOrigin.y-extractionOrigin.site.y)<=extractionOrigin.radius,'Normal extraction begins from inside the authored Safe Site');
  await pause(230);
  const pendingSite=await evaluate(`(()=>{const {run,returnState}=globalThis.__returnFlowProbe(),b=globalThis.__returnFlowBaseline;return{phase:returnState.phase,disabled:document.querySelector('#veil-return').disabled,x:run.player.x,y:run.player.y,eaterX:run.eaters[0].x,cargo:{...run.elementDust},pickup:run.map.dust.at(-1).ready,time:run.time,settlements:globalThis.__returnFlowSettlements,captured:run.captured};})()`);
  assert.equal(pendingSite.phase,'normal-extraction-pending');assert.equal(pendingSite.disabled,true);assert.deepEqual({x:pendingSite.x,y:pendingSite.y},{x:extractionOrigin.x,y:extractionOrigin.y},'Ship movement stops at the extraction origin');assert.notEqual(pendingSite.eaterX,await evaluate('globalThis.__returnFlowBaseline.eaterX'),'Existing Dust Eaters keep moving during normal extraction');assert.deepEqual(pendingSite.cargo,{H:12,C:4,O:2});assert.equal(pendingSite.pickup,0);assert.ok(pendingSite.time>await evaluate('globalThis.__returnFlowBaseline.time'));assert.equal(pendingSite.settlements,0);assert.equal(pendingSite.captured,false);
  await waitFor(`document.body.dataset.mode==='craft'&&document.querySelector('#veil-view')?.hidden===true`,'Safe Site extraction did not return to BASE');
  const afterSite=await evaluate(`(()=>({settlements:globalThis.__returnFlowSettlements,hydrogen:globalThis.__returnFlowResources.state.elements.H}))()`);assert.equal(afterSite.settlements,1);assert.equal(afterSite.hydrogen,12,'Normal extraction settles cargo without loss');

  await launchVeil();await evaluate(`(()=>{globalThis.__returnFlowProbe().run.carriedInsights=['ethane'];})()`);
  await waitFor(`document.querySelector('.veil-normal-insight')&&document.querySelector('#veil-return')?.dataset.returnState==='insight-ready'`,'Carried Insight did not enable extraction away from the site');
  const bulb=await evaluate(`(()=>{const b=document.querySelector('.veil-normal-insight'),r=b.getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2,button:b.tagName,disabled:b.disabled,width:r.width,height:r.height};})()`);
  assert.equal(bulb.button,'BUTTON');assert.equal(bulb.disabled,false);assert.ok(bulb.width>=32&&bulb.height>=32,'Insight touch affordance has a mobile-sized target');
  await send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:bulb.x,y:bulb.y,radiusX:2,radiusY:2,force:1,id:1}]});await send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  await waitFor(`globalThis.__returnFlowProbe()?.returnState?.phase==='normal-extraction-pending'`,'Touching the ship Insight bulb did not start extraction');
  assert.equal(await evaluate(`document.querySelector('#veil-return').disabled`),true,'Pending extraction blocks another return input');
  await send('Page.reload',{ignoreCache:true});await waitFor(`!!document.querySelector('#collector-launch-handle')&&!document.querySelector('#open-supply')?.disabled`,'App did not recover after a pending normal extraction reload');
  const afterReload=await evaluate(`(async()=>{const {createResources}=await import('/src/veil/resources.js');const r=createResources({storage:localStorage});return{hydrogen:r.state.elements.H,active:!!document.querySelector('#veil-view')&&!document.querySelector('#veil-view').hidden};})()`);
  assert.equal(afterReload.hydrogen,12,'Reload during pending extraction does not settle transient cargo twice');assert.equal(afterReload.active,false);
  await launchVeil();assert.equal(await evaluate(`globalThis.__returnFlowProbe().run.carriedInsights.includes('ethane')`),false,'Previous run Insight does not enter the next sortie');assert.equal(await evaluate(`document.querySelector('#veil-return').disabled`),true,'Fresh sortie starts locked outside the site');
  assert.equal(exceptions.length,0,`Safe Extraction mobile UI must not throw: ${JSON.stringify(exceptions)}`);
}finally{try{socket?.close();}catch{}try{child?.kill('SIGKILL');}catch{}await pause(100);server.close();await rm(profile,{recursive:true,force:true});}
console.log('Safe Extraction mobile browser flow passed: locked spawn, explicit authored site, short pending phase, one lossless settlement, live Eater, disabled repeat input, Insight-bulb touch anywhere and reload isolation.');
