import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {mkdtemp,rm} from 'node:fs/promises';
import {spawn,spawnSync} from 'node:child_process';
import {extname,join,normalize,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {fileURLToPath} from 'node:url';

const root=resolve(fileURLToPath(new URL('..',import.meta.url))),types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.json':'application/json','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.webmanifest':'application/manifest+json'};
const server=createServer(async(req,res)=>{try{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname),relative=pathname==='/'?'index.html':pathname.replace(/^\/+/,''),file=normalize(join(root,relative));if(!file.startsWith(root)){res.writeHead(403).end();return;}res.writeHead(200,{'content-type':types[extname(file)]??'application/octet-stream','cache-control':'no-store'});res.end(await (await import('node:fs/promises')).readFile(file));}catch{res.writeHead(404).end('not found');}});
await new Promise(done=>server.listen(0,'127.0.0.1',done));const {port}=server.address(),origin=`http://127.0.0.1:${port}`;
let chrome='';for(const command of ['google-chrome','chromium','chromium-browser']){const found=spawnSync('which',[command],{encoding:'utf8'});if(found.status===0&&found.stdout.trim()){chrome=found.stdout.trim();break;}}assert.ok(chrome,'Chromium is required for SHOCK utility mobile validation');
const profile=await mkdtemp(join(tmpdir(),'molecule-craft-shock-utility-')),debugPort=9274,pause=ms=>new Promise(resolvePause=>setTimeout(resolvePause,ms));let child=null,socket=null;
try{
  child=spawn(chrome,['--headless=new','--no-sandbox','--disable-gpu','--disable-background-networking',`--user-data-dir=${profile}`,`--remote-debugging-port=${debugPort}`,'about:blank'],{stdio:['ignore','ignore','pipe']});let tabs=null,stderr='';child.stderr.setEncoding('utf8');child.stderr.on('data',chunk=>stderr+=chunk);
  for(let attempt=0;attempt<160;attempt++){try{const response=await fetch(`http://127.0.0.1:${debugPort}/json/list`);if(response.ok){tabs=await response.json();if(tabs.length)break;}}catch{}await pause(100);}assert.ok(tabs?.length,stderr.slice(-1000));
  socket=new WebSocket(tabs.find(tab=>tab.type==='page')?.webSocketDebuggerUrl??tabs[0].webSocketDebuggerUrl);await new Promise((ok,fail)=>{const timer=setTimeout(()=>fail(new Error('DevTools websocket timeout')),5000);socket.addEventListener('open',()=>{clearTimeout(timer);ok();},{once:true});socket.addEventListener('error',fail,{once:true});});
  let sequence=0;const pending=new Map(),exceptions=[];socket.addEventListener('message',event=>{const message=JSON.parse(event.data);if(message.id&&pending.has(message.id)){const task=pending.get(message.id);pending.delete(message.id);message.error?task.reject(new Error(message.error.message)):task.resolve(message.result);return;}if(message.method==='Runtime.exceptionThrown')exceptions.push(message.params.exceptionDetails);});
  const send=(method,params={})=>new Promise((resolveSend,reject)=>{const id=++sequence;pending.set(id,{resolve:resolveSend,reject});socket.send(JSON.stringify({id,method,params}));});
  const evaluate=async expression=>{const response=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(response.exceptionDetails)throw new Error(response.exceptionDetails.exception?.description??response.exceptionDetails.text);return response.result?.value;};
  await send('Runtime.enable');await send('Page.enable');await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await send('Page.navigate',{url:origin+'/'});await pause(450);
  const result=await evaluate(`(async()=>{const [{createInitialResourcesState},{createUniverse},{createRun,beginShock},{createVeilRenderer},{flightConfig},{CARBON_CHARGED_ANCHOR},{ELECTRICAL_FIELD,electricalEffectiveAt}]=await Promise.all([import('/src/veil/resources-persistence.js'),import('/src/veil/universe.js'),import('/src/veil/expedition-run.js'),import('/src/veil/renderer.js'),import('/src/veil/growth.js'),import('/src/veil/shock-structures.js'),import('/src/veil/electrical-field.js')]);const state=createInitialResourcesState();Object.assign(state.progress,{choCompleted:true,coreFractured:true,worldAwakened:true,rareEcologyEligible:true});const capabilities={combustionDrive:true,nitrogenField:true,coreFractured:true,worldAwakened:true,rareEcologyEligible:true},map=createUniverse(73,state.elements,{capabilities}),run=createRun(map,flightConfig(state),{predators:false,fuel:{shock:{molecule:'nitromethane',amount:1,capacity:3}}});Object.assign(run.player,{x:CARBON_CHARGED_ANCHOR.x,y:CARBON_CHARGED_ANCHOR.y,vx:0,vy:0,speed:0,angle:0});const canvas=document.createElement('canvas');canvas.style.cssText='position:fixed;left:0;top:0;width:390px;height:844px';document.body.append(canvas);const renderer=createVeilRenderer(canvas),pixelData=()=>canvas.getContext('2d').getImageData(0,0,canvas.width,canvas.height).data,changed=(a,b)=>{let count=0;for(let i=0;i<a.length;i+=4)if(Math.abs(a[i]-b[i])+Math.abs(a[i+1]-b[i+1])+Math.abs(a[i+2]-b[i+2])>20)count++;return count;},hash=data=>{let value=2166136261;for(let i=0;i<data.length;i+=29)value=Math.imul(value^data[i],16777619);return value>>>0;};renderer.draw(run,0,false);const intact=pixelData(),before=electricalEffectiveAt(CARBON_CHARGED_ANCHOR,'awakened',{shockStructures:map.shockStructures});renderer.reset();map.shockStructures=[];renderer.draw(run,0,false);const absent=pixelData();map.shockStructures=[{...CARBON_CHARGED_ANCHOR,active:true,fractured:false,fracturedAt:null}];renderer.reset();renderer.draw(run,0,true);const reducedIntact=pixelData();const event=beginShock(run,()=>true);run.time=.18;renderer.reset();renderer.draw(run,.18,false);const fractured=pixelData(),after=electricalEffectiveAt(CARBON_CHARGED_ANCHOR,'awakened',{shockStructures:map.shockStructures});return{canvas:[canvas.width,canvas.height],intactPixels:changed(intact,absent),reducedPixels:changed(intact,reducedIntact),fracturedPixels:changed(intact,fractured),hashes:[hash(intact),hash(fractured)],event:{anchorFractured:event.anchorFractured,remaining:event.remaining},anchor:map.shockStructures[0],before,after,remainingElectrical:after>0};})()`);
  assert.deepEqual(result.canvas,[390,844]);assert.ok(result.intactPixels>40,'intact Anchor must be visible on the mobile renderer');assert.ok(result.reducedPixels>20,'reduced motion must retain the Anchor state read');assert.ok(result.fracturedPixels>40&&new Set(result.hashes).size===2,'fracture must visibly change the Anchor');assert.equal(result.event.anchorFractured,true);assert.equal(result.event.remaining,0);assert.equal(result.anchor.fractured,true);assert.ok(Math.abs(result.after/result.before-.6)<1e-9);assert.equal(result.remainingElectrical,true);assert.equal(exceptions.length,0,`SHOCK utility mobile render must not throw: ${JSON.stringify(exceptions)}`);
  console.log('SHOCK utility mobile Chromium',JSON.stringify({canvas:result.canvas,intactPixels:result.intactPixels,reducedPixels:result.reducedPixels,fracturedPixels:result.fracturedPixels,event:result.event,electricalScale:result.after/result.before}));
}finally{try{socket?.close();}catch{}try{child?.kill('SIGKILL');}catch{}await pause(100);server.close();await rm(profile,{recursive:true,force:true});}
console.log('SHOCK utility 390x844 browser validation passed: Carbon Anchor intact/fractured states, reduced-motion readability, one-charge fracture and nonzero Electrical reduction are visible without exceptions.');
