import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createResources,RESOURCE_KEY} from '../src/veil/resources.js';
import {combustionPacketFor} from '../src/veil/molecule-roles.js';

const database=JSON.parse(await readFile(new URL('../data/molecules.json',import.meta.url)));
const memory=()=>{const data=new Map();let reject=false;return {getItem:key=>data.get(key)??null,setItem:(key,value)=>{if(reject)throw Error('quota');data.set(key,value);},removeItem:key=>data.delete(key),reject(value=true){reject=value;},data};};
const emptyTanks={propellant:{molecule:null,amount:0},fuel:{molecule:null,amount:0},oxidizer:{molecule:null,amount:0},coolant:{molecule:null,amount:0}};
const loadout=(propellant=null,fuel=null,oxidizer=null)=>({propellant:propellant??{molecule:null,amount:0},fuel:fuel??{molecule:null,amount:0},oxidizer:oxidizer??{molecule:null,amount:0}});

const storage=memory(),resources=createResources({storage});resources.setCatalog(database);assert.equal(resources.state.schemaVersion,6);assert.equal(Object.hasOwn(resources.state,'molecules'),false);assert.deepEqual(resources.state.tanks,emptyTanks);
resources.discover('hydrogen');resources.state.elements.H=82;resources.save();assert.ok(resources.spend({H:2}),'The handmade H2 template checks two atoms out of BASE STOCK');resources.save();
assert.equal(resources.fillTankFromElements('propellant','hydrogen',40).added,40);assert.deepEqual(resources.state.tanks.propellant,{molecule:'hydrogen',amount:40});assert.equal(resources.state.elements.H,0);assert.deepEqual(resources.prepareExpedition(),loadout({molecule:'hydrogen',amount:40}));assert.ok(resources.consumeBoost());

resources.state.elements.H=8;assert.equal(resources.fillTankFromElements('propellant','hydrogen',4).added,4);resources.discover('carbon-dioxide');resources.state.elements.C=2;resources.state.elements.O=4;resources.save();
const replacement=resources.fillTankFromElements('propellant','carbon-dioxide',2);assert.equal(replacement.discarded,4);assert.deepEqual(resources.state.tanks.propellant,{molecule:'carbon-dioxide',amount:2});assert.deepEqual(createResources({storage}).state.tanks.propellant,{molecule:'carbon-dioxide',amount:2});

const combustionStorage=memory(),combustion=createResources({storage:combustionStorage});combustion.setCatalog(database);for(const id of ['hydrogen','oxygen'])combustion.discover(id);Object.assign(combustion.state.elements,{H:8,O:4});combustion.save();assert.equal(combustion.fillTankFromElements('fuel','hydrogen',4).added,4);assert.equal(combustion.fillTankFromElements('oxidizer','oxygen',2).added,2);const packet=combustionPacketFor('hydrogen');assert.ok(combustion.consumeCombustion(packet));assert.deepEqual(combustion.prepareExpedition(),loadout(null,{molecule:'hydrogen',amount:2},{molecule:'oxygen',amount:1}));

const failingStorage=memory(),failing=createResources({storage:failingStorage});failing.discover('hydrogen');failing.state.elements.H=2;failing.save();const beforeFailure=failing.snapshot();failingStorage.reject();assert.equal(failing.fillTankFromElements('propellant','hydrogen'),false);assert.deepEqual(failing.snapshot(),beforeFailure);

const base={elements:{H:0,C:0,N:0,O:0,F:0,P:0,S:0,Cl:0},molecules:{hydrogen:17,methane:2,oxygen:4,water:9},recipes:['hydrogen','methane','oxygen'],hints:[],dust:{H:0,C:0,O:0},loadout:{drive:'hydrogen',cooling:true},progress:{bestChain:0,runs:0,cleared:false,craftPrompt:false,sound:true,foundElements:['H'],regions:['veil'],checkpoint:'veil',frontier:false,totalCollected:0,signalMisses:0,signalLast:{}},workspace:null};
const legacy5=memory();legacy5.setItem(RESOURCE_KEY,JSON.stringify({...base,schemaVersion:5,tanks:{propellant:{molecule:'hydrogen',amount:70},fuel:{molecule:'methane',amount:7},oxidizer:{molecule:'oxygen',amount:9},coolant:{molecule:null,amount:0}}}));const migrated5=createResources({storage:legacy5});assert.equal(Object.hasOwn(migrated5.state,'molecules'),false);assert.deepEqual(migrated5.state.tanks.propellant,{molecule:'hydrogen',amount:70});
const legacy3=memory();legacy3.setItem(RESOURCE_KEY,JSON.stringify({...base,schemaVersion:3,tanks:{hydrogen:3,methane:18,oxygen:36}}));const migrated3=createResources({storage:legacy3});assert.equal(migrated3.state.schemaVersion,6);assert.deepEqual(migrated3.state.tanks,{propellant:{molecule:'hydrogen',amount:120},fuel:{molecule:'methane',amount:18},oxidizer:{molecule:'oxygen',amount:36},coolant:{molecule:null,amount:0}});
const legacy4=memory();legacy4.setItem(RESOURCE_KEY,JSON.stringify({...base,schemaVersion:4,tanks:{propellant:{molecule:'hydrogen',amount:2},fuel:{molecule:'methane',amount:9},oxidizer:{molecule:'oxygen',amount:17},coolant:{molecule:null,amount:0}}}));const migrated4=createResources({storage:legacy4});assert.deepEqual(migrated4.state.tanks,{propellant:{molecule:'hydrogen',amount:80},fuel:{molecule:'methane',amount:9},oxidizer:{molecule:'oxygen',amount:17},coolant:{molecule:null,amount:0}});
const legacy2=memory();legacy2.setItem(RESOURCE_KEY,JSON.stringify({...base,schemaVersion:2,molecules:{hydrogen:200,methane:20,oxygen:40,water:30}}));const migrated2=createResources({storage:legacy2});assert.deepEqual(migrated2.state.tanks,emptyTanks);assert.equal(Object.hasOwn(migrated2.state,'molecules'),false);
console.log('Generic tank supply passed: v6 inventory removal, direct batches, replacement discard, consumption, rollback, persistence, and v2-v5 migration.');
