from pathlib import Path

p=Path('tests/veil-ui-check.mjs')
s=p.read_text()
old="q('open-supply').click();assert.equal(q('supply-dialog').open,true);q('launch-veil').click();assert.equal(q('supply-dialog').open,false);assert.equal(q('veil-view').hidden,false);"
new="q('open-supply').click();assert.equal(q('supply-dialog').open,true);q('launch-veil').click();await settle();assert.equal(q('supply-dialog').open,false);assert.equal(q('veil-view').hidden,false);"
if old not in s: raise SystemExit('missing initial launch block')
s=s.replace(old,new)
old="""const tankAction=q('craft-tank-actions').querySelector('[data-tank-use=\"propellant\"]');assert.ok(tankAction);const hBefore=game.run('resources.state.elements.H');tankAction.click();assert.equal(game.run('resources.state.elements.H'),hBefore,'A short tap does not produce');
const holdDown=new game.window.MouseEvent('pointerdown',{bubbles:true,cancelable:true,button:0});Object.defineProperty(holdDown,'pointerId',{value:70});tankAction.dispatchEvent(holdDown);assert.equal(q('tank-charge-stage').hidden,false);assert.match(q('tank-charge-label').textContent,/噴射剤へ充填/);game.tick(1600);
assert.equal(game.run('resources.state.elements.H'),hBefore-240);assert.deepEqual(game.run('resources.state.tanks.propellant'),{molecule:'hydrogen',amount:120});assert.equal(game.run('molecule.atoms.length'),2,'The handmade molecule remains as the production template');
const checkedOut=game.run('resources.state.elements.H');game.run('clearField()');assert.equal(game.run('resources.state.elements.H'),checkedOut+2);assert.equal(game.run('molecule.atoms.length'),0);"""
new="""assert.equal(q('craft-tank-actions').hidden,true,'Discovered molecules no longer expose repeat-fill craft actions');assert.equal(q('craft-tank-actions').querySelector('[data-tank-use=\"propellant\"]'),null);const hBefore=game.run('resources.state.elements.H');assert.deepEqual(game.run('resources.state.tanks.propellant'),{molecule:null,amount:0});
const checkedOut=hBefore;game.run('clearField()');assert.equal(game.run('resources.state.elements.H'),checkedOut+2);assert.equal(game.run('molecule.atoms.length'),0);"""
if old not in s: raise SystemExit('missing old repeat-fill block')
s=s.replace(old,new)
old="""q('open-supply').click();assert.equal(q('supply-dialog').open,true);assert.equal(q('open-supply').textContent.trim(),'収集殻');assert.equal(q('shell-propellant').querySelector('small').textContent,'H₂');assert.equal(q('tank-model-name').textContent,'H₂ · 水素');assert.equal(q('tank-comparison').children.length,2);
q('tank-model').click();assert.equal(q('supply-dialog').open,true,'The model itself stays an inspection surface');assert.equal(q('collection-dialog').open,false);q('tank-open-collection').click();assert.equal(q('supply-dialog').open,false);assert.equal(q('collection-dialog').open,true);assert.match(q('collection-detail').textContent,/水素/);assert.equal([...q('collection-detail').querySelectorAll('button')].some(button=>button.textContent==='この分子をクラフト'),false);q('collection-dialog').close();q('open-supply').click();q('tank-craft-molecule').click();assert.equal(q('supply-dialog').open,false);assert.equal(game.run('molecule.atoms.length'),0,'Selecting a target automatically puts the old workspace away');assert.equal(game.run('resources.state.elements.H'),beforeTarget);assert.equal(q('craft-target').hidden,false);assert.match(q('craft-target').textContent,/水素/);assert.equal(game.run('resources.state.workspace.targetMoleculeId'),'hydrogen');"""
new="""q('open-supply').click();assert.equal(q('supply-dialog').open,true);assert.equal(q('open-supply').textContent.trim(),'収集殻');assert.equal(q('shell-propellant').querySelector('small').textContent,'∅');const h2Choice=q('tank-molecules').querySelector('[data-molecule-id=\"hydrogen\"]');assert.ok(h2Choice);const stockBeforeLoadout=game.run('resources.state.elements.H');h2Choice.click();assert.equal(game.run('resources.state.elements.H'),stockBeforeLoadout,'Loadout selection is free');assert.deepEqual(game.run('resources.state.tanks.propellant'),{molecule:null,amount:0},'Loadout editing does not fill or discard the current tank');assert.equal(game.run('resources.selectedLoadout().propellant'),'hydrogen');assert.equal(q('shell-propellant').querySelector('small').textContent,'H₂');assert.equal(q('tank-model-name').textContent,'H₂ · 水素');assert.equal(q('tank-comparison').children.length,2);assert.equal(q('tank-craft-molecule').hidden,true,'Discovered loadout molecules do not require repeat crafting');
q('tank-model').click();assert.equal(q('supply-dialog').open,true,'The model itself stays an inspection surface');assert.equal(q('collection-dialog').open,false);q('tank-open-collection').click();assert.equal(q('supply-dialog').open,false);assert.equal(q('collection-dialog').open,true);assert.match(q('collection-detail').textContent,/水素/);assert.equal([...q('collection-detail').querySelectorAll('button')].some(button=>button.textContent==='この分子をクラフト'),false);q('collection-dialog').close();game.window.dispatchEvent(new game.window.CustomEvent('molecule-craft:craft-molecule',{detail:{id:'hydrogen'}}));assert.equal(game.run('molecule.atoms.length'),0,'Selecting a target automatically puts the old workspace away');assert.equal(game.run('resources.state.elements.H'),beforeTarget);assert.equal(q('craft-target').hidden,false);assert.match(q('craft-target').textContent,/水素/);assert.equal(game.run('resources.state.workspace.targetMoleculeId'),'hydrogen');"""
if old not in s: raise SystemExit('missing old supply craft block')
s=s.replace(old,new)
old="""q('open-supply').click();q('launch-veil').click();assert.equal(q('craft-target').hidden,true,'Launching exploration clears the craft target');const fuel=game.run('resources.state.tanks.propellant.amount');assert.equal(game.run('veilUI.run.map.depletion.H'),inventoryDepletion(JSON.parse(game.run('JSON.stringify(resources.state.elements)')),'H'),'Launch uses the actual base inventory');"""
new="""q('open-supply').click();const launchStock=game.run('resources.state.elements.H');q('launch-veil').click();await new Promise(resolve=>setTimeout(resolve,540));assert.equal(q('craft-target').hidden,true,'Launching exploration clears the craft target');const fuel=game.run('resources.state.tanks.propellant.amount');assert.equal(fuel,120,'Departure auto-synthesizes the selected propellant to full capacity');assert.equal(game.run('resources.state.elements.H'),launchStock-240,'Departure consumes only the atoms needed for launch fill');assert.equal(game.run('veilUI.run.map.depletion.H'),inventoryDepletion(JSON.parse(game.run('JSON.stringify(resources.state.elements)')),'H'),'Launch uses the actual base inventory after auto synthesis');"""
if old not in s: raise SystemExit('missing old launch block')
s=s.replace(old,new)
s=s.replace('Production H Veil UI passed: Collector Shell launch, manual H₂ design, fixed hold fill, explicit encyclopedia/craft routes, target cleanup, boost spending, multitouch cancellation, blur pause, exact resource/workspace reload and refunds. Canvas/WebGL are stubbed; this is not a visual or subjective playtest.','Production H Veil UI passed: Collector Shell loadout selection, launch auto-synthesis, manual H₂ discovery, explicit encyclopedia route, target cleanup, boost spending, multitouch cancellation, blur pause, exact resource/workspace reload and refunds. Canvas/WebGL are stubbed; this is not a visual or subjective playtest.')
p.write_text(s)
Path(__file__).unlink()
